### ISSUE TITLE
LOS Thread bug

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#1039]

**Comment by zgrose** [comment]
FYI, I tweaked your post slightly for readability (mine). You can use four \` characters to keep your block nice. One \` is good for single `words` or `maybe a single line of text`.

Now lemme see if I can give you some meaningful code help....

**Comment by zgrose** [comment]
I'm not seeing your block 
````
if (LOSMap ==null){
    legacyMode=true;
    return;
}
````
in the develop branch, so I presume you're on a local branch. Have you checked for the obvious that your source and your runtime jars are out of sync?

**Comment by derimmer** [comment]
> I'm not seeing your block
> 
> ```
> if (LOSMap ==null){
>     legacyMode=true;
>     return;
> }
> ```
> 
> in the develop branch, so I presume you're on a local branch. Have you checked for the obvious that your source and your runtime jars are out of sync?

<Thunk!> The sound of my head hitting the desk. 

You are totally right Zoltan. I added that block to my dev code! To handle this very error! 

I am just not very good at this stuff! LOL. 

So, now I need to look at the earlier code: 

`final ASLMap theMap = (ASLMap) map;
        if(theMap == null || theMap.isLegacyMode()) {
            legacyMode = true;
        `

If there is a problem with creating LOSMap then it should meant theMap is null or is legacy mode so the code break should be triggered by the above block but obviously isn't. I will do more testing there. Thanks.

**Comment by derimmer** [comment]
Previous fix seems to have solved problem. Can no longer replicate.
