### ISSUE TITLE
Bd47 - LOS Issue

### ISSUE THREAD

**Issue by BruceCarson** [vasl-developers/vasl#1045]
LOS encounters -1 level open ground hex when tracing a LOS from level 2 to level 1.  This LOS should not be blocked.

<img width="473" alt="image" src="https://user-images.githubusercontent.com/3753108/143724796-c187ebe3-2fcb-4548-9d61-f2c5cf2dd950.png">

**Comment by zgrose** [comment]
reporting EE2 as Level 0 also seems to be a problem (note the `EE2 (Level 0)` notation).

**Comment by BruceCarson** [comment]
My opponent did the LOS check.  We've noticed that the person who doesn't draw the LOS gets the wrong level numbers reported, but the person who does the check sees the correct values.

**Comment by derimmer** [comment]
> My opponent did the LOS check. We've noticed that the person who doesn't draw the LOS gets the wrong level numbers reported, but the person who does the check sees the correct values.

Does the person who does the check see the correct result (not blocked) along with the correct levels?

When I draw the los I get a clear result (as in the los is clear).
![bd47snip2](https://user-images.githubusercontent.com/7696161/143726836-8015d0a8-e4f9-49fe-8fd4-91d2d9d964b1.PNG)

What VASL versions and board versions are you and your opponent using?

There was a bug with reporting out the levels of the start and target hexes. I know I fixed it for the local machine and thought it was working on the remote machine as well. That may be the problem with the reporting. But the los check itself should still be working correctly on both local and remote machines.

**Comment by BruceCarson** [comment]
1: No the person who did the LOS also saw it blocked.  I tried reproducing the problem starting fresh and the LOS works.  correctly.   I've attached our game file in case that could help narrow down what happened?  I had to zip it because for some reason you don't allow .vsav file attachments :)

**BD47 data:  Says it is ver 6.5 in the "Terrain Transformations" dialog** 
version 6.0
Nov 2011 TR

**Module Data**
<?xml version="1.0" encoding="UTF-8"?>
<data version="1">
  <version>6.6.4-beta1</version>
  <VassalVersion>3.4.6</VassalVersion>
  <dateSaved>1322805026979</dateSaved>
  <description>Virtual Advanced Squad Leader</description>
  <name>VASL</name>
</data>

[BFP30 Melee Near The Coast Chinese 2.zip](https://github.com/vasl-developers/vasl/files/7613749/BFP30.Melee.Near.The.Coast.Chinese.2.zip)

**Comment by derimmer** [comment]
When I open your .vsav file, the error appears. If a start a new game and recreate the map without the PTO light jungle transformation, los works. If I apply the PTO light jungle transform, the error appears. 

So there is a bug in the PTO light jungle transform. I will check it out. 

In your game, click on the ASL button on the toolbar (potato masher guy on orange background), select Pick New Boards for this scenario, select TerrainSSR. Click on the Reset button. then scroll down the transforms list to PTO Transformations and select Palm Trees. I can't recall if you need to change any roads but you can do that separately as well. Don't use the dropdown in the top right corner to apply the PTO light jungle transform. That should make the map look as it should without messing up the los checker.

**Comment by BruceCarson** [comment]
I tried your temporary fix and it didn't work.  So we'll have to resort to actually figuring out the LOS ourselves (GASP!), until the bug is fixed.

**Comment by derimmer** [comment]
I have fixed this particular bug and the fix will be in 6.6.4 as it was a code bug when applying the PTO transformation and cropping. The problem was in method VASLBoard.fillWoodsRoadHexes(). There may be a similar bug in other similar methods in VASLBoard - the same solution should work if other bugs are found.
