### ISSUE TITLE
While setting up an ASL scenario an error was generated

### ISSUE THREAD

**Issue by rddunn** [vasl-developers/vasl#1054]
I’m running vassal 3.6.1 with module VASL 6.6.3.1.

I’m creating a new scenario setup and was adding a Japanese vehicle by dragging the counter to the board when an error occurred.

I’d like to add the error file, but am not sure how to do that in this forum.

BTW, I’ve been doing this exact action in vassal/VASL for the past 2 years and have never gotten this error. BUT, I did upgrade to 3.6.1/6.6.3.1 yesterday. Not a coincidence, I’m sure.

[errorLog-3.6.1.txt](https://github.com/vasl-developers/vasl/files/7657206/errorLog-3.6.1.txt)

**Comment by Cattlesquat** [comment]
The run-of-the-mill part (map null) should be fixed for 3.6.2 by : https://github.com/vassalengine/vassal/pull/10908

The exotic DNS thing that prevented the automatic bug report is for More Advanced Minds
