### ISSUE TITLE
oba-flowchart extension needs to be updated for Vassal 3.6

### ISSUE THREAD

**Issue by uckelman** [vasl-developers/vasl#1056]
When I load VASL 6.6.3.1 with oba-flowchart.vmdx, I get a Defunct Custom Code error:
```
2021-12-14 21:33:51,449 [79482-SwingWorker-pool-1-thread-1] ERROR VASSAL.launch.AbstractLaunchAction - Removed classes, methods, and fields in /home/uckelman/projects/VASSAL/modules-src/vasl/vasl-6.6.3.1_ext/oba-flowchart.vmdx
(used by => removed item, version when removed

scottgreenman.asl.obaflowchart.OBAFlowchart => VASSAL.tools.DataArchive.getFileStream(java.lang.String), 3.6.0
```
`DataArchive.getFileStream()` should be replaced with `DataArchive.getInputStream()`, as indicated in the 3.5.8 javadoc: https://vassalengine.org/javadoc/3.5.8/VASSAL/tools/DataArchive.html

**Comment by derimmer** [comment]
I am away from my desktop for a couple of weeks. Will not be able to look at this until January.

**Comment by uckelman** [comment]
You'd need to modify `OBAFlowchart,java` in the extension. Do you not have the source code for it?

**Comment by derimmer** [comment]
Thanks. I guess I don't know. I have certainly never seen or accessed source code for any extension. 

We have access to the .vmdx files on vasl.info.  I know that we can unzip them and have done so to access their buildfile and images. I did not think they contained source code as well.

**Comment by uckelman** [comment]
Have a look inside the extension. The source might be there. If it's not, you have two options: Get the source from whomever has it, or decompile the class file from the extension. (If you have to decompile the class file, I can help with that---I've had to do it a few times recently.)

**Comment by derimmer** [comment]
The extension contains just the compiled code. I have no way of contacting the original author. So that leaves us with decompiling and I would appreciate your help on that.

**Comment by uckelman** [comment]
It turns out that the class which needs modification has almost nothing in it:
```
package scottgreenman.asl.obaflowchart;

import VASSAL.build.GameModule;

class OBAFlowchart extends Flowchart
{
    OBAFlowchart() throws Exception {
        super(GameModule.getGameModule().getDataArchive().getFileStream("OBAFlowchart.xml"));
    }
    
    public static void main(final String[] array) throws Exception {
        System.out.println(new OBAFlowchart().toXML());
    }
}
```

**Comment by uckelman** [comment]
Rename this to .vmdx: oba-flowchart-fixed.zip](https://github.com/vasl-developers/vasl/files/7989831/oba-flowchart-fixed.zip)

Does that work for you?

**Comment by derimmer** [comment]
Yes, this seemed to work. I tried it under vassal3.6.3 and 3.5.8, both with vasl6.6.3.1.

This suggests that it would be fine to release the fixed extension now rather than wait until vasl6.6.4 (which will require vassal3.6.X)?

Many thanks.

**Comment by derimmer** [comment]
I have uploaded the revised extension to the website
