### ISSUE TITLE
LOS Bug: Single hex buildings with 2nd level

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#1066]
See #1064. All boards with similar buildings should be checked for similar bug.

**Comment by derimmer** [comment]
I have checked the los enabled boards and could not find any other bugs of this type.

I did find the following situation on bd4a/b:

![4asnip](https://user-images.githubusercontent.com/7696161/151875839-02407777-c8cf-479d-b7e4-16fea189cc4f.PNG)
 J9 and M13 currently have only a ground level in the los data. This seems wrong but I don't know what is right. Anyone have any ideas as to how many levels these two terrain types should have on these boards?

**Comment by zgrose** [comment]
J9 is a Tower (B34).
34.2 The height and LOS characteristics for each Tower are specified by SSR. Towers will be defined by SSR as being either a LOS obstacle or Hindrance. Each Tower contains only a single Tower Location that exists at a Level above ground level which is specified by SSR; the Tower Obstacle Hindrance height is 1/2 Level above the SSR designated Tower Location height.

EX: An SSR reads, “Hex PBC9 contains a Tower Hindrance with a Tower Location 1 Level above ground level,” describes a 11
/2 Level LOS Hindrance.

**Comment by zgrose** [comment]
I presume M13 is meant to be a silo or something? Seems to fit B31.3 if that's a standard board.

**Comment by derimmer** [comment]
@zgrose thanks.

So given the variability of J9, just having it with a ground level location is fine. The new "virtual locations" that I added in 6.6.3 will allow los to be drawn to whatever higher level is specified by SSR. It will not work properly as los obstacle but we can't have everything. 

As for M13 (and others just like it on 4a/b), I would need to correct the boards if there is supposed an upper level. Anyone know for sure?

**Comment by derimmer** [comment]
Tom Repetti tells me that J9 is simply a wooden building with a square centre dot and therefore has a 1st and 2nd level and is a 2.5 level obstacle. M9 and the like are stone buildings with a big round centre dot and therefore are Stone Level 1 with a 1st level and 1.5 obstacle height. I will code them that way and issue a corrected board.

**Comment by derimmer** [comment]
4a/b fixed and re-issued
