### ISSUE TITLE
Where o where are my extensions tonight

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#1070]
In reviewing some other issue threads, FB and GS posts today, I am pretty sure that I came across some commentary from our vassal colleagues about the important of having the VASL extensions directory stored in a readily accessible place (preferably in the Documents hierarchy) and most certainly NOT in Program Files or other like directories where the VASSAL files would normally be stored. 

I was in the middle of something, noted the value of this advice, moved on with the intension of returning to the scene of the comments later. Now of course I can't find them. 

@uckelman @BrentEaston Any help? Does this ring a bell? 

Since vassal3.2.17, I have kept all my extension in c:\program files\vassal-3.2.17\extensions. They have always worked just fine but I am happy to move them if that is the advice. 

Of course, I may have this completely muddled in my mind.

**Comment by zgrose** [comment]
i'm guessing you only play VASL because that wouldn't seem a great structure if i was playing more than one module. i usually toss my vasl extensions under wherever i put my vasl mod. so that could be c:\foo\bar\vasl\extensions. just my 2 cents.

**Comment by uckelman** [comment]
You shouldn't store any data files under C:\Program Files.

**Comment by derimmer** [comment]
> You shouldn't store any data files under C:\Program Files.

I think there are members of our user community who would not think of extensions as "data files". I think I will put out an APB on this as we quite often get asked to debug problems which turn out to be file access issues, whether it be for extensions or saved games or whatever.

What about Apple devices? Is it an issue there as well and what names do they use for "C:\Program Files" and "Documents"?

**Comment by uckelman** [comment]
> I think there are members of our user community who would not think of extensions as "data files"

I know! I've been telling people this for 15 years.

> What about Apple devices?

On any Unix, the place to your data files is in your home directory. The Mac bundle ends up in something like `/Applications/Whatever/Blah`. That's _not_ where you should store your data files, but doing that won't cause permissions problems like it does on Windows.

**Comment by hongkongwargamer** [comment]
I am a Mac guy .. my extensions (under PREFERENCES) are in VASSAL/VASL 6.0/Maps Extensions Overlays/extensions-complete

**Comment by derimmer** [comment]
Here is a draft message that I could post in all the usual places (FB, GS, Discord). Edits and suggestions welcome to ensure that (a) the message is clear and (b) I suffer the minimum amount of abuse from those preferring their own specific solution (which may well work for them but is unlikely to helpful to those of our users who are still struggling with copy-paste). 

>>Message begins
I have observed recently more and more requests for help solving VASL problems which are in fact issues of file management and access. 
These problems arise primarily for Windows users and seem to be increasing with the arrival of Windows 11 but there is probably some good practice advice here for Mac and Unix users.
The key point is to separate data from program files
You wouldn’t wash your tidy whites with your new blue jeans and you shouldn’t put your data files in with your program files. 
In Windows, avoid placing data files in areas such as C:\Program Files or any subdirectory under such a heading. Place your personal files in areas such as Documents on your device or in a cloud storage location such as One Drive, Google Drive, etc. 
So, what is a data file? For VASL purposes consider all boards, overlays, .vsav files, .vlog files, and extensions to be data files. All of these should be put in places where windows will let you as the user, and apps such as VASSAL, have access to them. 
From what I have seen recently, I would recommend that folks pay particular attention to their extensions and boards directories to make sure they are and will remain accessible. 
Default access permissions for file types and for file locations can differ from version to version of windows and from computer producer to producer when windows comes pre-installed. It is possible   that what has worked well for a long time will stop working on a new or upgraded device. 
For those of your who are expert users, you understand that there is a lot more detail to this and other ways to solve the problems. You will have solutions in place already, I am sure. For those who are not experts, I would strongly recommend that you move all of the VASL file types described above into locations under the Documents folder or in a cloud storage.
There is some risk that moving extensions to new locations might have an impact on previously saved games. I did a quick test using the BFP extension and a game saved with the extension saved in one place worked well when I opened it after having moved the extension. But this is no guarantee so approach with caution and do a little testing on your system.  
<<Message ends

**Comment by uckelman** [comment]
Oh, geez, _please_ don't recommend that people put files that they intend to _save_ with Vassal on cloud storage. We see endless problems from people trying to save modules they've edited to OneDrive, because it's flaky and I/O operations time out.

**Comment by zgrose** [comment]
> Oh, geez, _please_ don't recommend that people put files that they intend to _save_ with Vassal on cloud storage. We see endless problems from people trying to save modules they've edited to OneDrive, because it's flaky and I/O operations time out.

I suspect that ship has already sailed and the onus is on the app developer (of all apps, not singling out VASSAL) to be more fault-tolerant.

**Comment by derimmer** [comment]
Sent
