### ISSUE TITLE
More than one Map Centerer

### ISSUE THREAD

**Issue by BigAl737** [vasl-developers/vasl#1076]
Thought I'd break this issue out from another I recently closed. @derimmer please close this issue if it didn't warrant being opened.
VASSAL 3.5.8 VASL 6.6.3.1 Windows 10 64 bit
When you edit the VASL module and try to save, you get this pop up:

![image](https://user-images.githubusercontent.com/10384413/149580598-95111860-62ac-4002-9491-22fcdbca1117.png)

I've broken out the pertinent comments from the issue I closed https://github.com/vasl-developers/vasl/issues/1069:

From @uckelman 
The reason you're seeing the warning about multiple Map Centerers on the Main Map is that VASL 6.6.3.1 has two Map Centerers on the Main Map. I can see that from checking the buildFile. One of them should be removed. I'm not sure why neither shows up in the editor.

From @derimmer 
Looking at the VASL project on Github:

MapCenterer.java was created by Rodney Kinney in 2000-2003 and is an empty class that extends VASSAL's MapCenterer. It does not seem to have been touched since.

I suspect that somewhere along the line the reference in the buildFile got duplicated. Who knows why. I will delete the additional reference.

It does raise a question about whether we need the MapCenterer.java class at all? When I search the project I can't find any usages of it at all.

From @uckelman 
It's probably safe to remove the class, in that case. If you do remove the class, then you need to replace the references to it in the buildFile with <VASSAL.build.module.map.MapCenterer/>, making sure that you leave only one per Map.

**Comment by derimmer** [comment]
I removed the duplication MapCenterer in PR#1073. I left the class in place for now.
