### ISSUE TITLE
bug with overlay 6

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#1078]
from gs:

http://www.gamesquad.com/forums/index.php?threads/overlay-bug.167094/#post-2081001

**Comment by BigAl737** [comment]
This is a legacy overlay issue which I don't support. The drag and drop overlay from the Overlay extension works.

**Comment by derimmer** [comment]
@BigAl737 Thanks. 

I am doing some work on the legacy overlays as I think I can get los working with some of them. I will look it this one at the same time. I will also post on GS that your draggable overlays works.

**Comment by BigAl737** [comment]
Wow, that'd be a game changer for the usefulness of the legacy overlays. I do like how the legacy overlay terrain transforms work with the board transforms. Add in LOS and it may be time to revisit the legacy method of placing overlays. Although, as I think about it, the legacy method had other drawbacks as well.

**Comment by derimmer** [comment]
> Wow, that'd be a game changer for the usefulness of the legacy overlays. I do like how the legacy overlay terrain transforms work with the board transforms. Add in LOS and it may be time to revisit the legacy method of placing overlays. Although, as I think about it, the legacy method had other drawbacks as well.

You are right Al. I think the two methods have their respective strengths and I don't see much reason to think we will get rid of one or the other.
