### ISSUE TITLE
BFPA and BFPB Towers and Storage Tanks transformation not working properly

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#1079]
from gs:

Boards BFPA and BFPB have both Towers and Storage Tanks. Towers are defined as round brown things and Storage Tanks as round gray (grey) things. When I select make all buildings wooden (brown) or stone (gray/grey) the round things all become the same color and can't be differentiated.

**Comment by zgrose** [comment]
Not sure I'd call that bug, but semantics. :)

**Comment by BigAl737** [comment]
I could adjust the colors of the towers and storage tanks so that the universal all wood/all stone transforms wouldn't recognize them. But that induces other problems like when winter is in effect. That's fixable too now that I think about it. Mind if I take a crack at this?

**Comment by derimmer** [comment]
It's all yours Al!

**Comment by BigAl737** [comment]
Since we converted all boards to use metadata, terrain transforms are still processed with the color and colorSSR files, right?

**Comment by BigAl737** [comment]
It's been 4 minutes and Doug hasn't responded yet. Call 911 :-)

**Comment by derimmer** [comment]
@BigAl737 Ha!

I suspect that in many instances, the terrain transforms are now using the board boardmetadata.xml file and the SharedBoardMetaData.xml file in the module. 

But there are more than likely some transforms and some boards where information is missing and transforms revert to the color and colorSSR files. 

If I were fixing transforms or adding new ones, I would start by ensuring the necessary data is in the .xml files. If the transform works when tested then I would stop there and not update color or colorSSR.

My next step is to start removing the color and colorSSR files from boards. I don't see that happening this spring, but hopefully over the summer for vasl6.6.5 in the fall.

**Comment by BigAl737** [comment]
Thanks Doug. I see that the color and colorSSR file within the bdBFPA and bdBFPB directories are specific for BFP boards. A quick glance at the vasl/dist directory and I only find reference to BFP in the SharedBoardMetadata.xml lines 1261 and 1262, but I don't think these apply to BFP color transformations.

So I'm thinking that bdBFPA and bdBFPB still use the color and colorSSR files within their directory. I'll start there.

I'm not asking anything from you Doug. Just keeping you involved in my process.

**Comment by davidsullivan317** [comment]
A quick clarification: if the Board metadata file is present the colors and colorSSR files are not used. That information should have been moved into the metadata file. Those files can (and should) be deleted and no longer created.

**Comment by derimmer** [comment]
I now having this working in the sense that those buildings that are "transformed" either to stone or wood do so with a different colour scheme than the original buildings on the board. Thus, they appear as "All Stone" or "All Wood" but with different colours so that the Towers and Storage Tanks can be differentiated (easily to my eye).
