### ISSUE TITLE
Boards 87 and 88

### ISSUE THREAD

**Issue by BigAl737** [vasl-developers/vasl#1099]
Received these from Tom. They need reviewing then releasing. I won't get to this till mid March at the earliest. If someone wants to take this over, please do. Else, I'll get it done as soon as I'm able.

Thanks Tom for doing these!

[bd87.zip](https://github.com/vasl-developers/vasl/files/8052904/bd87.zip)
[bd88.zip](https://github.com/vasl-developers/vasl/files/8052905/bd88.zip)

**Comment by BigAl737** [comment]
@derimmer these are ready for your LOS majik. Pushed the files to vasl/boards/src.

**Comment by derimmer** [comment]
these boards are now available in the dropdown. I will push them to the website next. Whoever wants to announce them can do so.
