### ISSUE TITLE
Truly blank 5/8" counters

### ISSUE THREAD

**Issue by davidsullivan317** [vasl-developers/vasl#111]
The 5/8" blank counters all have a little arrow on them. Let's add a truly blank counter to each nationality.

**Comment by zgrose** [comment]
Were you thinking of this as a toggle (e.g. Toggle CA Mark) or a separate piece in the counter tray?

**Comment by derimmer** [comment]
Closing. We seem to have survived 6 years without anyone picking this up. Does not seem like there is a need.
