### ISSUE TITLE
cropping interferes with LOS calculation

### ISSUE THREAD

**Issue by jrvjrv** [vasl-developers/vasl#1112]
Start a new game with board 2. Crop the board to hexrows r-gg. Draw LOS from 2BB5 to 2DD6.
Result: LOS shown as clear.
Expected: LOS is blocked. When there is no cropping the LOS shows as blocked.

This behaves the same way for LOS from Z4 to X3, which is blocked (plateau-ed) when not cropped but shows as open when the board is cropped.

vasl 6.6.3, VASSAL 3.5.8, linux

**Comment by derimmer** [comment]
Definitely a bug. I have done some testing and can only replicate the bug when the hex in the top left corner of the map is both half-hex in height and half-hex in width. 

For example if you do the crop @jrvjrv describes but select Crop to nearest full hex row, then the los works properly. 

So, at least I know where to look.
