### ISSUE TITLE
VASL 6.2 discussion

### ISSUE THREAD

**Issue by davidsullivan317** [vasl-developers/vasl#113]
With summer winding down I'm starting to think about VASL 6.2. I have a bunch of LOS enhancements I'm going to get out in the coming months. Please use this thread for discussions on what you'd like to include. At some point I'll reach out to the masses to see if anything floats to the top of the "boy, we could sure use this" list.

**Comment by wintrymix** [comment]
What are we looking at for a release date for 6.2?  Last I knew, we were targeting 31 December, but that no longer seems operative.  I'm just trying to determine whether it worth doing more documentation or if I should start thinking about post-release updates/future releases.

**Comment by davidsullivan317** [comment]
The last change was checked in today. I've built beta3 and put it here: https://www.dropbox.com/sh/jmzfyzvptx2cfjm/AAA6uOHydqsTS7tnM7qwKQOna?dl=0

Barring any objections I'm going to release this for testing today or tomorrow.

**Comment by davidsullivan317** [comment]
I released beta 3 for testing today. FYI http://forums.gamesquad.com/showthread.php?120802-VASL-6-2-is-available-for-testing

**Comment by davidsullivan317** [comment]
Unfortunately I have to fix a bug with 6.1.0 where it errors opening some of the new V6 boards. I'll be releasing 6.1.1 shortly. Is there anything else worth patching in 6.1?

**Comment by davidsullivan317** [comment]
6.2 is ready to go! I'm going to release it tomorrow. Thanks all for you help on another great release.
