### ISSUE TITLE
Increment Global Property by 0.5 doesn't work

### ISSUE THREAD

**Issue by BruceCarson** [vasl-developers/vasl#1145]
I have need of a global property that can increment/decrement by 0.5.  It looks like they only handle whole numbers.  Is there a way to get this to work?
(I've tried adding 2's for 1's and dividing, but that doesn't seem to be able to display the 0.5 correctly either)...

![image](https://user-images.githubusercontent.com/3753108/162586069-a7b5b81c-6ed6-4655-89d1-becba38588c1.png)

**Comment by BigAl737** [comment]
Does this help?

https://forum.vassalengine.org/t/non-integers-in-stack-viewer/11650

**Comment by zgrose** [comment]
Do you have Java skills? Might be the fastest way to get a global variable in whatever data type works best for you. An AbstractBuilder might be able to do the job.

**Comment by derimmer** [comment]
This is all VASSAL stuff and your question might best be answered on their site. From my own experience, I don't think I have ever had the need to set a non-integer value using this or a dynamic property. That being said, I don't see why the values would have to be integers.

**Comment by BruceCarson** [comment]
> Does this help?
> 
> https://forum.vassalengine.org/t/non-integers-in-stack-viewer/11650

Thanks BigAl737 - this lead me in the right direction.  I ended up using the MOD operator instead and it is working great!
{(AFVMF/2).toString()+((AFVMF%2==0)?"":".5").toString()}

**Comment by BruceCarson** [comment]
> Do you have Java skills? Might be the fastest way to get a global variable in whatever data type works best for you. An AbstractBuilder might be able to do the job.

zgrose- no direct Java skills, but I know C# extremely well.  I'm sure at some point I'll be diving into some Java here!

**Comment by derimmer** [comment]
Since the problem appears to be solved without a need to make a VASL change, I am going to close this issue.
