### ISSUE TITLE
HidePiecesButton misues translation keys

### ISSUE THREAD

**Issue by uckelman** [vasl-developers/vasl#1158]
These three warnings appear in errorLogs when VASL is loaded:
```
2022-05-02 08:50:33,670 [8912-AWT-EventQueue-0] WARN VASSAL.i18n.BundleHelper - No Translation: Icon when pieces and draggable overlays are showing:
2022-05-02 08:50:33,670 [8912-AWT-EventQueue-0] WARN VASSAL.i18n.BundleHelper - No Translation: Icon when only draggable overlays are showing:
2022-05-02 08:50:33,670 [8912-AWT-EventQueue-0] WARN VASSAL.i18n.BundleHelper - No Translation: Icon when only map is showing:
```
They're due to a misuse of `Resources.getString()` in `VASL.build.module.map.HidePiecesButton`:
```
      Resources.getString("Icon when pieces and draggable overlays are showing:"), //$NON-NLS-1$
      Resources.getString("Icon when only draggable overlays are showing:"), //$NON-NLS-1$
      Resources.getString("Icon when only map is showing:"), //$NON-NLS-1$
```
There's one more misuse in the same class:
```
return Resources.getString("Change Show Map Mode Button"); //$NON-NLS-1$
```

The argument to `Resources.getString()` is supposed to be a translation key, not the literal text.

**Comment by BrentEaston** [comment]
Custom code cannot use Resources.getString except with existing Vassal translation keys. 

The default action of Resources.getString() if not translation is available is to return the key, so apart from displaying the warning, there is no actual impact.

Just removed the Resources.getString calls and use the Strings directly. These look like Editor prompt texts for a custom component, these can never be translated. Any texts to be displayed in-game that might need to be translated should be stored in a component data field of some type (as opposed to hard-coding in the custom code) and translated using the standard module translation mechanism.
