### ISSUE TITLE
Concealment Enhancement

### ISSUE THREAD

**Issue by sage944** [vasl-developers/vasl#1160]
AN IDEA...
Concealment in VASL

What I have been doing when I am allowed a concealed setup is to select all and Conceal them offmap using CRTL+C.  I then build my stacks and deploy them on map.  Doing it this way creates a "?" for EVERYTHING that must be individially deleted when stacked so that only one "?" conceals the stack.  What would be a nice addition would be a method or automatic process that eliminates all the extra "?" counters in the stack EXCEPT the top one that conceals all below it.

I hope that I have conveyed what I mean.  If this sounds good and you have questions, just reply to me.  I am limited to Visual Basic programming and Java is new to me.

**Comment by jrvjrv** [comment]
This is a laudable idea in theory, but I hope it is obvious that an implementation has to avoid eliminating dummy counters.

**Comment by derimmer** [comment]
To be honest, I very much doubt that such an approach will be implemented unless you take it on yourself to do so. The reason for this is that there is an equally valid way to reach the same end state.

1. Create your stacks. 
2. Right click the top unit in the stack and then conceal it using CTRL+C or the popup menu option. 

This will conceal every unit in the stack while only adding one ? counter on top of the stack. Which is exactly where you want to end up. 

Yes it has to be done stack by stack but even with an OB of Stalingradian proportions this does not seem to me to be a significant issue.

**Comment by sage944** [comment]
Very well.  I was thinking of the “fog of war” aspect wherein your opponent does not know the contents of a stack…beyond how tall it is.  Having the extras autodelete in a stack would be a great step saver.  Obviously, I cannot program it myself not knowing Java.  If I did then I would develop it and offer it as an extension.  The way I’ve been doing it will have to suffice…it does work, I suppose.

Good Hunting!  Thanx for the reply…VASL is a great interface making F2F gaming easier.

Best,
Jeffrey D. Fisher
Omaha, NE USA


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by sage944** [comment]
I had not thought of that.  If the autodelete was inherent to the stack then why would it get used on dummies?  Still, logically, a “Stack Control Menu” might be needed when an entire stack is selected.  It would not work (disabled/grayed out?) for individual units and is selectable only if selecting ≥2 units.

Just an idea…

Best,
Jeffrey D. Fisher
Omaha, NE USA


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by zgrose** [comment]
BTW, instead of mass concealing, you can mass HIP your units to re-arrange them pre-scenario.

**Comment by sage944** [comment]
Roger that.  I’ll figure something out.  The HIP method would work to conceal the personnel until deployed.  However, it would be a difficult option FOR ME since I can barely see them when HIP.  I am nearly blind (diabetes) with no detail vision.  Don’t get old…it sux.

Best,
JDF


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by jrvjrv** [comment]
This is another way you might possibly achieve your goal. The counters in the counter tray are "live" counters, i.e. you can change their state. A different way of approaching the problem would be to conceal your counter in the counter tray (select then ctrl-c or right-click, conceal) then drag it on the map concealed. Concealed units in the counter tray do not have the extra "?" counter put on top. Build your stacks using these "tray-concealed" counters then add a "?" counter on top of each stack. It is still not optimal in that you have to add a "?" counter on each stack, but I think it is better than deleting extra "?" counters.

**Comment by jrvjrv** [comment]
Ok, another thing I just learned: build your stack using unconcealed counters and add a "?" from the "?" tab in the counter tray on top, i.e. don't use ctrl-c. There's no need to pre-conceal the others counters in the counter tray, although that works too.

**Comment by sage944** [comment]
The “Conceal-in-the-tray” idea has merit if you can set up concealed.  If a stack gains Concealment at the end of its CCPh then a single “?” counter dropped onto the stack or concealing the top counter works.  I was thinking that if you drag and select a number of counters and do a CTRL+C then EVERYTHING gets a “?”.  When you stack them the lowest “?” would get eliminated automatically leaving the concealment in place.  Similarly, if a counter is “pulled out” of a stack—a personnel unit moves off, for instance—it then grows a “?” of its own if it is still concealed.

I really wished I knew more about Java.  I would code it or at least attempt to.  I know it would be a complicated logical process ‘cuz, it make my head hurt thinkin’ ‘bout it.

Have a Happy New Year and Good Hunting!  VASL is a great interface, no mistake!

Best,
Jeffrey D. Fisher
Omaha, NE USA


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by derimmer** [comment]
Honestly, this is a solution in search of a problem. 

You are worried about setting up ? stacks in the view of your opponent - reinforcements in particular. Do what every opponent I have ever played does and ask them to look away from the screen (or minimize the vASL window) until you are done. This happens all the time in my VASL games and has never been a problem.

I just don't see anyone investing time and effort to make the changes you want (especially since messing with ? counter code is difficult and risky). Too little benefit for too much effort. 

I am willing to be convinced otherwise but so far I just don't get it.

**Comment by sage944** [comment]
Okay.  I’ll just work around it…somehow.  I was concerned only then when my opponent concealed a stack by CTRL+C it made the stack double in height because all counters in the stack got a “?” even the MGs.  😊  Kind of amusing but tedious to “clean up”.

I do not concern myself with whether or not the opponent is viewing you concealing your stacks; there’s no control of that.  The Concealment is still there regardless of whether the opponent “knows” what’s in the stack.  The “Fog of War” would be nice but difficult to code.  I get that.

All-in-all, VASL is a great interface and versatile in many ways.  I get something out of “building” maps to make a scenario for.  Hell, I might have enjoyed a career as a cartographer!

Thanx for your replies.  Have a great New Year!  It might have been better had the Cornhuskers gone to a bowl game this year.  ☹

Best,
Jeffrey D. Fisher
Omaha, NE USA


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by derimmer** [comment]
I think we have had a good discussion about this. I am going to close the issue. @jrvjrv has already created a new spin-off issue around communicating some of the keystroke commands. See #1274. I will comment on that shortly

**Comment by sage944** [comment]
😊 Is that to say I’m a VASL “mover and shaker”?  😊

Have a great day, chief!

Best,
Jeffrey D. Fisher
Omaha, NE USA


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
