### ISSUE TITLE
Free French SW

### ISSUE THREAD

**Issue by WaterRabbit64** [vasl-developers/vasl#1169]
The Free French (blue) support weapons are missing the PIAT(b).

The Free French Radio has an incorrect contact value of "7".  It should be "8".

**Comment by derimmer** [comment]
@BigAl737 any chance you could send me the images for these two? I can take it from there.

**Comment by BigAl737** [comment]
Radio(b) is in addition to the existing French radio with contact value 7. The flip side is the existing French R1/X6 malf side.
![frRadio(b)](https://user-images.githubusercontent.com/10384413/218299053-822750f6-3b3c-4d2c-a01a-17fd074d560c.png)
The PIAT is an add on counter to the French LATW counters menu; front/back
![frPIAT(b)](https://user-images.githubusercontent.com/10384413/218299087-90d1dd6a-a1e9-4879-a237-a50c7c8316d9.png)
![frPIAT(b)B](https://user-images.githubusercontent.com/10384413/218299089-c151f46b-dd9b-4458-a6cd-f100def597e6.png)
