### ISSUE TITLE
Hide HIP units only

### ISSUE THREAD

**Issue by jrvjrv** [vasl-developers/vasl#1181]
If a player wants to take a snapshot of an on-going game to post on a social media site, HIP units appear on the map "ghosted". If it is possible that the player's opponent might view the image it would be nice if there were a way to make the HIP units invisible instead of ghosted. I suggest adding another stage to the "show/hide pieces/draggable overlays" button, but that is only a suggestion.

**Comment by zgrose** [comment]
I like the latter better since then you don't have to un-expand stacks and/or reveal labels on concealed units.

**Comment by derimmer** [comment]
I was starting to look at this today. Basically, we just piggyback on a VASSAL class, Imagesaver, for this task. We should be able to overwrite the parts necessary to make changes. 

BUT, and it's a big but, in VASSAL this class shows as Deprecated for Removal. Meaning that they intend to get rid of this class at some point. I don't know if they intend to replace it with something else or what. 

I have posted in the VASSAL forums and will see what response I get. 

But until then, I think this will have to go on hold. I am going to shift it from 667 to 668.

**Comment by uckelman** [comment]
The only deprecated parts are the `launch` member and one inner class. VASL isn't using either of those, so there should be no problem.

**Comment by derimmer** [comment]
> The only deprecated parts are the `launch` member and one inner class. VASL isn't using either of those, so there should be no problem.

Thanks. Got the same reply from Brent over in Vassal. 

What we want to try and do is save the map image with the opponent’s view. We have this as an option when we do “Sace contents to text file.” So I will look over there and see if it shows me how to adjust ASLImageSaver in the same way.

**Comment by derimmer** [comment]
@jrvjrv @zgrose 

While it took me a while to sort out the differences between the image saver code and the text saver code, once I did so, implementing the preferred solution was very easy. So easy that it worked first time which almost never happens (to me at least). 

The fix will be in 6.6.8-beta4. After selecting Save Map As PNG Image, players will get the same Save As Seen by Opponents? dialog, with a Yes/No choice. 

Here we see the results of a quick test (snipped to show the key part and not the full map as was saved):

Yes:  
![image](https://github.com/vasl-developers/vasl/assets/7696161/b22fde2c-3344-411e-a156-07fbad09c37d)

No: 
![image](https://github.com/vasl-developers/vasl/assets/7696161/a93aa01d-96dd-4ffb-afbc-179d66533a20)

@jrvjrv does this solution address your original suggestion satisfactorily?
