### ISSUE TITLE
Counter dimensions in the buildFile

### ISSUE THREAD

**Issue by pacman-ghost** [vasl-developers/vasl#1195]
From VASL 6.6.2, the counter dimensions in the `buildFile` seem to have changed e.g.

In 6.6.1:
```
    <VASSAL.build.widget.PieceSlot entryName="50* MTR" gpid="2465" height="48" width="68">
    <VASSAL.build.widget.PieceSlot entryName="81* MTR GrW 34" gpid="2488" height="60" width="80">
```

In 6.6.2 thru 6.6.4:
```
    <VASSAL.build.widget.PieceSlot entryName="50* MTR" gpid="2465" height="64" width="75">
    <VASSAL.build.widget.PieceSlot entryName="81* MTR GrW 34" gpid="2488" height="64" width="75">
```

IOW, 1/2" and 5/8" counters are the same size. Is this intended? They're also not square, but that's another issue... :-)

vasl-templates uses the `height` attribute to identify 1/2" counters, so it's currently showing everything as 5/8".

**Comment by derimmer** [comment]
I certainly did not make such a change deliberately and I don't know anyone who did. 

If you select the buildFile in github and then select History in the top right corner you can see all the commits that changed the buildFile. 

6.6.1 was released Oct 15, 2020, and 6.6.2 on April 26, 2021. If you view all of the buildFile commits (about 30) between those dates you should be able to find which one(s) made those changes. Then we can go from there.

**Comment by pacman-ghost** [comment]
It's happened here:
```
commit 4b3d397909ad498fc9f466e7661d6ed1070625af                                                      
Author: Doug Rimmer <dougrimmer@rogers.com>                                                          
Date:   Fri Mar 5 11:04:20 2021 -0500                                                                
    #878 make weather/ec counter label background transparent                                                             

dist/buildFile
```

**Comment by derimmer** [comment]
OK. That makes me the culprit. And I can certainly attest that there was no intention or reason on my part to have done so. I can see the the commit made 8500+ changes to the buildFile!

What solution do your need? Do you need all 5/8" counters to revert to the 60x80 size? Do you need the 1/2 counters to revert to 48x60?

Given that we have made considerable other changes to those counters in subsequent commits, I am thinking that text-editing the buildFile, which I am normally loath to do, may be the best solution. I should be able to do a replace all that does not screw up the file.

**Comment by pacman-ghost** [comment]
> What solution do your need? Do you need all 5/8" counters to revert to the 60x80 size? Do you need the 1/2 counters to revert to 48x60?

It doesn't really matter what's in there, just that there's some way to differentiate between 5/8" and 1/2" counters. Right now, vasl-templates checks for height <= 48.

How is this file maintained? I was guessing it's generated from some other files, or maybe you maintain a `.vmod` using VASSAL, and something went wonky along the way.

My first question is: do we know how this happened? Otherwise, it's likely to happen again. Or, reverting the wonkiness might restore the original values...? 

Otherwise, I can probably whip up a quick script that extracts the old values from the 6.6.1 buildFile, and insert them back into the 6.6.4 file (a "replace all" might not be enough, since we need to know which counters are 5/8" and which are 1/2")

**Comment by derimmer** [comment]
> How is this file maintained? I was guessing it's generated from some other files, or maybe you maintain a `.vmod` using VASSAL, and something went wonky along the way.
> 
> The question is: do we know how this happened? Otherwise, it's likely to happen again. Or, reverting the wonkiness might restore the original values...? If you're using VASSAL, this might be some new behaviour (or a bug), so the problem will just come back again.
> 
> Otherwise, I can probably whip up a quick script that extracts the old values from the 6.6.1 buildFile, and inserts them back into the 6.6.4 file (a "replace all" might not be enough, since we need to know which counters are 5/8" and which are 1/2").

The buildFile is not maintained as such. It is usually changed by VASSAL itself when editing/adding counters via the VASSAL editor. The buildFile can be text-edited directly but I myself only do this in two situations: (1) to add a reference to a new custom code class that needs to be added to VASL and "built" at runtime; (2) to cut-and-paste counters into the file. All these counters are also built at runtime when VASL loads. 

I have not had time to go back and see what I was doing at the time and how such changes could have gotten into the buildFile. I certainly have never knowingly changed every 5/8 counter. At this point, I can't tell you how it happened.  One idea I have is that a prototype got changed and that changed all the counters that use the prototype. But I haven't been able to check this. 

Given all the changes that have taken place since then, I would say that "reverting the wonkiness" is not doable.  I certainly would not attempt it. 

If you want to develop a script that would likely be the best option. However, it is important that it be applied to the most current version of the build file. Unlike code files, github does not merge buildFile changes; it replaces the older file entirely with the new file. So we would want to be sure that you have the most recent version. I am working on a number of bug fixes at present. Most of these do not result in changes to the buildFile but we will need to coordinate so we don't overwrite each other's work.

**Comment by pacman-ghost** [comment]
> Given all the changes that have taken place since then, I would say that "reverting the wonkiness" is not doable. I certainly would not attempt it.

When I say "wonkiness", I mean maybe there was a config setting in the VASSAL editor that was inadvertently changed, or maybe VASSAL introduced a new default size for counters that no-one noticed, and has been applied to all your counters, something like that. In such a case, it would be just a matter of fixing the underlying problem, not manually reverting every single change in the buildFile :-)

> Unlike code files, github does not merge buildFile changes; it replaces the older file entirely with the new file.

That would be Github doing this, not git, but yes, I would wait for a quiet time in your dev cycle to do this.

It's easy for me to write a script to restore the original values, but it's a waste of time if VASSAL is going to undo it all the next time you make a change to a counter :-/

How about trying this:
- you manually revert one counter (e.g. the 50* MTR) back to 48x68
- feed that modified buildFile into VASSAL, or whatever it is you do, and make a change to another counter
- check if the 50* MTR is still 48x68, or if it's been changed back to 60x80

**Comment by derimmer** [comment]
Sounds like a plan. Should be able to try this over the next couple of days.

**Comment by derimmer** [comment]
In my dev environment, I opened the buildFile and edited the Ger 50* mtr, changing the height="64" width="75" to height="48" width="68". I built and ran the project in my dev environment. It worked fine, no noticeable change in counter appearance. I searched on height="48" width="68" in the buildFile and the one that I created was the only instance.

Next, I built the VASL module outside of my dev environment using the mvnw command from a command line prompt (this is the way I was taught to build the VASL mod and I do it this way every time). I copied the VASL module to a new location, opened VASSAL and used the VASL editor to make an unrelated change to a different counter (I deleted a DBCommon prototype from a blank 5/8 counter.  I saved the change and ran the new VASL module under VASSAL. It worked fine, no noticeable change in counter appearance. 

I then renamed the .vmod to .zip, and opened the zip file. I opened the buildFile and searched for height="48" width="68". I found that all the items in the panelwidget with the 50 * mm mtr that I edited had changed to height="48" width="68" even though I had not edited them myself. Plus, when running the .vmod under VASSAL I had dragged a squad onto the board and dropped a 50*mm mtr on top. All of the counters in the panelwidget holding that squad had changed to height="48" width="68".  Next, I discovered that in the panel widget holding the 5/8 blank that I edited, the 1/2 counters had changed to height="48" width="68" and the 5/8 counters had changed to height="60" width="80". One counter switched to height="49" width="68". Another switched to height="48" width="48".  Finally, one other panelwidget, Unit--Basic, had all counters with height="48" width="68". I had at one point concealed the squad added a CX counter to the stack when testing the .vmod. 

So it appears that a change to a few counters can spread as they get used in games. It appears that VASSAL makes adjustments to synchronize sizes. Sort of. 

In no way could I see any visible differences.  

Editing the buildFile directly is always a bad idea and I am not certain whether the fix I suggested will work.

@uckelman what to the height and width references in the buildFile signify? Is this just a reference to how they appear in the counter palette or does it effect how they loo on the map? If the image file is of a different size, is the image stretched or shrunk to fit? Or does the counter contain a transparent space around the image if necessary?

**Comment by uckelman** [comment]
Height and width for PieceSlots is unrelated to the size of the piece they contain. They reflect the preferred size of the PieceSlot as displayed in the piece palette.

**Comment by pacman-ghost** [comment]
OK, but the underlying problem is that VASSAL has started changing this preferred size for so many counters - can we stop it from happening?

**Comment by uckelman** [comment]
Why do you need to? As I said, it doesn't affect the sizes of any pieces. The sizes are the preferred sizes of the display in the piece palette, not of the pieces themselves. If you're relying on the PieceSlot width and height to represent anything other than the preferred size of the UI element in the piece palette, you're doing it wrong. It's only accidental that the width and height corresponded to piece sizes before.

**Comment by derimmer** [comment]
@pacman-ghost As I understand Joel's comments, we can freely change those height and width settings back to their previous vasl settings if that helps with your vasl-templates. I cannot see any reason not to do that in the short term. 

You are correct to worry about this problem arising for you again. It would seem to me that we need to help you find a more durable way of distinguishing between the 1/2" and 5/8" inch counters.  Off the top of my head, I don't know what that is but I hope that we can come up with something. 

I have a significant change to the buildFile coming up shortly as we have to add new prototypes to many vehicle counters. I would like to get that completed and then proceed to revert height and width. This should all be done before 6.6.5 releases this fall. Does that work?

**Comment by pacman-ghost** [comment]
There's no point reverting the values in the buildFile. I don't think there's anything you can do, I'm going to have to work around the problem at my end.

**Comment by derimmer** [comment]
Woke up at 4:00 am this morning with the absolute certain knowledge of what caused this problem. As you found, the commit that made the change involved the work I had done to update the EC/Weather counters. Part of this work was to add a label naming each of the counters. 

I believe these labels, which are visible in the counter palette, resulted in the changes to the buildFile. If I remove those labels and we revert all the other counters, I am thinking we will have stability in the buildFile. 

This is your choice. If you want to focus on developing a work around, which is probably necessary in the long-term, then I will leave the current buildFile as is.

**Comment by pacman-ghost** [comment]
> Woke up at 4:00 am this morning with the absolute certain knowledge of what caused this problem. 

Yeah, I know this feeling well :-/

> If you want to focus on developing a work around, which is probably necessary in the long-term, then I will leave the current buildFile as is.

Leave it. The work-around is a PITA, but it will give a more stable result. 

OTOH, I am in bprobst camp of not really liking those labels, so this could be my chance to get rid of them... :-D
