### ISSUE TITLE
Chinese LMG(j) doesn't show Malf'd side

### ISSUE THREAD

**Issue by BruceCarson** [vasl-developers/vasl#1229]
I, of course, managed to malf my LMG in a game.  But it turns out the counter doesn't seem to have a back-side...

<img width="101" alt="image" src="https://user-images.githubusercontent.com/3753108/193429612-a4028d03-c1bc-4020-93ea-b292c9ac6526.png">

**Comment by derimmer** [comment]
@BruceCarson @styson AFAI can tell, this counter is in the BFP extension and so should be referred to them. 

I am going to close this as a VASL issue.
