### ISSUE TITLE
Dice over map display bug

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#1237]
See http://www.gamesquad.com/forums/index.php?threads/vasl-6-6-5-is-released.176609/

**Comment by derimmer** [comment]
@mtl1971 Morris, you are doing such great work fixing the errors I created in ASLChatter! Thank you. 

Would you be able to take on this one as well? It relates to my post of Oct 28 in the above thread. Basically the background colour of the text panel (not the font colour) is not changing between the local and remote player's dice rolls. This is for dice over the map. Thanks.

**Comment by mtl1971** [comment]
Sure, no trouble - I'll take a look.

**Comment by mtl1971** [comment]
This seems to do it:
https://github.com/vasl-developers/vasl/pull/1253/files

Though I'm not sure if there is anything else relying on the '...' in the user name

**Comment by derimmer** [comment]
> This seems to do it: https://github.com/vasl-developers/vasl/pull/1253/files
> 
> Though I'm not sure if there is anything else relying on the '...' in the user name

No there isn't. I am pretty sure that the ". . . " was just a bit of style we added in the previous VASL version of the chat window. So, no harm to take it out.

**Comment by derimmer** [comment]
You also added a "no third dice" message. Is this necessary?

**Comment by mtl1971** [comment]
Yes - for the situation where one player has turned on dust, and the other
has not... there may be a more elegant solution, but the recent changes
were causing the game to crash for me when I had dust on, but my opponent
did not in 6.6.5.

**Comment by derimmer** [comment]
> Yes - for the situation where one player has turned on dust, and the other has not... there may be a more elegant solution, but the recent changes were causing the game to crash for me when I had dust on, but my opponent did not in 6.6.5.

I see the value in that. I noticed when I was testing out some other code in solo mode that I was getting a lot of "no third dice" messages.  Our solitaire-playing friends may find that a bit tiresome. 

Do the messages go away if playing an opponent and neither have dust turned on?

**Comment by mtl1971** [comment]
Yes. the message should only appear if one person has dust on, and the
other does not.

**Comment by mtl1971** [comment]
Argh - actually there is a problem with doing that - just ignoring them is probably the best way to handle them.
https://github.com/vasl-developers/vasl/pull/1263
