### ISSUE TITLE
Extend map border to 400px

### ISSUE THREAD

**Issue by mistertakai** [vasl-developers/vasl#124]
The map edge is 200px wide right now (if I'm not mistaken). This leads to frequent problems with offboard setup and (more severe) to stack extension problems at the top of the map. I find myself moving stacks frequently down in the map window, just so they can be expanded and a unit picked.

I would suggest to double the map edge width, even though that means that users with small displays need to scroll more.

I'm not sure what this change would meand for updating existing logs. Could be that units will be off by 200x200 then.

**Comment by davidsullivan317** [comment]
This change makes games started in 6.1 and before incompatible. All pieces are offset by the additional 200 pixels so players will either have to finish on 6.1 or move all of the counters to the right spot. FYI
