### ISSUE TITLE
Third Die Not Showing

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#1243]
The third die required by Heavy Dust and higher is not showing.

**Comment by mtl1971** [comment]
Hi @derimmer - here's a PR to reinstate the 3rd DR:

https://github.com/vasl-developers/vasl/pull/1248

I'm not sure if you are still tinkering with the new HTML chat window - if so, please do give it a once over to ensure it isn't going to interfere with your work...

**Comment by derimmer** [comment]
Thanks for this @mtl1971. Seemed to work perfectly in my tests and I agree with the refactoring of the dice classes.

**Comment by derimmer** [comment]
@mtl1971 Testing this after your last commit. 

When online with another player, if one player has set a dust level but the other has not (No Dust) then the player with the No Dust level will not see any IFT or TH DR made by his opponent. Instead, he will see a * null message. 

I am ok with this. It clearly indicates to players that something is wrong. 

If the player with No Dust makes a TH or IFT DR then the player who has the Dust setting will see a message such as      
TH ... Hubertus Hull, *no third die* . Again this seems fine, as it flags an inconsistency. 

Is this what you expected?
