### ISSUE TITLE
Dice Over Map Sniper Activation Bug

### ISSUE THREAD

**Issue by BruceCarson** [vasl-developers/vasl#1245]
The SA prompt should not show for a single die:
![image](https://user-images.githubusercontent.com/3753108/202823710-fe5fcdcc-436b-42c6-89d4-d18173b76f5b.png)

In the Log, the SA correctly showed for the 1st roll, but did not show for the single die.

**Comment by mtl1971** [comment]
I think this fixes it.
https://github.com/vasl-developers/vasl/pull/1251

**Comment by derimmer** [comment]
@mtl1971 

The PR for this contained some non-code files that were messing the build process. 

I have reverted the PR and build now works.

I will push the SAN code change.

**Comment by mtl1971** [comment]
Sorry about that!

**Comment by derimmer** [comment]
Believe me, this was small potatoes compared to the mistakes I usually make.
