### ISSUE TITLE
minefield counter labels changed?

### ISSUE THREAD

**Issue by zgrose** [vasl-developers/vasl#1268]
What used to say Minefield, Minefield Dummy, Minefield AP and Trip Flare in 6.6.4 just says Minefield, Minefield, Minefield, Red Trip Flare  in 6.6.5.

<img width="793" alt="Screenshot 2022-12-20 122310" src="https://user-images.githubusercontent.com/5044847/208738900-87f7dd59-536a-40c6-92fa-72c58cdec6b3.png">

**Comment by derimmer** [comment]
Using 6.6.5/3.6.7 and 6.6.6-beta1/3.6.9, I see the Dummy, AP, and AT labels. Perhaps something in VASSAL3.6.8 removed them and this has been fixed in 3.6.9. @zgrose have you tried this with 6.6.5 and 3.6.9?

**Comment by derimmer** [comment]
Checked again using vasl6.6.6-beta5 and vassal3.6.11. Labels are displaying properly. This appears to have been triggered by vassal3.6.8 and resolved by 3.6.9.
