### ISSUE TITLE
Move selected items up/down in a stack while expanded using keystrokes

### ISSUE THREAD

**Issue by jrvjrv** [vasl-developers/vasl#1270]
As far as I know the only way to change order in a stack is with a mouse. This can be amazingly awkward, especially when there are a mix of ⅝" and ½" counters, some are HIP and the stack is tall. 

Suggested behavior: on keystroke for up all selected units that are currently directly beneath an unselected counter move above that counter. 
e.g. with "S" for a selected counter, "U" for an unselected counter using the keystroke for "up": S-S-U-S-U ⇒ S-U-S-U-S ⇒ U-S-U-S-S ⇒ U-U-S-S-S

**Comment by derimmer** [comment]
@jrvjrv on my machine, using Win10, and VASSAL3.6.7/VASL6.6.5, if I expand and stack and then select a unit(s) with the mouse, the down arrow key will then move any selected counters to the bottom of the stack and up arrow will move them to the top. Left arrow will move then down one position in the stack while right arrow will move them one position higher in the stack. This works even when multiple selected units are not adjacent to each other in stacking order. 

I have just tested this with the kind of stack you describe and all seems to work well including ? gain/loss.

Is this the behaviour you wanted? I don't know if the same keys work on a MAC or Linux system but some key combo should.

**Comment by jrvjrv** [comment]
Thank you. This does work in linux. This behavior is not documented in the vasl shortcut keystrokes help. I will close this bug and open a new one for the documentation.
