### ISSUE TITLE
support lack of right of inspection for unconcealed units, especially in pillboxes/caves

### ISSUE THREAD

**Issue by jrvjrv** [vasl-developers/vasl#1273]
Per B30.7 & G11.52 an opponent may not inspect the contents of a pillbox or cave except as noted, even when the contents are unconcealed. Currently this relies on the opponent not mouse-overing the stack. This then implies the opponent can't look at the units outside the pillbox/cave. My first thought would be a concealment-like behavior but the counters don't have a "?" and use rather some other marker so it's clear they are not concealed but they are not available for inspection, perhaps the asterism, "⁂".

**Comment by zgrose** [comment]
Couple comments...
Turning off the detail viewer wouldn't prevent anyone from expanding the stack, so I presume this idea is focusing on addressing the accidental revelation of information the player shouldn't have and not a "security" measure.

Secondly, if you expand the thought to a non Location based feature, you have the extra issue that you already brought up about free LOS checks but added to that is the observing unit may be HIP. So player B may *think* there is no EU in LOS when in fact there is.

I think a HIP ? counter is really the best solution for both A2.9 and A12.16 and caves/pillboxes and is already in game. Maybe an easy way to apply/remove the No ROI blocker would be a more viable path?

>>> turning off the detail viewer until both sides have finished setup.
Tangentially, if/when you can do this, we probably should be able to pass/share the night/weather/dust/etc layers as well? That would be super handy.

**Comment by derimmer** [comment]
Thanks Zoltan

I agree that turning off the detail view deals with the accidental reveal only.

I agree that a HIP counter may be the best way. And that an easier way to add/remove it would be useful. You may be right, a button to add a ? HIP at the 2nd position in each stack of a player's side and then the owning player removes as required.  Am I right in thinking that once NO ROI is lost during play, it can never be regained? If a unit goes out of LOS, it may conceal or attempt to conceal but it does not regain NO ROI?

**Comment by derimmer** [comment]
> we probably should be able to pass/share the night/weather/dust/etc layers as well? That would be super handy.

Not sure what is meant by this?

**Comment by zgrose** [comment]
AFAIK, you only have ROI when in LOS, so it can come and go during play.

> Not sure what is meant by this?
If you play a game and toggle on Night and then save the game, when you open that log up, the Night won't be on.

All these settings don't persist in the save.

![Screenshot 2024-07-31 174326](https://github.com/user-attachments/assets/9f6aed44-3527-44cd-ab24-16c72b3a16af)

**Comment by derimmer** [comment]
LOL. So you were just piggybacking another issue onto this! Well done. 

It is issue #1515 and I will give it some attention next!

**Comment by zgrose** [comment]
Just figured I'd mention since being "in setup" would probably have the same problem. :)

**Comment by derimmer** [comment]
Thinking about the NO ROI approach. How does this sound

Add a version of each nationalities' ? counter to the "?" Panel for that nationality, replacing the "7 Morale" text with "No ROI".

Players could drag-drop it onto stacks, position it and HIP it. 

This works but is slow and laborious. So in addition to that:

Add a "Add ROI" menu item to the Unit prototype so it would show on virtually every unit/gun/veh in a stack. 

The item would have a submenu of two items "This stack" and "All Friendly stacks". 

These two items would be Trigger Actions and would do three things, create the counter at the top of the stack. Select the counter and move it down one counter in the stack. HIP the counter.  It would have to test that the stack has more than one counter.

The NoROI counter would have a menu item "Remove No ROI" and two sub options, "This stack" and "All Friendly Stacks".

This strikes me as workable. What do you think?

**Comment by zgrose** [comment]
Seems reasonable. I'm not someone that would probably use the feature, so maybe ask on GameSquad what people think? Always good to measure twice and cut once.

**Comment by derimmer** [comment]
I have pushed up code changes and image files to implement this. I missed linking the commit to this issue. The feature will appear in the next 669-beta and beyond.
