### ISSUE TITLE
Document move selected items up/down in a stack while expanded using keystrokes

### ISSUE THREAD

**Issue by jrvjrv** [vasl-developers/vasl#1274]
Selected items move up/down in a stack by pressing arrow keys, up=move to top, down=move to bottom, left=move up one past one unselected item, right=move down past one unselected item. This should be documented in the vasl shortcut keystrokes help.

**Comment by derimmer** [comment]
@jrvjrv I agree. 

It should be noted that the use of the arrow keys (and other counter/stack keystrokes) are documented in the Counters help item. 

The Counters and keystrokes shortcuts documents could well be merged into one document but personally I think there is a benefit in having two separate items. 

I will add the arrow key shortcuts to the vasl shortcut keystrokes item under help.  This will be in VASL6.6.6.
