### ISSUE TITLE
Custom colors for map pointer/"this guy" thingy

### ISSUE THREAD

**Issue by davidsullivan317** [vasl-developers/vasl#131]
Different "this guy" colors for each player -- so when multiple people are kibitzing on the board you know who is referring to what

Also apply "zoom" factor to the size of the circle so it's smaller when zoomed out.

**Comment by derimmer** [comment]
We have lived without this for 6 years. Closing

**Comment by uckelman** [comment]
We've already added this for VASSAL 3.5, so you'll get it for free in a few months.

**Comment by davidsullivan317** [comment]
That's good news. I've had multiple people ask me about using the pointer in other modules.

**Comment by derimmer** [comment]
Both the VASL PieceFinder and VASSAL Map Flare exist in VASL at present. Neither appear to allow users to customize the colour. 

No one is complaining.  Closing
