### ISSUE TITLE
Remove colors file from bdXX files

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#1313]
This is the final round of removing txt files from board archive files (bdXX). 

Only two txt files are now required: data and SSRControls (where necessary). 

I will continue to try to port the SSRControls files into the BoardMetaData.xml files. My problem at present is that I can't get the code to read them properly.

**Comment by BigAl737** [comment]
Data is still required?Sent from my iPadOn Jan 27, 2023, at 10:41 AM, Doug Rimmer ***@***.***> wrote:﻿
This is the final round of removing txt files from board archive files (bdXX).
Only two txt files are now required: data and SSRControls (where necessary).
I will continue to try to port the SSRControls files into the BoardMetaData.xml files. My problem at present is that I can't get the code to read them properly.

**Comment by derimmer** [comment]
@BigAl737 I believe that it is for most TPP and HASL boards which do not have a BoardMetaData.xml file (and are not likely to grow one in the near future). 

I prefer an all-or-nothing approach so in terms of new files (including the famous bd77) we should continue to have a data file and a BoardMetaData.xml file - but no need for a colors file!

Logically, at some point we should add a BoardMetaData.xml file to every board and then delete all the data files. But that may be a lot of work for very little gain. 

Clearing out all of the other files gives us a big gain in terms of consistency of color maps used in transforms and overlay management. So it has been worthwhile.

**Comment by derimmer** [comment]
Data is not required. . . I just tested that with a geo board. As Sully wrote in his message (which I don't see here), we could just delete it. Being a bit of a pedant, I would prefer keep the data file until we can delete it from all boards. But that is just my preference. If someone deletes a data file, I am certainly not going to add it back in!

@BigAl737 when creating a new board with a BoardMetaData.xml file, I would prefer that you also add a data file but it is not required and so it's up to you. When updating an existing board that already contains both a BoardMetaData.xml file and a data file, it is NOT necessary or useful to update the data file. You can either delete it or just leave it alone (my preference).

**Comment by BigAl737** [comment]
Ahh, very good. I didn't screw things up :-)

Thanks again for all you're accomplishing to make VASL better Doug. Your efforts seem tireless. We are a fortunate VASL community indeed.

**Comment by derimmer** [comment]
All colors files removed except for deluxe boards e-h which have some funky colors and the few HASL boards with LOS. I will test each of those individual to ensure terrain transforms still work.

**Comment by derimmer** [comment]
I have also updated the Wiki page in the repo to identify which files are now required to create bdXX archive files.
