### ISSUE TITLE
Japanese infantry crews break behavior

### ISSUE THREAD

**Issue by jrvjrv** [vasl-developers/vasl#1324]
A "break" item shows on the right-click menu, with keyboard shortcut ctrl-f.

Expected behavior: 2-2-8 crew is replaced with a broken 1-2-7 Japanese crew and marked with a DM counter. This would be the case for a voluntary break.
Actual behavior: 2-2-8 crew is not replaced; DM counter *is* placed

Note if the striped counter is showing, ctrl-f works as expected.

**Comment by derimmer** [comment]
In VASL 6.6.5, the 228 crew on the SQ tab and the one on the HS tab have different right click menus.  The SQ one does not have a Break item on the menu; the crew on the HS does. 

I believe I have fixed the behaviours and made the two crew counters consistent. This should be in 6.6.6
