### ISSUE TITLE
Japanese crew: switch between infantry and "vehicle" crew

### ISSUE THREAD

**Issue by jrvjrv** [vasl-developers/vasl#1325]
Currently there is no way to replace a Japanese infantry crew (2-2-8) with a "vehicle" crew (1-2-7). Add a keyboard shortcut and menu item to enable this. Ctrl-v seems to me the obvious choice for shortcut, base on the squad-halfsquad model.

**Comment by derimmer** [comment]
Is there an ASL game event that would trigger this? when would you need to do this?

**Comment by jrvjrv** [comment]
> Is there an ASL game event that would trigger this? when would you need to do this?

Any break result, voluntary or involuntary, from either 2-2-8 or 1-2-8 will result in a broken 1-2-7 vehicle crew [G1.3]. It would be nice if an already-striped 2-2-8 (a 1-2-8) striped again or broke to a broken 1-2-7. But I think being able to move between the two (2-2-8, 1-2-7) would be a convenience too.
