### ISSUE TITLE
CPVA crew: switch between infantry and "vehicle" crew

### ISSUE THREAD

**Issue by jrvjrv** [vasl-developers/vasl#1326]
Currently there is no way to replace a CPVA infantry crew (2-2-8) with a "vehicle" crew (1-2-7) in the context menu or by keyboard shortcut. Add a keyboard shortcut and menu item to enable this. Ctrl-v seems to me the obvious choice for shortcut, base on the squad-halfsquad model.

**Comment by derimmer** [comment]
Same question as for the Japanese: what game event would trigger this?

**Comment by jrvjrv** [comment]
> Same question as for the Japanese: what game event would trigger this?

Any break result, voluntary or involuntary, from either 2-2-8 or 1-2-8 will result in a broken 1-2-7 vehicle crew [W7.28]. It would be nice if an already-striped 2-2-8 (a 1-2-8) striped again or broke to a broken 1-2-7. But I think being able to move between the two (2-2-8, 1-2-7) would be a convenience too.

**Comment by derimmer** [comment]
> Any break result, voluntary or involuntary, from either 2-2-8 or 1-2-8 will result in a broken 1-2-7 vehicle crew [W7.28]. It would be nice if an already-striped 2-2-8 (a 1-2-8) striped again or broke to a broken 1-2-7. 

Yes, I think I have all of the above working now. And this is in accordance with the rules of ASL. 

> But I think being able to move between the two (2-2-8, 1-2-7) would be a convenience too. 
I cannot find anything in the rules that would require a GO 228 to be replaced by a GO 127. So, as you say, a convenience.  

I cannot think of another situation in VASL where we code such conveniences. 

Personally, I am inclined to hold off on this for now.

**Comment by jrvjrv** [comment]
> > Any break result, voluntary or involuntary, from either 2-2-8 or 1-2-8 will result in a broken 1-2-7 vehicle crew [W7.28]. It would be nice if an already-striped 2-2-8 (a 1-2-8) striped again or broke to a broken 1-2-7.
> 
> Yes, I think I have all of the above working now. And this is in accordance with the rules of ASL.
> 
> > But I think being able to move between the two (2-2-8, 1-2-7) would be a convenience too.
> > I cannot find anything in the rules that would require a GO 228 to be replaced by a GO 127. So, as you say, a convenience.
> 
> I cannot think of another situation in VASL where we code such conveniences.
> 
> Personally, I am inclined to hold off on this for now.

If you have coded the 2-2-8⇒1-2-8⇒broken 1-2-7 chain, you have done most of the work that needed to be done. I may not have realized that there was such a chain at the time I wrote the bug because there was no way to go from the 2-2-8/1-2-8 to the 1-2-7. I may have suggested it to accomplish that.

The convenience I still see is if there was an error and the 1-2-7 was put out by mistake. If it is caught immediately then you can use undo, but if not, the only way to fix it is to delete the 1-2-7 and pull a 2-2-8 out of the counter tray. That's not awful because it won't happen very often but since the behavior is very like ctrl-v for casualty reduction of squads (and reversing that) think you might consider adding it. I figure it would be a fairly analogous behavior which might not be useful very often, but still might have an occasional benefit and in any event would cause no harm. Having the striping chain work for crews was the main object.
