### ISSUE TITLE
CPVA infantry crew: add break behavior

### ISSUE THREAD

**Issue by jrvjrv** [vasl-developers/vasl#1327]
Add new menu item and keyboard shortcut for break. On break, replace 2-2-8 crew with broken 1-2-7 crew. This would be the case for a voluntary or other non-combat break.

Note that the striped 1-2-8 crew has a "break" behavior and behaves as expected.

**Comment by derimmer** [comment]
Do they behave like Japanese crews in every respect or are there differences.

**Comment by jrvjrv** [comment]
> Do they behave like Japanese crews in every respect or are there differences.

As far as I know they should be the same.

**Comment by derimmer** [comment]
For testing purposes:

https://www.dropbox.com/s/0i0smwmhvfqi457/vasl-6.6.6-test.vmod?dl=0
