### ISSUE TITLE
French counter error

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#1335]
For the French, the 65mm INF Gun for the French, Ordnance Note 9 is a B11. VASL has it as a 12.

**Comment by BigAl737** [comment]
Here you go:

![frINF65s](https://user-images.githubusercontent.com/10384413/218184651-0102d02a-b2cc-4d45-8777-6ee8b4da2b8d.gif)

**Comment by derimmer** [comment]
Genius as ever @BigAl737!

Many thanks.
