### ISSUE TITLE
Give the Boards pages on vasl.info archive status 

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#1339]
When new boards are created or boards are updated, they are added to the repo here on Github to be used by the auto-synchronization  functionality in VASL. 

Traditionally, we have also pushed the bdXX files to VASL.info. 

Given the success of auto-synchronization and the large number of updates I triggered while removing the old school text files from bdXX files, I have stopped pushing changed or new bdXX files to VASL.info. 

We haven't told anybody this and only a couple of people seem to have noticed. 

Now that the removal of the text files is almost complete, it is time to decide whether to resume updating VASL.info or to add a notice to the boad pages at VASL.info explaining that these pages are no longer being updated. 

I vote for the second option. I see no reason to encourage people get bdXX files from vasl.info. I would not go so far as to remove the pages. They might be useful in some kind of apocalyptic situation where github was not available. 

Any thoughts or objections?

**Comment by BigAl737** [comment]
Option 2. Keeping both invites errors. I think it'd be easy enough to rebuild VASL.info after an apocalypse. Aren't boards saved locally after they are auto-synched? If so, players can still play scenarios with their locally downloaded boards until VASL.info is revived.

**Comment by styson** [comment]
I agree with dropping support for self-download.

**Comment by derimmer** [comment]
Pushed a commit to the website repo on Feb 15
