### ISSUE TITLE
LOS engine: hindrance cancelled by trench, foxhole but not by PFZ:Open Grnd

### ISSUE THREAD

**Issue by jrvjrv** [vasl-developers/vasl#1353]
LOS between 12F3 & 12H2 passes through 12G3, a grain hex. With no fortification counters hindrance is reported as one. With foxhole or trench in 12G3 no hindrance is reported. With a pillbox in 12G3 a hindrance of one is reported. With a PFZ:Open Grnd counter in the hex a hindrance of one is reported.

This also affects brush and orchard terrains. And A-T Ditches.

Expected: the presence of a foxhole or trench counter should not affect hindrances.
Desired: a PFZ:Open Grnd counter should affect hindrance

VASSAL version 3.6.11, vasl version 6.6.5

**Comment by derimmer** [comment]
The first part of this (dealing with foxholes and trenches) has been fixed in 6.6.6 and is in the beta mod. See issue #1220 

I don't believe the part dealing with PFZ: Open Ground has been fixed. It is going to have to wait for 6.6.8.

**Comment by derimmer** [comment]
I got PFZ done as part of #1438. It will be in 6.6.7.
