### ISSUE TITLE
Add Known Minefield Counters

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#1371]

**Comment by BrunoASL2023** [comment]
need the whole series of minefield counters: AT, AP< Dummy, Known (with left/right arrow,...)

**Comment by derimmer** [comment]
> need the whole series of minefield counters: AT, AP< Dummy, Known (with left/right arrow,...)

@BrunoASL2023 

Here is what the Mines window looks like today:

![minessnip](https://user-images.githubusercontent.com/7696161/224997586-0960b474-9842-42e3-8dbc-7c5d93c3d43e.PNG)

I know there was a problem with the AT and AP labels disappearing on this list but that has been fixed. 

We are working on adding Known Minefield counters. 

Beyond that, what do you want? I need something more specific than your post.
