### ISSUE TITLE
list of available boards not being sent to clients

### ISSUE THREAD

**Issue by jrvjrv** [vasl-developers/vasl#1387]
I downloaded a board yesterday (bdSA). It was in the list of available boards. Today if I hide the board in my boards directory (rename to sav.bdSA), SA no longer appears in the list of available boards. My guess is that the web service that delivers the list of available boards is not working. Unsure whether the bug should be here or in vasl-website.

**Comment by jrvjrv** [comment]
See also: https://boardgamegeek.com/thread/3051282/vasl-automatic-board-downloading

**Comment by jrvjrv** [comment]
Note that as far as I can see this state produces no errors or warnings to the user. When in this state vasl should at least notify the user.

**Comment by derimmer** [comment]
I believe I have found the problem: 

BoardVersionChecker.java contains a method that gets the list of boards and versions (v5boardVersions.xml) from the github repo:

It does so in the following method:

`private void readVersionFiles()  {

        // Need to disable SNI to read from Github
        System.setProperty("jsse.enableSNIExtension", "false");

        try {
            URL base = new URL(boardVersionURL);
            URLConnection conn = base.openConnection();
            conn.setUseCaches(false);

            //Properties p = new Properties();
            try (InputStream input = conn.getInputStream()){
                parseboardversionFile(input);
                //p.load(input);
            }`

This code has been untouched for several years and is actually no longer used. I replaced it in 2018 with a method in ASLBoardPicker for various reasons.  The code still runs when BoardVersionChecker.addTo() runs at startup and calls it. Starting yesterday, the code fails at the line "try (InputStream input = conn.getInputStream()){ with an IOException.

This line of code is in the ASLBoardPicker method that I added in 2018:

`private ArrayList<String> getallboards() {
        ArrayList<String> allboardslist = new ArrayList<String>();
        try {
            URL base = new URL(BoardVersionChecker.getboardVersionURL());
            URLConnection conn = base.openConnection();
            conn.setUseCaches(false);
            try (InputStream inputStream = conn.getInputStream()) {
                allboardslist = parseboardversionFile(inputStream);
            }
        } catch (IOException e){

        } catch (JDOMException e) {
            // throw new JDOMException("Cannot read the shared metadata file", e);
        }
        return allboardslist;
    }`

This method is the one that currently gets the list of boards and it is now failing as well.

Note the first line in the BoardVersionChecker method, which dates from 2014:
System.setProperty("jsse.enableSNIExtension", "false");

If I comment out this line (disabling the disablement) then the code runs both in BoardVersionChecker and ASLBoardPicker and auto-syncing works again. 

This makes no sense to me. I was working in the BoardVersionChecker method yesterday when this stopped working. But I did not touch the code that is broken.  I can find nothing on the internet to suggest that GitHub made a change. 

Can anybody offer any thoughts? @uckelman ? @davidsullivan317 ? 

The bad news is that I cannot fix this in VASL6.6.5. The disabling line is part of that build. 

The good news is that 6.6.6 is just about ready to go. However users will HAVE to upgrade to 6.6.6 to get the benefit. 

Any thoughts about why this happened or what I might have done to trigger it?

**Comment by derimmer** [comment]
Although we were catching the error in a try . . . catch, it was failing silently so no message that I can find. I will undo the fix and try to get the exception message. 

Here is the exception message:
detailmessage=PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
cause=sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed

Here is the stack trace:

stackTrace = {StackTraceElement[50]@7705} 
 0 = {StackTraceElement@7707} "java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)"
 1 = {StackTraceElement@7708} "java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:369)"
 2 = {StackTraceElement@7709} "java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:312)"
 3 = {StackTraceElement@7710} "java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:307)"
 4 = {StackTraceElement@7711} "java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1357)"
 5 = {StackTraceElement@7712} "java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1232)"
 6 = {StackTraceElement@7713} "java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1175)"
 7 = {StackTraceElement@7714} "java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)"
 8 = {StackTraceElement@7715} "java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:478)"
 9 = {StackTraceElement@7716} "java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:456)"
 10 = {StackTraceElement@7717} "java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:199)"
 11 = {StackTraceElement@7718} "java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:171)"
 12 = {StackTraceElement@7719} "java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1369)"
 13 = {StackTraceElement@7720} "java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1278)"
 14 = {StackTraceElement@7721} "java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:401)"
 15 = {StackTraceElement@7722} "java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:373)"
 16 = {StackTraceElement@7723} "java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)"
 17 = {StackTraceElement@7724} "java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:197)"
 18 = {StackTraceElement@7725} "java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)"
 19 = {StackTraceElement@7726} "java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)"
 20 = {StackTraceElement@7727} "java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)"
 21 = {StackTraceElement@7728} "VASL.build.module.map.ASLBoardPicker.getallboards(ASLBoardPicker.java:363)"
 22 = {StackTraceElement@7729} "VASL.build.module.map.ASLBoardPicker.refreshPossibleBoards(ASLBoardPicker.java:259)"
 23 = {StackTraceElement@7730} "VASL.build.module.map.ASLBoardPicker.setBoardDir(ASLBoardPicker.java:199)"
 24 = {StackTraceElement@7731} "VASL.build.module.map.ASLBoardPicker.addTo(ASLBoardPicker.java:188)"
 25 = {StackTraceElement@7732} "VASSAL.build.Builder.build(Builder.java:82)"
 26 = {StackTraceElement@7733} "VASSAL.build.AbstractBuildable.build(AbstractBuildable.java:104)"
 27 = {StackTraceElement@7734} "VASSAL.build.module.Map.build(Map.java:716)"
 28 = {StackTraceElement@7735} "VASSAL.build.Builder.create(Builder.java:127)"
 29 = {StackTraceElement@7736} "VASSAL.build.Builder.build(Builder.java:80)"
 30 = {StackTraceElement@7737} "VASSAL.build.AbstractBuildable.build(AbstractBuildable.java:104)"
 31 = {StackTraceElement@7738} "VASSAL.build.GameModule.build(GameModule.java:713)"
 32 = {StackTraceElement@7739} "VASSAL.build.GameModule.build(GameModule.java:644)"
 33 = {StackTraceElement@7740} "VASSAL.build.GameModule.init(GameModule.java:1913)"
 34 = {StackTraceElement@7741} "VASSAL.launch.Player.launch(Player.java:87)"
 35 = {StackTraceElement@7742} "VASSAL.launch.Launcher$1.run(Launcher.java:98)"
 36 = {StackTraceElement@7743} "java.desktop/java.awt.event.InvocationEvent.dispatch$$$capture(InvocationEvent.java:313)"
 37 = {StackTraceElement@7744} "java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java)"
 38 = {StackTraceElement@7745} "java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)"
 39 = {StackTraceElement@7746} "java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)"
 40 = {StackTraceElement@7747} "java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)"
 41 = {StackTraceElement@7748} "java.base/java.security.AccessController.doPrivileged(Native Method)"
 42 = {StackTraceElement@7749} "java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)"
 43 = {StackTraceElement@7750} "java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)"
 44 = {StackTraceElement@7751} "java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)"
 45 = {StackTraceElement@7752} "java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)"
 46 = {StackTraceElement@7753} "java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)"
 47 = {StackTraceElement@7754} "java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)"
 48 = {StackTraceElement@7755} "java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)"
 49 = {StackTraceElement@7756} "java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)"

**Comment by zgrose** [comment]
Yup. Certificate changed and/or one of its certs in the chain can’t be validated.

**Comment by jrvjrv** [comment]
As far as I read this is happening on access to boardVersionURL, i.e. https://raw.githubusercontent.com/vasl-developers/vasl/develop/boards/v5boardVersions.xml. In my browser I am able to access the url without any unusual warnings. Is there some cache of certificates that java uses that needs to be flushed?

**Comment by zgrose** [comment]
Every time this has happened to me at work, it’s because a cert is missing and Java doesn’t do all the background downloading that browsers do. Still no internet, here is something that you could try: download the latest Java20 JRE and replace the one in the VASSAL folder with that and see if that has the missing bits included. It’s a long shot.

It may also be that GitHub is now requiring SNI in some way? Not a network guy to know if that’s relevant to this.

**Comment by jrvjrv** [comment]
Wild guess: viewing the certificate for the boardVersionURL in firefox, it has dates:
```
Validity
Not Before Tue, 21 Feb 2023 00:00:00 GMT
Not After Wed, 20 Mar 2024 23:59:59 GMT
```
That is consistent with the certificate changing yesterday. I also note that the certificate is issued *primarily* to "*.github.io" and only has validity to "*.githubusercontent.com" via "Subject Alt Names." Is it possible that java does not inspect the "Subject Alt Names"?

**Comment by zgrose** [comment]
Running of a hotspot on my phone I can confirm that using Java20 changes nothing.

Just to confirm, @derimmer, that the URL being used is actually, exactly, ` https://raw.githubusercontent.com/vasl-developers/vasl/develop/boards/v5boardVersions.xml`?

**Comment by zgrose** [comment]
FYI, this is probably why that line was added in the first place: https://stackoverflow.com/questions/7615645/ssl-handshake-alert-unrecognized-name-error-since-upgrade-to-java-1-7-0/14884941#14884941

I mean, it **seems** like you might just have to build a 6.6.5a, with just that line stripped out. Rollback to that commit, create a 6.6.5a branch from that, make the edit and build.

**Comment by jrvjrv** [comment]
> FYI, this is probably why that line was added in the first place: https://stackoverflow.com/questions/7615645/ssl-handshake-alert-unrecognized-name-error-since-upgrade-to-java-1-7-0/14884941#14884941

In the link it suggests, "-Djsse.enableSNIExtension=false." I tried this but it had no apparent effect.

**Comment by zgrose** [comment]
That **should** be the link to the commit used for the release. But whatever works best.
<img width="1021" alt="Screenshot 2023-03-23 123933" src="https://user-images.githubusercontent.com/5044847/227293528-890aeaa2-e32f-43c8-965c-80ca3e98930e.png">

> In the link it suggests, "-Djsse.enableSNIExtension=false." I tried this but it had no apparent effect.
You set it outside the app, but then the app overrides it.

**Comment by derimmer** [comment]
In our case we want to enable the SNI. Try it with "-Djsse.enableSNIExtension=true" perhaps?

**Comment by jrvjrv** [comment]
> In our case we want to enable the SNI. Try it with "-Djsse.enableSNIExtension=true" perhaps?

Since the code explicitly sets it to false, presumably after the command line parameters are processed, that would probably not be productive.

**Comment by derimmer** [comment]
> That **should** be the link to the commit used for the release. But whatever works best. <img alt="Screenshot 2023-03-23 123933" width="1021" src="https://user-images.githubusercontent.com/5044847/227293528-890aeaa2-e32f-43c8-965c-80ca3e98930e.png">
> 
> > In the link it suggests, "-Djsse.enableSNIExtension=false." I tried this but it had no apparent effect.
> 
> You set it outside the app, but then the app overrides it.



> > In our case we want to enable the SNI. Try it with "-Djsse.enableSNIExtension=true" perhaps?
> 
> Since the code explicitly sets it to false, presumably after the command line parameters are processed, that would probably not be productive.

We are trying to undo that code. When I delete that line of code, board updating works. When the code runs and sets to false, board updating does not work.

**Comment by derimmer** [comment]
@zgrose I see the commit and when I click it I go to the commit, which was about adding BG1 to the boards list. Where should I go from there?

**Comment by zgrose** [comment]
Somewhere there should be a spot to create a branch from that commit. I'll be back at my desk in 5ish if you don't spot it in the meantime.

**Comment by derimmer** [comment]
Thanks. So, it appears that a VASL reissue is needed. I will try to do it with 665 using your advice @zgrose. I think I have found what you mean.

**Comment by zgrose** [comment]
BTW, @jrvjrv I think you're probably right about the Alt Names being at play here. I made a github.io repo and put the board version file in there and edited the build file to point to that instead and the drop-down list populated. Based on that StackOverflow above, SNI is often used for virtual hosting and so it kinda all ties together.

Of course, pushing a new build file (and managing a second repo) is basically like rolling out a new cut anyway, but it's nice to get some confirmation that we're not chasing a red herring.

**Comment by zgrose** [comment]
If you want, for curiosity, the edit to the buildFile is: `boardVersionURL="https://zgrose.github.io/v5boardVersions.xml"`
Again, it will only get the list and fail everywhere else.

**Comment by jrvjrv** [comment]
> SNI is often used for virtual hosting and so it kinda all ties together.

From what I (quickly) read, SNI is sort-of the inverse of alt names. In SNI the certificate served is dynamic based on the domain. alt names serves a single certificate which applies to a fixed list of domains. But this is only my very shallow understanding, and I could be very wrong.

**Comment by jrvjrv** [comment]
BTW rather than choosing one or the other, enableSNIExtension=true or =false, you might consider doing it both ways with a try/catch in case github decides to switch back. That's a bit kludgy but it has the advantage of being kludgy. 

Also it might be nice to have a status message from the board picker, e.g. 542 boards available on-line, 80 boards currently downloaded, 55 boards in boards directory but not listed on-line.

**Comment by zgrose** [comment]
>BTW rather than choosing one or the other, enableSNIExtension=true or =false, you might consider doing it both ways with a try/catch in case github decides to switch back. That's a bit kludgy but it has the advantage of being kludgy.

From what I've read, you can't (or couldn't) change it after it (https) has been called once. Seems like it would be best to leave it out of the source and then allow users to override via the command-line (in some way). Given that it is a 10+ year old hack there may be a more modern approach to the issue as well.

**Comment by jrvjrv** [comment]
Thanks for the 6.6.5.1 patch. vasl connect to server continues to work.

Are there any other places that vasl attempts to contact github? I will also note that at least two of the urls in dist/buildfile give 404 errors
```
boardRepositoryURL="https://raw.githubusercontent.com/vasl-developers/vasl/develop/boards/bdFiles"
overlayRepositoryURL="https://raw.githubusercontent.com/vasl-developers/vasl/develop/boards/bdFiles/overlays"
```
Not related to the current problem, but it would be nice to fix if these are being used somewhere and remove if they are not.

**Comment by zgrose** [comment]
Those are partial URLs, IIRC. The board and/or overlay file name is appended to them.

**Comment by jrvjrv** [comment]
> Those are partial URLs, IIRC. The board and/or overlay file name is appended to them.

Ah. As part of trying to figure out what was going wrong I tested all the urls found in buildfile. Appending a board name does indeed generate a download.

**Comment by uckelman** [comment]
I'm having trouble following this. Where can I see a diff of the proposed change?

**Comment by jrvjrv** [comment]
@zgrose one minor quibble with the patch. the version shows as "VASL 6.6.5-beta3 - VASSAL 3.6.11" in the bar rather than "VASL 6.6.5.1".

**Comment by zgrose** [comment]
@uckelman should be that just `System.setProperty("jsse.enableSNIExtension", "false");` was removed/commented out.

@jrvjrv 6.6.6 will solve that problem. :)

**Comment by derimmer** [comment]
> @zgrose one minor quibble with the patch. the version shows as "VASL 6.6.5-beta3 - VASSAL 3.6.11" in the bar rather than "VASL 6.6.5.1".

I rushed it.  Changed the reference in the pom, missed it in the buildFile. Sadness.

**Comment by derimmer** [comment]
In continuing on with the development work that I was doing when this problem arose, which just happened to involve the BoardVersionChecker and ASLBoardPicker classes, I have discovered a second instance where the line 

`System.setProperty("jsse.enableSNIExtension", "false");` 

is used. It appears in BoardVersionChecker.getRepositoryFile(). In this second case, the method is trying to copy a bdXX archive file or and ovrXX archive file from github rather than the v5BoardVersions.xml file. 

It appears to work in the case of updating a board file. I haven't yet been able to test it with overlays as I am in the process of developing that functionality. 

Would the different file types being copied account for why it worked it one case and not in the other?

**Comment by zgrose** [comment]
From what I read on StackOverflow, once you've opened an HTTPS connection, you can't change that property. So it's probably just ignoring that attempt to set the property. IIRC.

**Comment by uckelman** [comment]
In case you're wondering what caused the problem, it's this: https://github.blog/2023-03-23-we-updated-our-rsa-ssh-host-key/

**Comment by derimmer** [comment]
Thanks @uckelman.
