### ISSUE TITLE
Rework the auto-sync workflow

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#1398]
Why does the VASL server delete the existing file before it authenticates it has a good download? It would be real nice to have it download to a temporary file first, authenticate, then delete the old file, and finally rename the temporary file to what it should be named. It would also be nice if it verified internet access right before before it goes into the download process, given it will trash any board files it attempts to download since it can't get to them without that access.

**Comment by derimmer** [comment]
I have worked up some code changes and pushed them to the 667dev branch. You will find them in 

VASL/build/module/map/BoardVersionChecker.java

at

updateBoard() (around line 300) and getRepositoryFile() (around line 360)

The bulk of the changes are in updateBoard(). getRepositoryFile() contains just one change - to test for a file size of 0 for the temp file. I don't actually think the test is needed because any download error would already have been caught by the try . . . catch. Am I right?

I have tested this for downloading a missing bd file and it seems to work. I haven't run it against an updated bd file yet. 

I choose not to go with a TempDir for holding the temp file. Seemed more complicated than required?

**Comment by zgrose** [comment]
I would replace `// Fail silently on any error` with **something** getting written to log. Even if it is just the exception's message and stacktrace. Helps a ton in troubleshooting.

Also note that a partial download will pass this test. I think your best bet is to try to use `bdtest` (load it up/etc; don't know the exact process) and if it succeeds, then overwrite.

**Comment by derimmer** [comment]
> I would replace `// Fail silently on any error` with **something** getting written to log. Even if it is just the exception's message and stacktrace. Helps a ton in troubleshooting.
> 
Agreed.

> Also note that a partial download will pass this test. I think your best bet is to try to use `bdtest` (load it up/etc; don't know the exact process) and if it succeeds, then overwrite.

Understood but I think it would drive users mad. Gonna keep it for step 2 if need be. I am still thinking that a partial download would trigger the I/O exception before the size test code is even reached.

**Comment by derimmer** [comment]
I have updated the code as per several suggestions. Thanks very much. Tested it with a board update rather than a missing board and it worked fine. 

Code changes pushed. This will be in 6.6.7-beta3 for wider testing.
