### ISSUE TITLE
Make dice images larger

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#1399]

**Comment by derimmer** [comment]
@mtl1971 You have done great work on Chatter. Any thoughts about how best to do this? Is it just a question of making the image files stored in VASL larger? They are currently 26x26. Or do we handle this in code?

**Comment by mtl1971** [comment]
Let me have a look, Doug. Code would be better I think - with the generated html fragments.

**Comment by derimmer** [comment]
Feedback has been almost universally in favour of the smaller sizes. Not going to proceed and will roll back test of larger sized "1" images.
