### ISSUE TITLE
Test the VASSAL3.7.0 beta

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#1400]
VASSAL have issued the first 3.7.0 beta. I think we should do some testing with it as some of our user base tends move quickly to new VASSAL versions. 

From a post by @uckelman in one of the VASSAL Forums:

> Modules saved in 3.7 are not openable by earlier versions of VASSAL. We recommend keeping a backup copy of any pre-3.7 modules you plan to modify in 3.7 until you’ve verified that everything works to your satisfaction.

> Some code deprecated more than a year ago has been removed. Modules containing custom code using that code MUST be updated if they are to work with 3.7.

Both of these could cause issues for unsuspecting VASL gamers.

Would anyone be willing to download the beta and test drive it with VASL6.6.6?

@zgrose you are always very good at sussing out problems and what's causing them. Any chance you would be willing to have a look?

**Comment by uckelman** [comment]
Removed deprecated code won't cause you a problem because you already dealt with that when you moved to 3.6. There isn't any deprecated code newly removed for 3.7.
