### ISSUE TITLE
EC markers 

### ISSUE THREAD

**Issue by mistertakai** [vasl-developers/vasl#142]
Some thoughts and suggestions regarding the EC counter tab, aligning it better to 2nd edition rules, especially chapter E. In ASL three different subsystems influence the game: EC, Weather and Fog/Mist/Rain/Falling Snow. The existing markers reflect this only partially. As the marking of these conditions are not playable pieces, modelling them as counters is not necessary. 

1) First visuals: it would be less distracting if the EC markers would come as a draggable overlay, rather than a counters. They would integrate better visually into the map. The compass is a prime example. Also some of them require quite a bit of text, so the one-hex size limit could be foregone with a switch towards overlays.

2) Also on this tab, the _saturated_ marker should be labelled as fordable, deep or flooded to denote water depth.

3) The existing _current strength_ marker should be labelled heavy, moderate or slow.

4) The _rain marker_ behaves unlike the others. It increases and decreases, but does not flip. For the sake of consistency, it should respond to the flip keyboard shortcut as well.

5) There should be a _weather marker_ with the following states as per E3:
- Mud
- Overcast
- Fog
- Mist
- Clear & Gusty
- Snow
- Clear
- Mud & Overcast

Or each state could be modelled as a separate counter as fog and snow have their own substates. 

6) A fog level marker is missing (E3.31).

7) Snow should get its own marker, as rain and snow never occur at the same time (in ASL). Today rain and snow share a counter. The snow states as per E3.7 are: 
- Falling Snow
- Ground Snow
- Ground Snow & Falling Snow
- Deep Snow
- Deep Snow & Falling Snow
- Deep Snow & Drifts
- Extreme Winter

8) The "Clear No Mist" marker should be removed as that is something from KGP and there is a CG specific mist marker already available for that. Instead a fog density marker should be provided with the three states: none +0, light +1, medium +2, heavy +3

9) The beach slope marker does not fit well into the EC tab?

**Comment by davidsullivan317** [comment]
Daniel - would you be interested in doing this? New counters like this aren't that hard.

**Comment by mistertakai** [comment]
I'd love to, but no time this year at all. I can hardly get a PBEM log in these days. If nobody jumps on it, i'll give it a go next year, when things are more quiet over here. Thanks!

**Comment by derimmer** [comment]
With great graphics help from Al C, I am working on this issue for VASL6.5, pretty much following the script laid out above. I have been playing around with adding a label to each of the Weather/EC/environment counters so that it is easier to tell what each counter represents. What do you think of the following efforts? No need to be kind. I think the label of the left side rather than the top is helpful when selecting the counters from the palette. 

![weathersnip](https://user-images.githubusercontent.com/7696161/77217274-9b1c2200-6af7-11ea-823c-6b7454c61f19.PNG)

**Comment by bkemp01** [comment]
The labels are a great idea.

**Comment by BigAl737** [comment]
I like the labels. Maybe a little more subtle background color. White would be good even.

My 2 cents.
