### ISSUE TITLE
Remove cropping restrictions in LOS engine

### ISSUE THREAD

**Issue by davidsullivan317** [vasl-developers/vasl#143]
LOS engine to support all cropping options.

**Comment by derimmer** [comment]
I have just pushed up a bunch of code changes covering issues #143 and #281. The purpose of these changes is to enable the los functionality to work regardless of the crop/flip configuration (including cropping to a whole hex as well as a half-hex width). It should cover all the core boards that have LOS data along with the 1a-9b boards. It will also work with HASL maps that have los data; the only one at present being RBv2. 

These changes need testing before being pushed up to develop. Of course, I have and continue to do tests myself but there are so many possible perms and combinations of cropping/flipping that I invite others to do some testing as well. 

Cloning feature/BugFixCroppedFlipped will get you the necessary code. I have merged all of the current changes to develop (as of April 4) into this so testing will confirm that it works with all of the pending 6.4.0 changes. 

I am not anticipating that this will make the 6.4.0 release but we might be able to get it out later this year in 6.4.1.
