### ISSUE TITLE
Assemble/Disassemble bug

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#1486]
See GS: http://www.gamesquad.com/forums/index.php?threads/assemble-disassemble-issue.187257/#post-2137859

**Comment by derimmer** [comment]
@zgrose in your GS post you said "seems like you could create a pull request for your branch in github to accomplish this". 

Not sure exactly what you meant by this. How can he push changes made via the VASSAL editor to Github?

**Comment by zgrose** [comment]
Every edit in the UI is persisted to the buildFile.

**Comment by derimmer** [comment]
Yes, so then we have to extract the buildFile and put it into a dev environment and push it - or just plain upload it to his branch in Github.. 

I do this frequently. 

Thanks.
