### ISSUE TITLE
Add Hakkaa Paalle Counters

### ISSUE THREAD

**Issue by Wargamerx** [vasl-developers/vasl#149]
I'm guessing this will be a significant effort.  Should 6.2 be deferred to include it or wait until 6.3?

**Comment by davidsullivan317** [comment]
Is anyone here interested in working on the HP counters? Otherwise I might try fishing for an owner.

**Comment by Wargamerx** [comment]
I'm working on the artwork now.  It will take a while, over 100 new counters

**Comment by mistertakai** [comment]
Nice! Thanks a bunch.

**Comment by davidsullivan317** [comment]
Excellent - thanks Jeff.
