### ISSUE TITLE
Chat window bug

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#1503]
user text messages are not appearing in chat window when

(1) Show dice results after each roll has been enabled and (2) a dr button has been pressed. 

When a message is entered, it does not display. If a second message is entered or the Enter key is clicked, both messages will display.

There may also be similar issues when playing a log file. 

VASSAL folks believe it is an html parsing error. 

I cannot find it. 

See GS http://www.gamesquad.com/forums/index.php?threads/vasl6-6-7-beta2-vmod-released.185950/page-3

**Comment by uckelman** [comment]
* I cleaned up the code for `ASLChatter` as I went because otherwise I couldn't hunt for the problem: https://github.com/vasl-developers/vasl/pull/1514

There are no functional changes in that PR. The problem turned out to be a bad interaction between Vassal setting a preferred size on the `JTextPane` and the `GroupLayout` that you're using. The `JTextPane` doesn't actually need a preferred size to get a good layout, so I've removed that in the current build of Vassal.

* Please try a current build of Vassal and let me know if this fixes the problem:  https://vassalengine.org/builds/

**Comment by derimmer** [comment]
Thank you for this. I really appreciate the effort. I know this must have taken some time. 

I am reviewing all of the cleanup changes just for my own learning purposes. I did note that you may have removed a couple of methods that I believe are required by a particular extension. I need to test that it will still work. Then I will test the actual bugfixes. 

Again, a million thanks for taking this on.

**Comment by uckelman** [comment]
The only methods I removed were either unused private ones (so nothing can be relying on them) or overrides of methods from the superclass which are no-ops in both, so are still available. I don't see any way those changes will disturb an extension.

**Comment by derimmer** [comment]
> The only methods I removed were either unused private ones (so nothing can be relying on them) or overrides of methods from the superclass which are no-ops in both, so are still available. I don't see any way those changes will disturb an extension.

And of course you are right, whatever I thought those methods were doing at some point, they no longer were!

I have tested the latest VASSAL build and the Chatter cleanup changes and 

(1) I see no unintended consequences
(2) the "text message delay" bug is solved

Thanks again. I will push the VASL changes shortly.

**Comment by derimmer** [comment]
@uckelman 
I presume that a number of VASL classes could benefit from the same kind of cleanup. Did you use a code analyser/refactoring tool to do this for ASLChatter? We use the IntelliJ IDE; is there a particular tool/plug-in that works best?

**Comment by uckelman** [comment]
I did the cleanup by hand; I don't have any recommendations for Java refactoring tools.
