### ISSUE TITLE
Window decorations inconsistancy for call-out windows

### ISSUE THREAD

**Issue by jvarsoke** [vasl-developers/vasl#151]
Some call-outs, like the "Brokies" or "IFT" call-out windows do not have traditional window decorations (max, min, close).  To close these you need to find the UI button that launched them.  The UI should stick to one UI motif or the other.

**Comment by jvarsoke** [comment]
Perhaps that's the case.  Arguably Gnome 3 is relatively prominant, if not also "crap".

**Comment by uckelman** [comment]
I'm using Cinnamon, myself, in case that's of any use.
