### ISSUE TITLE
Sword and Fire M3A1(a) Scout Car

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#1532]
https://mail.yahoo.com/d/folders/1/messages/52506?.lang=en-CA

**Comment by derimmer** [comment]
see http://www.gamesquad.com/forums/index.php?threads/russian-lend-lease-m3a1sc.185983/#post-2135376

**Comment by apbills** [comment]
Fixed in vasl-6.6.8-beta5_apb.vmod to be supplied to derimmer via e-mail.  All MG info in Has Info is in black until future modifications allow for html in this trait.

**Comment by apbills** [comment]
Fixed " VASL Counters->Allied O/B->Russian->Lend-Lease->APC->M3A1 SC(a) [Single Piece] " - removed 'r' in "Has Info".
Fixed " Game Piece Palette->ru->LLw->M3A1 SC(a) Wreck " - added link to wreck image.

**Comment by derimmer** [comment]
Alan, just doing some testing. For the wrecks, the American colored one produces a wreck counter as does the armed Russian one. The unarmed Russian does not and I got this message in chat:

 Bad Data in Module: Source: ruM3A1 SCB.png Error: Image not found. Turn on the Audit Trail preference to generate more details in the errorlog.

This is using your most recent .vmod and 3.7.7.

**Comment by derimmer** [comment]
Fixed and texted in 6.6.8-beta6
