### ISSUE TITLE
CC counter bug

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#1564]
http://www.gamesquad.com/forums/index.php?threads/minor-counter-bugs.190229/#post-2145142

**Comment by apbills** [comment]
I believe there is a bug in how the Area of Effect trait is working in terms of toggle on/toggle off.
Brute-forced it by changing the single counter that was duplicated into 4 counters in the tray to four single counters in the tray, each replacing with 2 other of the counters based on CTRL+F or CTRL+H.  Area of Effect is always visible on those that are Melee, and does not exist in those that are just CC.  It works and given we already carry 4 counters in the tray is not a problem in terms of functionality or space.
