### ISSUE TITLE
Hollow Legions

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#1581]
Merge the Hollow Legions counters into the VASL module.

**Comment by derimmer** [comment]
There are also some counter behaviour issues that need to be sorted out first. I will try to find the GS/Discord references

**Comment by apbills** [comment]
Added Eritrean nationality to Axis O/B, including a copy of the entire Italian "?" tab.
Added Ethiopian nationality to Allied O/B, including a copy of the entire Allied Minor "?" tab.
This could have added sub-panels to Infantry, HS, and SMC under Italian and Allied Minor however, I decided it was best to just keep them as their separate nationality for now.
Note that all counters were reworked, both the images and the counter traits to conform to VASL module standards and the beta5 .svg implementation for broken units.
