### ISSUE TITLE
Deluxe-sized hexes not persisting when game closed and reopened. 

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#1589]
From email:

"We spoke some time ago about problems with the Orsogna VASL map, namely that it would not keep the “use deluxe sized hexes” option between saves. i.e. the loaded file would display normal sized hexes but with the counters in deluxe positions.

We’ve encountered the same problem with the separate FB HASL maps.

It seems to occur when I crop FB NE and FB NW to overlap properly. All appears well then when I reload the file one of the map sections is normal sized again, throwing the counters out of position.

What’s bizarre is that sometimes its FB NE that resizes itself, sometimes FB NW. It may be to do with which map I have cropped, I’m not sure. I’m guessing that it’s the same issue as the Orsogna map

I’m 6.6.7 and 3.7.5"

**Comment by derimmer** [comment]
@zgrose @uckelman 
Another approach that we have been taking to this is to see if can shrink the counter sizes during play rather than increase hex sizes. In both approaches the goal is that once a new ratio of counter-to-map-hex has been established, it can be persisted up and down the zoom scale. This approach has the advantage of not having to worry about repositioning counters. 

In development this has been working well and the developer (not me) is down to two issues:

1. When units are moved via drag-drop, the revert to their previous size while being dragged. Once dropped they revert to their "shrunken size". We have tracked this down to VASSAL.build.Module.map.PieceMover.AbstractDragHandler.makeDragImage(). It is called and passed two parameters, double mapzoom and double os_scale, which seem to control the size of the dragging image. We have also (mostly) figured out how to intervene and change the value of the variables to match the shrinkage required for the drag image to match the size of the onboard image.

2. When a stack of "shrunken" units is expanded. the selection area for the individual counters is remaining at its unshrunken level - which is causing mis-selection of units. This functionality appears to exist in class StackMetrics, which is extended by ASLStackMetrics. So we should be able to modify the size of the selection are according. However, we haven't quite figured out how to do so. 

@zgrose Zoltan, I know it has been a while but since your name is on ASLStackMetrics, I wonder if you could have a look at the code for both ASLStackMetrics and StackMetrics and give us some advice on how to accomplish this. 

John Young is doing the good work on this and we have been collaborating on GS at http://www.gamesquad.com/forums/index.php?conversations/board-magnification.62552/

Thanks.

**Comment by zgrose** [comment]
Pretty sure all I did was revert a change that was "leaking" the underscores on the counters when the counters were displayed in full color instead of just the white boxes. Probably not the best resource at the moment.

**Comment by uckelman** [comment]
`os_scale` represents the UI's own scaling factor, used when painting. `mapzoom` is the scale factor the `Map` has. You should _never_ use `os_scale` outside of a function that's doing painting.

**Comment by derimmer** [comment]
> `os_scale` represents the UI's own scaling factor, used when painting. `mapzoom` is the scale factor the `Map` has. You should _never_ use `os_scale` outside of a function that's doing painting.

Super, because that is exactly how we want to use it. To change the size of the area to be painted while a counter is being dragged. Thanks.

Secondly, we are still having trouble with selection areas of an expanded stack. Although we can shrink the counter image in the stack, we have not found a way to change its selection area accordingly. @uckelman could you point us to the parameters that govern this? Many thanks.

**Comment by uckelman** [comment]
> we have not found a way to change its selection area accordingly

It's not clear to me what you mean by this.

**Comment by derimmer** [comment]
We have found a way to make counters smaller relative to the map. However, the selection area for those counters is not changing. 

Not a problem if there is just one counter in a hex or you want to select a whole stack. 

But if you expand a stack and then try to select one or more of the counters, you will often select the wrong counter because it's selection area is different in size (larger) than the actual counter you are looking at. 

We need to be able to adjust the selection areas for counters in an expanded stack to match the size (and bounds) of the visual image.

**Comment by uckelman** [comment]
I still don't understand what you're saying. Can you post a screenshot demonstrating it?

**Comment by derimmer** [comment]
https://github.com/vasl-developers/vasl/assets/7696161/081af1b1-6fe2-4e47-8105-663be30f0b4e

The best way to show this is with a short video. I hope it will play. 

If it does, you will see that when I move the mouse and click (hard to see the actual click I know), the wrong counter is being selected because the area of selection for the mouse does not match with the size of the counter image (which we have shrunk). At the end, I drag a counter out of the stack, as you should see, while it is being dragged the counter image becomes much bigger. It should remain the same size. I believe we can fix this by use of os_scale. But we don't know how to fix the first problem of the area of selection

**Comment by derimmer** [comment]
Understood. Where and how should we be looking to do that? What variables stores "their sizes for the purposes of interaction"? At a guess I would say Rectangle [] bounds in ASLStackMetrics.draw() is one place. As I read it, bounds is passed as a parameter to ASLStackMetrics.getContents() which overrides VASSAL.StackMetrics.getContents(). The first thing the overriding method does is call VASSAL.StackMetrics.getContents(), which sets the values of elements in bounds. So, We should be able to "alter their size for the purposes of interaction" by changing the values in bounds later in ASLStackMetrics.getContents()? Does that seem right?

**Comment by uckelman** [comment]
All size and location information for pieces comes from `GamePiece.boundingBox()`, `GamePiece.getShape()`, and `GamePiece.getLocation()`. `GamePiece` is an interface, though, so there is no single location that stores piece sizes. I'm not optimistic that you could do what you're proposing via modifying `StackMetrics`.

I had thought that `Board.setMagnification()` existed for handling changing board size. We don't use it in Vassal at all; my memory is that it exists just so VASL can do what you're trying to do.

**Comment by derimmer** [comment]
John's extension seems to be working fine. Thanks for all the help. Code changes to support the extension will be in 668. The extension should be released shortly. No further work required on the substance of the original purpose of this issue.

**Comment by derimmer** [comment]
It appears that the VASL code changes associated with the new BoardZoomer extension are creating a bug that makes it harder, and at times impossible, to drop counters in the intended position. These problems are easily replicated without the extension loaded and so it is reasonable to focus on the changes that were made to VASL itself. Plus, I used git bisect to identify the specific commit which introduces the problem and it is 'e49c52c . . . ' which is listed above.

That commit changed 4 classes and added one new one. Any one with thoughts about how to figure out exactly where and how the problems is being caused, please don't hestitate to share. Any ideas about how to test this code?

**Comment by derimmer** [comment]
Of the five classes, the new one, BoardZoomer.java, does not appear to be used unless the extension is installed and the problem with counter placement happens even when the extension is not loaded, so I think we can rule out BoardZoomer.java as the cause.

**Comment by derimmer** [comment]
With the advent of BoardZoomer, no further work is being done on fixing the Use Deluxe Hexes method. I am going to close this issue and open a new issue to remove the Use Deluxe Hexes option. That will leave the VASSAL zoom (magnification) and the BoardZoomer methods for increasing/decreasing the size of both hexes and counters (VASSAL zoom) and increasing/decreasing the size of each of hexes and counters independently (BoardZoomer).
