### ISSUE TITLE
Finnish 338 HS not breaking

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#1618]
Finnish 338 HS created from the 838 full-squads do not break. 

I think it is the same bug that affected the 238. It's a question of layers.

**Comment by apbills** [comment]
I can get neither the 'E' nor the 'AE' 338 HS to NOT break, both after reducing from their full squads as well as from the HS tab.  Using 377/668b5 on Windows 11.  OP has confirmed on 3.7.7/6.6.8b5 as well.  I will assume something in 3.7.7 fixed an issue with layers.  I recommend we close this issue.
