### ISSUE TITLE
M4A1 show info bug

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#1625]
http://www.gamesquad.com/forums/index.php?threads/vasl-map-online-problem-suggestion-form.88223/page-62#post-2150512

**Comment by apbills** [comment]
Fixed 8 total counters in the Allied O/B->American->Veh->MT->MT (75) sub-panels: M4, M4 FT, M4A1, M4A1 FT, M4A2, M4A2 FT, M4A3, M4A3 FT counters.
