### ISSUE TITLE
License Renewal

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#1645]
The annual license renewal process with JetBrains is underway. 

If you use and are satisfied with the Community Edition then you do not need to bother with this. 

If you use the Ultimate Edition (or would like to move to it), then let me know and I will add your names to the license request. So long as you have active on one of our projects over the last year, they have been pretty good about giving us Ultimate licenses.

Part of the value of the Ultimate license is that it is in fact a much larger license that gives you access to a wide range to tools produced by JetBrains. 

Let me know.

I will want to submit the license renewal request by this Friday, Feb 2nd. 

As far as I can tell, besides myself @styson and @BigAl737 are the only other license holders.

**Comment by BigAl737** [comment]
Hi Doug,
I've not used my license and don't plan to. If someone else can use it, please transfer it to them. FYI, I'm no longer buying ASL product so do not have access to source material for new ASL releases. I am available if you have need of graphics projects.

The amount of VASL support by you and @apbills is very evident and commendable. I know you have the support of others as well. This is great to see. Thank you for your time maintaining and improving a resource that is so beneficial to the ASL community.

**Comment by zgrose** [comment]
I have an All Products license (which is amazeballs), so all set here.
