### ISSUE TITLE
Board 41 Errror

### ISSUE THREAD

**Issue by davidsullivan317** [vasl-developers/vasl#167]
Board 41 version 6.0 has an error in hex DD4. It shows a single building in this hex wheres both the original style Board 41 and the new style Board 41 show a small outbuilding in the hex near the CC4/DD4 hexside.

**Comment by FredKors** [comment]
Yes, confirmed

**Comment by FredKors** [comment]
Yes, confirmed



2015-01-02 16:33 GMT+01:00 David Sullivan <notifications@github.com>:

**Comment by BigAl737** [comment]
Fixed and committed. I'm not a programmer (although I play one on TV) so I hope I did everything correctly. I updated the bd41 version to 6.1 (was 6.0) and updated the bd41 gif.

**Comment by davidsullivan317** [comment]
Just remembered I need to update the LOS data, so reopening.
