### ISSUE TITLE
Chat not reporting ? units properly

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#1710]
From email:
![image002](https://github.com/vasl-developers/vasl/assets/7696161/bd8a03cd-52d2-437f-bf1d-58b156db3b97)

Steps:

Created 458
Moved unconcealed 458
Concealed using CTRL+C (no output in window)
Moved concealed stack (?+45)
Moved just the concealed 458
Created T-40
Concealed using CTRL+C (no output in window)
Moved large ? + T-40 as stack
Moved just the concealed T-40
Moved just the large ? on top of the T-40
Rotated the concealed T-40
 

I then tried this with the other concealment method of dragging a ? counter on top of a unit on the board
![image006](https://github.com/vasl-developers/vasl/assets/7696161/52d8bf85-46c6-4111-a91f-554ae0fe6ee5)

Steps”

Create 458
Place small ? on top of 458
Move stack
Move just the concealed 458
Move the small ? on top of the 458
 

There is something about the concealment trait that is a) messing up the reporting (since the topmost counter in a stack is not reporting) and b) the “ownership” of a stack is not flowing through to the chat window since the report line is not using the preferences based on that information.

**Comment by apbills** [comment]
I have noticed that the addition of the line number in front of reported text has eliminated this issue in my games.  Maybe we have seen positive unintended consequences?

**Comment by derimmer** [comment]
@apbills I have just replicated your tests above using my most recent development build of VASL - beta8. I was not able to reproduce any of the problems you initially found. As you say, perhaps the line numbers did more than they knew. I am going to mark this issue as closed.
