### ISSUE TITLE
Disable Full Colour Stacks pref is not working in 668

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#1728]
See Discord discussion, April 22.

**Comment by derimmer** [comment]
From Zoltan on Discord in April: 

seems like public void draw(Stack stack, Point location, Graphics g, Map map, double zoom, Rectangle visibleRect) {} is no longer called and now public void draw(Stack stack, Graphics g, int x, int y, Component obs, double zoom) {} is the primary path? (ASLStackMetrics.java) Perhaps there is a new place to put if (disableFullColorStacks) {} so that the zoomer feature can leverage  the preference as well

**Comment by derimmer** [comment]
@zgrose I am trying to work on this. In testing for the cause, I find that public void draw(Stack stack, Point location, Graphics g, Map map, double zoom, Rectangle visibleRect) {} gets called when a stack is created and the preference is correctly set so that it selects the super call. But still the stack is always displayed in full color. 

I have noticed when working in the VASSAL editor that there are two versions of Stacking options saved in the module (which always generates a warning from VASSAL that there should only be one. These two versions of Stacking options have different values, which I think may be BoardZoomer related. I am going to check this out as a possible cause. 

Any other thoughts? I can't see why the draw method in ASLSTackMetrics isn't working?

**Comment by zgrose** [comment]
IIRC, originally the change was just an if block that skipped over the 'new' drawing code and I presume just punted to the default VASSAL draw. With all the zoomer stuff, I'm guessing that the default VASSAL draw is never called anymore since it doesn't have the zoomer awareness and would probably draw the counter the wrong size? It may be that the uncolored version will have to be implemented in it's own way that is also zoomer aware?

**Comment by derimmer** [comment]
I have "fixed" this bug but in a way that I cannot believe is correct. 

The Full Color Stacks effect (or non-effect if disabled) only applies when dealing with unexpanded stacks, correct? An expanded stack will always show the normal counter images. 

ASLStackMetrics has a drawUnexpanded() method which in turn calls the VASSAL.StackMetrics.drawUnexpanded() method. That method tests for the value of field StackMetrics.blankColor. 

if (this.blankColor == null) {
            p.draw(g, x, y, obs, zoom);
        } else {
            Graphics2D g2d = (Graphics2D)g;
            g.setColor(this.blankColor);
            Shape s = p.getShape();
            AffineTransform t = AffineTransform.getScaleInstance(zoom, zoom);
            t.translate((double)x / zoom, (double)y / zoom);
            s = t.createTransformedShape(s);
            g2d.fill(s);
            g.setColor(Color.black);
            g2d.draw(s);
        }

In my testing, I could find no case in which blankColor was anything but null. Setting it to ColorWhite when loading ASLStackMetrics() results in the else statement being active and the disabled Full Color Stacks feature now works as intended. 

I cannot believe that this is anything but a hack. If I look at the changes made from 667, the last version in which the DisableFullColorStacks preference worked, I can see nothing that would have affected the value of blankColor in StackMetrics().

I am reluctant to push up this change as it feels like the problem is still out there. Ideas?

**Comment by derimmer** [comment]
> From Zoltan on Discord in April:
> 
> seems like public void draw(Stack stack, Point location, Graphics g, Map map, double zoom, Rectangle visibleRect) {} is no longer called and now public void draw(Stack stack, Graphics g, int x, int y, Component obs, double zoom) {} is the primary path? (ASLStackMetrics.java) Perhaps there is a new place to put if (disableFullColorStacks) {} so that the zoomer feature can leverage the preference as well

@zgrose meant to start my previous with this reply. Both of the .draw() methods in ASLStackMetrics test for disableFullColorStacks. And in my testing the preference setting is correctly picked up and the StackMetrics draw code is triggered.

**Comment by zgrose** [comment]
> I am reluctant to push up this change as it feels like the problem is still out there. Ideas?

I bet you can wait until you get more comfortable with the wheres and whys.

**Comment by zgrose** [comment]
So I went a re-pulled the report and setup IDEA and had a look....

````
/**
   * The color used to draw boxes representing counters beneath the top one in a stack.
   * A value of null indicates that the counters should be drawn fully
   * @return
   */
  public Color getBlankColor() {
    return blankColor;
  }
````

Looks like the cross-pollination of source has VASL and VASSAL chasing each other's tail. :)
Looks like setting the BlankColor to a non-null White is what disableFullColorStacks should be doing.

**Comment by zgrose** [comment]
Popping a @derimmer just in case you didn't see the above.

**Comment by derimmer** [comment]
Thanks Zoltan, that looks like a better approach, especially if it comes right after the code to load/change the preference. Which I believe runs whenever ASLStackMetrics is loaded.
