### ISSUE TITLE
cvp counter has buttons reversed

### ISSUE THREAD

**Issue by jrvjrv** [vasl-developers/vasl#1735]
cvp counters (found under Axis/Allied OB, {nationality}, "?") have a "+" button and a "-" button. Clicking the "+" button *decreases* the total; clicking the "-" button *increases* the total. These seem to be reversed. The keyboard shortcuts "+" and "-" do The Right Thing.

**Comment by derimmer** [comment]
Just tried using them in vasl6.6.9-beta4 due to be released this week and they seem to have been corrected. Not sure when it happened.
