### ISSUE TITLE
board and overlay versions should be checked before publishing

### ISSUE THREAD

**Issue by jrvjrv** [vasl-developers/vasl#1741]
Currently board and overlay versions are given in (at least) three places, the "data" file, BoardMetadata.xml and v5boardVersions.xml. I assume there is some automated build process for assembling these, and in that build process there should be a check that the versions in all three places match.

**Comment by derimmer** [comment]
Your assumption is incorrect. There is no automation in the build process whatsoever. It is by hand all the way. Despite that such errors are rare. Given that I have personally updated each los-enabled board file at least 3 times over the past couple of years as I removed most of the text files that used to produce board errors, I think we have done pretty well to avoid the version typo that you found in the RR overlay. Good catch on that one by the way! 

Now that we have almost all the work on removing text files from the bd files complete, and have both bd files and overlays on auto-syncing, I think the risk of future errors is low. 

The data file no longer needs to be updated in bd files that contain a BoardMetaData.xml file. I have deleted the v5boardVersions.txt file from the VASL module.
