### ISSUE TITLE
Counters throw exception when attempting to conceal with ctrl-c

### ISSUE THREAD

**Issue by jrvjrv** [vasl-developers/vasl#1747]
Steps to reproduce: install BFP.vmdx (version v5.01.1) from the vasl extensions download. Start in wizard, select board 00 geoboard, done. Open counter tray, BFP tab, select Poland in Flames on drop down, MMC, pull 4-5-8 from tray onto map, ctrl-C, "eek a bug".

This is from vasl6.6.8 but same thing happens in vasl6.6.9-beta2.vmod
[errorLog-3.7.12.txt](https://github.com/vasl-developers/vasl/files/15444940/errorLog-3.7.12.txt)

**Comment by derimmer** [comment]
This appears to be happening in a wide range of circumstances, not limited to BFP Polish counters. It is happening for Swedish counters and for certain guns. I have broadened out the issue and will take a more comprehensive view. First thoughts are missing ? counters in the "?" counter palette.
