### ISSUE TITLE
PTO Transformation behavior

### ISSUE THREAD

**Issue by Wargamerx** [vasl-developers/vasl#176]
If you load a board and select Terrain SSR, once you select one of the PTO options, the grain and orchard options switch to out of season if the month happens to be a non 'in-season' month.  There are no seasons in PTO, and both options should be set to in-season if PTO is selected.

**Comment by davidsullivan317** [comment]
I think the month drop-down is just a convenience for selecting the proper orchard/grain setting for ETO scenarios. For PTO players should just not use the month selector unless they explicitly wanted orchard/grain changes (e.g. SSR). I'm not sure we want to change that.
