### ISSUE TITLE
vasl-6.6.9-beta4 buildFile

### ISSUE THREAD

**Issue by pacman-ghost** [vasl-developers/vasl#1776]
This now has a `.xml` extension. Is this intended...?

**Comment by derimmer** [comment]
VASL source code is still using buildFile. I have noticed that when I build a module and then open it as a zip file, the buildFile has been renamed buildFile.xml. 

I would assume that if we used buildFile.xml in the source file it would not cause a problem but I have not tried it. 

I intend to keep using buildFile in the source code as sometimes when codling/testing I need to import buildFile.xml from the module to my dev environment to work with changes that can only be made via the VASSAL.Editor.
