### ISSUE TITLE
a broken SW under a concealment counter can still be revealed when using the "Show/Hide Broken/Malf Counters" button

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#1802]

**Comment by geezer09** [comment]
Create a branch feature/issue_1802 to fix this. To be merged at a later date. Perhaps we could change the wording of the document about Show/Hide Broken/Malf Counters button located in the help menu to reflect this new change.

**Comment by derimmer** [comment]
> Perhaps we could change the wording of the document about Show/Hide Broken/Malf Counters button located in the help menu to reflect this new change.

Yes, we should definitely do this for this specific fix.

It also raises a broader issue, applicable to all changes, about how we manage user documentation. I am going to create a discussion item on github to talk about this.

**Comment by derimmer** [comment]
I have tested this in dev670 and it works (no surprise). As much as anything else, I am interested to see what you have done. No approval or review on my part is required for this or other changes you have made. I will let you know if I have any questions on other issues. If not, I will let you know when I  have looked at everything and we can use your workflow to release the beta. 

I would appreciate you walking me through the workflow when we get to that point.
