### ISSUE TITLE
VASSAL.build.IllegalBuildException: failed to load class VASL.build.module.map.NoROIManager

### ISSUE THREAD

**Issue by FredKors** [vasl-developers/vasl#1815]
There is a <VASL.build.module.map.NoROIManager AddAllKey="71,650" Name="NOROIManager" RemoveAllKey="72,650"/> in the buildFile but no corrispondent class in the code

**Comment by derimmer** [comment]
The NoRoiManager is a feature I am working on. I may have pushed some changes up to develop prematurely.

**Comment by FredKors** [comment]
👍

**Comment by derimmer** [comment]
I have now pushed up the code and images needed to implement No ROI functionality. This will be a feature tested in vasl-6.6.9-beta9.
