### ISSUE TITLE
Pre-V6.2 saved game converter

### ISSUE THREAD

**Issue by davidsullivan317** [vasl-developers/vasl#184]
I'm going to release 6.2.1 adding a converter for pre-6.2 saved games. 
![untitled](https://cloud.githubusercontent.com/assets/5281926/6131579/9f0d5162-b112-11e4-9806-8b464edee850.png)

**Comment by FredKors** [comment]
Nice!

2015-02-10 17:51 GMT+01:00 David Sullivan <notifications@github.com>:

**Comment by davidsullivan317** [comment]
The change is checked in to release-6.2.1. If you have a chance please give it a shot and let me know if you see any problems.
