### ISSUE TITLE
Counter gets unconcealed when moving ? counter below it

### ISSUE THREAD

**Issue by geezer09** [vasl-developers/vasl#1848]
In most cases when I move a concealment counter below a unit I want to unconceal it, but not always. If i have a stack of three counters with a squad below two concealment counters and I move one of the concealment counters below the squad it will unconceal it, even if there is another concealment counter above it. 

I think this will be an easy fix in the concealable class.

**Comment by zgrose** [comment]
Situation: 6-6-6/6-6-6/?/?)

Moving the ? down reveals the top 6-6-6, moving the 6-6-6 up works fine.

Maybe take a peek there for clues.

Semantically, to me, moving a concealment counter down probably *should* unconceal the counter. But maybe that's just because I'm so used to it. :)

**Comment by derimmer** [comment]
Testing this in the 670 build, I notice that when concealing a stack of Hungarian units, dragging a ? counter from the counter palette does NOT conceal the units. CTRL-C on the top unit does conceal the entire stack. 

In 668, dragging ? counter works properly. In 669, it does not. 

So far this works with other nationalities that I have tested in 669 and 670. I suspect that this is a bug related to my implementation of NoRoi counters. I will create a new issue and look to fix it in beta1. I don't think that this has anything to do with your work
