### ISSUE TITLE
Linux bug for drag and move

### ISSUE THREAD

**Issue by geezer09** [vasl-developers/vasl#1861]
The following two methods in ASLPieceMover were commented out recently just before releasing releasing version 6.6.9, probably to address a bug but i am not sure. This dosent seem to cause any issues in windows but in linux it screws up the click and drag function when moving pieces.

        @Override
        protected void moveDragCursor(int dragX, int dragY) {
            if (drawWin != null) {
                dragCursor.setLocation(dragX - drawOffset.x, dragY - drawOffset.y);
            }
        }

        /**
         * Removes the drag cursor from the current draw window
         */
        @Override
        protected void removeDragCursor() {
            if (drawWin != null) {
                if (dragCursor != null) {
                    dragCursor.setVisible(false);
                    drawWin.remove(dragCursor);
                }
                drawWin = null;
            }
        }

**Comment by jrvjrv** [comment]
Any thoughts on when this fix for linux bug with drag-and-drop will be released? I am starting to get annoyed with ghost images on my window.

**Comment by geezer09** [comment]
I think this is not happening in 6.6.8 if you want a quick fix. I am not familiar with what issue was fixed by commenting out those lines in the code so I don’t want to release a new version that will fix a bug for 7 users to reintroduce one for the rest. Doug said he would be back shortly so he might put a new version out shortly.

**Comment by derimmer** [comment]
Somehow these changes were left out of the 6.7.0-beta1 build. I will push them up to github and pull them into develop right now.

**Comment by geezer09** [comment]
hey @jrvjrv, can you test this out, it should be fixed in the last beta release.
