### ISSUE TITLE
Light Woods SSR transformation missing from a bunch of boards

### ISSUE THREAD

**Issue by davidsullivan317** [vasl-developers/vasl#187]
The following core boards do NOT support light woods: 1-4,8,11,14,20-31,33,42-45,48-56,58-63

**Comment by BigAl737** [comment]
I got this.

**Comment by BigAl737** [comment]
Bds1-4 and 52 are done. Will upload later.

**Comment by BigAl737** [comment]
8, 11, 14, 20, 21, 22 are done. Will push them later.

**Comment by BigAl737** [comment]
23, 24, 33 are done. Will push later.
25-31 no woods to convert

**Comment by BigAl737** [comment]
boards 2 and 3 pushed and submitted for upload

**Comment by BigAl737** [comment]
All missing lightwoods graphics generated. Scott is helping with updates of bd files.

**Comment by BigAl737** [comment]
Just pushed files to add light woods transforms to bds 42-45 and 48,49. Will update bd versions and push updated boards to VASL.info soon.

**Comment by BigAl737** [comment]
I will finish updating the src board folders with the light woods.gif files and modifying the metadata files to incorporate the light woods transform. I am not planning on updating the SSR file as my understanding that this is a legacy file that is no longer required. Also, I will not push the boards for download on VASL.info. I'm thinking this should be done as part of the recomplialtion of all boards as Sully suggested once updates have settled down.

**Comment by BigAl737** [comment]
Light Woods transform for bd07 and 16 are done and available for download from vasl.info as part of #380.

**Comment by BigAl737** [comment]
Pushed lightwoods.gif and revised metadata files for boards 20, 21, 22, 23, 24, 50, 51, 53, 54, 55, 56, 59. Lightwood transforms should be active with next board compilation that I think is planned in the near future. I don't think this update rates it's own update to the board versions. OverlaySSR and Data files not updated as I think they will be deleted with next board update anyway.

I think this completes this issue but will leave topic open a few more days for comments.

**Comment by derimmer** [comment]
Al, I am pretty sure that auto-synching won't work unless you bump the version numbers - meaning that most people won't benefit from your good work. 

Version bumping needs to happen in 3 places:

1. The Boardmetadata.xml in the bdXX file and in the vasl/src/boards/boardXX folder
2. v5boardVersions.txt in vasl/src on github
3. versions.json in vasl-website on github.

**Comment by BigAl737** [comment]
I understand Doug and thanks for the follow up. I can certainly do this but didn't think it was worth it for such a little used addition. I thought this could wait to be incorporated with the all board updates Sully suggested once the multitude of recent board issues have stabilized somewhat.

**Comment by BigAl737** [comment]
Files have been added/amended to vasl/src that will incorporate this transform with the next required board compilation. No further need to hold this topic open.
