### ISSUE TITLE
bdgSK orchards depicted as out-of-season without terrain SSR

### ISSUE THREAD

**Issue by jrvjrv** [vasl-developers/vasl#1894]
Orchards are shown as out-of-season on the default board, e.g. L7, CC7, FF6

**Comment by geezer09** [comment]
There are a couple of open PRs that will fix this bug I think. I'll go ahead and merge those PRs, can you check to see if the issue is fixed.

**Comment by geezer09** [comment]
@jrvjrv are you able to double check to see if this issue had been satisfactorily fixed? If so you can close those issue, otherwise I’ll look into it some more.

Thanks

**Comment by jrvjrv** [comment]
> @jrvjrv are you able to double check to see if this issue had been satisfactorily fixed? If so you can close those issue, otherwise I’ll look into it some more.
> 
> Thanks

Very much nicer. Thank you.
