### ISSUE TITLE
End of turn marker removal

### ISSUE THREAD

**Issue by mistertakai** [vasl-developers/vasl#196]
Lax markers and starshells should be removed at the end of a turn. There is currently no way to do that save than going through the stacks one by one and removing them manually. I would vote for replacing "remove Pin/TI markers" in the menu bar with "remove markers at end of turn" to improve usability. Remove markers at end of turn would then remove Lax markers and starshells as well. I'm not sure if there are other counters that could go.

![image](https://cloud.githubusercontent.com/assets/3066447/6545210/a4fc5614-c57a-11e4-9e62-c7ff9cfda26e.png)

**Comment by davidsullivan317** [comment]
There is already an option to remove starshells. Honestly, I don't think LAX counters by themselves justify the change. Are there other EOT counters that would be included? If not I'd recommend closing this.
