### ISSUE TITLE
Overlays not working with PTO in effect

### ISSUE THREAD

**Issue by davidsullivan317** [vasl-developers/vasl#20]
Trying to setup ESG 53 (PTO light jungle).

When placing overlay X3 on board 35 (including some space on board 42) the board 42 bsuffers a lot of strange transformation, creating roads and orchard everywhere..

The problem appears when doing any PTO transformation.. The board 35 changed also appear in top of the board 42.. It´s clear is something about the overlays from board 35 overlapping board 42.

BTW same problem if using 5.9.2

**Comment by BigAl737** [comment]
With #330 firmly in pace, can we close this issue David?
