### ISSUE TITLE
Partial support for LOS checking with overlays

### ISSUE THREAD

**Issue by davidsullivan317** [vasl-developers/vasl#204]
Adding LOS to overlays is actually an order of magnitude more complicated that adding LOS to boards, which is why it hasn’t happened yet. The complexity is several fold: 1) overlay archives borrow heavily from board archives so the interface is kind of clunky, 2) most overlays have multiple images/orientations, each of which would need its own custom LOS information as “rotating” LOS information would likely be error prone, and 3) overlays can span boards, dangle off the edge of the map, etc. 

I’m thinking a partial solution would be to allow LOS checking when overlays are present and only turn off LOS checking if the LOS string touches the overlay. This would get us 90+% of the way there with very little work as LOS checks touch the overlay a small percentage of the time on most scenarios. The business rule would read something like, “If the LOS starts on , ends on or crosses an overlay turn off LOS checking and use the default string color. When this happens give the user a visual cue that the LOS checker was not used.”

**Comment by BigAl737** [comment]
How about making overlays available from a draggable window (similar to the way we drag the Phase Wheel onto the map), would that help the LOS issue? I'd prefer to directly drag, rotate, and place overlays instead of the current system. Maybe that's not possible?

**Comment by davidsullivan317** [comment]
That's exactly what I was thinking. In refactoring the board archive code I left overlays alone thinking we would move in that direction at some point. 

It won't help with the LOS issues as creating and applying the LOS data would still be problematic.
