### ISSUE TITLE
Update the developer documentation

### ISSUE THREAD

**Issue by mistertakai** [vasl-developers/vasl#21]
We have a Wiki now - let's use it :-)

**Comment by davidsullivan317** [comment]
Doug Rimmer is looking into updating the development documentation, so hijacking this issue.

**Comment by derimmer** [comment]
Thanks to David for his help with this. If others have time to review it and provide comments, that would be most welcome. I have tried to build a structure that is not tied to particular software tools and versions but I am sure there is more that could be done. Let me know if you think there are missing pieces.

**Comment by davidsullivan317** [comment]
Thanks Doug - go ahead and delete the "Setting up IntelliJ for VASL development.doc" file in the same folder as it's no longer current. Let me know if you want me to merge this into the develop branch.

**Comment by derimmer** [comment]
Perhaps we should wait a couple of days to see anyone chooses to comment first. 

 

So, merge away on Thursday if no one has.

 

Doug
