### ISSUE TITLE
Finnish HS are set to full squads

### ISSUE THREAD

**Issue by zgrose** [vasl-developers/vasl#210]
vasl-6.3.0-Snapshot-20150327

![screen shot 2015-03-29 at 9 42 33 am](https://cloud.githubusercontent.com/assets/5044847/6886621/f1aad8cc-d5f7-11e4-9a54-21528d9965b9.png)

**Comment by styson** [comment]
I still see the full squad images on the HS panel in VASL version 6.3.0-Snapshot
