### ISSUE TITLE
Overlay X23 has its coordinates in the wrong hexes

### ISSUE THREAD

**Issue by styson** [vasl-developers/vasl#212]
When applied in VASL, coordinates in red are used, when printed overlay has 1 and 2 as shown in green.
![635640905978455410](https://cloud.githubusercontent.com/assets/178219/7073615/48041f74-deba-11e4-9109-ba6097499128.png)

**Comment by BigAl737** [comment]
212 I'll update this when I add X30 to ovrX

**Comment by BigAl737** [comment]
pushed and submitted for upload

**Comment by BigAl737** [comment]
complete as part of #260
