### ISSUE TITLE
Finnish boxed 1st line 5-4-8 and  4-4-7 squads show only two sillouettes when broken

### ISSUE THREAD

**Issue by davidsullivan317** [vasl-developers/vasl#213]
Finnish boxed 1st line 5-4-8 and  4-4-7 squads show only two sillouettes when broken

**Comment by Wargamerx** [comment]
Fixed all 6 new squad and HS counters here:
https://www.dropbox.com/s/32bwoapa8mfe394/vasl-6.3.0-Snapshot-20150320%20JDC3.vmod?dl=0

New image included fiBrks7bx.png

**Comment by styson** [comment]
I confirmed that the squad and HS counters are fixed in that build, but there are also a lot of Finnish Gun changes in that buildFile. @Wargamerx, can you verify those changes, and/or merge the buildfile?

**Comment by davidsullivan317** [comment]
I will take this issue
