### ISSUE TITLE
The 1/2" blank counter placed DM when flipped and another DM counter flipped back

### ISSUE THREAD

**Issue by davidsullivan317** [vasl-developers/vasl#215]
Should not place DM when flipped back from "broken" side

**Comment by styson** [comment]
any better details on this issue?  I can't reproduce so far with 6.2.2.

**Comment by davidsullivan317** [comment]
Use the Russian 1/2" blank counter. Flip it and delete the DM counter that appears. Flip it again and it will create another DM counter.

**Comment by davidsullivan317** [comment]
Decline to fix. The blank counters do not really "flip" or have a broken side, so CTR+f just adds a DM if one is not there.
