### ISSUE TITLE
Problems with Finnish mortars 

### ISSUE THREAD

**Issue by davidsullivan317** [vasl-developers/vasl#216]
81* MTR Savu M42 - when DM, and you click malf, becomes a 5PP DM Finn mtr malfed, not the 4PP like it should. Also it is missing control info:
* IR should have a 43+ superscript
* S NA prior to 11/41
* S8 11/41 +
* Smoke only has a range of 3-24 43+

The 81* MTR Krh/32 disappears when you dm it.

The 81* MTR GrW34 (g) become an LMG when you dm it.

**Comment by Wargamerx** [comment]
You must have the wrong version.  All looks correct with the version I sent you.

**Comment by davidsullivan317** [comment]
I'm still seeing these two problems in the latest build (https://www.dropbox.com/s/32bwoapa8mfe394/vasl-6.3.0-Snapshot-20150320%20JDC3.vmod?dl=0):
1) 81* MTR Savu M42 - when DM, and you click malf, becomes a 5PP DM Finn mtr malfed, not the 4PP like it should

2) The 81* MTR GrW34 (g) become an LMG when you dm it.

![image](https://cloud.githubusercontent.com/assets/5281926/7105782/61fc6350-e0ef-11e4-9c7c-49ed6b3d30a2.png)

**Comment by davidsullivan317** [comment]
I'm going to take this issue
