### ISSUE TITLE
Support multiple instances of the same board on the map

### ISSUE THREAD

**Issue by davidsullivan317** [vasl-developers/vasl#220]
The board picker does not support multiple instance of the same board on the map. For example when using two copies of the same board you cannot crop both of them - only one. 

There may be other limitations as well, but have to check. E.g. applying SSR terrain changes, BSO, etc.

**Comment by mistertakai** [comment]
That would be a most welcome change. AP102 cannot be setup without this, for example.

**Comment by styson** [comment]
Adding overlays would be a concern as well - how do I select the right board?

**Comment by derimmer** [comment]
In terms of overlays, the best solution would be to move overlay selection to a drag-and-drop method. I know David has been thinking about this. Not sure how complex that would be.
