### ISSUE TITLE
Board 52 is too narrow

### ISSUE THREAD

**Issue by zgrose** [vasl-developers/vasl#229]
bd52.gf is 1799 x 645 whereas other boards (all boards?) are 1800 x 645 and that can produce visual anomalies when laid out next to other boards.

see http://forums.gamesquad.com/showthread.php?123212-Map-issue-how-to-make-the-quot-gap-quot-disappear&p=1760007#post1760007

**Comment by BigAl737** [comment]
I'll take this one.

**Comment by BigAl737** [comment]
Done. Will upload later.

**Comment by BigAl737** [comment]
pushed to: https://github.com/vasl-developers/vasl-boards-extensions/tree/master/boards

#229 is fixed and added lightwoods #187 

I'll leave this open if Sam wants a reminder to update the website.

**Comment by BigAl737** [comment]
version 6.1 is active and uploaded to website.
