### ISSUE TITLE
Fix board 17z BSO

### ISSUE THREAD

**Issue by davidsullivan317** [vasl-developers/vasl#230]
The title says it all.

**Comment by davidsullivan317** [comment]
These are done with the exception of this issue: 17 includes a railway line on the western edge of where the "z" board overlay should be. In other words, looks like when MMP created 17z the railway graphic was not used. Everything else in the overlay layer; it looks like just a matter of using that image and removing the railway line.

**Comment by BigAl737** [comment]
I'll take this one.

**Comment by BigAl737** [comment]
#230 is done. I'll push the board in a sec.

**Comment by BigAl737** [comment]
Calling SAM Tyson...

Bds 3, 10z, 17z, 19, and RBv2 are in their respective vasl/boards/src folder. You are cleared to add/update them on the VASL.info site please. Thanks very much.

Al

**Comment by styson** [comment]
vasl.info updated, including 10z and 17z

**Comment by BigAl737** [comment]
Thanks Sam.
