### ISSUE TITLE
Mark Unmoved button should be on the left

### ISSUE THREAD

**Issue by davidsullivan317** [vasl-developers/vasl#231]
The button disappears too often on various screen configurations. so it should be to the left of the QC counters.

**Comment by FredKors** [comment]
Ok, I’ll try to change the position of the button.

From: David Sullivan 
Sent: Sunday, July 19, 2015 2:29 PM
To: vasl-developers/vasl 
Subject: [vasl] Mark Umoved button should be on the left (#231)

The button disappears too often on various screen configurations. so it should be to the left of the QC counters.

**Comment by FredKors** [comment]
Done!

From: David Sullivan 
Sent: Sunday, July 19, 2015 2:29 PM
To: vasl-developers/vasl 
Subject: [vasl] Mark Umoved button should be on the left (#231)

The button disappears too often on various screen configurations. so it should be to the left of the QC counters.
