### ISSUE TITLE
Context menu: switch order of CW and CCW items

### ISSUE THREAD

**Issue by jvarsoke** [vasl-developers/vasl#232]
This is an incredibly trivial change that mitigates a lot of frustration.  When my opponents and I use the right-click context menu for rotating the VCA or TCA we choose the wrong direction 90% of the time -- much more than chance would favor.  And I think I figured out the small HID reason why:

Clockwise is the first choice
Counter clockwise is the second choice

As people imagine rotating things they seem to assume a 12 o'clock position, or 1-3 o'Clock position when working on which is CW/CCW in their head (regardless of AFV orientation).  This makes CCW an "UP" or "Left" direction and CW a "Down" or "Right" direction.  This conflicts with the order in the context menu.  So, instinctively people choose the wrong one.

Of course, anyone who uses the interface on a more regular basis will get used to the reversed order, but the small change would mitigate adoption frustrations.

[yeah, this is a really long explanation for what is probably a 5minute change that developers will see as unimportant -- small UI things are so often neglected]

**Comment by davidsullivan317** [comment]
A couple of thoughts on this request: 

While not a large change it's not trivial. VASL uses a bunch of templates to define the counter rotation command and each of these would have to be updated and tested. Testing would be most of the effort.

I'd prefer to get some feedback from the VASL community before making a change like this. People have stuff like menus memorized and what's seems logical to you (i.e. the menu order implying the rotation order) may not make sense to others. Would you mind hosting a GameSquad discussion before "blessing" this request?

**Comment by jvarsoke** [comment]
Understandable.  Thanks for not dismissing the request out-right.

I assumed the order of the context-menu was just part of an array -- somewhere were the two values would be trivial to swap.  [to be clear, I'm not suggesting changing the hot-keys, nor what it Clockwise and CounterClockwise means -- just the order of the menu items].

I'm sure people who are used to it will be inconvenienced until they adapt, should a change be made.  Personally, I'll have to undo my mnemonic to "pick the wrong one". ;)
