### ISSUE TITLE
More reminders for special die rolls

### ISSUE THREAD

**Issue by Taschenschieber** [vasl-developers/vasl#236]
In the spirit of pull request #228, I'd like to add some more reminders for special die rolls. The ones I can think of right now are HoB, Unlikely Hit/Kill, Dud, MALFs, Double Hit on low caliber guns and Cower (already implemented). Anything else that people tend to forget?

I'd also like to make the whole thing look a bit better (color is annoying right now) and implement a setting for full reminders, Starter Kit reminders only and switching them off entirely.

Might get to it this weekend, but no promises.

**Comment by rdewhurst** [comment]
Great idea. The things I forgot most are at Night: NVR change from the WC roll, Jitter fire from the Straying DR, but we don't currently have special VASL DRs for those.
Casualty MC on MC? Fate on Rally? Booby traps on TCs?

**Comment by Taschenschieber** [comment]
Fate and Casualties are things I shouldn't have missed. I'll have to look into the night rules to check if there are any sensible methods to recognize WC or Straying rolls, but I'm afraid there probably aren't. Booby traps can go on the list, I don't think there are too many special effects for TCs anyway.

So thanks for your thoughts! :)

**Comment by Taschenschieber** [comment]
I would really appreciate a pointer about where the module's GlobalProperties are set up, as they are not in the buildFile as I would expect after reading the VASSAL documentation...

**Comment by davidsullivan317** [comment]
By global property do you mean creating a preference that you can use in your code? If so the LOS class provides a simple example of how to do this: vasl/src/VASL/build/module/map/VASLThread.java

**Comment by Taschenschieber** [comment]
Exactly that, and thanks. I've spent about an hour looking for an example like that, which was a) annoying and b) embarrassing.

**Comment by davidsullivan317** [comment]
I've merged your code changes.
