### ISSUE TITLE
CX for dummies

### ISSUE THREAD

**Issue by davidsullivan317** [vasl-developers/vasl#237]
No, not the book,silly, but rather adding the  CX option to concealment counters as dummy stacks can double-time.

**Comment by hongkongwargamer** [comment]
Yes .. needing to clone a CX counter from somewhere else is a dead giveaway that it's a dummy stack.

**Comment by derimmer** [comment]
Is there a reason NOT to do this? I tried adding a Place Marker trait to the Russian ? counter and it worked fine, showing up in the Move submenu just as it does for other counters. Simple to add it to the ? counter for each Nationality. What about Cloaking counters? And not the 5/8" counter I presume?

I could not find a prototype to add this to as the ? counter just uses the Unit prototype. Adding in there would add it twice to MMC and SMC counters, which get it from INFMark.

**Comment by derimmer** [comment]
While it is easy to add CX to the counters in the counter palette, the option does not show when using the popup menu. Need to add this in code?

**Comment by zgrose** [comment]
More than one piece id involved?

**Comment by derimmer** [comment]
Hmmm, yes if I add it individually to each counter. There is no good prototype to use. Might have to create a new one. This is not going to be an easy one.

**Comment by derimmer** [comment]
Was able to create a new prototype that handled this quite well. @BigAl737 as per our discussion, I have got a degree of consistency between nationalities but we still have ? counters in two different counter palettes. I could not redirect the concealable.java class to look to VASL counters. Didn't want to risk mixing up that class which I find very hard to understand. So, less than optimum but working.

**Comment by BigAl737** [comment]
As long as the ? counters in both locations are exact copies of each other, we should be good. The potential problem is if down the road, the ? counters in the VASL Counters piece tray are changed and those changes aren't copied to the ? counters in the hidden piece tray.

We need a VASL secretary to record all this stuff for the follow on generation :-)

**Comment by BigAl737** [comment]
and oh yeah... nice job Doug. Concealment is everywhere in the build file. Glad you found a way to simplify the process.

**Comment by derimmer** [comment]
> We need a VASL secretary to record all this stuff for the follow on generation :-)

Best way to do that is to create an issue and describe it!
