### ISSUE TITLE
Add SSO to bd 3 and 19 for scenario J44 and OB3

### ISSUE THREAD

**Issue by BigAl737** [vasl-developers/vasl#243]
I've got this done. If I upload it to the source board files it will over write some of the files (data, metadata, SSR control...etc.). Is that okay? Don't want to lose something that can't be recovered should it need to be.

**Comment by davidsullivan317** [comment]
Go ahead and upload your changes. The beauty of GIT is that nothing that is done cannot be undone. 

BTW - are you bumping the versions of the boards and also incrementing board version file?

**Comment by BigAl737** [comment]
Re your BTW, I update the board version in the data and metadata files. I will ask Sam to post the new versions to the VASL Boards download site. Is that how it’s done?

Al

**Comment by BigAl737** [comment]
This is done...if I did it correctly that is. Sam, you'll find a new bd03 and bd19 file. Please upload these to the VASL Boards download web page. That is you are the right person to ask to do this. My apologies if not. bdRBv2 is ready to post to the boards web page as well. You'll find that in the RBv2 src folder. Thanks Sam.

**Comment by davidsullivan317** [comment]
One more step if you don't mind Al - bump the version numbers in the board version file here: https://github.com/vasl-developers/vasl/blob/develop/boards/v5boardVersions.txt

**Comment by BigAl737** [comment]
Done
