### ISSUE TITLE
Give me writing access?

### ISSUE THREAD

**Issue by Taschenschieber** [vasl-developers/vasl#246]
Hello,

it might make things easier if I could directly write to this repo instead of having David pull my stuff over and over again.

Not sure what's the best way of reaching out, so I'm just throwing it here.

(I'm not 100% comfortable with having my clear name here, but we have talked on the Facebook VASL group before and I can drop one of you guys a note there so you know who I am.)

**Comment by mistertakai** [comment]
Adding your full legal name to your GitHub profile helps.

**Comment by Taschenschieber** [comment]
Like I said, not too keen on having my nickname and real name _too_ closely related in public. I just sent you and David messages on Facebook, where I have my full name.

**Comment by zgrose** [comment]
Doesn’t one add collaborators by GitHub username anyway?

**Comment by davidsullivan317** [comment]
You've been added.
