### ISSUE TITLE
Malf, Booby Trap DR notifications

### ISSUE THREAD

**Issue by Taschi120** [vasl-developers/vasl#248]
Suggested in #208. Current idea is, make Malf notifications dependent from what counters currently are in play and make Booby Traps a scenario info option.

**Comment by derimmer** [comment]
I have done the Booby Trap part. I cannot figure out a way to do the Malf part. I assume that what is meant is that a Malf notice would show in the chat window IF AND ONLY IF a Gun/SW/Vehicle was in play. I cannot find any metadata/traits/properties that would allow for this to be checked easily. Am I missing something? If not, I am tempted to close this issue.

**Comment by derimmer** [comment]
Closed
