### ISSUE TITLE
Sniper icons no longer report on DR images

### ISSUE THREAD

**Issue by davidsullivan317** [vasl-developers/vasl#253]
They do report in the chatter but are now missing from the DR image.

**Comment by FredKors** [comment]
Fixed

From: David Sullivan 
Sent: Friday, November 20, 2015 11:29 PM
To: vasl-developers/vasl 
Cc: Federico Corso 
Subject: [vasl] Sniper icons no longer report on DR images (#253)

They do report in the chatter but are now missing from the DR image.

**Comment by davidsullivan317** [comment]
f9696ecb1b775c02a2ab459b553641bfa2c9b505
