### ISSUE TITLE
Desert boards do not change into the ETO colors anymore.

### ISSUE THREAD

**Issue by davidsullivan317** [vasl-developers/vasl#256]
Desert boards (DT0) do not change into the ETO colors anymore.

**Comment by zgrose** [comment]
It seems that this is just a matter of adding the colorSSR blocks into the BoardMetadata.xml files?

e.g.

````
		<colorSSR name="DTOtoETO">
			<colorMap fromColor="DTO_Level0_1" toColor="Level0" />
			<colorMap fromColor="DTO_Level0_2" toColor="Level0" />
			<colorMap fromColor="DTO_Level0_3" toColor="Level0" />
			<colorMap fromColor="DTO_Level0_4" toColor="Level0" />
			<colorMap fromColor="DTO_Level0_5" toColor="Level0" />
			<colorMap fromColor="DTO_Level0_6" toColor="Level0" />
			<colorMap fromColor="DTO_Level1" toColor="Level1" />
		</colorSSR>
````

With just that much into a bd26 file I was able to get this effect. Is there more to this issue than some busywork?

<img width="706" alt="screen shot 2016-06-20 at 6 29 12 pm" src="https://cloud.githubusercontent.com/assets/5044847/16215226/eb6b4f12-3714-11e6-8a54-e981987c2f53.png">

**Comment by davidsullivan317** [comment]
Better to add the transformations to the shared metadata file. All boards get these transformations by default. I don't know off the top of my head why they are not working. 

https://github.com/vasl-developers/vasl/blob/develop/dist/boardData/SharedBoardMetadata.xml

**Comment by zgrose** [comment]
Perhaps you're referencing the wrong color names? I was using the DTO_ colors in the board files.

This would require a full VASL version bump to fix tho, correct?


````
<color name="DTO_Level0_1" red="233" green="197" blue="40" terrain="Open Ground" elevation="0" />
<color name="DesertL0" red="251" green="223" blue="147" terrain="Open Ground" elevation="0" />

		<colorSSR name="DTOtoETO">
			<colorMap fromColor="DesertL_2" toColor="Level_2"/>
			<colorMap fromColor="DesertL_1" toColor="Level_1"/>
			<colorMap fromColor="DesertL0" toColor="Level0"/>

````

**Comment by davidsullivan317** [comment]
Could be - I haven't looked at this. The ETOtoDTO transformation supports a limited number of terrain types, but brush is one of them and that does not appear to be working. 

And, yes, updating the shared metatdata requires a release. But the board metadata transformations take precedence so we could do both.

**Comment by zgrose** [comment]
Boards 26-31 have their board files updated, no complaints yet. I don't have a setup that supports testing code changes so if anyone wants to take that on, I can supply the colorMap (or you can grab from a board like 26) and see if the shared metadata has the same effect.

**Comment by derimmer** [comment]
I have tested that Zoltan's changes continue to work on boards 26-31. I also changed the SharedBoardMetaData.xml file in the boardData directory so that it now aligns with the colors and transforms found in the BoardMetaData.xml files in boards 26-31. I believe that this issue can now be closed.
