### ISSUE TITLE
VASLize AP 11 Overlays

### ISSUE THREAD

**Issue by BigAl737** [vasl-developers/vasl#260]
'nuff said

**Comment by BigAl737** [comment]
I've got this one.

**Comment by BigAl737** [comment]
pushed and submitted for upload

**Comment by BigAl737** [comment]
complete

**Comment by BigAl737** [comment]
I probably closed this too early. Sam, GS guys are reporting that ovrOB is not available on the website as part of the standard overlays archive file. I confirmed this. Also noted that ovrX and ovrST weren't updated in the archive as well.

The updated overlays referenced above are all available here:
https://github.com/vasl-developers/vasl-boards-extensions/tree/master/boards/overlays 

I will, or Sam can close this issue again when the web is updated.

**Comment by styson** [comment]
Correct me if I'm wrong, but the vasl-boards-extensions repo contains all of the boards and overlays, precompiled/zipped/renamed-without-zip files that I need to push to the website.

Currently I am pulling all of the boards from the vasl-developers repo, and building zip files from the src. I would be more than happy to simplify this process and just pull the complete files.

**Comment by derimmer** [comment]
Hi Sam

 

My understanding matches yours. 

 

Under the current system, we (meaning you) have to migrate files from vasl-boards-extensions to the vasl.info website. As far as I know, you are the only one who is doing it and knows how to do it (perhaps David Sullivan does too). 

 

IMHO, it is much easier for you to take the compiled boardarchive files from vasl-boards-extensions/boards than to go into vasl-developers/vasl/boards/src and build the zip files from there. 

 

For those involved in building boards we should be responsible for both updating the vasl-developers/vasl/boards/src with all of the necessary files and then compiling those files and adding the compiled file to vasl-boards-extensions. 

 

Given that we have a number of new people involved in this (myself included), which is good news, it seems that we are having some miscues in the mechanics of this here and there. 

 

This is further complicated by the fact that the board building process seems to happen in two parts. First the creation of the gif file, the overlays, and the boardmetadata file. And secondly (and for the most part by different people) the addition of the LOSData. Some people know how to compile the boardarchive files (using BoardBuilder) and some don’t yet (and may not need/want to know). 

 

David Sullivan has written a short document about all of this process available at https://github.com/vasl-developers/vasl/wiki/Updating-Boards-in-the-Age-of-Automatic-Board-Synchronization. It would appear that it could use some further elaboration which I would be happy to take a stab at and post for comments. 

 

Doug

**Comment by BigAl737** [comment]
Doug, this is an excellent synopsis. Thank you!

I understand the process better now...I think :-)

I went back and read yet again David's board building checklist. Although I don't know how to use board builder (I am doing the compilation process manually), I was understanding the steps and following them...I thought. It seems I was missing step 6, not realizing that there was yet a third location to post board and overlay files. And I believe my omission was confusing Sam. My apologies guys.

I'm back to work now and gonna step back for a week and just stay out of the way. If someone would like to flesh out ovrOB, ovrST and ovrX and put them where Sam needs them to be for updating vasl.info, I would appreciate it. Else I'll continue to educate myself over this next week and try again to get it right when I get back.

Thanks guys. And again, my apologies for messing up the system I'm trying hard to understand.

Have a great week!

Al

**Comment by bkemp01** [comment]
I think us elves are supposed to place the board "source" files (i.e. what needs to be assembled into a board archive) plus the layered file (PSD/XCF) into the VASL source repo (vasl/boards/src) and place the assembled board archive into the boards repo (vasl-boards-extensions/boards). We should also update the v5boardVersions.txt in vasl/boards/src. Similar steps would apply to overlays. Unless I'm missing something it seems that running BoardBuilder is not needed as long as the proper files are being included during a manual build of a board archive file.

What the elves can't currently do is create the LOSData. That requires David or Doug at this point. Where that fits into the steps I'm not sure.

**Comment by derimmer** [comment]
Brian, you may well be right. I only know one way to build the boardarchive file and that is by running BoardBuilder, which as far as I know has only one purpose and that is to build boardarchive files. If there is a “manual” way to do so, then fine. I don’t know what it is but that shouldn’t stop anyone else. 

 

David has a strong preference (ok, mandatory requirement) that I use BoardBuilder to rebuild the boardarchive files after adding LOSData to them. Which I kind of screwed up this weekend but think I eventually got it sorted. 

 

You are definitely right about updating the v5boardVersions.txt file. 

 

I will try to add all of this to David’s initial notes. 

 

LOSData is added to a boardarchive file once the elves create one. Thanks to David’s amazing hard work, adding LOSData is becoming pretty straightforward for geo boards. It took me about 15 minutes for boards 71 and 73 this weekend. Board 72 took longer because I had some learning to do. This was only the second time I had done it and I managed to make a mountain out of a molehill but all part of the learning curve.

 

After adding the LOSData we then have to update/upload the files to the various repositories. Something I totally buggered this weekend. 

 

Doug

**Comment by bkemp01** [comment]
No worries with BoardBuilder, it's just that this weekend was the first I
have ever heard it mentioned and I've been contributing boards for a couple
of years without it. If that is the preferred method we could use a little
help on how to run it. Or it may be that those of us that are making boards
already know what needs to go into the archive and maybe BoardBuilder was
intended for the non-elves to be able to easily compile a board archive
without having to understand the inner workings. Or maybe BoardBuilder was
intended to add some sort of automated background process to build board
archives on the fly. I guess only David can say what the purpose is.

It seems most of us are rather unsure of all of these mechanics. The wiki
page Davis put up is certainly helpful but as Al mentions it could use some
more detail.

**Comment by BigAl737** [comment]
I think we can safely close this one.
