### ISSUE TITLE
VASLize boards 69 and 70

### ISSUE THREAD

**Issue by BigAl737** [vasl-developers/vasl#261]
Brian Kemp has got these well underway.

**Comment by bkemp01** [comment]
Added boards 69 & 70 to src. David, please create the LOSdata. Sam, please publish to vasl.info.

**Comment by davidsullivan317** [comment]
Tagging commit to issue. 7a5447085335320b8d1e5492927a541e38c49c10 

I'll get LOS added and the boards built this weekend.

**Comment by styson** [comment]
Boards 69 & 70 are now included on vasl.info.
