### ISSUE TITLE
VASLize board 71 and 73

### ISSUE THREAD

**Issue by BigAl737** [vasl-developers/vasl#262]
New map cabal member Scott Hasson has graciously offered his services. Welcome Scott! (sfx: golf claps) Board 73 is almost done.

Sully, can you invite Scott to become a member of this esteemed group? His email:

swhasson@yahoo.com

**Comment by davidsullivan317** [comment]
You'll have to send me his Github account name

**Comment by BigAl737** [comment]
pushed and submitted for upload

**Comment by BigAl737** [comment]
Completed...thank you Scott!
