### ISSUE TITLE
VASLize board 72

### ISSUE THREAD

**Issue by BigAl737** [vasl-developers/vasl#263]
'nuff said. I'll take this one unless someone else really has a hankerin to do it. Just let me know and it's yours.

**Comment by BigAl737** [comment]
pushed and submitted for upload

**Comment by BigAl737** [comment]
complete

**Comment by derimmer** [comment]
I have pushed 71, 72 and 73 with LOS checking up to vasl-developers/vasl-boards-extensions/tree/master/boards.

I think that there is one step missing in order for folks to have access to them and that is to get them to vasl.info. I don't know how to do this? Does it happen automatically at some point or does someone (me?) need to do it?

I pushed 69 and 70 up the same way and I think they also need to get into vasl.info. It does not appear that the versions currently on vasl.info have los checking active. 

Perhaps there is a testing or QC step here that Sully would normally do? If someone wants to grab the boards from vasl-developers/vasl-boards-extensions/tree/master/boards and try them out, that would be great. LOS Checking appeared to work fine to me. 
Thanks for any help on this.

**Comment by bkemp01** [comment]
Not sure but do the LOSData files need to be added to vasl/boards/src?

**Comment by derimmer** [comment]
I did the work on 69 and 70 under David Sullivan's direction and did not do so. I don't recall him telling me to do so. 

OTOH, I am very new to all of this. So I could easily have missed something.

**Comment by davidsullivan317** [comment]
Yes - the LOS files should be pushed to the vasl/boards/source. When
updating a board we always want to build the board with BoardBuilder from
the repository to ensure all files are there.  -Sully

**Comment by derimmer** [comment]
OK. Will do.

**Comment by derimmer** [comment]
Thanks for the reminder Sully. I have now done this as per your document on the wiki. I pushed the board files to the board repository yesterday and to the code repository today.

**Comment by bkemp01** [comment]
I added an exclusion for .xcf files to BoardBuilder, with more GIMP users
coming on board it seems this file type is seeing more action. I think it
is a good idea to keep the layered bitmap files someplace for safe keeping
and for future board updates. If vasl/boards/src is not the place for them
can someone please help with finding them a home to live in?

Also noticed that the board archives for 71-73 in the boards repo contain
an embedded/redundant copy of the board archive making them twice the file
size of a "normal" board archive file. I think this may be because Al
uploaded a board archive to the vasl/boards/src folders which was then
included in the new archive when BoardBuilder was run. This should probably
be cleaned up.

**Comment by BigAl737** [comment]
I see this too Brian and I think you’re exactly right as to the cause. Good catch. Since I’ve got no clue as to how to run board builder, I think it’s best for someone else to fix this. So thank you whoever.

In the future, is it best to NOT include a board archive file in the vasl/boards/src?

Al

**Comment by derimmer** [comment]
I will look after this and will upload the changes to the VASL board and code repositories. Wish me luck.

**Comment by bkemp01** [comment]
It looks like the process is for the board archives to be built using the
BoardBuilder tool which takes the files from vasl/boards/src and compiles
them into a board archive file which then get uploaded to the
vasl-boards-extensions repo and that repo (I think) is used in the board
auto updater code and also (I think) ties to the vasl.info website for the
zip file downloads.

I think we should _not_ include a board archive file in the
vasl/boards/src. I think we _should_ include our layered source file (PSD
or XCF) in vasl/boards/src, at least until such time as we have some other
repo to hold them.

It would be great if someone could spell some of this out for us lowly
elves.

Thanks

**Comment by mistertakai** [comment]
Keeping the source files (PSD/XCF) for the boards in vasl/boards/src is the way to go. Tom did that for the other boards as well. This ensures that we have everything in the repo and no assets are missing. The BoardBuilder should filter that stuff out prior to uploading to the vasl-boards-extensions repo.

**Comment by bkemp01** [comment]
Thanks Daniel. I know most boards have a source file in the repo (some of
the BFP boards seem to be missing). Unfortunately I think that some people
that have been fixing board issues have been making edits directly to the
GIF files in src which means the original layered sources are falling
behind and at some point won''t be of much use. The proper way to fix a
board issue would be to make edits to the layered source files and use that
to generate new GIF files just like when we create a new board.

**Comment by bkemp01** [comment]
I copied the LOSData from the board archives of bd69 and bd70 to
vasl/boards/src so that future builds of these boards will include the
LOSData.
