### ISSUE TITLE
Reported RBv2 link is dead on vasl.info

### ISSUE THREAD

**Issue by BigAl737** [vasl-developers/vasl#265]
http://forums.gamesquad.com/showthread.php?88439-The-VASL-Map-Bazaar-is-open!&p=1791538&viewfull=1#post1791538

Confirmed. I too get 404 page not found.

**Comment by davidsullivan317** [comment]
There is separate repository, with it's own issues DB, for the vasl.info code. Would suggest this be moved there.

**Comment by Taschenschieber** [comment]
Looks like somebody forgot to upload the file, it's AWOL in the repo.

**Comment by styson** [comment]
I came across this today, and now have it fixed.

http://vasl.info/other.htm
