### ISSUE TITLE
SdKfz 10/4 does not flip

### ISSUE THREAD

**Issue by mistertakai** [vasl-developers/vasl#268]
The German SdKfz 10/4 does not flip, as it should. It's backside should be missing the trailer depiction.

![image](https://cloud.githubusercontent.com/assets/3066447/12181546/30e67e04-b583-11e5-98fa-468e21a8662e.png)

The counter should look like this:

![image](https://cloud.githubusercontent.com/assets/3066447/12181705/2846c280-b584-11e5-9bb0-f946e5cc7f3e.png)

Thanks for looking into this.

**Comment by zgrose** [comment]
For whomever is most in tune with the pieces:

<img width="1367" alt="screen shot 2016-01-07 at 1 29 28 pm" src="https://cloud.githubusercontent.com/assets/5044847/12183275/c90b4dea-b542-11e5-80d7-9406263c824e.png">

**Comment by BigAl737** [comment]
This seems to be fixed. The Trailer version "flips" to the non-trailer version with ctrl+V.

Both versions "flip" to depict the correct wreck image.

![image](https://cloud.githubusercontent.com/assets/10384413/24524101/ea861f94-1541-11e7-9c8b-ff2650c5201a.png)

Interesting that the cardboard counter non-trailer side does not have the halftrack symbol in the upper right hand corner. The VASL counter does. I'll bet there's errata for that somewhere. But that's beside the point here. VASL has it right.

And if anyone wants to tell me why the VASL wreck side info window says MG -/-, I'd like to know.

Regardless, can this be closed?

**Comment by zgrose** [comment]
> And if anyone wants to tell me why the VASL wreck side info window says MG -/-, I'd like to know.

Because copy/paste is the counter maker's friend! It's just there in the definition (bolded).

<VASSAL.build.widget.PieceSlot entryName="SdKfz 10/4 w/o Trailer Wreck" gpid="5340" height="60" width="80">+/null/prototype;DBGlobal	info;CS 5,**MG -\/-\**	prototype;geWRK\\	piece;K;D;ge\/veh\/sdkfz105bw;SdKfz 10\/4 w\/o Trailer Wreck/	\	\\	null;0;0;5340</VASSAL.build.widget.PieceSlot>

**Comment by BigAl737** [comment]
Thanks Zoltan. I wasn't very clear but I was wondering why the MG -/- is part of the info window in the first place. This note is not on the physical counter. Or maybe I misunderstood your answer and you're saying that it's just a cut and paste error. If that's the case I should delete it and make the wreck side info window to read the same as the non-wreck side.

**Comment by zgrose** [comment]
Not sure why wrecks even have info strings but I think I've got the MG -/- convert to MG:AA.

**Comment by zgrose** [comment]
Tagging for easy reminder to self:
http://www.gamesquad.com/forums/index.php?threads/temp-counter-error-collection-thread.131969/#post-1880614
