### ISSUE TITLE
LOS off on cropped board 

### ISSUE THREAD

**Issue by davidsullivan317** [vasl-developers/vasl#270]
Flipping board u and cropping (to middle of hexrow) A - P 
When done LOS tool off. Cannot have it snap to center dot of hex.

If I flip board u and crop A-Q (to middle of hexrow)
LOS tool works just fine.

**Comment by derimmer** [comment]
Did some quick testing on this. It is not a board u issue as it happens with other boards as well. Plus, while it seems to be actually doing the LOS check properly along the line - which is using the wrong start and stop points -  it is showing the wrong hex values (as if board wasn't cropped).

**Comment by derimmer** [comment]
Belay part of my previous comment. The problem with the display of the hex values only happens when I use my development version - must have done something that is messing that up. When I using the beta vasl 6.3.0,. I get the errors as described in the original post.

**Comment by davidsullivan317** [comment]
The LOS should have turned off when the board is cropped a-p but didn't because an exception is no longer being thrown. I've forced it to turn off. This is fixed in the 6.3 branch if you want to take a look.
