### ISSUE TITLE
Counter error on It Lancia 1ZM

### ISSUE THREAD

**Issue by ThirstyMan** [vasl-developers/vasl#271]
The Italian vehicle Lancia 1ZM is displayed as -4/6 it should be -4/8 according to ASLRB.

**Comment by JLeslie1004** [comment]
Fixed. Also, I am not aware of any errata that says this vehicle should be using Armored Car movement rates and according to Chapter H, this vehicle should have the two white dots behind the MP allowance signifying Truck movement rate. Fixed that too. 
![lancia](https://cloud.githubusercontent.com/assets/16937555/12675193/9d1015e8-c656-11e5-9b27-9aeb4c6b16f3.gif)

**Comment by mistertakai** [comment]
Thanks, Jeff

**Comment by zgrose** [comment]
Oops, used a magic word in the commit and closed prematurely.
