### ISSUE TITLE
Instructions for Adding Boards to VASL or Updating Existing Boards

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#274]
As per the various lines of discussion over the past week about the process for adding Boards to VASL or updating existing boards, I have tried to update the initial documentation created by David Sullivan. Revised page is [here](https://github.com/vasl-developers/vasl/wiki/Creating,-adding-LOS-data-to,-and-Updating-Boards-in-the-Age-of-Automatic-Board-Synchronization). 

I encourage you to review and edit the document (or send comments to me) to correct errors or omissions, or to add further detail if you think it would be helpful. If it raises questions in your mind or is unclear to you, please ask away. 

I am not an expert on any part of this process and have not done many of the steps involved. I wrote this based on what some of you have told me about what you do. If I misunderstood or mixed up any of what needs to happen, please point that out. 

In particular:

Are overlaySSR and SSRControls mandatory or optional files for inclusion in the VASL board file.

The document refers to an example of the boardmetadata.xml file and a Wiki page on Boardbuilder. Still to come.

I did not describe the process for adding files to vasl.info. Can someone let me know how it is done. Sam, I think you are the man on this at present?

**Comment by BigAl737** [comment]
Thanks for updating this Doug. I'll follow it for the next board I need to update and let you know how it goes. Right now the hang up seems to be getting the file uploaded to the vasl.info website downloads page. The new overlays I did are still not uploaded although the AP11 boards are. And I can't get feedback on if I've put those overlay files where they need to be so Sam can upload them to the website. So I'm not sure if the hang up is me or not. I guess I'll wait for Sully to get back. He seems to be the big cheeseburger around here :-)

**Comment by styson** [comment]
I have been working on updating the website release process.  As a stop-gap, I will add the new overlays to the files.

**Comment by BigAl737** [comment]
Fantastic Sam! Thanks very much. I look forward to learning more about the website release process. Thank you for handling this part of the process for us all.

Allan

**Comment by styson** [comment]
I have changed the website to use the [gh-pages](https://github.com/vasl-developers/vasl-website/tree/gh-pages) branch as its content. If we can get that branch set as the default brach, then we can remove the master branch. At that point, any commits to the [vasl-website repo](https://github.com/vasl-developers/vasl-website/tree/gh-pages) will be live on the website. For board and overlay updates, that means that the new zip files can be dropped right into the boards and overlays folders. Any new boards, such as 74 & 75) would also need to be get links added to the board.htm folder.

**Comment by BigAl737** [comment]
This is so cool Sam! I noticed today that the RBv2 board link was dead so I pushed the board to the link you specified and the download link is alive again. Thanks for streamlining this process.

Al

**Comment by derimmer** [comment]
I have been trying to puzzle out exactly what needs to be done to ensure that new/updated boards are available on the vasl.info website. 

If I understand correctly, all that needs to be done is for the map creator to place a copy of the board archive file (without the .zip extension) in a zip file of the same name and then place that zip file in the vasl-website repository.

The process for this "placing" is that same as for adding boards to the vasl-boards-extensions repository which feeds the new automatic board updating functionality in VASL6.3 - except that in the case of these boards, they must not be wrapped in a zip file. 

Can it be this simple?

If I have it right, then I will update the instruction document on the wiki accordingly. If not, please explain. 

Thanks.

**Comment by styson** [comment]
That is correct regarding the zip files and vasl.info.
The other key piece is to update the version number in the boards/versions.json file.

**Comment by BigAl737** [comment]
Your understanding is correct Doug. There is one final step. You must update the .json file referred to by Sam in his email from another thread. I’ve pasted the contents of that email below.

"Currently the versions are pulled from https://github.com/vasl-developers/vasl-website/blob/gh-pages/boards/versions.json <https://github.com/vasl-developers/vasl-website/blob/gh-pages/boards/versions.json>. This file might be duplicated, but for now it is the source for the website. Changes made to the file take 5-10 minutes to propagate to vasl.info <http://vasl.info/> via github pages."


Seems we are duplicating our board posting efforts a bit but the process does seem to work so I’m not advocating streamlining it at this point. I think it is important to realize that the automatic board update process of VASL 6.3.3 gets it’s board version number data from the 5boardversions text file here:

https://github.com/vasl-developers/vasl/tree/develop/boards <https://github.com/vasl-developers/vasl/tree/develop/boards>

So whomever uploads the board to the vasl-website repository should be the one to immediately update the 5boardversions text file in the vasl-developers link above.

Allan

**Comment by BigAl737** [comment]
I just loaded VASL 6.3.3 and loaded a new game with board 40. VASL said my board was out of date and that the update failed. Said it was using bd40 v6.0. However, I could load the AP103 SSO so I know the board was actually v6.1. I quit VASL and  reaccomplished the same steps. VASL again said my board was out of date but this time the update was successful. However the board version said 6.0 but again I could load the AP103 SSO so I know the board version was 6.1. I can’t see any reason that VASL should say the update succeeded AND it was using v6.0.

This stuff is gonna drive me to an early grave :-)

**Comment by derimmer** [comment]
Al, I did the same as you. . . .downloaded 6.3.3 and then started a game with board40. Did it about 3 times, everytime it told me update had succeeded and that it was using v6.0. Which seemed right as no AP103 SSO available.

I then downloaded board40 from vasl.info (which said it was v6.1) and opened it in a game. VASL told me it was 6.1 and indeed it was and the AP103 SSO was available. 

Perhaps the problem may be that the board40 in vasl-board-extensions is v6.0 and not v6.1. I find it hard to be sure but from what I can tell, board40 was last updated in vasl-board-extensions by David in November 2015. If you have been trying to update the board there, it may not have worked. 

I am no expert in this stuff, so I may be misdirecting you. . . .

**Comment by derimmer** [comment]
Al, looking at this further, I see that you updated board40 in https://github.com/vasl-developers/vasl/tree/develop/boards <https://github.com/vasl-developers/vasl/tree/develop/boards/src> and also updated the 5boardversions.txt file. Which needs to be done. But as well, I think board40 still needs to be updated at vasl-extensions-boards.

**Comment by BigAl737** [comment]
Can you do that for me Doug? I’m on the road and don’t have the ability at present.

**Comment by derimmer** [comment]
Will try later tonight. Out for a couple of hours now.

**Comment by BigAl737** [comment]
Priorities Doug, priorities :-)

**Comment by derimmer** [comment]
Board40 v6.1 is now in vasl-boards-extensions. Good night and thank you mam.

**Comment by BigAl737** [comment]
And that seemed to do the trick Doug. Sleep well after a job well done.

thanks!

**Comment by derimmer** [comment]
I have updated the instructions page on the wiki to incorporate Sam and Al's comments about adding the files to the website. I think.

I am not sure that have understood how gh-pages branch should be used so feel free to edit.

**Comment by zcrater** [comment]
Am I just missing it?  My VASL v6.3.3 with board 40 v6.2 does not list the AP103 SSO.  I see above that board 40 v6.1 did have the SSO for AP103.

Zeke

**Comment by BigAl737** [comment]
Hmmm, I’ll check into this tomorrow.

Al

**Comment by derimmer** [comment]
Allan there was an error in the metadata file in board 40 which was preventing los from working at all. I fixed but may have used an older version. Coltan uploaded it for me. 

Doug. 

Ps am out of town and not really able to help on this.
