### ISSUE TITLE
Help text: malf/broken units

### ISSUE THREAD

**Issue by mistertakai** [vasl-developers/vasl#275]
The help text under Help -> Malf/broken Units says:

> After you load a game, a new icon (representing a Malf Gun) will appear in the
> 'VASL controls' dlog. Tag the button to open a resizable subdialog, where folders
> representing the current map(s) will appear. Double-click a folder to open it, &
> a list of those hexes containing broken/malf ctrs will drop down. Double-click
> the hex-folders to open them & a list of ctrs will drop down. Click on one of the
> listed ctrs, and the main map will attempt to re-center on that hex. All off-map
> ctrs will appear in a single folder named 'offboard'. The ctrs in the list are
> 'live' - right-click on one, or tag it to give it the highlight - give it a ctrl-
> command & that change will be immediately duplicated by its on-map twin.

In fact, after clicking the button broken/malfed units/sw will be highlighted with a red circle. The help text should be corrected.

This is a very useful function that a lot of people do not know about.

**Comment by davidsullivan317** [comment]
The help text needs to be completely reworked.

**Comment by davidsullivan317** [comment]
replaced with #406
