### ISSUE TITLE
British Acquisition marker and HIP

### ISSUE THREAD

**Issue by mistertakai** [vasl-developers/vasl#277]
A very minor glitch: the British acquisition markers do not turn translucent like the others, instead they get a white background. The large version also has a graphical problem. See this screenshot:

![image](https://cloud.githubusercontent.com/assets/3066447/13539599/aff0cf6a-e251-11e5-9b9f-907a7874bbb1.png)

**Comment by davidsullivan317** [comment]
The "ghosting" of hip counters is a known issue and occurs with all of the area acq counters. 

I've fixed the "white background" issue.
