### ISSUE TITLE
Could all standard overlays also be draggable?

### ISSUE THREAD

**Issue by styson** [vasl-developers/vasl#280]
This would allow easy manipulation of overlays when setting up scenarios, especially when using VASL as a design tool.

Drag an overlay onto the boards, then be able to rotate it and move it around.

**Comment by davidsullivan317** [comment]
Yes they could. I've thought of this myself. The overlay code needs a once-over - they're difficult to make/maintain, difficult to add to boards, not yet supported by auto-synch, and the code needs some TLC. Might be time to rethink the whole paradigm.

**Comment by styson** [comment]
Seems like LOS concerns might be an issue. Would that matrix have to get recalculated after each change? Does that already happen for the current draggables?

**Comment by BigAl737** [comment]
You could do this just like we can do it now with the firelanes, colored arrows, turn tracks, etc. And I agree with you, I think that it’d be easier to handle overlays this way. Essentially we’d treat each overlay like a counter, but make it selectable with shift+click so you don’t accidentally pick it up once placed. The big benefit here is you can place the overlay across board borders. And the art already exists however the placement numbers aren’t on the art. But I really don’t see why we can’t do this...well with the exception of our time or lack thereof :-)

My 2 cents.

Al

From: Sam Tyson 
Sent: Friday, March 11, 2016 12:14 PM
To: vasl-developers/vasl 
Subject: [vasl] Could all standard overlays also be draggable? (#280)

This would allow easy manipulation of overlays when setting up scenarios, especially when using VASL as a design tool.

Drag an overlay onto the boards, then be able to rotate it and move it around.

**Comment by zgrose** [comment]
An issue with draggable overlays that has to at least be addressed is that one orients them visually on the map when you lay them down. However, the instructions for overlays are given as hex-pairs (e.g. place Wd5 on B5-C5) which is not so easy to figure out in VASL (I see BigAl737 just noted this).

Maybe just toss the overlay images into a "Designers Extension" if that's the main use-case?

**Comment by davidsullivan317** [comment]
Remember LOS is NA for overlays now. Doug Rimmer added an enhancement to detect and avoid them during LOS checks in 6.3. Maintaining that level of support would be straight forward.

**Comment by davidsullivan317** [comment]
@zgrose We could add the numbers to the images - a small 1 or 2 (yellow maybe) in the center of the hex. We could also resuse the current overlay images for the "counters."

**Comment by styson** [comment]
Adding the numbers onto the overlays would solve the placement problem.

We could have the number layer only visible when the overlay is selected.

**Comment by derimmer** [comment]
From a user's perspective, I think making overlays drag-and-droppable (and rotatable) is a big plus. Maybe I am just a numbnuts but it almost always takes me 2-3 tries to get an overlay properly placed on a map using the current dialog box. So many ways to screw it up. 

Not sure of the overall level of effort required but I think very worthwhile.

**Comment by davidsullivan317** [comment]
Let's use #330 and close this one
