### ISSUE TITLE
Updating games with cropped and flipped boards turns off LOS

### ISSUE THREAD

**Issue by davidsullivan317** [vasl-developers/vasl#281]
If you create a game with a board that is both cropped and flipped and update the board configuration the LOS engine will throw and exception and turn off. The problems is that when the board is flipped the variables columnNumber and rowNumber in the Hex objects are changed reflect the hexes new position in the flipped hex grid, but these values are not being reset when a new board configuration is picked. Either the flipped hexGrid or the individual Hex instances are being retained in memory and not getting reset. 

We want to remove cropping restrictions and add LOS support to non-GEO boards. This bug should be addressed as part of that work as the cropping and flipping logic needs to be refactored to support arbitrary relationships between the terrain and hex grids. 

```
java.lang.ArrayIndexOutOfBoundsException: 10
    at VASL.LOS.Map.Map.crop(Map.java:2945) ~[vasl-build/:na]
    at VASL.build.module.map.boardPicker.VASLBoard.cropLOSData(VASLBoard.java:105) ~[vasl-build/:na]
    at VASL.build.module.ASLMap.buildVASLMap(ASLMap.java:294) [vasl-build/:na]
    at VASL.build.module.ASLMap.setBoards(ASLMap.java:167) [vasl-build/:na]
```

**Comment by derimmer** [comment]
I have created a [beta3 build](https://www.dropbox.com/s/usiss0ue2xfnvgw/vasl-6.4.0-beta3.vmod?dl=0) of 6.4.0 which includes the code for maintaining LOS Checking under any  cropping and/or  flipping configuration. Happy to have folks test drive this. It includes Sully's counter-linking code from issue #94 and all commits to develop as of today.
