### ISSUE TITLE
Japanese leader do not flip when broken

### ISSUE THREAD

**Issue by davidsullivan317** [vasl-developers/vasl#284]
A DM is placed but the counter remains on the GO side.

**Comment by BigAl737** [comment]
They don't break, they wound, right? So isn't CTRL W the more appropriate command when they break?

If I'm right, maybe a better option would be to add a restrict command property to hide the CTRL F command.

**Comment by styson** [comment]
I agree with that logic, Al.

**1.4 SMC:** Japanese SMC have no Broken side, and cannot break voluntarily.

**Comment by davidsullivan317** [comment]
Ctl-F is added way down in the prototype stack. Not worth changing for such a minor nuisance. Decline to fix.
