### ISSUE TITLE
Hell's Corner Map

### ISSUE THREAD

**Issue by BigAl737** [vasl-developers/vasl#286]
VASLize Hell's Corner Map

(http://forums.gamesquad.com/showthread.php?67652-what-s-your-VASL-wish&p=1814632&viewfull=1#post1814632)

**Comment by bkemp01** [comment]
This has been in the works for a while.

**Comment by BigAl737** [comment]
Doug, I'm trying to upload files to vasl/website so that the Hell's Corner board will be available to download. I've been reading up on Git, GitHub, and SourceTree so I've learned a few things...I think. On  vasl-website, I created a new branch called _features/bdHC-upload_ and have pushed 3 files to it. If you can find these, then quality control them for me, I will go ahead and merge that commit into gh-pages then delete that branch, or it's probably best if you just do it :-). Everything works for me on my local system but I want to make sure I didn't break any links on the other.htm page and that the added Hell's Corner link works. I've already pushed the Hell's Corner source files to vasl and vasl-boards-extensions. I've named the board bdHC. Thanks for your help.

**Comment by derimmer** [comment]
Al

I downloaded the .zip file. Works perfectly. The change to versions.json looks fine. I could not seem to download the other.htm file so I could not test. If you double-click it on your local device it should open in a browser. If it looks fine, it is fine. 

As for commiting them, as far as I can tell, you committed the 3 files to feature/bdHC-upload. And then you reverted them (essentially deleting them). I am not sure why. You may have done so accidently. 

I think you are good to go. Push them up to feature/bdHC-upload again. And then commit them to gh-pages. I am happy to do the last step for you if you wish but you have to push them back to feature/bdHC-upload first.

**Comment by BigAl737** [comment]
Thanks Doug. You gave me the confidence to merge the other.htm file. As you can see, I ended up deleting everything and starting over. It worked :-)

Hell's Corner is on the site. I tested the download and opened it in VASL. Thanks for your help in this process. I'm learning how to navigate the whole Git Zen thing better. What does it say about me when I confess that I'm enjoying this learning process.

Thanks to Brian Kemp, Tom Repetti and Tim Fachko for completing this board. It looks fantastic! I know the ASL population will really put it to good use. Any bets on how long before the first action packed screen shot is posted? I'll bet it's by Jackson.

I think it's time to close this issue. Next...
