### ISSUE TITLE
Transparency changes when a HIP counter in rotated

### ISSUE THREAD

**Issue by zgrose** [vasl-developers/vasl#289]
Steps:
Dragged a Russian 76L ART obr. 39 onto FB_SE XX10
Set the Gun to HIP
Rotate the gun

In this screenshot you can see that the unrotated counter is visible but the rotated counter is twice again transparent.

<img width="307" alt="screen shot 2016-04-20 at 8 34 14 am" src="https://cloud.githubusercontent.com/assets/5044847/14680651/d2b3905a-06d2-11e6-89fb-581d6aab4100.png">

**Comment by BigAl737** [comment]
I just tried this with VASL 6.2.2 and it works okay. If I get time today I'll look for counter trait differences between 6.2.2 and 6.3.3.

**Comment by davidsullivan317** [comment]
I know what this is. For simplicity I used a single prototype - DBOwner - to add HIP to all counters. If you remove the Invisible trait from this prototype it fixes the problem but will also undo adding HIP to all counters. We'll have to reapply HIP by adding the Invisible trait all applicable prototypes, which will be a PITA.

**Comment by davidsullivan317** [comment]
BTW - I think we should up the transparency value from 30 to 50%. Even without this bug HIP counters are really hard to see. For players over 40, anyway.

**Comment by davidsullivan317** [comment]
Fixed

**Comment by davidsullivan317** [comment]
Note - this may remove HIP from some counters. We'll have to come back to that.
