### ISSUE TITLE
German PzKw35t wreck depicts FT-17 730 (f) wreck

### ISSUE THREAD

**Issue by BigAl737** [vasl-developers/vasl#290]
http://forums.gamesquad.com/showthread.php?88223-VASL-Map-Online-Problem-Suggestion-Form&p=1814838&viewfull=1#post1814838

Confirmed in VASL 6.3.3

![screen shot 000022](https://cloud.githubusercontent.com/assets/10384413/14686743/a6accd8c-06e6-11e6-9caf-a7c34d4710d8.jpg)

**Comment by BigAl737** [comment]
I fixed this in the VASL module downloaded to my local PC but David Sullivan's wise words tell me that it's not as simple as doing that and then pushing my local version buildFile to the vasl/dist directory.

The PzKw 35t Wreck gif already exists in the vasl/dist/images directory. It's named pz35tb.gif.

![pz35tb](https://cloud.githubusercontent.com/assets/10384413/24523029/2484c79e-153e-11e7-8781-ef1cfa17d788.gif)

The PzKw 35t Wreck piece itself does not exist in the VASL buildFile. When I made the change to my local system, this was added as line 6551 in my local buildFile:

				<VASSAL.build.widget.PieceSlot entryName="PzKw 35t Wreck" gpid="7441" height="60" width="80">+/null/prototype;DBGlobal	info;CS 4,sD5\	prototype;geWRK\\	piece;K;D;pz35tb.gif;PzKw 35t Wreck/	\	\\	null;92;30;7441</VASSAL.build.widget.PieceSlot>

I think it best for someone with more VASL savvy than I add the PzKw 35t piece to the buildFile. The traits are embedded in the above line of code. And if you want to teach me how to do this, I'm eager to learn.

Here's what it looks like in play:

![image](https://cloud.githubusercontent.com/assets/10384413/24523189/b14bb9da-153e-11e7-93b8-3f8799d459c5.png)

**Comment by zgrose** [comment]
I believe if you:
1- open the build file, scroll to `<VASSAL.build.widget.ListWidget divider="-1" entryName="ge" height="0" width="0">`
2- scroll to `<VASSAL.build.widget.ListWidget divider="-1" entryName="Ttw" height="0" width="0">`
3- add your new piece into there

it should work to create that piece definition.

**Comment by BigAl737** [comment]
Thanks Zoltan. I'll give that a look.

**Comment by BigAl737** [comment]
I'm gonna push a change to the buildFile that adds this piece as Zoltan suggested. Be warned though that I tried to check the change by building a test VASL module by zipping the files from the vasl/dist directory. When I opened my test module, the dreaded eek a bug window appears and all the counter graphics show boxes with the word nil in them. This may be occurring because I don't know how to build a VASL module from the component files. Or maybe I harmed the buildFile. So someone may want to check for damage and revert this change to the buildFile if I did something that caused this issue.

**Comment by derimmer** [comment]
Hi Al

 

Zipping the files from vasl/dist is not how we normally build a module. I don’t know whether it should work or not (I suspect not, the VASL module is not like a bd file, a zip file without the extension). 

 

I am happy to show you how to build a module or let me know when you have pushed up the change and I can clone it and build one for you and then share it via dropbox.

**Comment by BigAl737** [comment]
Hi Doug,
I would like to learn how to build a module so I accept your offer of instruction. Since I've made two changes to the buildFile recently, you may want to compile a test module on your own to make sure I didn't screw things up. I bet you'd get a more timely result than waiting for me to grasp module building.

**Comment by derimmer** [comment]
Will do so asap.

**Comment by BigAl737** [comment]
Good news...I didn't corrupt the buildFile. Bad news...I need to correct the syntax cause the wreck image is not being found. I'll push that correction shortly.

**Comment by zgrose** [comment]
Tested in 6.4.0 and closing.
