### ISSUE TITLE
VASL 6.4 release discussion

### ISSUE THREAD

**Issue by davidsullivan317** [vasl-developers/vasl#293]
Time to look forward to VASL 6.4

**Comment by davidsullivan317** [comment]
I just found out Jet Brains provides free licenses for all Jet Brains products to developers actively participating in open source projects. https://www.jetbrains.com/buy/opensource/?product=idea

I submitted VASL for this program and it was approved for 6 licenses. This normally costs $250/year. You can read the product details here: https://www.jetbrains.com/idea/buy/#edition=personal 

If you are a regular contributor and would like one of the Jet Brains licenses please contact me offline.  My email is the same as my username here at gmail.

**Comment by styson** [comment]
I use Resharper in the c# realm - what Jet Brains products would apply in VASL?

**Comment by davidsullivan317** [comment]
You get access to all product even if you don't use them on VASL.

**Comment by zgrose** [comment]
Snazzy. Already have a subscription though. IDEA is da bomb (although I'm doing more C# work these days).

**Comment by derimmer** [comment]
I am currently using the "community" edition of IntelliJ by Jet Brains. I assume that this would be something more than that?

**Comment by BigAl737** [comment]
Not having a clue what Jet Brains does, I probably wouldn't be the most deserving of a license.

**Comment by derimmer** [comment]
I assume that the purpose of this issue is to discuss what enhancements we want in the next major version of VASL. I have a couple of thoughts:

1. To enable LOS checking on HASL boards. 
2. To reduce counter clutter by eliminating the need for counters such as CX and DM; there are several ways that have been discussed
3. Replace the current sniper finder with a better tool, much like the button for finding broken/malf'd units (which is terrific). 
4. Create a drag-drop method for adding overlays to boards

**Comment by davidsullivan317** [comment]
'Tis the time of year in MN where the summer wains and young men's thoughts turn to programming. Mine do to. I'm going to start ramping up on my work for the VASL 6.4 release. If you want to jump in let me know. If you want to see certain issues included go ahead and tag them for inclusion.

**Comment by BigAl737** [comment]
Draggable overlays?

**Comment by BigAl737** [comment]
Besides draggable overlays, here's another idea for 6.4...

VASSAL masking for counters within a stack can be set to any color. Default is white. There's been much discussion on GS about how you can see partial bits of counters within a stack if you change the mask color to clear. This seems to be popular because it looks so much better than white. Makes a VASL game look more like a real world game. I'd link it but GS format has changed and it's still foreign to me. Anyway, could we add a VASL option to select a nationality color for the mask color? This could be a drop down menu with the nationality colors all defined. Or maybe it could be defined as a playing piece trait. This would be so much better looking than generic white and mask all parts of the counters in a stack.

**Comment by zgrose** [comment]
Every piece already has a mask image (what you see when you inspect a stack). I think its a bug that the collapsed stacks don't show their mask. You'd solve all the issues if it just respected the info that is already there.

**Comment by davidsullivan317** [comment]
Hey gents. I'm not finding the time and/or motivation to work on VASL this winter. If someone else would like to take on organizing the release it would greatly increase the likelihood we get something out in the coming months. I'll still be around to help and answer questions, and might take on some simple changes, but that will be about it.

**Comment by zgrose** [comment]
Maybe we can just wrap up the commits that are already in place (maybe plus the "info leak" issue rollback) and just do a 6.3.4 instead? I think your computer has the best setup for creating builds at the moment.

**Comment by derimmer** [comment]
How much work is involved (either in creating 6.4 or 6.3.4)? 

 

I have no knowledge about this so I am not sure what any of us would be taking on.

**Comment by BigAl737** [comment]
Sorry to hear this David. Hope all is okay. You still playing THE game?

I haven’t but I have been working on the BFR ItR overlays. About 2/3s done. They will be released with the new overlay placement module extension.

Al

**Comment by derimmer** [comment]
Hi Sully

 

If no-one more experienced has stepped up, I am willing to give this a shot. Do I just create a vmod as per our alpha test modules or is there more to it than that?

 

Doug

**Comment by davidsullivan317** [comment]
@BigAl737 Still playing! When I got back into the VASL coding I made a commitment to myself not to let it interfere with playing the game. 

@derimmer It's a bit more involved than that. There's a fair amount of administrivia involved. Here's what I've been doing: 

1. Refine the list of issues in the release and issue backlog in general. If something's not going to get done coordinate with assigned dev to pull it out. E.g. Al's working on the new overlay paradigm so we have to decide if we want to wait, pull it out, or partially deliver. I've got a bug in the new sniper finder to fix. etc. 
2. Coordinate builds - create test builds as necessary for dev testing. This is easy - I can show you how to do this. 
3. Coordinate the testing. It's a good idea to have some tech-savy users kick the tires. In the past I've tried to do as much of this myself as I can. 
4. Coordinate upload to vasl.info
5. Create the release communication 

Obviously, one person doesn't have to take all of this on. Many hands make little work.

**Comment by derimmer** [comment]
In for a penny, in for a pound. I will give this a shot. 

 

Sully has sent me some general instructions and I will be in touch. 

 

Doug

**Comment by derimmer** [comment]
First thing we need to do is decide what is going to be in or out of 6.4.

 

We have 85 open issues on GitHub. How many of them are we going to include in 6.4? 

 

At present, 30 of them are marked as part of 6.4 (see below. Clicking on the signpost in GitHub will show you a filtered list of 6.4 items) plus there are 6 closed issues also marked for 6.4

 



 

Let’s put a deadline on it: if we want a full and complete 6. 4 to go out for some user testing in late Feb, how many of these 36 issues would be release-ready by mid-Feb?

 

Let me know what is ready now or is still being worked on and is expected to be ready. 

 

Plus, let me know if anyone is working on something for 6.4 not covered by an Issue in GitHub (bad, bad, bad).

 

Thanks.

 

Doug

 

PS. As far as my work is concerned, #312 LOS for RB is release-ready right now. 

 

From: Doug Rimmer [mailto:dougrimmer@rogers.com] 
Sent: Wednesday, January 4, 2017 10:30 AM
To: 'vasl-developers/vasl' <reply@reply.github.com>; 'vasl-developers/vasl' <vasl@noreply.github.com>
Cc: 'Comment' <comment@noreply.github.com>
Subject: RE: [vasl-developers/vasl] VASL 6.4 release discussion (#293)

 

In for a penny, in for a pound. I will give this a shot. 

 

Sully has sent me some general instructions and I will be in touch. 

 

Doug

**Comment by zgrose** [comment]
I’d like to roll back the change that created the “stacked counter visibility problem.” Other than that, I’ve just been helping with boards and PiF stuff lately.
-z

**Comment by derimmer** [comment]
Hi Zoltan

 

Is this something that you can do or is it something that I or David Sullivan need to do. Can you remember the change?

 

Doug

**Comment by zgrose** [comment]
I believe we just need to revert the changes to commit fb7b0249fd6de2df5776315a30eb1eb7247bdb20 to return to the previous behavior. I also have a pull request in for a smarter board version checking that could use some testing to validate.

**Comment by zgrose** [comment]
There are two changes according to my current file state. Rollback of the changes to concealable and comment out the override to draw in ASLStackMetrics. I'll try to get a branch up for you guys to test it out today.

**Comment by zgrose** [comment]
OK, you can follow the previous discussion over on the comments for commit f91804a6de52a55724a17036eedb861491f65e2d and I'm creating a branch now that rolls back that change for testing.

**Comment by zgrose** [comment]
My pull requests #334, #340 are in place and **should** cover all the code contributions I had for this cycle.

**Comment by derimmer** [comment]
Thanks for this Zoltan. Much appreciated.

**Comment by derimmer** [comment]
Closing this issue. We have the major elements ready and a beta out for testing.
