### ISSUE TITLE
Null pointer exception in error

### ISSUE THREAD

**Issue by jrvjrv** [vasl-developers/vasl#296]
I am trying to track down a problem, and I got the following:

java.lang.NullPointerException: null
                at VASL.build.module.map.boardPicker.ASLBoard.initializeFromArchive(ASLBoard.java:132) ~[na:na]

I believe this is not the underlying error but an error when trying to report an error. Line 132 in ASLBoard.java is the ErrorDialog.dataError() line below:

 try {
            VASLBoardArchive = new BoardArchive(archiveFile.getName(), archiveFile.getParent(), ASLMap.getSharedBoardMetadata());
        } catch (IOException e) {
            ErrorDialog.dataError(new BadDataReport("Unable to open board file", boardFile.getName(), e));  // LINE 132
        }
        boardFile = archiveFile;  // LINE 134

The problem is the reference to the variable, "boardFile," in line 132. That variable is not set until line 134 as best I can tell.

**Comment by jrvjrv** [comment]
I suspect my real, underlying problem is that the user (not me) extracted the bdX.gif file from the bdX.zip file, then renamed bdX.gif -> bdX. I get the NullPointerException as described above when I do that.

**Comment by derimmer** [comment]
Yes, doing what you describe would cause a problem. Instead of extracting the gif file, the user needs to rename bdX.zip to bdX. And then ensure that the bdX file is in the directory where VASL looks for boards (set in Preferences in VASL).

**Comment by jrvjrv** [comment]
Just to make sure this is clear, I know the original problem is not a vasl issue. However, whenever any exception is thrown in that try-catch block, instead of reporting that error it throws another error, the NullPointerException, instead. The problem with the exception code still needs to be fixed. The user's problem is only harder to figure out because of this bug.

**Comment by davidsullivan317** [comment]
Yes - this is a bug. boardFile.getName() should be archiveFile.getName(). Or the name can be removed from the data error call all together. 

If you want to know why you are getting an exception run VASL in debug mode and set a break point on line 128 and then step through the BoardArchive initialization.
