### ISSUE TITLE
German ? doesn't conceal black SS

### ISSUE THREAD

**Issue by Taschenschieber** [vasl-developers/vasl#297]
e. g. N7 on the upper board: 
![image](https://cloud.githubusercontent.com/assets/5377412/15718752/18fedc6a-282d-11e6-8cdf-e294b2125bad.png)

**Comment by Taschenschieber** [comment]
Problem also shows up the other way around, e. g. in N7: 
![image](https://cloud.githubusercontent.com/assets/5377412/15719990/b63b7394-2832-11e6-970c-bd91855ac2c2.png)

**Comment by zgrose** [comment]
Remove your redundant chatter extension, btw. That's why you have 2 counter-tray and 2 broken unit finder buttons.

**Comment by Taschenschieber** [comment]
Huh. Thanks. I thought I already had cleaned out all my extensions, but apparently not. Thanks.

**Comment by davidsullivan317** [comment]
VASL uses the nationality to ID counters to identify when concealing units. Concealment counters cannot be shared between nationalities. The black SS are treated as their own nationality (having their own tab in the counter window). 

It _might_ be possible to fool VASL into thinking the Waffen SS counters are German, but I'm not optimistic. Changing how concealment works would be a lot of work to handle a very small set of scenarios. Not sure the bang-for-the-buck is there.

**Comment by zgrose** [comment]
One thing to keep in mind, in reference to the counter clutter issue, is that the concealment counter is actually a bit redundant in VASL and is what, IMO, creates this problem in the first place. If we just let each counter mask itself, there would be a need to a special counter on top.

How far the community wants to stray from "cardboard reality" into "VASL reality" I don't know. But having work on the PiF extension a bit now, the further we stray from cardboard reality, the more convoluted the code gets.

**Comment by derimmer** [comment]
I am of the view that we should keep the ? counter on top. Counting the size of stacks is an important game element, FtF or online. 

 

But that’s just my opinion. If we think we should make a change, I would strongly suggest polling the community first.

**Comment by zgrose** [comment]
You can still count the stacks. I don't expect it would be popular.

**Comment by davidsullivan317** [comment]
Decline to fix. An easy work-around is to add an additional concealment counter and HIP the SW, for example.
