### ISSUE TITLE
LOS thread to vertex could use graphical indication of which hex vasl thinks is being bypassed

### ISSUE THREAD

**Issue by jrvjrv** [vasl-developers/vasl#298]
See this thread: http://forums.gamesquad.com/showthread.php?127332-LOS-question-for-board-2

The user receives no direct feedback of which hex of the three at a vertex vasl is going to consider as the target of the LOS. A way to make it more apparent which hex was considered would be to add some kind of graphic emphasizing which hex the LOS is traced too/from. I attach a picture showing how this might appear. The angle would move to the other hexes around the vertex as the mouse moved into them.
![vertex los](https://cloud.githubusercontent.com/assets/7386638/16059043/465d91b6-324f-11e6-887b-0b982523877d.png)

**Comment by davidsullivan317** [comment]
@jrvjrv The hexes are shown when using the verbose option. Have you tried that?
