### ISSUE TITLE
Overlay OW1 misaligned

### ISSUE THREAD

**Issue by mistertakai** [vasl-developers/vasl#301]
Overlay OW1 seems to be misaligned:

![image](https://cloud.githubusercontent.com/assets/3066447/16355499/6a0e95a8-3ab8-11e6-90ac-17dd9914b5c2.png)

**Comment by davidsullivan317** [comment]
This is probably a dup of #302

**Comment by BigAl737** [comment]
Just pushed the fix to this. The alignment will not be perfect because the geoboard hex grid isn't perfect. However, the alignment was off an extra pixel or two so I tightened it up a bit. I'll close this issue after testing.

**Comment by BigAl737** [comment]
Tested okay. It's still off a pixel in some orientations but that's as close as we can get it I believe.
