### ISSUE TITLE
Overlay RR13 misaligned

### ISSUE THREAD

**Issue by mistertakai** [vasl-developers/vasl#302]
Overlay RR13 seems to be misaligned:

![image](https://cloud.githubusercontent.com/assets/3066447/16355502/851e511c-3ab8-11e6-84fa-5a42674f8b17.png)

**Comment by BigAl737** [comment]
Improved alignment and pushed updated files. Again, the improved alignment won't be perfect for all orientations as the vasl geoboard hex grid is not perfect. I'll close this issue when testing is complete.

**Comment by BigAl737** [comment]
The website updates pretty quick. Testing is complete. Should be good to go. All aboard. Time to roll those trains.

**Comment by styson** [comment]
I love website automation!

**Comment by mistertakai** [comment]
I tested it - that looks so much better - thanks a bunch!

**Comment by BigAl737** [comment]
Me too Sam. Nice job!
