### ISSUE TITLE
PzKw IVF2 (piece id 2582) has incorrect special ammo

### ISSUE THREAD

**Issue by zgrose** [vasl-developers/vasl#304]
Reported at http://forums.gamesquad.com/showthread.php?127533-errata-report-German-Vehicle-Note-23

Current state:
<img width="268" alt="screen shot 2016-07-10 at 10 11 20 am" src="https://cloud.githubusercontent.com/assets/5044847/16714934/b687bdb8-4686-11e6-9e5d-9f2a665b1cf0.png">

Chapter H entry:
<img width="324" alt="screen shot 2016-07-10 at 10 11 34 am" src="https://cloud.githubusercontent.com/assets/5044847/16714935/bbd739f6-4686-11e6-8657-9886256f260f.png">

**Comment by zgrose** [comment]
Apparently Chapter H is incorrect. See GameSquad thread for additional details.

**Comment by BigAl737** [comment]
Here's the refreshed link:
http://www.gamesquad.com/forums/index.php?threads/errata-report-german-vehicle-note-23.127533/

I was looking to fix this if it still needs it and if I can get the final answer on the correct value.

**Comment by zgrose** [comment]
I think it was fixed Jul 11 in @fd32df1 but you can check it out and confirm.

**Comment by BigAl737** [comment]
Looks like it was fixed. I think you can close this one.
