### ISSUE TITLE
Some shortcuts not working on non-US keyboards

### ISSUE THREAD

**Issue by Taschenschieber** [vasl-developers/vasl#305]
As reported on Facebook (https://www.facebook.com/groups/vaslmeetup/permalink/1144759802210898/), some keyboard shortcuts seem to be broken on non-US keyboard layouts. In particular, it seems that the common denominator between the affected shortcuts is that they require special keys like Shift or ALT GR to get the required keystroke (for example, [ is ALT GR + 8 on a German keyboard).

This seems to me like an upstream issue from VASSAL, but a possible workaround might be to replace the affected shortcuts so that they only use alphanumerical keys, which would make them more ergonomic for havers of weird keyboards.

**Comment by davidsullivan317** [comment]
@Taschenschieber Any interest in looking at this? I don't have the requisite keyboard.

**Comment by davidsullivan317** [comment]
In the FB post on the OP it looks like switching the keyboard locale to US works. If you REALLY REALLY want to change the keys used by VASL you can do that in the VASSAL module editor. Every keystroke can be changed. Making these user-configurable preference is not realistic. 

![image](https://cloud.githubusercontent.com/assets/5281926/25409312/08502b4c-29d7-11e7-9880-08f86c442052.png)
