### ISSUE TITLE
Mask not showing for concealed unit

### ISSUE THREAD

**Issue by zgrose** [vasl-developers/vasl#306]
Figured I'd toss this out here to get some experienced eyeballs on it.

I'm working on the PiF extension and I have the Polish Infantry counters setup mostly. I have the Conceal command in place but I can't get the poqmarkme.gif to show up on the counter.

I have the counter in place (in [extension]/images/po/poqmarkme.gif) but I get no image and no error. Any suggestions as to what else might need to be in place?

I'm fairly certain the counter is "concealed" because it reports as ? when moved around the map.

**Comment by bkemp01** [comment]
You'll need new poXXX prototypes. Pretty good thread recently on GS...

http://forums.gamesquad.com/showthread.php?127204-Creating-new-nationality-as-extension-concealment-problem

Thanks for tackling this

**Comment by zgrose** [comment]
I've got the prototypes in place. I'll check that thread for more secrets.

**Comment by zgrose** [comment]
Gonna have to get the source code setup again for debugging. My current suspicion is that its looking in the wrong archive for the image file.

**Comment by zgrose** [comment]
OK. Seems to be a combination of factors here. Apparently when you edit a Can be Concealed trait, you are presented with an image picker:

<img width="620" alt="screen shot 2016-07-18 at 2 54 52 pm" src="https://cloud.githubusercontent.com/assets/5044847/16931788/a1e417cc-4cf7-11e6-86ec-435a9fde041b.png">

This image picker will grab a full file path and place it into the buildFile something like this:
````
conceal;C;po\/poqmark.gif;po;;
````

However, the code in Concealable.java says:

````
concealedToMe = Op.load(imageName + ".gif").getImage(null);
````

Which results in a search for po/poqmark.gif.gif

Removing the .gif from the buildFile XML manually results in an image appearing. However it looks like this whole section of code results in an output other than the expected use of the po/poqmarkme.gif file as you can see that the image is an actual concealment marker shrunk. So there is probably bug-upon-bug at play here.

<img width="383" alt="screen shot 2016-07-18 at 3 02 19 pm" src="https://cloud.githubusercontent.com/assets/5044847/16931980/abdc7a2a-4cf8-11e6-84c1-cdd3dd27942c.png">

**Comment by bkemp01** [comment]
Check out Jeffrey Malter's (CountermanCX) Sweedish Volunteers extension
(5SV.mdx) for an example that (mostly) works. The Inf markers conceal
properly. Only problem I see with it is the 5/8" guns conceal with a 1/2" ?
counter.

**Comment by bkemp01** [comment]
Can this be closed?

**Comment by zgrose** [comment]
Ya, `concealedToMe = Op.load(imageName + ".gif").getImage(null);` is the problem. It should probably do `concealedToMe = Op.load(imageName).getImage(null);` first as this is what would find the correct image in new modules and then probably fall back to `concealedToMe = Op.load(imageName + ".gif").getImage(null);` if it doesn't find anything for legacy support. IMO.

**Comment by derimmer** [comment]
Since PiF Polish concealment countes, SV concealment counters, and Chicom concealment counters all seem to be in working order now, I am going to close this issue.
