### ISSUE TITLE
Versioning off on the desert boards

### ISSUE THREAD

**Issue by davidsullivan317** [vasl-developers/vasl#307]
I don't know if this has been reported before, but the desert boards (26-31) are all labelled as "v6.1" on the vasl.info site, and looking inside each file this seems to be correct in the data file, but when you load them they report as "6.0" (and get auto-updated accordingly).  Not a big deal, I guess, but I think this means they will auto-update every single time you use them.

**Comment by davidsullivan317** [comment]
@zgrose It looks like this one is yours. FYI

**Comment by zgrose** [comment]
Remind me again why we need the data text file if it isn't being used....?

**Comment by davidsullivan317** [comment]
For legacy versions of VASL

**Comment by zgrose** [comment]
Why would be expect a legacy version of VASL to load a 6.x board?

**Comment by derimmer** [comment]
Is anybody having problems getting LOS checking to work on board 40? Is there a known reason? 

 

I am using the latest version in the vasl-boards-extensions repository and it is not working for me.

**Comment by davidsullivan317** [comment]
The metadata files has bad quote marks on line 80, so it does not parse.

**Comment by davidsullivan317** [comment]
@zgrose VASL 6.1 and below do not support the new metadata format. We can drop the old format at some point.

**Comment by derimmer** [comment]
I fixed this and tested the LOS and it seemed to be working. Now remind me again how I get the revised board into GitHub. I am trying to use SourceTree and it does not seem to register that I have changed bd40.

 

Have not done this for a while and am forgetting whatever I knew!

 

Doug

**Comment by zgrose** [comment]
In the vasl repo:

boards/v5boardVersions.txt
boards/src/bd40

be sure to update bd40/BoardMetadata.xml and bd40/data



In the vasl-boards-extensions repo:

boards/bd40



In the vasl-website repo:

boards/bd40.zip
boards/versions.json
boards/v6bds40-49.zip
boards/v6boardsAll.zip



You can look at my commits for examples.

-z

**Comment by derimmer** [comment]
Thanks Zoltan

I am 1 for 3. I was able to push to revised board file up to the vasl-boards-extensions repo.

I could not do so for the vasl repo as I have another commit for that repo and when I try to create a pull request it want to pull both commits which I absolutely do not want to happen. I could not figure out how to create a pull request for the one commit alone or how to undo the other commit.

As for the vasl-website repo, I could not figure this out at all. I am sorry but I have no clue on this one. I could not find an example of a commit that helped. 

Since the only change required was to the BoardMetadata.xml file, I did not update the v5boardVersions.txt or the versions.json files in their respective repos as I did not change the version number.

**Comment by zgrose** [comment]
BTW, you co-opted the desert issue in GitHub, BUT, if you don't change the version number, how will VASL know to update their boards...? :)

**Comment by derimmer** [comment]
All of this happens because I don’t know what the hell I am doing and I cannot decipher GitHub for love nor money. 

 

I will undo the change I made to bd40 in the vasl-boards-extensions and things will be back to the way they were. 

 

There is a bug in bd40, a better man than me can fix it. 

 

I appreciate your efforts to help Zoltan.

 

doug

**Comment by zgrose** [comment]
Send me the updated BoardMetadata.xml file and I can push it to all the right places for ya. You can email it directly to zgrose@mac.com <mailto:zgrose@mac.com>
-z

**Comment by BigAl737** [comment]
This is very helpful Zoltan. I’ve saved it for future reference. Thanks.

Al

**Comment by davidsullivan317** [comment]
Can this be closed?

**Comment by zgrose** [comment]
I'll double check that they don't auto update loop and close when I get back to my desktop.

**Comment by zgrose** [comment]
OK, my bad, I forgot to upload to the vasl-boards-extension repo. I just tried a new game, saw my 26 get updated and stay updated as v6.2 when I started a second game so I think this is closable.

<img width="334" alt="screen shot 2017-02-25 at 10 06 43 am" src="https://cloud.githubusercontent.com/assets/5044847/23333552/1f8cdb84-fb42-11e6-98cc-dbca98aa3326.png">

**Comment by derimmer** [comment]
Zoltan

 

I see that you updated Board 24 recently in vasl-boards-extensions. Did you make changes to either the Boardmetadata.xml file or the LOSData file? I need to update both of those files as a consequence of the LOS work I have just completed. 

 

I can update your version of the board file easily but I don’t want to overwrite any changes you may have made to those two files (which I are only ones I have to update). 

 

Thanks. 

 

Doug 

 

PS. I notice that the board folders in vasl\boards\src have not been updated for boards 26-31. Or at least GitHub is not indicating that they have been. Did you update these along with the vasl-boards-extensions? If so, then I probably overwrote your changes to board 24. I pushed my changes up to vasl\boards\src several days ago and am just about to do the same for vasl-boards-extensions.

**Comment by zgrose** [comment]
The actual changes were made 6 to 8 months ago or so. What I posted the other day were the built boards so the automatic downloader would get the new 6.2 files. If you have been working off the 6.2 files or branched somewhat recently, you should be fine I would think.

**Comment by derimmer** [comment]
Great. Thanks.

**Comment by derimmer** [comment]
I had bumped the version number up to 6.3 before I pushed the files up to vasl\boards\src, so I must have been working on 6.2. Hopefully we are all good.
