### ISSUE TITLE
bd40 is missing SSO AP103 from LOS issue update

### ISSUE THREAD

**Issue by BigAl737** [vasl-developers/vasl#308]
Recently bd40 was updated to v6.2 to fix a LOS issue with the metadata file. In the update, the SSO for AP103 was omitted. I've fixed that omission and pushed the applicable corrected vasl/board/src files. I need someone who knows what the LOS issue was to check that I did not inadvertently reintroduce the LOS issue. Once that is done, I can update the version to 6.3 and push the board to vasl.info for public download.

**Comment by derimmer** [comment]
That would be me Allan. I cannot test it as I am away from my machine for a couple more days.  I should be able to do so later this week

**Comment by BigAl737** [comment]
Thanks Doug, here's the updated bd40 (its zipped). It's still marked as v6.2 but it's really v6.3. Didn't change the version number yet to bypass the auto board update. When you give the okay, I'll change the version number and then push v6.3 to the website.

Al

edit: it's taking forever to upload the bd40 zip file. I'll email it to you Doug.

[bd40.zip](https://github.com/vasl-developers/vasl/files/455466/bd40.zip)

**Comment by derimmer** [comment]
Hi Al

 

I tested your file and it still contained the LOS error (the LOS checker was not finding the terrain under the bridge). 

 

I have fixed this by swapping out the LOSDATA file in the bd40 board archive file. That is the only change that I made. File tested and working, as far as LOS is concerned.

 

Here is the bd40 board archive file with the updated LOSDATA file.

 

Doug

**Comment by BigAl737** [comment]
Thx Doug. I didn't see an attached file with your message. Can you push the LOSDATA file to vasl/boards/src/bd40? I'll zip up and post the updated bd40 to the web page. Else, please email the bd40 archive file and I'll update the vasl source and web page. Appreciate your help.

**Comment by davidsullivan317** [comment]
Can this be closed?

**Comment by derimmer** [comment]
Yes, I am pretty sure this was fixed.

**Comment by BigAl737** [comment]
Doug can you download bd40 v6.3 from the website and verify the LOS issue works okay? If so we can close this.

**Comment by derimmer** [comment]
I did. It does. Close.

**Comment by BigAl737** [comment]
Done :-)
