### ISSUE TITLE
Adding new map frame to vasl.info

### ISSUE THREAD

**Issue by BigAl737** [vasl-developers/vasl#309]
Perry of GS fame has a few maps that he's asked permission to post to vasl.info for public download. Having vaslized these maps for him, I recommend we do so as they are high quality. One is a map based on Wittman's Last Battle, the other is Tom Morin's Stalingrad Railway Station. He's got more to come and since he doesn't know how to post the maps to vasl.info, he's asked for my help. I was wondering if:

You agree with me that it would be good to post these to vasl.info, and if so:

How best to do that.

I think a new frame on the Other Boards & CG Maps page would be the way to go. Something like "Fan Generated" as a header with the maps nestled within the frame; similar to how the MMP HASL maps are presented. This is new posting territory for me so I would need some instruction in how to do it.

Thanks all for you consideration.

Allan

**Comment by bkemp01** [comment]
On the "Other" page at the very bottom is a section for "Homegrown VASL
boards". I wold recommend putting them there.

**Comment by BigAl737** [comment]
Sounds like a better idea Brian. Now I just need to figure out how to do so.

**Comment by styson** [comment]
I can add the content to the site, just need to know which boards to include there.

**Comment by BigAl737** [comment]
Thanks Sam. I'll get those to you. Might be a couple of days. 

Al

**Comment by zgrose** [comment]
Somewhat tangential, what do you guys think about dumping the 10 board zips (bd01 to bd10, bd11 to bd20, etc). They don't seem to add much value and just make the updating process a bit tedious. Seems like the individual board and the all boards archive would be sufficient.

**Comment by styson** [comment]
sounds good to me

**Comment by BigAl737** [comment]
I think that would be fine. We could always make them available again if the masses revolt.

**Comment by derimmer** [comment]
If you are new to VASL then adding all 70+ MMP boards one at a time would be a grind. That being said, creating the 10 board zips is no joy either. 

 

On balance, I would prefer to keep offering them if the workload is at all manageable.

**Comment by BigAl737** [comment]
Sam, I'll push two boards to vasl-boards-extensions soon. They are bdWittLastBattle: Wittman's Last Battle, and bdTCRS: The Central Railway Station.

Perry Pender updated the originals so if you want to associate his name with these boards I think that would be okay. Perry will add more boards in the future. His desire is that they're available for all to enjoy so he really appreciates you hosting them on the web.

Thanks for posting them Sam.

Al

**Comment by davidsullivan317** [comment]
Hey Al - did you want to put the board source in the repository?

**Comment by derimmer** [comment]
In connection with this, I was just updating a document I worked on last fall/winter, describing the process for creating/updating board files (NOT maps) and all the places to put them. I would like to post this in vasl-boards-extensions/Documentation on GitHub but would like to have Sully’s ok first. 

 

Plus, it could benefit from the addition of more detail on how to get board files into vasl.info, which is beyond my ken. 

 

Feel free to edit or comment if parts are inaccurate/unclear.

 

Doug

**Comment by davidsullivan317** [comment]
You don't need my okay; have a ball.

**Comment by BigAl737** [comment]
I can but it’d be same gif file that is zipped in the bd file. I don’t have the original source file which I believe was created with Hexdraw.

**Comment by BigAl737** [comment]
Once Sam posts these, we can close this.

**Comment by styson** [comment]
Perry's boards are now on the website.
