### ISSUE TITLE
Concealment Counter Issue

### ISSUE THREAD

**Issue by johnpettit** [vasl-developers/vasl#310]
"I just accidentally found a potential abuse of VASL. My opponent concealed his units. But before he did, I was checking the Info on one of his mortars. Once concealed, the Info still showed me which counter the mortar is. Can this be fixed?"

Reported second hand from an ASL FB post

Regards

JP

**Comment by davidsullivan317** [comment]
Decline to fix. Just tell your opponent what happened, have him unconceal the counter, and turn off the info marker.
