### ISSUE TITLE
Draggable overlays with the v2 Red Barricades map

### ISSUE THREAD

**Issue by shmcbee1964** [vasl-developers/vasl#319]
Hey.  I'm playing a CG of the Barricades and one of us discovered the draggable overlays, specifically the OBA ones.  One got used for an fire mission and we discovered that it cannot be removed from the map after use.  Nor could it be manipulated at all.  Anyone heard of this and know of a workaround?  Thanks.

**Comment by zgrose** [comment]
Shift-click to select an overlay.

**Comment by BigAl737** [comment]
Zoltan answered this issue. This can close.
