### ISSUE TITLE
Counters disappearing from extension windows. 

### ISSUE THREAD

**Issue by davidsullivan317** [vasl-developers/vasl#320]
I was able to reproduce with these steps:

Start VASL with the Tray extension
Start a new game using whatever map (I happened to use 00).
Open the Tray window. Note the native size of the tray window.
Enlarge the tray window.
Place a counter on the Tray window in the area created above.
Place a counter on the VASL board.

If you've used the Tray and prefs for its size is already saved, just aim for about 4-5 inches down and 3-4 inches over. :)

Happens in 6.3.1 but not 6.2.2 (the only older versions I have handy).

**Comment by BigAl737** [comment]
Which VASL version increased the size of the main map padding? Could that have something to do with this?

From: David Sullivan 
Sent: Saturday, October 01, 2016 8:04 AM
To: vasl-developers/vasl 
Subject: [vasl-developers/vasl] Counters disappearing from extension windows. (#320)

I was able to reproduce with these steps:

Start VASL with the Tray extension
Start a new game using whatever map (I happened to use 00).
Open the Tray window. Note the native size of the tray window.
Enlarge the tray window.
Place a counter on the Tray window in the area created above.
Place a counter on the VASL board.

If you've used the Tray and prefs for its size is already saved, just aim for about 4-5 inches down and 3-4 inches over. :)

Happens in 6.3.1 but not 6.2.2 (the only older versions I have handy).

**Comment by davidsullivan317** [comment]
@zgrose What is the exact name of the tray extension you are using? I'm not able to reproduce this.

**Comment by zgrose** [comment]
tray.mdx

Pretty sure i'm using the one from the vasl-boards-extensions repo.

**Comment by davidsullivan317** [comment]
I was able to recreate the issues with 6.3.3. It appear the fix for #292 also fixed this problem. @zgrose Would you might confirming with this build? https://www.dropbox.com/s/gk4amknx6a0vs4v/vasl-6.4.0-alpha1.vmod?dl=0

**Comment by zgrose** [comment]
I gave the alpha1 a whirl using the repro steps above and it seemed to work as expected.
