### ISSUE TITLE
New Way to Handle Terrain Overlays

### ISSUE THREAD

**Issue by BigAl737** [vasl-developers/vasl#330]
Opening this thread to track commentary on switching the way VASL handles overlays. I think we all agree that the current method is not the most user friendly and has drawbacks. The inability for an overlay to span two map boards is one.

I propose we offer a module extension that provides access to overlays that are simply dragged, placed, and rotated on board; like how counters are placed. I've done some very preliminary work on this. You can find it here:

https://www.dropbox.com/s/nou9ih24yftj65a/OverlayDraft.vmdx?dl=0

I invite you to play around with it and see what you think. If you don't think this is the road to go please say so. Else, I'm open to suggestions.

Access the overlay window by clicking on the OVL tab. Shift click to select the overlay on the map. You'll see I use two methods to note hex 1 and 2; numeric or dots. The OG overlays use numeric. The O overlays use dots. Which is better?

Known issue: Checking LOS blanks out the overlay. There is a way to retain hindrance counters when checking LOS so I think we can correct this issue with the proper piece trait and/or update to the LOS coding.

This would be a big project that I'm willing to chip away at. Of course we retain the current overlay placement method until the extension is complete. However we could offer the extension as work progresses so both methods would be available concurrently. This would expand the time for completion and might allow this to be released at the same time VASL 4.0 is released.

Well, that's it. Thanks for letting me know what you think.

Al

**Comment by derimmer** [comment]
Without much of an understanding of the issues that it might create, I am in principle in favour of being able to dragdrop overlays into position. 

I think the benefit is worth the effort.

**Comment by zgrose** [comment]
Having built draggable overlays for the (previous) Lock n Load module, I remember the UI is actually more annoying than you might think, especially for large overlays, but since an extension wouldn't have to replace the existing framework while its being worked on and refined, why not.

**Comment by BigAl737** [comment]
I just uploaded an update that includes a large overlay...number 03. You can mess around with it. Same link as the first post. File is dated 10/11/16 10:54pm.

I know some of the overlays aren't lining up perfectly. I'll need to nudge them if we decide to press on with this.

**Comment by zgrose** [comment]
To see what I'm talking about, take a large overlay with lots of whitespace. It could be your cascading list solved the old LnL problem, though.

I'd sort by the overlay code (OG, O, H) first since that's the only information presented on the scenario card.

I prefer numbers to dots.

**Comment by davidsullivan317** [comment]
Wow, this is awesome. Thanks Allan! Definitely the right road to go down. Was it a lot of work? Maybe we can get some additional hands on it. 

We can definitely find a way to leave them on the board during LOS check - shouldn't be much work. 

I also prefer numbers to dots.

**Comment by BigAl737** [comment]
Okay cool. Great suggestions.

Numbers over dots. Got it. Now tell me this, If I rotate the numbers to align with the hexside, they look terrible (except when aligned with the cardinal 1 and 4 hexsides). That's why I keep the numbers in cardinal portrait format no matter the rotation of the overlay. Do you think that's okay? (The OG2 overlay is an example of this).

I'll implement the sort by code idea.

I don't think there will be overlays with a lot of white space. I can crop them to the artwork. I'll have to nudge them just a bit so there will be a little white space but not much. You won't see the entire overlay in the selection window (unless you make the overlay window really big) but I think that's okay. With the way they'll be sorted, I think players will find it intuitive to drag the one they want to the map and position it from there.

It's not a lot of work but the shear number of overlays will take a little time to convert. Time I don't mind expending but since this is not an addition to the core VASL module, I think that gives me more time to get this done. Plus we can release the module extension as work progresses.

David, before I proceed much further, I'd like to know how to work around the LOS disappearing issue. I'll bet I need to give each overlay a trait like we do for hindrance counters. Unlike Hindrance counters though, I'd prefer to bypass the ON/OFF option and just leave them always visible. I don't see a reason to make this a user preference. I could be wrong though.

How about terrain transforms for overlays? I could use the layer trait to make transforms selectable for each overlay. Is there a better way?

Thanks all.

**Comment by zgrose** [comment]
If Ef13 and the Armies of Oblivion river overlay look good, then all the rest will probably look good, too.

**Comment by BigAl737** [comment]
I've uploaded a new vmdx version which includes the AoO River overlay. Also changed over the sorting method too. Let me know what you think. Haven't converted the EF3 overlay yet.

**Comment by davidsullivan317** [comment]
I did some digging and VASL uses a custom class ([HindranceKeeper](https://github.com/vasl-developers/vasl/blob/ea5c665effbe3997630fac36b4439d35b2519bcb/src/VASL/build/module/map/HindranceKeeper.java)) to determine which counters stay on the board during LOS checks. I can tweak that to include overlays. Let try this: add a Marker trait to each overlay that adds a property called "Overlay" with a value of "true" (or whatever). Ideally set it up as a prototype so if it has to change you only have to change it in spot. 

BTW - I'd vote to make terrain transformations a nice-to-have. It would be good to prototype them now but, assuming everything pans out, converting all overlays should be the priority. We can come back to the terrain transformations later. This is probably going to involve a fair amount of coding to do the color transformations.

**Comment by zgrose** [comment]
The list and the centered view seem to be holding up well, @BigAl737

**Comment by davidsullivan317** [comment]
A couple of other thoughts while messing around with the overlays. 

We should use a different selection key. With the current draggable overlays it's really easy to accidentally shift-click an overlay forgetting you already have a stack selected. We don't want to compound that problem and have people accidentally deleting their overlays. Could we go with something like shift+ctrl+click?

Also, we'll want to make the images as small as possible. The LOS engine uses the bounding box of the overlay to know when it's passing through that overlay. E.g. the transparent part of the river overlay is bigger than necessary.

**Comment by BigAl737** [comment]
New version posted.

What's new:
Use ALT key to select overlay (choices are either ALT or SHIFT so I went with ALT)
Assigned marker: overlay=true (no caps)
Cropped river overlay as small as I could
Two versions of river overlay...small menu display (RV1) and large menu display (RV1a). Use CTRL F to make the small become the large. Which do you like better?

David, I'd like the permanence of the overlay to be independent of HindranceKeeper. That way you could keep or hide hindrance counters while always keeping overlays. Is that possible?

Allan

**Comment by BigAl737** [comment]
New version posted. Same link as in first post.

What's new:
There's been a bunch of talk on GS about how desert overlays don't work. So I thought that desert overlays should be my first priority. Once they're done, we can release a version of this extension while continuing to add the other overlays. You'll find X1 and Dier 1-3 ready for your inspection.

Check out the river overlay too. Wondering which presentation to keep.

David, will it work for you to add the Overlay equivalent of HindranceKeeper to VASL before VASL 4 is released?

**Comment by davidsullivan317** [comment]
It appears to be a simple change so I have a test version out shortly.

**Comment by davidsullivan317** [comment]
I've made changes that keep the overlays on the board during LOS and while using the QC toggle. They need further testing so keep an eye out for any side effects. 

The changes are available in the alpha2 build: https://www.dropbox.com/s/pgmupavf4i54ebf/vasl-6.4.0-alpha2.vmod?dl=0

**Comment by BigAl737** [comment]
Seems to be working David. Thanks!

I'm gonna keep going working on this. It seems it won't be a waste of time. Let me know if I'm wrong.

So if we add overlays using this interface, could the LOS engine be modified to read them? Getting a little ahead of myself I know.

**Comment by BigAl737** [comment]
Forgot about issue 280 where Sam first suggested this. Just re-read that thread.

Sam you mention an idea where the 1 and 2 numbers on the overlay would be visible only when selected. Now that you've had a chance to see overlays in place, do you still think this is needed?

**Comment by zgrose** [comment]
If you put a # in front of the issue then people get a quick link. #280

**Comment by BigAl737** [comment]
Thanks Zoltan.

**Comment by davidsullivan317** [comment]
Regarding LOS support for a new overlay paradigm... perhaps. At a minimum we need to implement the logic @derimmer created where the LOS is only disabled it touches the overlay. The hard part, and the reason overlays have never supported LOS checking, is solving the problem of creating the LOS data.

**Comment by derimmer** [comment]
The problem of creating the LOS data is really big. Not that it is especially difficult but it is especially large. It would have to be done 6 times, once for each rotated position of the overlay, unless we can figure out a translate algorithm to automate the process. Somehow it feels like we will always have something better to do. . . .

**Comment by BigAl737** [comment]
Well don’t lose any sleep on this :-) I was just curious. You’re right, there is always something better to do. And besides, it’s good for players to have to exercise their LOS muscles every once in a while.

**Comment by BigAl737** [comment]
New version posted. Same link as in OP.

What's new:
Added a BSO and SSO selection. The BSO is for the Singling map. Center it on hex P9.

David, the overlays remain on board when checking LOS however, the LOS checker is using the underlying board for LOS determination. The LOS checker is not being disabled by the overlay bounding box.

I think I'm about ready to start work on this in earnest. If there are any additional inputs, now would be a great time. Thanks.

**Comment by BigAl737** [comment]
I've got a good start on this. Of course many overlays aren't converted yet but all of the desert ones are as well as the BFP ones from Into the Rubble 2. I'm ready to release this to the masses and keep updating it as time permits. A big road block is that the current VASL release does not contain the code that David created that keeps the overlays from becoming invisible during a LOS check. I'll bet a VASL 4.0 release is a way off in the future but could we release an interim VASL version that contains David's anti cloaking code in the near future?

**Comment by davidsullivan317** [comment]
Have you been testing this with the 6.4 alpha3 release and are there any open issues?

**Comment by BigAl737** [comment]
I've been using 6.4 alpha 2 and haven't discovered any problems. Here's the link to the latest module extension if you want to mess around with it.

[https://www.dropbox.com/s/nou9ih24yftj65a/OverlayDraft.vmdx?dl=0](url)

**Comment by BigAl737** [comment]
Another feature I think I'll add to the extension. If you want to see it in action, follow these steps.

Save this [image ](https://www.dropbox.com/s/z5kv5w4go7kqc6d/SinglingBorderHTML.gif?dl=0)file to your computer

Save this [extension ](https://www.dropbox.com/s/09ljwz5z5t8f4ce/VASLOverlays.vmdx?dl=0)version to your computer
Open VASL 6.4 beta with the extension you just saved
Start a new game using the Singling Map (bdSG)
Open the Overlays window
Select the HTML menu
Drag and drop the Singling Map "overlay" to hex P9
Select ctrl+H to paste the following code into the text line:

```
<html>
<img style="width: 2024px; height: 1741px;" alt="Singling Border"
src="Paste your link to the image you downloaded in step one here">
</html>
```

If all goes well and my instructions aren't messed up this should result in the Singling map border being drawn around the map.

Select ctrl+V to make the Singling HTML counter invisible

If you want reselect the HTML counter, use alt+click on P9 to reselect

I envision lot's of potential here. With the HTML code tied to an "overlay", the border doesn't disappear when you draw a LOS string. It also allows you to move units off map without being constrained by the hex grid that you'd get if you simply added the border to the Singling gif artwork.

Al

**Comment by BigAl737** [comment]
One feature we lose with the overlay extension is the ability for terrain transformations. These were handled with gifs and files that were zipped with the overlay just like a board. It is possible to add terrain transforms using layers for each overlay but that is a ton of work. Is there a way for a java class to be added as a trait to each overlay that the transform files and gifs could be zipped into? Could this trait then activate when a transform was selected for the board on which the overlay is placed? Or could the overlay itself have a transform menu similar to the one the boards use?

**Comment by davidsullivan317** [comment]
Checked in fix so LOS is disabled when it touches the new draggable overlays

**Comment by BigAl737** [comment]
A new version (1.01) is available. It includes all the BFP overlays. You can get it here:

[https://www.dropbox.com/s/09ljwz5z5t8f4ce/VASLOverlays.vmdx?dl=0](url)

Would someone please replace this file on vasl.info: [http://vasl.info/extensions/e6/VASLOverlays.vmdx](url)

Thanks.

**Comment by derimmer** [comment]
I have pushed up the new .vmdx along with changes to the extensions.htm file to vasl-website. So far these changes haven’t show up in the actual site. Not sure how to trigger that. Sam?

**Comment by styson** [comment]
Checked this morning and the downloaded extension is now 1.01.
