### ISSUE TITLE
bd72 missing G7 bldg

### ISSUE THREAD

**Issue by BigAl737** [vasl-developers/vasl#332]
http://www.gamesquad.com/forums/index.php?threads/board-72.128866/

**Comment by BigAl737** [comment]
Corrected and pushed. Need Doug to update LOS file before posting new board version 6.1.

**Comment by derimmer** [comment]
Will do shortly

**Comment by BigAl737** [comment]
Will try to download bd72 from the site in the morning to ensure all pushed okay.

**Comment by BigAl737** [comment]
The corrected board pushed okay to the site. However, the LOS is still acting a little goofy as these screen shots attest:

![los red at hex border](https://cloud.githubusercontent.com/assets/10384413/20902873/8fdd0f82-bae5-11e6-8d01-7a6ac5704743.jpg)
The LOS is red at the hex border

![los red with pointer in this position](https://cloud.githubusercontent.com/assets/10384413/20902881/989d224c-bae5-11e6-9263-18a1aa2fbd92.jpg)
The LOS is red with the pointer here but...

![los green when pointer moves here](https://cloud.githubusercontent.com/assets/10384413/20902885/9fedefae-bae5-11e6-8c4f-bd0fec988e9d.jpg)
...when you move the pointer here, the LOS turns green.

**Comment by derimmer** [comment]
Hi Al

 

This all looks correct to me. 

 

In the first picture, it is the ground level terrain in G7 that blocks LOS to IN H6, just as a crest line would. 

 

In the second instance, I suspect that the LOS is being checked in H6, which should be blocked. 

 

In the 3rd instance, I suspect that the LOS is being checked in either G7 or H7. In both of these hexes you can be at the vertex. 

 

If you switch to verbose mode (Preferences – LOS tab – check Verbose Mode); you will get more information about exactly where the LOS is being checked to from. 

 

Remember that while you are at the vertex point, you must be in one of the three hexes. 

 



 

This picture attached shows LOS checked to the vertex in G7 (note range is now 1). Red is clear on my system.

 

Doug

**Comment by BigAl737** [comment]
Makes sense Doug. Thanks for the refresher. This issue is closed and I am outta here :-)
