### ISSUE TITLE
VASL undo last move button not working properly

### ISSUE THREAD

**Issue by nukescott** [vasl-developers/vasl#336]
Running VASSAL 3.2.17; VASL 6.3.3.
If I start on any board and take two 5/8" counters setup offboard, move one on board somewhere, and then move the other one on board, over the top of and past the first one, and then try to undo the moves with the undo button/arrow in the upper left of VASL controls, the counter on the screen backs up into the overstacked hex and one more hex, but then stops moving.  Text in the dialog box says it is undoing moves, but the pieces / board display stop updating.
[undo_bug.zip](https://github.com/vasl-developers/vasl/files/721418/undo_bug.zip)

The hopefully attached zipped log file should demonstrate the issue.

**Comment by derimmer** [comment]
I have been able to replicate the condition described in the original post. 

Is this a VASL issue or a VASSAL issue? I thought that ASLPieceMover.java would be involved but I can't trap any activity in the class when moving units. Is there some other VASL code involved in movement?

**Comment by derimmer** [comment]
Tried this again with 6.6.8-beta1 and 3.75. Unable to replicate. Closing
