### ISSUE TITLE
French R35 and British Carrier counter errors

### ISSUE THREAD

**Issue by BigAl737** [vasl-developers/vasl#339]
http://www.gamesquad.com/forums/index.php?threads/vasl-map-online-problem-suggestion-form.88223/page-16#post-1861428

The French R35 counter is missing the "Low Ground Pressure" square.

The British Carrier MMG A counter is missing the "*ATR: [12]TH; HD FP ok" info note.

edit: fixed the link

**Comment by BigAl737** [comment]
Confirmed that the French R35 should have low ground pressure. Corrected r35.gif below. Not sure where to push this to on Git Hub. Possibly here?:

vasl\dist\images\fr\veh

![r35](https://cloud.githubusercontent.com/assets/10384413/24488306/614db90a-14c2-11e7-9a0c-a344f4c9ec6c.gif)

**Comment by BigAl737** [comment]
Where is the GitHub VASL source file for this counter trait window? I can fix the Has info trait if I knew where to push it so that it will be incorporated in the next VASL build. Thanks.

![brit carrier atr counter traits](https://cloud.githubusercontent.com/assets/10384413/24488565/0da172fe-14c4-11e7-80bc-c6b0e13868ca.gif)

**Comment by zgrose** [comment]
Module edits (aka non-code edits) are the buildFile file. I'd have to look where the mod file itself is stored. This is the achilles heel of the way the Git repo is setup, IMO, but it is what it is.

**Comment by davidsullivan317** [comment]
Agreed, but I don't know that there is a better way. 

@BigAl737 - search the buildFile for the vehicle name is easiest. Otherwise you will see the XML follow the structure of the counter window. 

Please be careful to only merge the line you change. When you save the module you will change dozens of lines and your VASL password will be saved all over the place. FYI

**Comment by BigAl737** [comment]
Carrier fix took a little sleuthing to confirm. Associated vehicle note:
![scan_0212](https://cloud.githubusercontent.com/assets/10384413/24516746/394efb4c-1528-11e7-97f2-ff6b121178e5.jpg)
As you can see, the ATR version is not pictured.

Counter front and rear:

![scan_0214](https://cloud.githubusercontent.com/assets/10384413/24516871/a0eb16aa-1528-11e7-83a7-061b09007150.jpg)
![scan_0215](https://cloud.githubusercontent.com/assets/10384413/24516900/bfc34d5e-1528-11e7-9866-7c8e1cbc1466.jpg)

The VASL version is also missing the HD FP ok note.

There are two versions of MMG A Carriers in VASL. The fix should only apply to the BATR version. I'll attempt make the fix to the correct version shortly.

**Comment by zgrose** [comment]
For whatever reason, none of the ATR:[12]TH entries have the * on them... You also only got the Lend-Lease counter. About to commit the fix for the British counter (also without the * for consistency).
