### ISSUE TITLE
LOS Problems with Board 8

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#350]
extraneous terrain (especially at the bottom of cliffs) is causing errors in LOS checking. This needs to be fixed in the bd08 file.

**Comment by BigAl737** [comment]
This board needs the light woods transformation as well. Okay if I can fix both issues?

**Comment by derimmer** [comment]
Sure. Thanks. The issue from my end involves cliff hexsides that are part of a water hex. There should not be any ground level terrain at the "bottom" of the cliff that would be touched by Los along that cliff hexside.  Change the terrain to water. 

I am away from home today so I can't look at the board in more detail until Friday. 

There may be other issues but I can't think of them at the moment. 

Thanks. 

Doug

**Comment by derimmer** [comment]
Just a further thought . . . I had to update just about every board with depressions or cliffs. If you need to update such a board please grab the latest from VASL-boards-extensions on github and not from VASL.info.

None of your recent updates were an issue!

Doug

PS Amazing work!

**Comment by derimmer** [comment]
bd08 is consistent across repositories and on vasl.info
