### ISSUE TITLE
Errata missing from oba-flowchart extension

### ISSUE THREAD

**Issue by styson** [vasl-developers/vasl#352]
The oba-flowchart.vmdx file is marginally inconsistent with the [errata for the OBA flow chart](http://www.multimanpublishing.com/Support/ASLASLSK/ASLOfficialErrata/tabid/107/Default.aspx) as reported by MMP, which says in the FFE:2 section at the bottom, there should be an arrow going from the `Make Direction/Extent of Error DR` octagon to the Yellow `Resolve FFE:2/Flip to FFE:C` oval.

In the OBA flow chart extension it is missing that arrow/connection, so when one gets to `Make Direction/Extent of Error DR` box, instead of Done on the bottom it should have a continue button, and then go to `Resolve FFE:2 Flip to FFE:C`.  The rest of the errata have been incorporated/fixed though.

Reported by Scott Vanevenhoven, scott.vanevenhoven@studsvik.com

**Comment by BigAl737** [comment]
I took a look at this and I think it requires a java guru to fix. Certainly beyond my ability.

**Comment by davidsullivan317** [comment]
This is going to have to go back to the extension author, who appears to be Scott Greenman as we don't have the source. Anyone know him?

**Comment by davidsullivan317** [comment]
Moving this to the extensions repo. https://github.com/vasl-developers/vasl-boards-extensions/issues/28
