### ISSUE TITLE
bd03 version does not match master list

### ISSUE THREAD

**Issue by jrvjrv** [vasl-developers/vasl#355]
The master board list (https://raw.githubusercontent.com/vasl-developers/vasl/develop/boards/v5boardVersions.txt) says the current is 6.4. The version downloaded from the repository (https://raw.githubusercontent.com/vasl-developers/vasl-boards-extensions/master/boards/bd03) is version 6.3.

**Comment by derimmer** [comment]
bd03 is consistent across repositories and on vasl.info
