### ISSUE TITLE
bd05 version does not match master version

### ISSUE THREAD

**Issue by jrvjrv** [vasl-developers/vasl#356]
The master board list (https://raw.githubusercontent.com/vasl-developers/vasl/develop/boards/v5boardVersions.txt) says the current is 6.1. The version downloaded from the repository (https://raw.githubusercontent.com/vasl-developers/vasl-boards-extensions/master/boards/bd05) is version 6.2.

**Comment by derimmer** [comment]
bd05 is consistent across repositories and on vasl.info
