### ISSUE TITLE
Allied SW for Allied Minors

### ISSUE THREAD

**Issue by mistertakai** [vasl-developers/vasl#36]
Some scenarios (like AP40) have the British or Americans share their SW with the Allied minors. However VASL does not have the SW counters in the correct colors.

Could we add them to the counter mix?

AP40 requires a British PIAT. 
AP53 requires a British Mortar.

I'm not sure which SW are needed by other scenarios.

**Comment by davidsullivan317** [comment]
I'm going to close this - to work around this problem HIP the foreign counter and create a concealment counter.
