### ISSUE TITLE
board 69 master version does not match board version

### ISSUE THREAD

**Issue by jrvjrv** [vasl-developers/vasl#360]
The master board list (https://raw.githubusercontent.com/vasl-developers/vasl/develop/boards/v5boardVersions.txt) says the current is 6.1. The version downloaded from the repository (https://raw.githubusercontent.com/vasl-developers/vasl-boards-extensions/master/boards/bd69) is version 1.0.

**Comment by derimmer** [comment]
Board 69 updated in vasl/src, vasl-boards-extensions and vasl-website. New file version on vasl-info.
