### ISSUE TITLE
Boards listed in master version list but do not have files

### ISSUE THREAD

**Issue by jrvjrv** [vasl-developers/vasl#365]
The master board list (https://raw.githubusercontent.com/vasl-developers/vasl/develop/boards/v5boardVersions.txt) lists the following boards that do not have files at https://raw.githubusercontent.com/vasl-developers/vasl-boards-extensions/master/boards/bdXX:

STN
BFPDW6a
BFPDW6b
1 (not 01)
2 (not 02)
3 (not 03)
4 (not 04)
5 (not 05)
6 (not 06)
7 (not 07)
8 (not 08)
9 (not 09)
BFPDW5a
BFPDW5b
VOTG
PDH
75
KRETA
HH
RILEYS
ASLNEWS1
BFPR
BFPQ
BFPP
BFPO
RaM

**Comment by derimmer** [comment]
I believe this to be my fault. I had to update the master list as I made changes to about 40 boards and bumped the version number on all of them. 

I did this by updating my local copy of v5boardVersions.txt and then pushing the revised file up to GitHub. I think I did not have the latest version of v5boardVersions.txt when I started this process and so I unwittingly wrote over changes that had been made to the master list by others in the period between when I first cloned the file to my local drive and when I pushed the changes back up. 

Dumb-ass rookie mistake. Bugger!

Anyway, I will undertake to not only fix the issues that jrvjrv notes in this issue and others, but also to verify that the board version numbers used in v5boardVersions.txt match for all for boards currently in vasl-boards-extensions and vasl-website.

**Comment by jrvjrv** [comment]
If I may be so bold as to offer a suggestion, checking is something that can be automated. In fact the board version issues I found were found through a program, not by hand. One could even take this a step or two further and generate the v5boardVersions.txt file automatically rather than trying to maintain it by hand. Similarly "extra" files are easy to find in a program. There are a couple of boards that have files called "dataOrig" that I did not call out because the added size was so small.

**Comment by derimmer** [comment]
@bkemp01 Hi Brian

I notice that you uploaded the files for the PiF boards BFPDW5a, BFPDW5b, BFPDW6a, and BFPDW6b to vasl/src. However, I do not see the matching bd files for them in vasl-boards-extensions. I can upload them there if you like?

**Comment by bkemp01** [comment]
Not sure what happened to them but here is my commit from June 8, 2016 for
all of the PiF boards...

https://github.com/vasl-developers/vasl-boards-extensions/commit/e38c4e73a0654846aab41dd39224972f24827980

including bdBFPO, bdBFPP, bdBFPQ, bdBFPR, bdBFPDW5a, bdBFPDW5b, bdBFPDW6a &
bdBFPDW6b. All of them now seem to be missing. Feel free to add them back
as needed.

Thanks

**Comment by zgrose** [comment]
Looks like they were blown away in this merge: https://github.com/vasl-developers/vasl-boards-extensions/commit/4ea3f08f72108fb19b35a784280209359d6c2e95

**Comment by bkemp01** [comment]
Yes, and it looks like there were several other deletes there also... bdHH,
bdRaM and ovrYASL.

**Comment by davidsullivan317** [comment]
I'd highly recommend after all dust settles with the board updates that we rebuild all boards and do a mass update of the boards-extension repository. Should only take 5 mins. Let me know if/when you want me to do this.

**Comment by derimmer** [comment]
I am not currently working on any board updates so anytime soon would be fine with me. BUT, of course, others may have things in progress. Al?

I am willing, if needed, to add LOS to boards 74 and 76 but so far we do not have a bd file for either of them. I suspect that they can come after your rebuild, Sully.

**Comment by BigAl737** [comment]
I've got about 20 boards that I'll be updating soon. I hope to get to it this week. Trying to figure out board builder now.

**Comment by davidsullivan317** [comment]
Boards 1-9 were really old versions of 01-09, so those can be ignored (no harm in leaving them in the version file). Otherwise the other boards look to be back in the vasl-boards-extensions repository.
