### ISSUE TITLE
bdSC version not correctly formatted

### ISSUE THREAD

**Issue by jrvjrv** [vasl-developers/vasl#366]
The data file in bdSC (at https://raw.githubusercontent.com/vasl-developers/vasl-boards-extensions/master/boards/bdSC) has what appears to be a very old style of writing version: "v3". I think this does not parse well in vasl. The master version is 3.0, so the data file needs a line, "version 3.0".

**Comment by zgrose** [comment]
Next board build should pick up the changes.

**Comment by jrvjrv** [comment]
The version in both at vasl.info and in github still has v3 instead of version 3.

**Comment by derimmer** [comment]
The uncompiled board files in VASL\boards\src\bdSC contain Zoltan's change. The compiled board in VASL\boards\bdFiles did not. I updated bdSC in this directory and I upated bdSC.zip in VASL-website.

So all the active board files should now be updated. The change will happen on VASL.info shortly. I did not bump any version numbers.

**Comment by jrvjrv** [comment]
tested, and it now works. Are there any other map fixes that are awaiting compilation, @derimmer? I submitted a bucket of them and I think most of them got addressed, but I never went back and tested them.

**Comment by derimmer** [comment]
I don't know the answer to that. I remember you submitting a number of boards but I can't find the list on Github. There are certainly some outstanding board bugs on the Issues list.
