### ISSUE TITLE
Update instructions for building boards and adding boards to vasl-website

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#376]
Add David Sullivan's instructions for running boardbuilder (see #372) to the documentation and also include Zoltan Grose's instructions for adding zip files to vasl-website. 

One minor step still missing: 

Updating files in vasl-website automatically updates the board that appears on the vasl.info website. This does not appear to be true when adding new boards to vasl-website. They need some intervention to show on vasl.info. Can anybody tell me what needs to be done? I will then include that in the documentation.

**Comment by zgrose** [comment]
Other than "edit the boards.htm to display the new links" I'm not sure how much documentation can be done. But that's the file.

**Comment by derimmer** [comment]
I can work with that! Thanks.

**Comment by BigAl737** [comment]
Doug, for the total noob that is me, can you add instructions for how to run board builder. All I see when I open the file is code.

**Comment by derimmer** [comment]
Al, I have just added some instructions for BoardBuilder to the Wiki and updating the Wiki page on Creating and Updating Boards. Still more work on documentation to do but this should be enough to get you going. Happy to walk you through it.

**Comment by derimmer** [comment]
I have added all the new information I have to the various wiki pages and documents. 

When adding boards to vasl.info, I did not include the reference to adding board .zip files to the v6boardsAll.zip file in the vasl-website repository. Since this file is not being used there seemed no point in adding yet another step to a process that is complex enough as it is.  

Please let me know if anyone sees errors or omissions in any of the pieces.
