### ISSUE TITLE
bd74 v6.0 missing files

### ISSUE THREAD

**Issue by jrvjrv** [vasl-developers/vasl#377]
missing files: data, overlaySSR, colors, colorSSR. Users can't apply terrain SSRs as a result: http://www.gamesquad.com/forums/index.php?threads/is-there-bd-74-and-75-for-vasl.129734/#post-1864316

**Comment by derimmer** [comment]
@bkemp01 Brian, if you can add these missing files to the /src folder, I will rebuild the board

**Comment by bkemp01** [comment]
Committed legacy files and bumped to v6.1 in vasl/boards/src, please rebuild.

FYI the new way (VASL 6.3+) is to use BoardMetadata.xml but apparently the old data file is still required. For overlays to work pre-6.3 an overlaySSR file is needed. The colors & colorSSR files are generally not required.

**Comment by davidsullivan317** [comment]
I think we can safely sunset the old text files in the boards. The new metatdata XML approach has been active since 6.1, so we would only lose support for people still on 6.0 (if any).

**Comment by bkemp01** [comment]
Also Doug, I don't see the LOSData file in the src folder.

**Comment by bkemp01** [comment]
David, I tested and the data file is required even in 6.3.3 or transforms don't work. Transforms in 6.2.2 only work if overlaySSR is present.

**Comment by derimmer** [comment]
Yes, I forgot to copy LOSData to the src folder. I will do so.

**Comment by derimmer** [comment]
1. Added Losdata to sr/bd74
2. Bumped bd74 version to 6.1 in v5boardVersions.txt
3. Rebuilt bd74 and pushed up to vasl-boards-extensions. 
4. Created .zip file of rebuilt bd74 and pushed to vasl-website.

Tested bd74 updates to v6.1 when opening new game with the bd74
Tested LOS works in v6.1
v6.1 showing on VASL.info

Did not test transformation, nor download of v6.1 from vasl.info

If transformations work, this issue can be closed.

**Comment by davidsullivan317** [comment]
The "colors" and the "colorSSRules" elements have not been added to board 74 metadata file, which is necessary for the transformations to work.

**Comment by bkemp01** [comment]
I have tested the transformations and they do work as advertised in the current v6.1 of bd74.

The transformations are generally handled via board overlays (overlaySSR/overlaySSRules) nowadays. The only time "colors" and "colorSSR/colorSSRules" should come into play is if a board uses non-standard colors. Otherwise the default values are already baked into the VASL module. The idea is that a local copy in the board archive file should override the baked in default values.
