### ISSUE TITLE
Boards that are available but not in master list

### ISSUE THREAD

**Issue by jrvjrv** [vasl-developers/vasl#381]
These boards are available as bdXXXX at vasl-boards-extensions/boards/ but not in https://github.com/vasl-developers/vasl/blob/develop/boards/v5boardVersions.txt. When vasl checks for a later version it will not find these:

25a
AAC
AK1
AK2
ASLNews
ATB
AllAmerican
B&I
B3R
BB
BERLIN
BF2
BOB DZN
BRT
Bataan
BerlinRV
BlankCard
Blood & Iron
Bracchi
Brecourt
CAC
CE
CGV
CHDD1
CHDD2
CM
CRS
DTW
DaE
DfBG1
Dold1
Dold2
Dold3
Dold4
FACTRY
FAWJ1a
FAWJ1b
FB
FB_NE
FB_NW
FB_SE
FB_SW
FE1
FE2
FE3
FE4
FE5
FE6
FE8
FE9
FF01
FF02
FF03
FF04
FF05
FF06
FF07
FF08
FF09
FF10
FF11
FF12
FF13
FF14
FF15
FWAO
Filler1
Filler2
Filler3
Filler4
Filler5
Filler6
GB1
GB2
GB3
GB4
GB5
GE
GSTK
HB
HFv221
Hotton
Hurtgen
IvansWar
KX1
KX2
KX3
KX4
Kreta
MC1
MC1 Snow
MC2
MC2 Snow
MC2a
MC2a Snow
MC3
MC4
MC5
MC5 Snow
MC5A
MC5A Snow
MC6
MC7
MID
Ma
Mb
Melines
N1
N2
N3
NordicTwilight
OBS
OzB
PHD
PdH
Pel
QuatreBras
RC Novo
RC Orlovo
RG
Rileys
SCW0
SCW1
SCW2
STB
STB1
STB2
SantaMaria-HLV1
SantaMariaInfante
SpanishFury1
SpanishFury2
StLo
StN
Stonne
TCRS
TL
TPH2
TR1
TR2
TR3
TR4
TR5
TR6
TR7
TR8
Tobruck
Toktong
TttF
UV
VotG
WC1
WC2
WittLastBattle
breskenspocket
d1
d2
d3
d4
d5
d6
d7
kholmS
kholmW
kholmWO
oto2

**Comment by jrvjrv** [comment]
This is what should be in the master list if it is to reflect the current state of the boards folder:

00 = 6.0
01 = 6.0
02 = 6.4
03 = 6.3
04 = 6.0
05 = 6.2
06 = 6.1
07 = 6.0
08 = 6.3
09 = 6.1
10 = 6.0
10z = 6.1
11 = 6.0
12 = 6.2
13 = 6.1
14 = 6.0
15 = 6.0
16 = 6.1
17 = 6.1
17z = 6.0
18 = 6.1
19 = 6.2
1a = 6.0
1b = 6.0
20 = 6.4
21 = 6.0
22 = 6.2
23 = 6.1
24 = 6.3
25 = 5.2
25a = 5.2
26 = 6.2
27 = 6.2
28 = 6.2
29 = 6.2
2a = 6.2
2b = 6.2
30 = 6.2
31 = 6.2
32 = 6.1
33 = 6.1
34 = 6.1
35 = 6.0
36 = 6.1
37 = 6.0
38 = 6.0
39 = 6.1
3a = 6.0
3b = 6.0
40 = 6.4
41 = 6.2
42 = 6.2
43 = 6.2
44 = 6.2
45 = 6.1
46 = 6.0
47 = 6.1
48 = 6.1
49 = 6.2
4a = 6.2
4b = 6.2
50 = 6.2
51 = 6.0
52 = 6.1
53 = 6.1
54 = 6.0
55 = 6.1
56 = 6.0
57 = 6.0
58 = 6.0
59 = 6.1
5a = 6.2
5b = 6.2
60 = 6.1
61 = 6.1
62 = 6.1
63 = 6.0
64 = 6.1
65 = 6.1
66 = 6.1
67 = 6.1
68 = 6.0
69 = 6.1
6a = 6.2
6b = 6.2
70 = 6.1
71 = 6.1
72 = 6.2
73 = 6.0
74 = 6.1
75 = 6.2
7a = 6.1
7b = 6.1
8a = 6.3
8b = 6.3
9a = 6.1
9b = 6.1
AAC = 1.0
ABTF = 1.0
AK1 = 2.0
AK2 = 1.0
ASLNews = 2.0
ATB = 1.0
AllAmerican = 1.2
B&I = 1.2
B3R = 1.0
BB = 1.0
BDF = 1.1
BERLIN = 1.0
BF1 = 1.1
BF2 = 1.0
BFPA = 6.0
BFPB = 6.0
BFPC = 6.1
BFPD = 6.0
BFPDW1a = 6.0
BFPDW1b = 6.1
BFPDW2a = 6.0
BFPDW2b = 6.1
BFPDW3a = 6.1
BFPDW3b = 6.1
BFPDW4a = 6.1
BFPDW4b = 6.1
BFPDW5a = 6.0
BFPDW5b = 6.0
BFPDW6a = 6.0
BFPDW6b = 6.0
BFPE = 6.1
BFPF = 6.0
BFPG = 6.0
BFPH = 6.0
BFPI = 6.1
BFPJ = 6.1
BFPK = 6.1
BFPL = 6.1
BFPM = 6.0
BFPN = 6.1
BFPO = 6.0
BFPP = 6.0
BFPQ = 6.0
BFPR = 6.0
BOB DZN = 1.0
BRT = 1.1
BRV = 1.1
Bataan = 1.0
BerlinRV = 1.0
Blank0 = 6.0
Blank1 = 6.0
BlankCard = 1.0
Blood & Iron = 1.0
Bracchi = 1.0
Brecourt = 1.0
CAC = 1.0
CE = 1.1
CGV = 1.0
CH = 0.93
CHDD1 = 1.0
CHDD2 = 1.0
CM = 1.0
CRS = 2.2
DBP = 1.1
DTW = 1.0
DaE = 1.1
DfBG1 = 1.0
ER = 1.1
FACTRY = 1.0
FB = 1.0
FB_NE = 2.1
FB_NW = 2.1
FB_SE = 2.1
FB_SW = 2.3
FC = 1.1
FE1 = 1.1
FE2 = 1.1
FE3 = 1.0
FE4 = 1.0
FE5 = 1.0
FE6 = 1.0
FE8 = 1.0
FE9 = 1.0
FF01 = 1.0
FF02 = 1.0
FF03 = 1.0
FF04 = 1.0
FF05 = 1.0
FF06 = 1.0
FF07 = 1.0
FF08 = 1.0
FF09 = 1.0
FF10 = 1.0
FF11 = 1.0
FF12 = 1.0
FF13 = 1.0
FF14 = 1.0
FF15 = 1.0
FWAO = 0.3
Filler1 = 1.0
Filler2 = 1.0
Filler3 = 1.0
Filler4 = 1.0
Filler5 = 1.0
Filler6 = 1.0
FrFA = 6.0
GB1 = 2.0
GB2 = 2.0
GB3 = 2.0
GB4 = 2.0
GB5 = 2.0
GE = 1.0
GSTK = 1.0
GT = 1.0
HB = 1.0
HFv221 = 1.0
HH = 1.0
HOBI = 2.0
HOBII = 2.0
Hotton = 2.0
Hurtgen = 1.0
IvansWar = 1.0
KB = 0.11
KOTH = 1.0
KR = 1.0
KX1 = 1.0
KX2 = 1.0
KX3 = 1.0
KX4 = 1.0
Kreta = 1.0
LFT1 = 1.0
LFT2 = 1.0
LG = 1.0
MC1 = 1.0
MC1 Snow = 1.0
MC2 = 1.0
MC2 Snow = 1.0
MC2a = 1.0
MC2a Snow = 1.0
MC3 = 1.0
MC4 = 1.0
MC5 = 1.0
MC5 Snow = 1.0
MC5A = 1.0
MC5A Snow = 1.0
MC6 = 1.0
MC7 = 1.0
MID = 1.0
Ma = 1.0
Mb = 1.0
Melines = 1.0
N1 = 1.0
N2 = 1.0
N3 = 1.0
NG = 1.0
NUL = 1
NULV = 1
NordicTwilight = 1.1
OBS = 1.0
OTO = 1.0
OzB = 1.0
PB = 0.1
PBR = 1.1
PHD = 1.0
PdH = 1.0
Pel = 1.0
QuatreBras = 1.0
RB = 1.3
RBv2 = 2.2
RC Novo = 1.0
RC Orlovo = 1.0
RG = 2.0
RR = 1.0
SCW0 = 1.0
SCW1 = 1.0
SCW2 = 1.0
SG = 1.0
SH = 1.1
ST = 2.02
STB = 1.0
STB1 = 1.0
STB2 = 1.0
SantaMaria-HLV1 = 1.0
SantaMariaInfante = 1.0
SpanishFury1 = 1.0
SpanishFury2 = 1.0
StLo = 1.0
StN = 1.0
Stonne = 2.0
TCRS = 1.0
TL = 1.0
TO = 1.2
TPH2 = 1.0
TRBH = 1.0
Tobruck = 1.0
Toktong = 1.0
TttF = 1.0
UV = 1.0
VotG = 3.1
WC1 = 1.0
WC2 = 1.0
WittLastBattle = 1.0
a = 6.0
b = 6.0
breskenspocket = 1.0
c = 6.0
d = 6.0
d1 = 1.0
d2 = 1.0
d3 = 1.0
d4 = 1.0
d5 = 1.0
d6 = 1.0
d7 = 1.0
e = 6.0
f = 6.0
g = 6.0
h = 6.1
kholmS = 1.1
kholmW = 1.1
kholmWO = 2.1
oto2 = 1.0
p = 6.0
q = 6.1
r = 6.0
s = 6.0
t = 6.0
u = 6.0
v = 6.0
w = 6.0
x = 6.0
y = 6.0
z = 6.1

**Comment by zgrose** [comment]
Tried to make the changes a bit easier to read for humans in the Git compare window but I believe it is all there. Can alphabetize after the dust settles on version changes.
