### ISSUE TITLE
boards with spaces in names sometimes get 404 errors when retrieved

### ISSUE THREAD

**Issue by jrvjrv** [vasl-developers/vasl#382]
In BoardVersionChecker.getRepositoryFile there is code:

 URL website = new URL(url);
 URLConnection conn = website.openConnection();

When I borrowed this code as-is, I sometimes (but not always) got 404 errors for urls with spaces in them, for example in board names. I recommend something like:

 // url is a String
 URL website = new URL( url.replace( " ", "%20" ) );
 URLConnection conn = website.openConnection();

**Comment by zgrose** [comment]
I'm gonna go out on a limb and say vasl 3.x shouldn't support spaces in board names. Probably shouldn't support non-letters/numbers as well. The ROI for all the extra testing and bug fixes to support `bdMy Cool Name`seems miniscule.

**Comment by jrvjrv** [comment]
While I have no objection to any policy, having correct code that is never exercised because of policy seems to me better than having incorrect code that is covered up by policy.

**Comment by zgrose** [comment]
Right, but a feel-good patch that applies to one character (space) while ignoring all the other URL killing characters and leaves unresolved any other issues that spaces may have isn't anymore correct, IMO. There are also all the legacy parsing issues with our 50/50 XML/CSV module files that may (or may not) choke on other characters ( the $ and ; characters seem the most likely candidates).

If someone did want to tackle this though, I'd suggest taking a look at java.net.URLEncoder for a potentially robust solution for the URL itself.

**Comment by jrvjrv** [comment]
The reason I did not suggest the java.net.URLEncoder is that it does not do what it seems to say it does. It is intended for encoding query string parameters, as best I understand. If you apply it to a whole URL, it destroys it. For instance, this is the url for the board versions txt file after encode(): "https%3A%2F%2Fraw.githubusercontent.com%2Fvasl-developers%2Fvasl%2Fdevelop%2Fboards%2Fv5boardVersions.txt". That "URL" does not work in a browser nor in a program.

The difficulty is that different segments of the URL are encoded differently. The URLEncoder works on the query string segment, as I understand it. As my example showed, it should not be used for the path segment. I had a hard time finding a good solution for the path segment on-line. This page suggests using the URI class: http://www.baeldung.com/java-url-encoding-decoding (number 5 on the page). That may be even better than my immediate fix to my immediate problem. But my suggested fix would make the URL "better" and would not make it bad.

**Comment by jrvjrv** [comment]
After some research and testing, the best solution I have to the general problem of URL encoding seems to be the code below. It turns out to be a tricky problem to which I found no general solution. There may yet be one out there. In case of error the original URL is returned. This may not be desirable.

    // do not use on an already-encoded URL. It will double-encode it.
    public static String encodeUrl( String unencodedURL ) {
        try {
            URL url = new URL(unencodedURL);
            URI uri = new URI(url.getProtocol(), url.getUserInfo(), url.getHost(), url.getPort(), url.getPath(), url.getQuery(), url.getRef()); 
            return uri.toURL().toString();
        }
        catch( java.net.URISyntaxException ex ) {
            return unencodedURL;
        }
        catch( java.net.MalformedURLException ex ) {
            return unencodedURL;
        }
    }
