### ISSUE TITLE
Upgrade VASSAL version in code base to 3.2.17

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#385]
I am willing to play around with this and see if anything nasty happens. 

If anyone has thoughts about what issues might arise, let me know. Thanks.

**Comment by davidsullivan317** [comment]
All developers will need to update their development environments to use the new jar. For example, note the use of the VASSAL jar in my IntelliJ setup:
![image](https://cloud.githubusercontent.com/assets/5281926/24367853/c7254896-12e3-11e7-977d-86c24b357000.png)

**Comment by davidsullivan317** [comment]
I've upgraded the version of VASSAL in our source to 3.2.17. The need to explicitly place the Vengine.jar ahead of the other jars in the dependencies list appears to be no longer necessary. I've removed the VASSAL version from the jar name, which was never a good idea.

**Comment by derimmer** [comment]
Ok. Thanks for doing this. For new development projects we should clone 'develop' with 3.2.17 right?  

What about current work. Do we simply finish it and push it up as normal or do we need to update the VASSAL version ?

**Comment by davidsullivan317** [comment]
If you clone develop you'll get the 3.2.17 jars. Nothing new to do there.

You'll want to pull the changes into your existing development instances and tweak your project settings to remove the old VASSAL jar. Give it a try. 

We might need to update the development documentation. Again, I did not need to explicitly put the Vengine.jar first in the classpath.
