### ISSUE TITLE
overlay placement error - can anybody reproduce this?

### ISSUE THREAD

**Issue by styson** [vasl-developers/vasl#394]
When Eric Topp tries to add VASL overlay OB1 (from Action Pack 11) to board 71, an error occurs:
```
'data' not found in /Users/erictopp/D...
```

He has
VASL 6.3.3 
VASSAL 3.2.17
and is using Coordinates U1 U2 (as on scenario card for AP101)

**Comment by zgrose** [comment]
In my experience, this is usually that the overlay/board file isn't an overlay/board file but something else (like a zip of the board/overlay file with the .zip removed or some such). But just my first guess.

**Comment by jrvjrv** [comment]
That sounds likely. With windows by default the extensions for "common" file types are not displayed, so the user frequently sees "ovrOB1.zip" displayed as "ovrOB1". Alternately it could actually be named ovrOB1 but still be the .zip of the board, not the board itself. The user should either switch off "don't display file extensions" in file explorer (the method is different for each version of windows; this is up through 8: https://www.howtohaven.com/system/show-file-extensions-in-windows-explorer.shtml) or use the command line.
