### ISSUE TITLE
VASL Bd45 LOS problems

### ISSUE THREAD

**Issue by Eagle4ty** [vasl-developers/vasl#398]
Bd45 hex V3 has the LOS info for hex V2, shows a blocked LOS due to terrain height when none exists.

**Comment by derimmer** [comment]
Which versions of VASL and bd45 are you using? I have tried the LOS using 6.3.3 and 6.4.0-beta1 with v6.1 of bd45 and I cannot replicate the problem. Are you stringing the LOS just from V3-V2 or do you get the same problem if the LOS goes from V4 through V3 into V2?

**Comment by Eagle4ty** [comment]
Using latest version posted on vasl site. checked LOS (Incl verbose mode)
from W3-U4, W4-U3, W5-V2 all recorded as if terrain from V2 was in V3.
However, I did have to crop boards 20 & 61 for ASL Scenario A119 Konev's
Cross, so maybe that has something to do with it. Have now checked with
Bd45 only (both flipped and standard alignment), find no problem with the
LOS. Reloaded with cropped boards as noted, same problem exists (flipped
board config as well just to make sure). Thanks for the rapid reply, will
simply make adjustments as necessary.

t.y.

**Comment by derimmer** [comment]
Yes, currently LOS works with some crop and flip configurations but not all. This is being worked on (by me), #281, #143. In fact, I have some code ready for testing. Willing to give it a try?
