### ISSUE TITLE
IntelliJ licenses still available

### ISSUE THREAD

**Issue by davidsullivan317** [vasl-developers/vasl#400]
I've extended the open source licensing of the Jetbrains development suite for another year. We still have 3 licenses that are not assigned if anyone is interested.

**Comment by derimmer** [comment]
Hi Sully 

If there are any still free, could we use one for my buddy who is going to be working with me on some coding?

If so, how does he join VASL-developers?  He already has a Github account I think. 

Doug

**Comment by davidsullivan317** [comment]
I've received the renewal notice for the Jetbrains development suite and have done so. If you don't have one and would like to use one of the licenses we still have two remaining. 

If you don't know what I'm asking you don't need it.
