### ISSUE TITLE
FR: The ability to zoom the map but not pieces

### ISSUE THREAD

**Issue by pacman-ghost** [vasl-developers/vasl#401]
This would really help in situations like this:

![crowded](https://cloud.githubusercontent.com/assets/27834058/25555747/0e3ef2cc-2cde-11e7-83a8-c68da8c639d3.png)

Zooming in on everything using F3 doesn't help, since it's just as incomprehensible, just at a larger size :-/

Switching to deluxe-size hexes mid-game sorta works, but:
- the process is a bit clumsy (via "Pick new boards for this scenario")
- it doesn't handle labels nor map annotations properly
- there's no fine control over the hex size; it's either normal size or massive size

However, doing it like this does seem to work; in particular, the placement of pieces within the deluxe-size hexes is remembered when you zoom in and out, so it seems that all the machinery to do this is already in place (using VASSAL 3.2.16/VASL 6.3.3), we just need a better UI to control it e.g. Ctrl-F3/F4 to zoom in/out the board, but leaving the pieces at the same size...?

**Comment by davidsullivan317** [comment]
This isn't something we can do in VASL; it would have to be done in the VASSAL mothership.
