### ISSUE TITLE
Terrain chart has wrong MP cost for bocage

### ISSUE THREAD

**Issue by davidsullivan317** [vasl-developers/vasl#403]
The terrain chart lists the fully tracked cost for crossing bocage as 2+COT whereas it should be Z + COT, Z being a reference to half the vehicle's MPs. I am using 6.3.3

**Comment by zgrose** [comment]
Terrain Chart extension v1.2.1?

<img width="1135" alt="screen shot 2017-05-01 at 8 31 04 am" src="https://cloud.githubusercontent.com/assets/5044847/25583875/8e4b74ac-2e48-11e7-991a-68e461faa699.png">

**Comment by zgrose** [comment]
Should be fixed in the terrain extension v1.2.1 already.
