### ISSUE TITLE
Extra HoB menu on Japanese crews

### ISSUE THREAD

**Issue by zgrose** [vasl-developers/vasl#407]
I think the crews have an extra HoB menu trait. Just looking for confirmation one way or another before I snip it.

<img width="735" alt="screen shot 2017-05-05 at 8 09 59 am" src="https://cloud.githubusercontent.com/assets/5044847/25751621/8b580178-316a-11e7-9299-2b346b7385f5.png">

**Comment by styson** [comment]
The only thing listed under that HoB menu is Fanatic. I don't see anything in A10.8 that indicates Fanaticism evoked by SSR wouldn't apply to crews, but I have never seen that SSR invoked.

Checking the German/Russian/American crews shows the same HoB Fanatic option.

**Comment by zgrose** [comment]
That's not the problem. The problem is that on some other trait, applied more universally (jpINF or jp12 perhaps) is another HoB submenu.
 
<img width="328" alt="screen shot 2017-05-07 at 9 25 38 am" src="https://cloud.githubusercontent.com/assets/5044847/25782879/2fbdfe32-3307-11e7-9415-2c986c112a21.png">
