### ISSUE TITLE
Official release VASL 6.4.0

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#409]
We have put out VASL6.4.0beta4. No bugs reported. I am ready to release VASL 6.4.0 as an official release. Anybody working on any last minute changes that they want to push up and get in the release? 

I am heading out of town on May 18 and will release 6.4.0 before then unless someone asks me to wait.

**Comment by davidsullivan317** [comment]
The cleanup I needed to do on the PieceLinker is done.
