### ISSUE TITLE
6.4.1 suggestion

### ISSUE THREAD

**Issue by zgrose** [vasl-developers/vasl#415]
We know they've been piling up and relative to code fixes they are usually dirt easy to make. I propose the next release be a minor x.x.1 counter bug fix release focusing on counter image fixes and traits  (e.g. #413 and #339). There's no downside and it's super easy to test and makes tons of people happy.

**Comment by lafajita** [comment]
There is also the problem with Japanese crew counters, both 2-2-8 and 1-2-7.
The HoB line in the counter listing has no info, whereas just yesterday I noticed that there is another HoB listing which makes it possible make a 2-2-8 either Fanatic, or Berserk. The 1-2-7 only lists a single option of Fanatic. It should not be difficult to edit this particular bit of code.

**Comment by zgrose** [comment]
That's issue #407

**Comment by lafajita** [comment]
While I am dreaming up more stuff for you all to look into, I managed to find another problem - that has been around at least as far back as 6 2.2 - 

We have been provided with a semi-complete set of "Transparent" overlays. We don't come across many opportunities to use most of them, but once in awhile they do make for a "prettier " VASL map -

Except for this problem.

The single-hex Transparent overlay for "Brush" does not work.
The two-hex and three-hex version works OK, but not the one-hex version.

Just calling this to the attention of someone who might know how to fix this.

-- lafajita

**Comment by zgrose** [comment]
Splitting off the comment above for an issue and closing this as I'm not sure there is much interest in the topic at this time.
