### ISSUE TITLE
Sherman III(L) info has mis-placed "r"

### ISSUE THREAD

**Issue by jrvjrv** [vasl-developers/vasl#419]
Under Soviet Lend-Lease vehicles, some of Sherman III(L) info strings have "red CS", which appears as "ed CS" in red. These should either be "rred CS" or "Red CS".

This thread covers the issue: http://www.gamesquad.com/forums/index.php?threads/what-does-ed-mean.131358/

**Comment by zgrose** [comment]
The correct info string is rCS. There are 7 occurrences of `red CS` or `Red CS` in the buildFile. Swapping them all to `rCS` instead.
