### ISSUE TITLE
Transparent overlay issue

### ISSUE THREAD

**Issue by zgrose** [vasl-developers/vasl#422]
From #415 

While I am dreaming up more stuff for you all to look into, I managed to find another problem - that has been around at least as far back as 6 2.2 -

We have been provided with a semi-complete set of "Transparent" overlays. We don't come across many opportunities to use most of them, but once in awhile they do make for a "prettier " VASL map -

Except for this problem.

The single-hex Transparent overlay for "Brush" does not work.
The two-hex and three-hex version works OK, but not the one-hex version.

Just calling this to the attention of someone who might know how to fix this.

-- lafajita

**Comment by derimmer** [comment]
fixed errors in data file
