### ISSUE TITLE
6.4.1 beta1

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#423]
Hi Everyone

I have some code changes that I would like to put out as 6.4.1-beta1. All los stuff: still debugging clipping and flipping (sad face). 

Zoltan had suggested adding a number of counter fixes to 6.4.1. Happy to incorporate them. If anyone wants to make a push over the next couple of weeks, that would be great. I would intend to put out beta1 around end of the month. 

Any other changes that we should add?

**Comment by BigAl737** [comment]
I could do the counter art. I can even make changes to the traits within VASL. However I’ve found that I’m inept at getting the counter loaded into the build file. Let me know if I can still be of assistance.

Allan

From: Doug Rimmer 
Sent: Friday, July 14, 2017 7:16 AM
To: vasl-developers/vasl 
Cc: Subscribed 
Subject: [vasl-developers/vasl] 6.4.1 beta1 (#423)

Hi Everyone

I have some code changes that I would like to put out as 6.4.1-beta1. All los stuff: still debugging clipping and flipping (sad face).

Zoltan had suggested adding a number of counter fixes to 6.4.1. Happy to incorporate them. If anyone wants to make a push over the next couple of weeks, that would be great. I would intend to put out beta1 around end of the month.

Any other changes that we should add?

**Comment by zgrose** [comment]
Perhaps we can take a quick moment to review the intended workflow for the non-code bits.

If I understand the repo structure and section 6.0 of the GettingStartedWithVASLDevelopment document, the contents of the dist folder are essentially the non-java bits of the vasl.vmod.

So to add a new counter image to the vmod you just add your image to the dist/images folder in the same relative path as you chose for the image in the editor. Additionally, you'll update dist/buildFile with the updated/new counter definitions.

So unless I'm missing some piece of the puzzle:
1. edit the vasl.vmod with the native tools
2. extract the buildFile
3. use a Diff tool of some kind to snip out any unintentional changes
4. drop new/change counter art into the images folder

So I'll start collecting/doing counter trait changes. If there isn't an open issue for the change I'll create one so it'll be easier to track and make release notes.

**Comment by derimmer** [comment]
As you will know, the VASL Map is surrounded by a padding of 400 pixels to give room for offboard counters. 

 

The size of the padding seems discretionary. Is there a particular reason for 400 pixels? Have we ever tried/discussed a smaller padding that would allow more of the mapboard to show on screen?

**Comment by davidsullivan317** [comment]
We have to pick one value for the padding around the maps and stick to it.
It's part of the code and is used to compute the counter locations.

It was changed from 200 to 400 as there wasn't enough room for off-board
setup when the counter density got too high.

**Comment by zgrose** [comment]
Not only off-board setup but tall on-board stacks can push out of the window and counters would become un-selectable without stack wiggling.

**Comment by derimmer** [comment]
OK. Happy to leave it as is.

**Comment by derimmer** [comment]
6.4.1-beta1 is now on GS and the Facebook. Great work by Zoltan.
