### ISSUE TITLE
VASL Preference to render full color stacks or not

### ISSUE THREAD

**Issue by zgrose** [vasl-developers/vasl#431]
Option to use full color stacks or not.

To make it the least likely to be modified by the average user I've made it a "disable" setting with the default of false.

![screen shot 2017-08-09 at 4 01 57 pm](https://user-images.githubusercontent.com/5044847/29147513-5d649a30-7d1c-11e7-9484-ddfe5a9d7f09.png)

**Comment by zgrose** [comment]
@drimmer Not sure how equipped you are to building the module from a branch so I've committed to develop. Seems to be working while testing in the IDE. I'm not setup on my machine to do builds so if you can cut a beta2 in the near future, I'll test it out some more.

**Comment by derimmer** [comment]
Will do in the next day or so.

**Comment by derimmer** [comment]
Zoltan

 

Here is a link to the beta2 vmod on my dropbox. It ran on my machine (but I did no testing).

 

https://www.dropbox.com/s/b98rbyrunviecyu/vasl-6.4.1-beta2.vmod?dl=0

 

 

Doug

**Comment by zgrose** [comment]
Thanks. No crazy crashes and appeared to behave as intended (defaulted to full color stacks). Since it's probably the number one most discussed issue out there at the moment, wanna push out beta 2 for feedback? I'm sure we only have a handful of testers anyway so lets see if anything blows up for them.

This week I'll take a stab at the last few counter items (Japanese leader HoB menu and maybe that free french stuff) and then I think I'm done with stuff for 6.4.1.

**Comment by zgrose** [comment]
I think I've gotten everything I'm going to do for 6.4.1 into github. If you want to put out a beta3 for the Japanese SMC changes, that'd be great. I believe I've tagged most everything with the 6.4.1 milestone tag.

**Comment by derimmer** [comment]
Since there have been no problems with any of your counter changes, I think we can just go straight to release 6.4.1.  I have a couple of minor code changes that I need to finalize. So, I would hope to release 6.4.1 in the next couple of weeks.
