### ISSUE TITLE
German 5-4-8 AE counter error

### ISSUE THREAD

**Issue by zgrose** [vasl-developers/vasl#441]
Found what I believe is a counter error in VASL. I am using VASL 6.4.1

The German (Wermacht Blue) 5-4-8 Assault Engineer counter in VASL is shown with underlined Morale.

This is incorrect, there is no rule that automatically grants a squad designated as an Assault Engineer underlined Morale. And since the German 5-4-8 squad does not have underlined ML, then it will not have underlined ML as an Assault Engineer.

http://www.gamesquad.com/forums/index.php?threads/german-5-4-8-ae-counter-error.136623/

**Comment by bkemp01** [comment]
this issue also affected German 2-3-8 AE HS

**Comment by bkemp01** [comment]
these also don't have the layers to allow ELR/BH, additional fixes are required
