### ISSUE TITLE
Add LOS data to bdBFP1 and bdBFP2

### ISSUE THREAD

**Issue by BigAl737** [vasl-developers/vasl#445]
These are the missing deluxe ASL boards put out by BFP. The boards are created and I'll upload the files soon. I figured Doug would like to add LOS data before public release.

**Comment by derimmer** [comment]
Happy to do so.

**Comment by derimmer** [comment]
LOS added and everything pushed up to vasl, vasl-boards-extensions, and vasl-website. Will require vasl-6.4.2-beta2 to work.

**Comment by BigAl737** [comment]
Fantastic Doug.

Unfortunately auto LOS checking isn’t displaying properly on BFP1 and BFP2. This may very well have something to do with the mistakes I’ve been making to the metadata files. The metadata files erroneously lists single story bldgs as 1 level. You just taught me this lesson and I didn’t go back and correct my mistake for the BFP boards.

This is not a bigee. If you want, I can fix the metadata files and you can re-run the LOS at some point in the future. Else you can fix the metadata when you update the LOS but I think we might as well wait until we get more feedback on what else doesn’t work on these newly released boards...as if that’s possible :-)

bd79 looks like LOS is working fine. Nice job!

Al

**Comment by derimmer** [comment]
Damn. I didn’t check that before I posted it. There aren’t too many buildings. I can easily correct. Will get to it later tonight/tomorrow.

**Comment by derimmer** [comment]
I have just redone the los and uploaded everything. Bumped the board versions so anyone who has already grabbed BFP1 or BFP2 should get an auto sync. 

 

I ran some tests and it looked good to me. Let me know if you see anything out of wack. 

 

Just a reminder: you need Vasl6.4.2-beta2.vmod to have the los work properly on these boards. 

 

Doug
