### ISSUE TITLE
Add LOS data to bd79

### ISSUE THREAD

**Issue by BigAl737** [vasl-developers/vasl#446]
Hope I'm not keeping you too busy Doug :-)

bd79 files uploaded to vasl/boards/src.

**Comment by derimmer** [comment]
No problem. After all the work you put into RB, I am glad to help. 

 

Are BFPDW1 and 2 also uploaded? Sorry, I did not check, I thought you were still working on them. 

 

I will get to them all very shortly.

**Comment by derimmer** [comment]
Sorry, Al, my mistake. I am with you now. 

 

I have never tried to add LOS to a deluxe sized board. We will see what we will see!

 

I will do 79 first as it should be (grin) straightforward. 

 

Doug

**Comment by derimmer** [comment]
I have added los and pushed changes to vasl, vasl-boards-extensions and vasl-website

**Comment by derimmer** [comment]
Bd79 is live on the website. If someone wants to announce its availability, go ahead.

**Comment by derimmer** [comment]
Al, I have attempted to add LOS to these boards. It is a no go for the moment. 

 

Just as with the BFPDWb boards, each time we add LOS to a board with a new board configuration (size, shape, hex size, board edge changes), we have to make code changes in VASL. While these are not extensive for each new configuration, each addition complexifies the code. At some point, we (me) need to change to code to handle any configuration. 

 

But that is not your problem. I will try to see if I can make the necessary changes quickly and if it works, will put out a 6.4.2beta for testing, along with the los enabled boards. 

 

Doug
