### ISSUE TITLE
VASL6.4.2

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#451]
While we don't seem to have any pressing issues to address, it does feel like we should get 6.4.2 out this spring as there are some minor bug fixes and counter fixes to close out. 

I was thinking of March 1 as a working deadline for changes. If you are working on something that you would like included in 6.4.2, please let me know.

Doug

**Comment by zgrose** [comment]
I have nothing un-committed to the main branch. 

Might be nice to map and fix our Prototype tree, but maybe for a 6.4.3.

**Comment by derimmer** [comment]
Thanks. 

I know nothing about the prototype tree but should probably learn. So, happy to work on this with you. Do you want to create it as a new issue? (for 6.4.3)

**Comment by zgrose** [comment]
Sure, I'll toss something up to remind myself.

**Comment by zgrose** [comment]
#453 for 6.4.2, please.

**Comment by bkemp01** [comment]
#454 & #413

**Comment by bkemp01** [comment]
I think I've got a handle on #441, do we have a new release date in mind?

**Comment by derimmer** [comment]
As per previous, I was just about to issue a last call for changes for 6.4.2, then issue 6.4.2-beta3 on March 1st with 6.4.2 official release planned on or about March 13th. Here is the list of changes that I have for 6.4.2 so far (I have added #441). Strictly speaking, the board changes aren't part of a release but it seemed like a good idea to include the information with the announcement. Let me know if I am missing anything. 

•	Counter Fixes:
o	US M5 76L AT Gun smoke 
o	LVT4 shows 0 armor
o	Chinese FT should have X9
o	German 548 AE error
•	Code Enhancements:
o	Improvements to LOS Thread information label placement so that thread is never obscured.
o	Help text files updated
o	Added Chatter text for Sniper Activation dr
o	Added Chatter text for Booby Traps (players must add booby trap information to Scenario Information (INFO button)
•	Code Bug Fixes:
o	Resolved LOS problem and overlay problem with BFP DW boards
o	LOS checking to and from hex vertices 
•	Board Changes:
o	bd51 steeple on H2 added
o	Added LOS data to bd79 and BFP PiF and ITR2 boards
o	bdv PTO transformation bug fixed
o	bd62 missing Light Woods transformation fixed
o	HS17 Water Foul overlay added to Riley’s Road board

**Comment by derimmer** [comment]
6.4.2-beta3 out on GS and FB

**Comment by bkemp01** [comment]
FYI I didn't finish the commit for #441 until tonight thinking the next beta was to be released 3/1

**Comment by derimmer** [comment]
My fault Brian, I jumped the gun.

**Comment by bkemp01** [comment]
No problem, just wanted you to be aware that it wasn't in there

**Comment by bkemp01** [comment]
#441 needs additional fixes

**Comment by derimmer** [comment]
Will build and issue 6.4.2 on Tuesday. Let me know if there is anything new I can flag in the notice. Of course if you need a day or two more to finish something, I can (and will) wait.

**Comment by bkemp01** [comment]
#303 & #404 have also been committed

**Comment by bkemp01** [comment]
I expect to have the steeple counter finished tonight for #439

________________________________

**Comment by derimmer** [comment]
Just in the nick of time!! Was 30 seconds (literally) from pushing 6.4.2 build to GitHub and the website. No matter, the more changes the better. Getting on a plane tonight so may not have time to get back to this for a day or so. Expect build to go up on VASL.info before the weekend.

**Comment by bkemp01** [comment]
#439 committed

**Comment by derimmer** [comment]
Done and dusted. Live on vasl.info. Messages posted on GS and FB.

**Comment by davidsullivan317** [comment]
Thanks to all for getting this out the door, and to Doug for coordinating
everything. Much appreciated.

**Comment by bkemp01** [comment]
agreed, many thanks Doug

________________________________
