### ISSUE TITLE
LVT4 shows 0 armor

### ISSUE THREAD

**Issue by zgrose** [vasl-developers/vasl#454]
Counter should be 1 / 0?

![lvt4](https://user-images.githubusercontent.com/5044847/35200220-fa8b2224-febe-11e7-86e8-55d1feffff8f.gif)

<img width="418" alt="screen shot 2018-01-21 at 3 22 27 pm" src="https://user-images.githubusercontent.com/5044847/35200221-fcf2d8c2-febe-11e7-85b5-2a3c15a09a01.png">

**Comment by BigAl737** [comment]
It would appear so. Know a good counter guy? 😀

**Comment by bkemp01** [comment]
also applies to the LVT42 variant

**Comment by bkemp01** [comment]
b78f8bea87560fceaab0447af0ce9764ea544334
