### ISSUE TITLE
Where to put the HS Water Foul VASL "board"

### ISSUE THREAD

**Issue by BigAl737** [vasl-developers/vasl#460]
Gents,

It doesn't have a board associated with it so it's not really a BSO. More of a SSO with no board. I'd like to upload it to the VASL website downloads page. Where's the best place? Or if someone wants to upload for me, it's attached below the screenshot. I'll add the source files to VASL/boards/src.

![bdhs17](https://user-images.githubusercontent.com/10384413/35714343-97b69d1e-0778-11e8-8b05-b4cd8c542e01.gif)

[bdHS17.zip](https://github.com/vasl-developers/vasl/files/1687920/bdHS17.zip)

**Comment by bkemp01** [comment]
As far as VASL is concerned it is a board so I would suggest it could go on the "Other Boards & CG Maps" page in the MMP section. I can put it there if you would like.

**Comment by BigAl737** [comment]
Sounds good Brian. Yes please, go ahead an upload it there for me. Thanks.

**Comment by bkemp01** [comment]
added https://github.com/vasl-developers/vasl-website/commit/78f9c4cfe1773080323ab2b57466eb45b61cde45

**Comment by bkemp01** [comment]
included HS17 in the OVHS.zip download
