### ISSUE TITLE
VASLize Deluxe Boards i, j, k, l

### ISSUE THREAD

**Issue by BigAl737** [vasl-developers/vasl#461]
Tuomo has volunteered for this once he gets the go ahead from Ken.

**Comment by BigAl737** [comment]
Just uploaded the WO bds i, J, k, and l to VASL/Boards. Thank you Tom for getting these done so quickly. They need the LOS treatment and then upload to the website at a time when it is agreeable to publicly release these boards. Ken, can you weigh in here and let us know when it's okay to go public? Thanks.

**Comment by derimmer** [comment]
bd files and v5boardVersions (.txt and .xml) uploaded to vasl and vasl-boards-extensions. NO LOS added (yet). There is an issue and I will have to take some time to see if it can be done. But the bd files are in place

As per bd80-83, I have NOT added zip files to the website yet so these boards are not discoverable by users pending Ken or someone's decision to make them so.

**Comment by BigAl737** [comment]
It appears I got these linked and uploaded correctly to the web page however I'm not seeing the version numbers.

![image](https://user-images.githubusercontent.com/10384413/40029986-38627f92-5794-11e8-8222-05c3c58e3390.png)

All boards are v6.0. I did update the json file but I added the boards inline with the other DASL boards. Maybe I should have added them to the end of the json file instead? I'd be glad to fix this myself if someone would please let me know where I went wrong. Else, if someone wants to fix it for me, please do.

**Comment by BigAl737** [comment]
Dang, sorry to make a mess of this.

I see where Sam commented out the board link placeholders.

I think I know how to fix this but please confirm these steps.

Reverse commit the merge with gh-pages that changed the boards.htm file. That should give back the original boards.htm file.
Delete my board links (if they’re still there) and edit out the comment placeholder so Sam’s board links will become active.
Push this boards.htm file to a new branch I’ve already created.
And most importantly, I won’t merge the new branch with gh-pages until someone smarter than me gives me the go ahead.

**Comment by derimmer** [comment]
Once you push the local changes to your github branch I am happy to take a look before you commit to gh-pages but frankly not necessary. And you sure don't need anyone's permission.

**Comment by BigAl737** [comment]
Sam got ‘em for me. Thanks Sam.

I appreciate the instruction Doug.

**Comment by BigAl737** [comment]
There's been no public feedback for these boards so I'll assume they are working well and will close this issue.
