### ISSUE TITLE
VASLize boards 80-83

### ISSUE THREAD

**Issue by BigAl737** [vasl-developers/vasl#462]
These boards from MMPs Forgotten War.

**Comment by BigAl737** [comment]
Tom has 82 done. I'll proof it. Tom is working on 83.
Spencer and myself will work on 80 and 81 as a learning project.

**Comment by derimmer** [comment]
LOS added. Updated board files, bd files and v5boardVersions (.txt and .xml) uploaded to vasl and vasl-boards-extensions.

I have NOT added zip files to the website yet so these boards are not discoverable by users pending Ken or someone's decision to make them so.

**Comment by BigAl737** [comment]
I'm not sure if Ken is on GitHub. I'll email him.

**Comment by Javaslinger** [comment]
I am indeed on GitHub...  This is me incognito.  

I have emailed Chas.  I'll give him a day or two to respond but most likely he won't.  Are we putting up the boards ahead of the counters?

**Comment by Javaslinger** [comment]
As expected, I have not heard from Chas.  I say release the Kraken!  Or the boards in any case...  How far behind are the counters?

**Comment by BigAl737** [comment]
There's been no public feedback for these boards so I'll assume they are working well and will close this issue.
