### ISSUE TITLE
VASLize MMPs Forgotten War counters

### ISSUE THREAD

**Issue by BigAl737** [vasl-developers/vasl#463]

**Comment by BigAl737** [comment]
Here's some samples...

![test scan](https://user-images.githubusercontent.com/10384413/36655870-c769edf2-1a71-11e8-980d-bb93a18875e2.png)
Original Scan

![test-01](https://user-images.githubusercontent.com/10384413/36655873-cd016b78-1a71-11e8-8d97-dbda1e4277ba.png)
Vector generated converted to png

![test-02](https://user-images.githubusercontent.com/10384413/36655876-d0448568-1a71-11e8-90ef-fe1e60fee8e8.png)
Same except slightly shorter text which allows a little more offset from the bottom of the counter.

Comments/Suggestions?

**Comment by BigAl737** [comment]
One more with the MMC graphic a little more aliased.

![test-03](https://user-images.githubusercontent.com/10384413/36674737-686b0d26-1ab3-11e8-8f28-7c75cdfe9b05.png)

**Comment by davidsullivan317** [comment]
I like the original scan image of the soldiers. The other parts of the
counter look better hand-drawn.

But whatever is easiest.

**Comment by BigAl737** [comment]
Thanks Dave. How 'bout this one? It's not quite as dark.

![test-05](https://user-images.githubusercontent.com/10384413/36758847-06ec48d4-1bc2-11e8-928c-d6af41f8120f.png)

**Comment by davidsullivan317** [comment]
![image](https://user-images.githubusercontent.com/5281926/36759294-78ef6744-1bdc-11e8-990f-b5d3f98e3c9d.png)

**Comment by bkemp01** [comment]
looks good Al

________________________________

**Comment by BigAl737** [comment]
I'm gonna get working on this again as time permits. Jackson and Spencer, are you in a place to resume as well?

**Comment by hongkongwargamer** [comment]
As time permits - what else needs to be done?

**Comment by BigAl737** [comment]
I've got to finish the SK and US counters. Spencer was working on the ONC counters. You had the Chinese. Wasn't sure they were all done. I did notice that most of the 5/8" Chinese counters in the Dropbox file were 80px square instead of 60. Some of the 1/2" counters aren't 48x48. If you want to upload the correct sizes as you have time, that would be great. I'm gonna start putting them into a module extension. I figure that by dividing my time between counter making and making the extension, I hope to not get so burned out on this project. That plus my wife is feeling better. Still not out of the woods but the trend has been good so that's helped me pass more life task checks lately :-)

**Comment by hongkongwargamer** [comment]
I thought I corrected them all since you mentioned it last time but I will double check on that.  It's been a while.  

Good to hear that your wife's feeling better.

**Comment by hongkongwargamer** [comment]
Got a few things going on myself.  

- I have a separate folder with 60x60 (version) of the counters
- I checked and found 3 of the 48x48 counters are not 48x48... will have them fixed.

**Comment by BigAl737** [comment]
Hi Jack. Great to hear. I'm making headway too. About a half dozen more South Korean counters to go. Then a few US and I think we are mostly done :-)

To you VASL headmasters...I'm gonna start on incorporating these KFW counters into the VASL module. I'd like to create an extension first to work out the bugs. Then I assume it's easy enough to import the extension into core module. Correct? Any suggestions on a better path to follow? Thanks.

**Comment by davidsullivan317** [comment]
I don't think there's a way to merge an extension into the main module. I'd recommend adding the counters to the latest version of VASL.

**Comment by BigAl737** [comment]
Got ya David. However, since this is a sizeable addition...

What does the brain trust think about making KFW a stand alone extension? Is the core VASL module getting too big that it's getting unwieldy? Is KFW unique enough to warrant it as such? 

Pros as I see them..
future updates and corrections are easier to make
I know how to create an extension
doesn't add to the core modules' size and complexity
future updates to the core module won't affect the extension...once it's working, it stays working

Cons...
updates to core module prototype definitions won't update the extension
???

I'm thinking an extension is the way to go but I defer to the consensus of this august body.

If we go this route, what's the best way to have the extension interact with the core? Should it be a stand alone KFW tab within the counters menu, or an intermix of the KFW counters with the existing tabs as appropriate, a combination of such, or some other option?

Counters are getting pretty close to being finished. It's time to address this question. Thanks!

**Comment by derimmer** [comment]
I have no worries about the size of the VASL module. I worry about a proliferation of extensions, which for some reason give me more grief than they should. KFW feels core to me.

**Comment by BigAl737** [comment]
I respect your opinion Doug. Anyone else?

And I realized that if KFW goes core, there are still the same interface issues to address. Looking for advice on that too.

**Comment by zgrose** [comment]
I don't have KFW so I don't know how much overlap there is, but at first blush I'd put all the Korea stuff into a Korea tab. Unless a KFW scenario uses older counters, it's nice (to me) to have a single starting point for WW2 vs KW counters because who wants to deal with all the out-of-scope counters.

Re extension vs core, extensions are nice because they allow one to quickly distribute updates without too many side-effects. Core changes means one has to be on top of their Git branches.

**Comment by BigAl737** [comment]
Thanks David and Zoltan.

I been studying to see how to add the needed tabs, images, counter traits, etc to the buildfile. Editing the buildfile itself for a project this big looks to be insane. It looks like I can locally edit the VASL 6.4.3 module on my computer, then upload the build and image file to a temporary branch in the VASL repository. Then I think you guys can see what I'm doing and make suggestions/corrections.

Am I thinking along the right track?

**Comment by davidsullivan317** [comment]
Doug and I chatted on this yesterday. To minimize the pain here's what we
suggest:

Go ahead and create an extension like you'd suggested. With HP there were a
number of issues that needed to be fixed once the counters hit the street.
Using an extension will make the find-fix-retest cycle and your life a lot
easier.

Once the counter set is stable a developer can merge it into core VASL in
the next release. You can ignore that part.

Hopefully that's the best of both worlds.

**Comment by BigAl737** [comment]
Indeed it is David. I'll get started right away. I'll use this thread for posting draft extensions.

**Comment by BigAl737** [comment]
I'm having trouble to get concealed South Korean units to show the correct concealment marker. The associated expanded windows are shown below. The skGUN (KFW) prototype is simply a straight copy, paste and renamed amGun prototype. I can change the marker from the am version (shown) to a sk version I've created with no problem. I think the issue is the reference to nationality. Is this a VASL specific java add on feature of some sort? If so how do I access it to define the sk nationality so VASL will recognize it? Thanks.

![image](https://user-images.githubusercontent.com/10384413/49040199-5c2dc480-f16e-11e8-9cf6-d9de6a0ab58d.png)

**Comment by zgrose** [comment]
I think you just type `sk` in Nationality. I see in the Is Concealment Counter trait a reference to the country code as well (see image). Lastly, there is a bug/comment I had a while ago that VAS(SA)L is assuming the .gif isn't in the concealment counter name so you have to go into the build.xml and cut out the `.gif` part for it to pickup the reference properly (or the code has to be tweaked).

Hopefully enough info to get it sorted out?

<img width="772" alt="screen shot 2018-11-26 at 3 03 45 pm" src="https://user-images.githubusercontent.com/5044847/49042094-b50c5580-f18c-11e8-8b1e-e9bd77a67650.png">

**Comment by BigAl737** [comment]
Thx Zoltan. I made the changes to the sk concealment counter and the 5/8" SK counter that you see in the screens below. Started a game and tried to conceal the 5/8" SK counter and got the attached VASSAL bug file. The 5/8" SK piece is a direct copy of the 5/8" AM piece with the exception of a modified Arrow layer that allows the arrow to be (de)selected. I don't think that has a bearing on the concealment issue.

![image](https://user-images.githubusercontent.com/10384413/49050552-619c0680-f190-11e8-9fd9-f4dfef6af1cc.png)

![image](https://user-images.githubusercontent.com/10384413/49050470-fce0ac00-f18f-11e8-9e42-410d3862b34f.png)

![image](https://user-images.githubusercontent.com/10384413/49050520-31546800-f190-11e8-913a-6466e11ab7e4.png)

[SK Concealment Bug Report.txt](https://github.com/vasl-developers/vasl/files/2617827/SK.Concealment.Bug.Report.txt)

**Comment by zgrose** [comment]
Not in a position to help much at the moment other than to say look in Concealable.java line 306 (snipped below). Looks like it's expecting sk/skqmarkme.gif all lower-case and didn't find it so started trying to build its own?

````
if (concealedToOthers == null) {
      try {
        concealedToOthers = Op.load(nation + "/" + nation + "qmarkme.gif").getImage(null);
      }
      catch (Exception ex) {
        // Using generic qmarkme.gif image and prefs-specified colors
        int size = imageSize.width;
        BufferedImage rev = new BufferedImage(size, size, BufferedImage.TYPE_4BYTE_ABGR);
        Graphics2D g = rev.createGraphics();
        g.drawString("?", 0, 0);
        concealedToOthers = rev;
      }
    }
````

````
java.lang.IllegalArgumentException: Width (-1) and height (-1) must be > 0
	at java.awt.image.SampleModel.<init>(Unknown Source) ~[na:1.8.0_60]
	at java.awt.image.ComponentSampleModel.<init>(Unknown Source) ~[na:1.8.0_60]
	at java.awt.image.PixelInterleavedSampleModel.<init>(Unknown Source) ~[na:1.8.0_60]
	at java.awt.image.Raster.createInterleavedRaster(Unknown Source) ~[na:1.8.0_60]
	at java.awt.image.Raster.createInterleavedRaster(Unknown Source) ~[na:1.8.0_60]
	at java.awt.image.BufferedImage.<init>(Unknown Source) ~[na:1.8.0_60]
	at VASL.counters.Concealable.loadImages(Concealable.java:311) ~[na:na]
	at VASL.counters.Concealable.drawObscuredToOthers(Concealable.java:113) ~[na:na]
````

**Comment by BigAl737** [comment]
Git Hub search is wonderful. I found this... #306

**Comment by BigAl737** [comment]
Alrighty guys. The big shake up here shook some understanding into me and I solved the issue. Well Zoltan and the linked issue above helped too so thanks!

I went into the build file and manually changed all the skqmark.gif instances to drop the file extension (renamed to skqmark). You also have to add a nationality folder within the images folder (in my case it's named sk) and copy the skqmark.gif images to that folder. After several trial and errors, VASL returned this gem:

![image](https://user-images.githubusercontent.com/10384413/49399590-2482c780-f6ee-11e8-9c80-f36c29ad6d55.png)

Thanks for the help guys. I'll keep pushing forward with this extension.

It'd be nice to change the code so you don't have to manually edit the build file but then I'd bet we'd have to re-append the .gif file extension to the qmark's of all nationalities. Code change is above my pay grade. Just happy to keep going on this extension right now.

Al

**Comment by Javaslinger** [comment]
Nice!  I'm glad this issue has been worked out at last!
    On Monday, December 3, 2018, 3:35:33 PM EST, Allan Cannamore <notifications@github.com> wrote:  
 
 
Alrighty guys. The big shake up here shook some understanding into me and I solved the issue. Well Zoltan and the linked issue above helped too so thanks!

I went into the build file and manually changed all the skqmark.gif instances to drop the file extension (renamed to skqmark). You also have to add a nationality folder within the images folder (in my case it's named sk) and copy the skqmark.gif images to that folder. After several trial and errors, VASL returned this gem:



Thanks for the help guys. I'll keep pushing forward with this extension.

It'd be nice to change the code so you don't have to manually edit the build file but then I'd bet we'd have to re-append the .gif file extension to the qmark's of all nationalities. Code change is above my pay grade. Just happy to keep going on this extension right now.

Al

**Comment by BigAl737** [comment]
Can someone please enlighten me on the coding for the Turreted trait? I'm thinking it's the best trait to use for searchlight arcs but am trying to grok how it works. Thanks very much.

![image](https://user-images.githubusercontent.com/10384413/49907826-5994c580-fe24-11e8-8191-73cafc2c30db.png)

**Comment by bkemp01** [comment]
Al, if I recall the KWASL playtest extension had a good solution for the searchlights. Let me know if you need a copy of that.

**Comment by BigAl737** [comment]
Thanks Brian. I found it on my computer. Completely forgot we had this resource.

**Comment by BigAl737** [comment]
After a break, my burnout from working on this has cooled and I’m gonna git ‘er done. 

Is it still the intent to roll this into the core VASL module?

I ask because I can add the VASL core units that are used in KFW to the extension which will make a stand alone extension a little easier for players to use. Not worth doing if it won’t be stand alone.

**Comment by derimmer** [comment]
Al, as far as I know it is still the intent to roll KFW into the core VASL module once the inevitable bugs have been sorted out. So the extension would be a short-term thing to make debugging easier. Does that give you what you need to know? More importantly, does it make sense to you?

The above is more of a guideline than a rule. Our VASL group is entirely self-governing!

**Comment by BigAl737** [comment]
Thanks Doug. I'll create accordingly.

**Comment by BigAl737** [comment]
Just the Chinese to go. Then a lot of clean up and testing. Getting there. I'd say May for public release.

I'd recommend releasing it publicly as an extension. I'm sure they'll find some bugs. Once stable, then we can incorporate in VASL proper. Of course, that will probably induce some more bugs. It's good to have job security :-)

**Comment by BigAl737** [comment]
Ready for testing. I'm closing this issue and opening another for testing feedback.
