### ISSUE TITLE
Update colors file

### ISSUE THREAD

**Issue by BigAl737** [vasl-developers/vasl#467]
I wanted to capture this before it gets lost.

Tom discovered a couple of color issues while working on the KFW geo boards.

Change L5 winter color to 125,105,73
Change L4 OG color to 145,122,85

Chime in Tom if I got those wrong. Will changing the L4 OG color affect other boards with L4 hexes?

**Comment by davidsullivan317** [comment]
These values have been propagated to all of the boards for the most part. I'd recommend only changing them where needed.

**Comment by derimmer** [comment]
Someone (Brian Kemp if I recall) recently pointed out that the colors and colorsSSR files were out of date and provided updated ones. I have pushed those up to VASL/develop on GitHub where they sit in the vasl/dist/boardData directory.

My understanding is that all this does is provide a bit of reference point for the latest versions. The colors and colorsSSR file only have effect when they are contained within a bdXX file. And they must be contained within such a board file as per the instructions on the GitHub VASL wiki for making and updating VASL boards. 

I don’t know how this relates to the issue that Al raised but I thought I would mention it for completeness sake.

**Comment by bkemp01** [comment]
Maybe those files should be bumped to include these latest recommended
changes? Although I'm not certain of impact. My understanding has been that
whenever a bdxx archive contains a colors or colorSSR file it takes
precedence over the baked in copy in VASL so the only time the baked in
copy would come into play is the bdxx archive doesn't have it's own local
copy which seems like a rare thing these days.

**Comment by davidsullivan317** [comment]
The values in the colors/colorSSR files in the boards supersedes the values in the vasl/dist/boardData directory. I.e. if a value is missing in the board file it is still picked up in the global file. So we should keep the later up to date, just in case.

**Comment by derimmer** [comment]
I have updated 8 other board archive files that had level 4 and 5 terrain with these new colors plus the colors file in the VASL /boardData folder.

I have bumped the version numbers.
