### ISSUE TITLE
HIP bug

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#468]
The problem is as follows: 
-	your opponent moves a stack onto  one of your HIP counters such as a minefield;
-	no portion of your HIP counter will be visible below the opponent’s stack; the HIP counter will not be offset the way a known fortification counter  would be; 
-	if you then double click his stack to expand it so that you can select your HIP counter, it will not be part of the expanded stack; 
-	the only way to make your HIP counter display in the stack is for you to drag your opponent’s counters around (sometimes right out of the hex and back in, sometimes less)

Extensive investigation of this issue indicates that it is caused by VASSAL's treatment of HIPsters. A solution to extend the VASSAL classes involved as VASL classes seems overlay complex and likely to produce other errors. 

Logging the bug but suggestion no action at this time.

**Comment by zgrose** [comment]
duplicate of #459

**Comment by derimmer** [comment]
Linked but not entirely the same, IMHO. This bug is related to what the owner of the HIP counter sees and is able to do with his counter when covered by enemy units. #459 is what the enemy player sees when the owner of the HIP counter tries to manipulate it in some while it is covered by the enemy's units. Two sides of the same coin but different sides all the same.

However, I suspect the cause and therefore the solution to #459 also lies within VASSAL.

**Comment by zgrose** [comment]
True enough. I suspect HIPsters not glomming onto a stack as a stack moves through it is probably a Good Thing that we wouldn't want to accidentally break. So your final suggestion is probably the best. :)

**Comment by derimmer** [comment]
I am going to close this issue as per the above discussion and also #459
