### ISSUE TITLE
BFP ITR2 Board B needs an update

### ISSUE THREAD

**Issue by styson** [vasl-developers/vasl#474]
http://www.gamesquad.com/forums/index.php?threads/bfp-b-board-itr1-vs-itr-2.146635/post-1921343

![image](https://user-images.githubusercontent.com/178219/37355742-75114fda-26b2-11e8-96e2-3c485e2e6702.png)

**Comment by BigAl737** [comment]
I'm not seeing the .psd or GIMP graphic file that was used to convert this board to VASL in the vasl/boards/src folder. Can someone post it? If not, Sam, can you post the terrain layered printer files?

**Comment by derimmer** [comment]
Al, once you get this done, I would be happy to update the LOS for the board. Since U2 will now be a factory we need to update the LOS data to remove levels, etc. Should not take long.

**Comment by styson** [comment]
I asked Rick for the layered printer files.
