### ISSUE TITLE
Sewer counters Ctrl-L "Lost" not working properly

### ISSUE THREAD

**Issue by bkemp01** [vasl-developers/vasl#478]
Posted via GS...

Hi all, noticed a challenge with the sewer counters. When a unit gets lost, it is tricky getting to the "lost" sewer counter. What we found to work was Ctrl "L" activates the label portion of the counter, but afterwards it will show as the correct "Lost" counter. V

http://www.gamesquad.com/forums/index.php?threads/vasl-map-online-problem-suggestion-form.88223/post-1923099

Yes, something seems screwy. As if there's a "Ctrl-L" for "Lost" that's being hidden by the "Ctrl-L" for "Label". Ctrl-E for "Emerge" will cycle through the various options, but will never cycle to or from the "Lost" counter.

It would be better I think to have a "Ctrl-F" "Flip" option to change between the "Sewer" and "Lost" faces.

http://www.gamesquad.com/forums/index.php?threads/vasl-map-online-problem-suggestion-form.88223/post-1923186

**Comment by derimmer** [comment]
This was repeated as issue #803 and has been fixed in 6.6.4.
