### ISSUE TITLE
check all boards for Light Woods transforms

### ISSUE THREAD

**Issue by bkemp01** [vasl-developers/vasl#479]
KW terrain (W.3) specifies all Woods are Light Woods. We should check/update all boards to include the Light Woods overlays & BoardMetadata.xml/overlaySSR files.

**Comment by BigAl737** [comment]
I’ve done this check and all boards up thru 79 have it. Not all boards have been updated and posted for public release however. Which ones, I don’t know. I’d suggest checking the boards used in the KFW scenarios first. The rest we can update and post as required.

I’ll take care of the overlays in the overlay extension. Again, I need to see if any woods overlays are used in the KFW scenarios. I’ll do those first. The rest I’ll get to as time permits.

Al

**Comment by derimmer** [comment]
I am happy to help with board updating and posting. 

If I understand correctly, all boards up to 79 contain Light Woods overlays, a BoardMetadata.xml file and an overlaySSR file. Am I right, or left?

What needs to be done next is to:
1. ensure that the board version in BoardMetadata.xml has been bumped. (and update the v5boardVersions.txt file in the VASL module accordingly).

2. Push changes to vasl and vasl-boards-extensions on GitHub

3. Create new zip files for each board and then push the updated board to vasl-website on GitHub while also updating the versions.json file with the new board numbers (which will make the new boards available on VASL.info for downloading and synching. 

Am I missing anything? There may be other changes that need to be made to BoardMetaData.xml for each board?

I would be willing to do groups of 10 at a time.

**Comment by BigAl737** [comment]
You are spot on Doug. If you want to push the wayward boards then please do so. I don’t know which have been pushed and which haven’t. I believe it’s about 50/50. I can check the boards for you if you’d like but I’ll wait to see if that is indeed needed. It would take about an hour I’m guessing for me to do. Don’t mind doing that at all. Just let me know.

Al

**Comment by derimmer** [comment]
This work appeals to the inner pedant in me. Let me do boards 1-10 and then we can see where we're at.

**Comment by derimmer** [comment]
Brian, I should have realized that you opened this issue - if you were planning to do the work, I am happy to step back.

**Comment by bkemp01** [comment]
You are perfectly welcome to tackle this. A few things I would check...

1. does the light woods overlay gif file exist?
2. has light woods been added to boardmetadata.xml?
3 has light woods been added to overlaySSR?

I have noticed some drift in the creation of the light woods overlays... some need to be placed at coord 1,1 and some need to be placed at coord 0,0. I suppose checking the dimensions of the overlay gif file would show which was used... if 1800x645 then use coord 0,0 or if 1798x643 then use coord 1,1.

Then there is the issue of figuring out whether the changes and updated board versions have already been pushed to the vasl-boards-extensions and vasl-website.

If we plan to continue the practice of queuing up board changes without releasing them we should come up with a way to track those changes and which board version they are or will be released in. Sort of like we do with VASL releases and milestones to keep track of which fixes the next version will contain.

Thanks

**Comment by derimmer** [comment]
Good points. I noticed when I rummaged around in bd1-10 this morning that in some cases, changes had been made and pushed to vasl-boards-extensions and vasl-website but the source files in vasl on GitHub had not been updated. 

Regarding your last point, my preference is that anytime a board is changed, the changes should be pushed to vasl, vasl-boards-extensions and vasl-website. But, failing that, I agree that some way to track changes would be necessary.

**Comment by davidsullivan317** [comment]
>  changes had been made and pushed to vasl-boards-extensions and
vasl-website but the source files in vasl on GitHub had not been updated.

Yikes. That's not good. Maybe it's time to automate the updates to vasl.info
and vasl-boards-extensions so they are always created by the board builder.

Is the vasl-boards-extension repository used for anything other than board
updates? Maybe it's time to sunset that. It's a pain to update anyway.

-Sully

**Comment by bkemp01** [comment]
I think there was concern about a mass board update causing everyone to auto download every board so I think the idea was to prep some changes and either wait for a specific request or some other fix to trigger pushing the updates.

Isn’t vasl-boards-extensions where the auto board update mechanism checks versions and downloads updates from?

**Comment by BigAl737** [comment]
Before Korea, light woods SSRs were practically non existent. Lightwoods updating of all the boards before Korea was not a high priority. I took on that project though and with help, created a light woods transform and associated files for every board. Within the last 6 months, I’ve checked every board to ensure the proper files were modified so that the next time the board required an update, lightwoods would be included.

Brian is right in the reasoning for my not doing a mass board update at the time. But, bam, Korea arrives and now here we are. Though even now, how many boards are used in the Korea scenarios? I haven’t had time to check but it wouldn’t take me long to do so once I’ve got some time this weekend. I just don’t want us duplicating our efforts. 

So, unless someone calls me off, I will check the Korea FW geos this weekend. I’ll push the ones I find that haven’t been posted yet.

The other boards can wait for now. I will get to these ASAP.

Al

Sent from my iPad

**Comment by derimmer** [comment]
Yesterday, I checked the following board files in the vasl repository on GitHub: 1, 1a, 1b, 2, 2a, 2b, 3, 3a, 3b. I also opened each of these boards in VASL and applied the Light Woods transform to see which released boards are allowing LW. 

bd03 required no change.
bd01, bd1a, bd1b were all missing a LW reference in overlaysSSR. 
all the boards, except bd02 and bd03, will need a version bump to trigger the LW transform. 

The LW transformation is working on released boards bd02, bd03, reflecting the strategy of have the transform take effect the next time the board was updated. Both of these boards have been updated recently. 

Al, I am with you on not duplicating work. You have already put a lot of time in this and I certainly don't want to redo or overwrite anything that you have done. So, have at it and I will hold on anything further - but know that you can call on me at any time. 

Bear in mind that changes need to be pushed to all three repositories in GitHub.

**Comment by BigAl737** [comment]
All MMP produced numbered geo boards hae a LightWoods.gif file and associated reference in the BoardMetadata file. Some of these boards were missing the lightwoods reference in the overlaySSR file. I believe all overlaySSR files have been superseded by the BoardMetadata.xml files. If so the overlaySSR file is antiquated and probably should be deleted. Just to be safe though, I went back and added a lightwoods reference in the overlaySSR file for those boards missing this. Push coming soon. After that, I'll compile and push the boards that haven't updated since my lightwoods addition.

**Comment by BigAl737** [comment]
Like the overlaySSR file, I think the data file has been replaced by the BoardMetadata.xml file as well. I'll take a chance and assume that the time I'd spend updating the version number in the data file is a waste of time. I'm only pushing board 1 at this time so if I'm wrong, it shouldn't be too hard to fix...I hope.

Just pushed board 1. I don't think the version number in the vasl-website/boards/versions.json needs to be updated either. I did update it this time but is that still required?

**Comment by derimmer** [comment]
Al, yes as far as I know it is necessary to update the versions.json file. I continue to do so at any rate.

**Comment by zgrose** [comment]
I believe it it read by the website to put the version number on the page so people can see what they are downloading. Almost obsolete with the auto downloader but still in use.

**Comment by davidsullivan317** [comment]
Both the overlaySSR  and the data file should be deprecated by now. I'd be
curious if the website is using them. But even if so it should be fairly
simple to switch it to read the boardMetadata file.

-Sully

**Comment by BigAl737** [comment]
Well the updated board never showed up on the website. I've just done another push with an updated data file. Let's see if that works. bd01 should be v6.1.

**Comment by BigAl737** [comment]
bd01 isn't updating on the website to v6.1. Maybe the site is tired like me. I'll check it in the morning.

**Comment by derimmer** [comment]
Al, did not auto sync for me this morning either. I checked the vasl repository on Github and the v5boardVersions.txt file in the boards folder still shows bd01 as 6.0. Pretty sure that it must be updated to 6.1 for auto syncing to work.

**Comment by derimmer** [comment]
I downloaded the file from the website, unzipped it into my boards folder and opened it in VASL. VASL says v6.0 so no joy that way.

**Comment by BigAl737** [comment]
As you can see I updated the v5boardVersions.txt file and still no joy. Doug, you're right. bd01.zip is not updating on vasl-website/boards but I did push it there (commit 1fc459c). I did another pull to re-sync my repository and now it says I merged something and wants me to push 6 files. I don't want to make matters worse so I didn't push those files. I'm tempted to delete my local vasl-website repository and start over again. I used to be able to push boards no problem. Don't know what changed. Here's a screen that may be of help to somebody. I'm about ready to chop down SourceTree and I know it's my fault.

![image](https://user-images.githubusercontent.com/10384413/37876229-f362372c-2ff5-11e8-8a7e-3bd60b9eb5f6.png)

**Comment by derimmer** [comment]
Hi Al, just checked the website and after I merged the commits, bd01 v6.1 is live! I opened a game with bd01 on my local device and autosync worked. I tested the LW transform and all is good.

I think in this instance, you pushed the commits up to a branch but did not merge the branch into the master (gh-pages), which is the final, final step in the process. Or else the initial merge failed for some reason.

**Comment by BigAl737** [comment]
Thank you thank you thank you :-)

I’ll try my luck with another board soon.

How’d your game go?

**Comment by BigAl737** [comment]
With Doug's tutelage (thank you Doug), I've pushed new versions of bds 04, 08, and 11. Before I get too far in this process, I'll make sure someone else can download these boards and apply the Lightwoods transformation. Thanks.

**Comment by derimmer** [comment]
I just checked bd04, autosynced perfectly and LW transformation worked.

**Comment by BigAl737** [comment]
Okay cool. Thx. It seems when I push the updated bdXX.zip and versions.json files to vasl-website/boards, I have to push twice, once to origin/feature/websiteboardsupdate and again to origin/gh-pages to make the board update on the website. I'm not messing anything up, right? Do I need to push twice?

**Comment by derimmer** [comment]
I am not sure what you mean by push twice. If you mean push from your local computer, then no. You push once from your local computer to the feature/websiteboardsupdate branch using sourcetree. Then, from within Github, you merge the stuff you just pushed to feature/websiteboardsupdate into gh-pages.  To do this, in the github vasl-website repository, select the feature/websiteboardsupdate branch from the dropdown in the top left hand corner where it says "Branch". Then click on Pull Request on the right hand side. It will tell you if you can do the merge and will show a green button, saying something like Merge. Click this and you will get another screen with a similar option and then I think a third before you finally complete the merge. 

Pushing files directly to gh-pages from sourcetree will have the same effect but is not recommend (in fairly strong terms) for a bunch of reasons relating to managing repositories, most of which is beyond my understanding but I take the advice of others that this is really not a good way to do it.

**Comment by BigAl737** [comment]
Great explanation Doug. I did a bad thing pushing from within SourceTree to gh-pages. I've never done a pull request on the GitHub itself but I'll start from here. Your instructions seem very clear but then I'm not the sharpest tack on the wall. Thank you very much for your patience :-) I'll go try a board now...

**Comment by BigAl737** [comment]
GitHub says my pull request successfully merged commit 17dc2e8 into gh-pages. I'm waiting for the website to update bd24 to v6.5. That probably takes a few minutes. GitHub says the feature/websiteboardsupdate branch can be safely deleted with a big 'ol button just daring me to click on it. I probably shouldn't, right?

**Comment by derimmer** [comment]
I'll be online for a while if you need help within github.

**Comment by derimmer** [comment]
Correct, if you are going to keep adding boards, wait till you are finished before deleting the branch.

**Comment by derimmer** [comment]
I see bd24 v6.5 on vasl.info but I am not getting an auto sync when I open a game. You seem to have updated vasl-boards-extensions and vasl so not sure why. Sometimes it just takes a bit of time. Off-line now.

**Comment by BigAl737** [comment]
Have a good night Doug. Just opened bd24 within VASL and it auto-updated to v6.5 and the LW transform worked. Thanks again for you help.

**Comment by derimmer** [comment]
Cooking with gas, Al!

**Comment by BigAl737** [comment]
That cracked me up :-) I am now a board updating machine and I have you to thank. All the KFW scenario geos are done. Working my way through the others as time permits.

**Comment by derimmer** [comment]
Kudos to Al for an extensive piece of work. 

I will do a quick check of version numbers against the new v5boardversions.xml file since Sam now has VASL.info pointing to it.
