### ISSUE TITLE
PB British 458 counter

### ISSUE THREAD

**Issue by BigAl737** [vasl-developers/vasl#494]
Update requested for Pegasus Bridge British 458 counter.

[http://www.gamesquad.com/forums/index.php?threads/pegasus-bridge-458-airborne-counters-please.147457/post-1931022](url)

edit: see the second post of the thread for an issue with the ABtF British 648s.

**Comment by BigAl737** [comment]
From GS: "VASL has 648 counters for the British Airborne units in the "Pegasus Bridge" module but there are no 458 Airborne counters with the logo and underlined Morale."

I can look at this in early March.

**Comment by BigAl737** [comment]
I think it's best to add this ![br458spara](https://user-images.githubusercontent.com/10384413/53833985-5ba78580-3f36-11e9-90cd-468b5e24d80f.gif) here:

![image](https://user-images.githubusercontent.com/10384413/53834026-7aa61780-3f36-11e9-8a78-6a3f47df7558.png)

![br458spara](https://user-images.githubusercontent.com/10384413/53833985-5ba78580-3f36-11e9-90cd-468b5e24d80f.gif)

and this ![br248hpara](https://user-images.githubusercontent.com/10384413/53833992-5f3b0c80-3f36-11e9-9634-aeeda7121f8a.gif) here:

![image](https://user-images.githubusercontent.com/10384413/53834087-9e695d80-3f36-11e9-8eb0-84e2a76f102c.png)


![br248hpara](https://user-images.githubusercontent.com/10384413/53833992-5f3b0c80-3f36-11e9-9634-aeeda7121f8a.gif)

**Comment by derimmer** [comment]
Al, these are new units which i am happy to push up to develop. In order to do so, I need the lines from the buildfile that should apply to them. Did you create these within a VASL module on your local drive. If so, please look for them in the buildfile and copy-paste the buildfile lines to me. Thanks.

**Comment by BigAl737** [comment]
I just did the art. I'll get the buildfile lines for you asap. I'll post them here.

**Comment by BigAl737** [comment]
Emailed to lines to you Doug.
