### ISSUE TITLE
RBv2 Overlays not working

### ISSUE THREAD

**Issue by BigAl737** [vasl-developers/vasl#495]
[http://www.gamesquad.com/forums/index.php?threads/rbv2-map-transformations-not-working.147441/post-1930802](url)

I've identified the problem and a fix is in the works. As a side note, enabling even one of the RB SSR transformations disables the LOS engine for the entire map. If the transformation was treated as a drag and drop overlay instead, I believe the LOS engine would only be disabled for that portion of the map covered by the overlay. Maybe this justifies treating future SSRs and BSOs transformations as drag and drop overlays. Just a thought.

**Comment by BigAl737** [comment]
All files and folders with the exception of src have disappeared from my cloned vasl local repository and I can't update the bdRBv2 file to version 2.4 in the v5boardsVersions.txt and .xml files. Can someone do that for me please? Thanks.

![image](https://user-images.githubusercontent.com/10384413/40373758-16e09560-5d94-11e8-86c8-4803365b6e90.png)

I've also lost all the BoardMetadata files that were in each of the individual board folders as well. Re-cloning hasn't helped.

**Comment by derimmer** [comment]
Hi Al 

I will look after this. See my longer message to you re SourceTree/GitHub issues in general.

Doug

**Comment by derimmer** [comment]
Done

**Comment by BigAl737** [comment]
The terrain transform issue is fixed but I'll leave this thread open for comment on the following (if any). If the following is not of concern at this time, I'll close this issue in about a week.

From the first post in this thread:

_As a side note, enabling even one of the RB SSR transformations disables the LOS engine for the entire map. If the transformation was treated as a drag and drop overlay instead, I believe the LOS engine would only be disabled for that portion of the map covered by the overlay. Maybe this justifies treating future SSRs and BSOs transformations as drag and drop overlays. Just a thought._

An additional thought...maybe the RBv2 LOS coding could/should be updated to only disable itself when it interacts with an overlay.

**Comment by derimmer** [comment]
My early exploration suggests that this problem is due to the fact that there is no terraintype in the SharedBoardMetaData file for gutted buildings. As far as I can see all of the RB SSR transformations relate to turning buildings into gutted buildings. Non-RB SSR transformations, such as walls to open ground, work on the RB map without disabling LOS. I don't see why the SSR transformations should not. 

Need to create the gutted building types in any event for the day when we apply the LOS engine to VotG. 

I need to explore exactly how all this happens but I think I am on the right track here.  I would suggest leaving transformations as they are until I see if I can make progress.

**Comment by BigAl737** [comment]
Hi Doug, where are you at with this?

**Comment by derimmer** [comment]
Hi Al

This is the text I included about this issue when I posted vasl6.4.3-beta2 on FB and GS:

Red Barricades BSO overlays work with LOS. We received a request to see if we could get Board Specific Overlays (those added by clicking on the Terrain SSR button and then selecting “bdXX special overlays” or “bdXX Terrain Transformations”), to work with the LOS Engine on the Red Barricades Map. Success! We then tried to apply a more generalized solution that would work for all los-enabled boards. Fail. So, the RB fixes are in but that’s all.

I ran into some significant issues when I tried to develop a broader solution; much of which had to do with the use of transparent and non-transparent pixels in the overlay .gifs. Too much effort for too little gain was my conclusion. Perhaps a better coder could find a way but I could not.

**Comment by BigAl737** [comment]
Ah yes. I remember that now. Thanks for the reminder.

**Comment by BigAl737** [comment]
Can I close this?

**Comment by derimmer** [comment]
@BigAl737  Just closed it. Thanks.
