### ISSUE TITLE
Add "put in casualties bin" in addition to "delete"

### ISSUE THREAD

**Issue by jrvjrv** [vasl-developers/vasl#499]
All sides should get a "casualties bin" (a separate window?) where units/weapons that are eliminated can be put. In addition to a command for deleting counters, a separate command will remove them from the board and put them in the casualties bin.

**Comment by derimmer** [comment]
I am working on this casualties bin. I am able to calculate CVP for infantry quite easily by using the counter's name. It appears that all squads include "sq" in their name; half-squads include "hs", heros include "Hero". Then for leaders I can parse their name (6+1, 8-0, 9-2) to determine their CVP. It seems to work, although I still have to sort out wounded leaders. 

Two questions:

Are there squad, hs, hero or leader counters that don't follow this nomenclature?
Are their other kinds of infantry units that use different names?

As for vehicles, I am thinking of requiring players to enter a CVP for them when they are in the Casualties Bin. Seems the easiest way to handle it. What do you think?

**Comment by zgrose** [comment]
The unit names won’t help you a CR a squad into a HS though since most counters are made with layers? Just a guess though.

**Comment by davidsullivan317** [comment]
The layers are named and follow the pattern mentioned in Doug's post. Obviously, it would need to be thoroughly tested. 
![image](https://user-images.githubusercontent.com/5281926/61318762-69fe8b80-a7cb-11e9-8d5e-82d5181e1427.png)

**Comment by derimmer** [comment]
For the CR situation my current thought is three mouse actions:
1. Right click, select Sqd/HS.
2. Right click on the new HS counter, select Clone
3. Right click on the new Cloned HS, select Send to Casualties Bin.

A bit clunky but it will result in the right counters being in the right place. 

A slightly better workflow would exists for destroyed vehicles: clone the vehicle, send the clone to the Casualties Bin, Wreck the vehicle. 

It might be possible to combine some of these steps into a single popup menu choice but then it would lengthen the popup menu (or require submenus) which may be just as bothersome for users.

**Comment by hongkongwargamer** [comment]
> I am working on this casualties bin. I am able to calculate CVP for infantry quite easily by using the counter's name. It appears that all squads include "sq" in their name; half-squads include "hs", heros include "Hero". Then for leaders I can parse their name (6+1, 8-0, 9-2) to determine their CVP. It seems to work, although I still have to sort out wounded leaders.
> 
> Two questions:
> 
> Are there squad, hs, hero or leader counters that don't follow this nomenclature?
> Are their other kinds of infantry units that use different names?
> 
> As for vehicles, I am thinking of requiring players to enter a CVP for them when they are in the Casualties Bin. Seems the easiest way to handle it. What do you think?

Vehicles / Guns / Aircraft

While allowing user to put in the CVP, can we put in a default value?  
- Aircraft & Guns 2VP
- Vehicle 1VP (+Wagon/sledge but exclude other white counters)

User will then have to "add" 1 for MA, 1 for AF(5) & 2 for the crew

**Comment by derimmer** [comment]
@hongkongwargamer  Guns should be as simple as infantry. Aren't they always 2? (I note a Desert Scenario exception). Same for planes. 

Vehicles are the tricky one. Sure I can include a default value but I am not sure it helps much. Prisoners will need to be added as well. They should be simple.

**Comment by hongkongwargamer** [comment]
Yeah .. I shouldn't lump Guns with Vehicles.. esp when I meant to say "don't forget Guns".  Good point on Vehicles.  Happy with an User Entry.

**Comment by BigAl737** [comment]
While auto tallying of CVPs sounds cool it does increase the chance of errors because of the behind the scenes automation. I would simply add a Casualty Bin map window and let players sort it out from there. ASL is a contact sport after all :-)

However, I do have an idea I'll post in separately.

**Comment by BigAl737** [comment]
My approach would rely less on new code (because I don't know how to do that) and utilize features already in VASSAL.

The Casualties Bin would be a map window with two Regions, Allied and Axis. Each region would have a Global Property that would total CVP which is shown by a Text Label within each region. You would then use the Dynamic Piece Property to assign CVPs in one of two ways, automatically and manually through a pop up window.

I'd use the automatic method for MMCs.

For MMCs I'd use the xxINF, xxCRW prototype to add a Dynamic Property trait that assigns these units their appropriate CVP. Then when you send them to the proper region of the Casualties Bin the CVP is adjusted accordingly.

I'd use the manual method for LDRs, Guns, Vehicles and maybe prisoners.

For LDRs use the xxLDR1 proptype to add the manual Dynamic Property.

For Guns use the xxGUN prototype to add the manual Dynamic Property.

For vehicles, you could tie the Replace with Other trait (common to all vehicles with a wreck) with a Trigger Action that Clones, Sends to Casualties Bin, and calls up the manual Dynamic Property.

For prisoners, players could clone the unit in the Casualties bin so that two instances of the unit appear. Most players mark prisoners as such using the text label so double instances shouldn't be too confusing. Another option is to add the manual Dynamic Property trait to the POW counter itself.

For special cases you could override the prototype with a Restrict Commands trait and add the manual Dynamic Property.

I haven't tested any of this but I think it would work. I've done similar stuff in VASSAL modules before.

**Comment by bkemp01** [comment]
Al’s idea sounds very promising and using existing code capabilities may be the better route to take.

**Comment by derimmer** [comment]
As for Al's first suggestion, "simply add a Casualty Bin map window and let players sort it out from there", I think the feedback on GS and FB made it clear that would disappoint most people. 

As for Al's second suggestion, my implementation does use a map window. The idea of creating two regions is good - Al, could you show/tell me how to do that?

In terms of using properties, I am happy to try that way as well. I have a code solution working but always willing to see if there is a better way. Al, I will be in touch when I run into problems with counters!

**Comment by BigAl737** [comment]
I’ll try to post a simple module with a working allied/axis Casualty Bin map for you Doug.

If your coding is working...I’d say keep going with it. If you’d like though, when we talk at some point, I can better explain the properties option and you can decide which to use.

You da man Doug! Thx for all your time and efforts making VASL better.

**Comment by derimmer** [comment]
That would be super helpful Al. Thanks a lot!

 

Looking forward to it. 

 

Doug

**Comment by derimmer** [comment]
I have created a workable casualties bin that seems to be getting an ok reception. One small bug I have noticed is that buttons that certain extensions create are now showing up in the additional map window that is created as the casualties bin. Not sure if they are disappearing from the main map window or not. Does anyone have any experience creating extensions that create new buttons? If so, any thoughts about why these buttons might be showing up in the casualties bin map window (which is named separately from the main map window)?

**Comment by BigAl737** [comment]
I know the tabs won’t work until you start a game. Is that the issue?

**Comment by derimmer** [comment]
No. In the casualties bin window (which is a map window), there should be just two buttons: Allied CVP and Axis CVP but people are reporting other buttons showing up. One fellow, for example, told me that he was seeing buttons belonging to an Africa Korps extension. Don't know if they work or not but would be nice if they weren't there.

**Comment by bkemp01** [comment]
Do we know which extensions are exhibiting this behavior? Where can I download the casualties bin build?

**Comment by derimmer** [comment]
Get the build here.

 

https://www.dropbox.com/s/zhx003zbxfdgila/vasl-6.4.5-casbinbeta.vmod?dl=0

 

One person said he thought it was some sort of Afrika Korps extension. The other one, I don’t know.  It was mentioned on the GS thread.

 

http://www.gamesquad.com/forums/index.php?threads/casualties-bin.152782/

 

Doug
