### ISSUE TITLE
Slopes not working on BFP Board O

### ISSUE THREAD

**Issue by davidsullivan317** [vasl-developers/vasl#502]
LOS from OJ5 to OH1 is showing two hindrances, where there should be none.

**Comment by derimmer** [comment]
It appears that Map.checkTerrainIsHigherRule was missing a status.slopes test. When I add that, the Hindrances go away. Will push to GitHub. 

Does anyone know any other LOS-enabled boards besides BFPO which have slopes on them?

**Comment by davidsullivan317** [comment]
>  Does anyone know any other LOS-enabled boards besides BFPO which have
slopes on them?
I do not.

**Comment by bkemp01** [comment]
BFPC

BFPD

BFPF

BFPL

BFPDW2a

BFPDW4a

BFPDW4b

**Comment by derimmer** [comment]
Thanks Brian. I will test the fix with them.

**Comment by derimmer** [comment]
All looks good, although I could not find any slopes on BFPF.

**Comment by bkemp01** [comment]
on BFPF there are slopes at
C1/D1
B1/C2
B2/C3

**Comment by derimmer** [comment]
Now I see them. . . . I'd like to blame it on bad eyes, but in truth, it is a bad brain. 

Anyway, LOS is working with the slopes. Thanks.

**Comment by bkemp01** [comment]
they’re hiding in the grain
