### ISSUE TITLE
VASLize Hatten in Flames Map

### ISSUE THREAD

**Issue by BigAl737** [vasl-developers/vasl#504]
Subject says it all. Tim Fachko has volunteered to do this.

**Comment by BigAl737** [comment]
Tim has this done. I'm working on uploading it via sourcetree.

**Comment by BigAl737** [comment]
Thanks Sam. I've uploaded the correct file just now.

**Comment by derimmer** [comment]
Al, do you know if the map was made using the standard VASL palette?

**Comment by BigAl737** [comment]
No it's not. From my view, there are quite a few graphical differences between the printed board and the standard vasl palette...ground level snow being a big one. Personally I like the look of the printed board which was carried over to the vasl version. I'm guessing though that you'd like to add LOS? That may be doable without too much problem. We should talk more.

**Comment by derimmer** [comment]
There is standard VASL color for ground snow. If that was used, it might be easy. I am happy to add los if it is not much work. I am busy with a bunch of stuff this fall so if it is a lot of work, I won't be able to get to it until the winter. Happy to discuss further.

**Comment by BigAl737** [comment]
The stock vasl ground snow wouldn't have looked as pretty in my opinion. Let's table this till winter. Maybe start a new issue?

**Comment by BigAl737** [comment]
I"m gonna close this issue. We can open a new issue if/when we add LOS to the Hatten map.
