### ISSUE TITLE
BFP Extension Black SS 437 counter

### ISSUE THREAD

**Issue by BigAl737** [vasl-developers/vasl#505]
From GS: "I noticed that the Black SS 4-3-7 counters have a broken morale of 6, and the HS counterparts (2-2-7) have a broken morale of 7. Can you fix this please? The blue SS are fine."

I haven't verified this nor confirmed that the provided broken morale levels are correct. 

Link: http://www.gamesquad.com/forums/index.php?threads/bfp-extension.148410/post-1944011

**Comment by BigAl737** [comment]
I can get to this in early March. Someone please provide the correct black SS 437 and 227 broken morale values. Thanks.

**Comment by bkemp01** [comment]
I'll include this fix in the Obj Schmidt update.

**Comment by bkemp01** [comment]
According to PiF HBR 5.2 SS Green MMC the 437 should have bsm 7 and the 227 should have bsm 6.

**Comment by BigAl737** [comment]
Thx Brian

**Comment by bkemp01** [comment]
this fix was included in the last draft passed to Ken

**Comment by bkemp01** [comment]
this fix has been included in BFP_v431.vmdx
