### ISSUE TITLE
Board 45 LOS issues

### ISSUE THREAD

**Issue by styson** [vasl-developers/vasl#514]
Here are a couple more hexes that seem to have problems with the orchards on B45 when orchards are in season.

![image](https://user-images.githubusercontent.com/178219/46968116-0bf41a80-d078-11e8-9044-63c7f9809544.png)
![image](https://user-images.githubusercontent.com/178219/46968130-10b8ce80-d078-11e8-88a4-59e92221c992.png)
![image](https://user-images.githubusercontent.com/178219/46968138-144c5580-d078-11e8-815e-6735570e9b12.png)

In the first two instances, it seems the LOS should be hindered. In the 3rd case, it seems the hindrance was properly rendered. Agree?

Eben Johnson
ebenjohnson1@gmail.com

**Comment by derimmer** [comment]
Sam, I have tested this using VASL6.4.3 and bd45v6.2. I get the first error but not the second one. The third one is not an error as Eben notes and my tests show the LOS working fine. 

I will start to work on the first error but I would appreciate it if you and/or Eben could double check the second error.

**Comment by derimmer** [comment]
Sam, on investigation I have found other LOS irregularities on bd45 involving Orchard hexs. From my testing, it is clear that the changes I made to fix the earlier problem have created these new problems. I am going to have to rethink solving the original los issue (from V8 to Q7 with board flipped).
