### ISSUE TITLE
Eliminate the vasl-boards-extensions repository

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#517]
As per the discussion under issue #485, I will start to think about this one in the coming months.

**Comment by derimmer** [comment]
I think we are now ready to delete this repository. The new board selection process is in place and working well. We have not updated this repository since April. It is only required by those using older versions of VASL and, especilly due to @bkemp01's and @BigAl737's  work there are now many new and updated boards available or soon to be available. Users will need to be on recent versions to get these. 

Any reason not to delete the repository?

**Comment by styson** [comment]
proceed!

**Comment by bkemp01** [comment]
one less place to remember to update a new board version sounds good to me

**Comment by derimmer** [comment]
Done. I saved a zipped version to my hard drive. You never know.
