### ISSUE TITLE
Applying DTO terrain turns on DTO Broken Terrain, DTO Steppe Terrain & Use Desert Colors

### ISSUE THREAD

**Issue by jrvjrv** [vasl-developers/vasl#520]
version 6.4.3

Actual behavior: In vasl board dialog, scroll the transformations dropdown to DTO Transformations. In the Terrain dropdown, select DTO Terrain. DTO Broken Terrain, DTO Steppe Terrain and Use Desert Colors for ETO boards are checked. 

Expected behavior: probably only Use Desert Colors for ETO boards should be checked.

**Comment by derimmer** [comment]
I have looked at this again. In absence of any continuing discussion, I am not sure exactly what problem to solve. So, I will just close the issue.
