### ISSUE TITLE
Challenger AFV lacks the 1 ROF, as updated in MMP errata webpage

### ISSUE THREAD

**Issue by BigAl737** [vasl-developers/vasl#523]
http://www.gamesquad.com/forums/index.php?threads/vasl-map-online-problem-suggestion-form.88223/post-1953573

**Comment by bkemp01** [comment]
copy/paste from GS link...

"VASL British counter for the Challenger AFV lacks the 1 ROF, as updated in MMP errata webpage. Thanks for correcting.

p.H56 [British Vehicle Note 21] ((A30) Challenger): This vehicle has Fast Traverse (D1.31) and a 1 ROF, not the Slow Traverse (D1.32) and 0 ROF shown in the 1st Edition of West of Alamein.
[Applicable to WEST OF ALAMEIN] [Counters replaced in ARMIES OF OBLIVION]"

**Comment by BigAl737** [comment]
I'll get to this early March.

**Comment by BigAl737** [comment]
![chall](https://user-images.githubusercontent.com/10384413/53834446-7cbca600-3f37-11e9-8919-cf5324023a59.gif)
