### ISSUE TITLE
Customize-able MMC counter

### ISSUE THREAD

**Issue by BigAl737** [vasl-developers/vasl#524]
http://www.gamesquad.com/forums/index.php?threads/vasl-map-online-problem-suggestion-form.88223/post-1954193

**Comment by bkemp01** [comment]
copy/paste from the GS link...

"May I ask for the ability to select/enter more values on the "0" strength factor DYO counters? Presently you can change the strengths and type-in class. Broken side morale, assault fire, smoke exponent, spray fire and underlined morale are NA. Some of these are already available like the Assault Fire setting for SS squads from 1944 onwards. Fantastic if we can get the full palette.​"

**Comment by BigAl737** [comment]
I've almost got this done. I'll post it here as an extension.

**Comment by hongkongwargamer** [comment]
Al .. this is already done, is it not?  Might help with all the new products coming out.

**Comment by derimmer** [comment]
As far as I can see, the only things that have been implemented are the 0-0-0 values and the class value. 

None of the rest have been implemented across the board. 

@BigAl737 Can you dust off your work and send it along?

**Comment by BigAl737** [comment]
I found it in the basement behind the old photo albums. It's still pretty dusty.

You use the space bar to align the entries. I'd like to do better than that but don't want to hold you up. So here is what I've got so far.

[https://www.dropbox.com/s/mnvismua1aggy3e/CustomUnit_DRAFT_001.vmdx?dl=0](url)

It's summer in Alaska so my computer time is limited. I don't foresee working on this until the snow flies in August. Feel free to adapt as needed.

**Comment by derimmer** [comment]
@BigAl737 I am not able to get the dropbox link to work from within Github. Can you email it to me (dougerimmer@gmail.com) or post it on GS, Discord? Thanks.

**Comment by derimmer** [comment]
@BigAl737 

Hi Al

Hope you have had a good summer up there! I finally got the dropbox link to work (problem was at my end) and I have had a look around at what you have done.

Well done! I like the approach very much. And I like the idea of doing this as an extension to avoid further clutter of the nationality infantry boxes. 

I would like to add a few more wrinkles and then issue this as version 1.0 and see what kind of reaction it gets and suggestions for v2.0. OK by you? I would like to put it out around the same time as VASL667 issues, ie November.
