### ISSUE TITLE
21S8 doesn't appear to have a non-ground level

### ISSUE THREAD

**Issue by zgrose** [vasl-developers/vasl#526]
Draw LOS from 21S8 to 21X6. Press `CTRL-Up` to move the source LOS up a level and nothing happens. Press `Up` to move the target LOS up a level and the LOS thread goes red for clear.

Draw LOS from 21T4 to 21X6. Press `CTRL-Up` to move the source LOS up a level and the text "Level 1" appears and the LOS thread goes red for clear.

It appears as though the map doesn't define a Level 1 Location in 21S8 even though it has the same large square center dot as 21T4.

**Comment by derimmer** [comment]
Fixed
