### ISSUE TITLE
Counter Error German 2cm FlaK 38

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#530]
The physical counter for German Gun #26 (2cm FlaK 38) has no asterisk on its unlimbered side (ie, it is "20L (6)". The VASL counter for the 2cm FlaK 38 shows "*20L (6)".  The limbered side has an asterisk on both the physical and VASL counters. 

It seems the VASL counter, unlimbered side, should not have an asterisk and it should be deleted.

**Comment by BigAl737** [comment]
It's late middle February already!?! Where does the time go? Early March then. I think that still works with your core release time table Doug.

**Comment by derimmer** [comment]
Yes, I see you working on a bunch of fixes. That's great. I am planning for an end of March release.

**Comment by BigAl737** [comment]
![geaa20l6](https://user-images.githubusercontent.com/10384413/53832893-cd320480-3f33-11e9-841f-c9313aaee205.gif)

geAA20L6.gif

**Comment by davidsullivan317** [comment]
Should this be tagged for 6.4.3.1 and closed?

**Comment by derimmer** [comment]
Yes. I am just waiting until I actually release it before cleaning up the issues.
