### ISSUE TITLE
Release 6.4.3.1

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#532]
I was not planning on releasing VASL6.4.4 this spring as we have little in the pipeline. However, VASL6.4.3 has an annoying bug when cropping and/or adding overlays to a map of 2 x 2 boards and greater. 

I have coded a fix which seems to be working so I am planning to release VASL6.4.3.1 around the end of March. 

Does anyone else have code/counter additions or fixes that they would like to include?

Anything pushed to develop since September (when 6.4.3 was released) will of course be included in the build.

**Comment by BigAl737** [comment]
Hi Doug,

I think there’s a few simple counter fixes I could put together before you release. I’ll look into it this coming week.

**Comment by davidsullivan317** [comment]
Using this issue for a general announcement. 

I've submitted the annual IDEA IntelliJ+ tool set license renewal request. If you have a license and no longer need it please let me know. If you do not have one and would like one let me know that too.

**Comment by derimmer** [comment]
Well, I called it 6.4.4 in the end. Done and dusted
