### ISSUE TITLE
No release or tag for 6.4.3

### ISSUE THREAD

**Issue by jrvjrv** [vasl-developers/vasl#536]
It would be nice to have a release and a tag for 6.4.3, so that the code can be readily re-created.

**Comment by derimmer** [comment]
I may not be understanding this correctly but normal procedure when building a new official release is to  save the uncompiled source code to a branch within the repository using the name release-x.x.x. If you look at the branches under vasl you will find release-6.4.3, which contains the code that was used to build VASL6.4.3. I am pretty sure that I have done this for all the modules that I have built.

Is this what you meant or were you looking for something else?

**Comment by jrvjrv** [comment]
> I may not be understanding this correctly but normal procedure when building a new official release is to save the uncompiled source code to a branch within the repository using the name release-x.x.x. If you look at the branches under vasl you will find release-6.4.3, which contains the code that was used to build VASL6.4.3. I am pretty sure that I have done this for all the modules that I have built.
> 
> Is this what you meant or were you looking for something else?

If you look under https://github.com/vasl-developers/vasl/releases dave sullivan has created releases for various versions. There are also tags for the releases at https://github.com/vasl-developers/vasl/tags. I don't know if that is standard procedure, but I assumed it was and filed a bug. It may in fact be the result of rogue procedures.

**Comment by derimmer** [comment]
I will check with David. I thought I was doing what was required but clearly something is missing.

**Comment by derimmer** [comment]
David walked me through this so now I know what I should have done! :-) 

6.4.3 release and tag created.

**Comment by derimmer** [comment]
@jrvjrv @davidsullivan317 I have tried to create a release and a tag for 6.5.0. Could you please verify that I have done it correctly? Also, I think I created a tag . . . what should I be tagging? 

I forget most of this from last time. Need to write myself a note! LOL!

Thanks.

**Comment by zgrose** [comment]
A release is a GitHub construct. A tag is a git construct. When you create a release, it also creates a tag.

As long as you select the correct commit SHA for the state of the repo, that’s all you need to do.
