### ISSUE TITLE
Overlays placed by "overlay" button are not selectable once placed

### ISSUE THREAD

**Issue by jrvjrv** [vasl-developers/vasl#537]
**to reproduce**
click on "Overlays" button
select an overlay and drag onto map
  while still selected the overlay can be repositioned or deleted
de-select the overlay (click on map away from the overlay)
shift-left-click on the overlay

**expected results**
the overlay is selected

**observed results**
the overlay is not selected

**Comment by zgrose** [comment]
Docs say Alt-Click, no?

`Once placed and deselected, an overlay can be re-selected with ALT+left click. You'll know you have the overlay selected when you see the black bounding box around the overlay.`

**Comment by jrvjrv** [comment]
**version**
vasl 6.4.3
vassal 3.2.17

**Comment by jrvjrv** [comment]
> Docs say Alt-Click, no?
> 
> `Once placed and deselected, an overlay can be re-selected with ALT+left click. You'll know you have the overlay selected when you see the black bounding box around the overlay.`

I missed the doc, but I tried no-mod, ctrl, alt, shift applied to left- and right-click. ctrl-alt-right-click brings up a menu, but does not select the item, and selecting the menu items has no effect.

**Comment by jrvjrv** [comment]
xfce window manager uses alt-left-click to move the window by default. The combination is not passed to the program. Disabling the combination (Xfce menu, choose settings > settings manager > window manager tweaks > accessibility) gives back the functionality.

**Comment by davidsullivan317** [comment]
Linux is Latin for, "I suffer." :-)
