### ISSUE TITLE
VASLize BFP Operation Schmidt (OS)

### ISSUE THREAD

**Issue by BigAl737** [vasl-developers/vasl#538]
Did we ever open this as an issue? Easy to lose track of progress if not.

Maps are done and released. Counters are done. Extension in the works by Brian. Brian, any updates, ETA, need help, etc?

**Comment by derimmer** [comment]
Man, you guys have done so much work! Truly impressive.

**Comment by BigAl737** [comment]
Tis good to have you back Brian. Tis good indeed! I opened this issue to track completion of this BFP project. Use this thread or delete it at your discretion.

**Comment by bkemp01** [comment]
this was passed on to Ken

**Comment by styson** [comment]
Any update on this? I was just asked about it on Facebook.

@Javaslinger ?

**Comment by bkemp01** [comment]
back on my plate, end of month

**Comment by bkemp01** [comment]
will try to finish this weekend

**Comment by bkemp01** [comment]
BFP_v431.vmdx has been committed to vasl-website
