### ISSUE TITLE
LOS for split level buildings (B23.721) calculated incorrectly

### ISSUE THREAD

**Issue by jrvjrv** [vasl-developers/vasl#542]
vasl 6.4.3
vassal 3.2.17

to reproduce
draw LOS thread
start LOS in 24v3
end LOS in 24n7
use ctrl-up-arrow to adjust view level in 24v3 to level 2

expected result
LOS is clear

actual result
"Blocked in U4 (LOS must leave the building before leaving the source hex to see a location with a different elevation (A6.8 Example 2))"

**Comment by derimmer** [comment]
The code works in reverse: it will show the los as clear. But still a bug; I think I have a fix, just need to do some more testing.

**Comment by derimmer** [comment]
Fixed and closed
