### ISSUE TITLE
LOS for upper level rubble calculated incorrectly

### ISSUE THREAD

**Issue by jrvjrv** [vasl-developers/vasl#543]
vasl 6.4.3
vassal 3.2.17

to reproduce
place building level one counter in hex 1T2
place stone rubble counter on top
Draw LOS thread
Start in hex 1U2
End in hex 1S3
Use ctrl-up-arrow to adjust viewer height in 1U2 to level 1

expected result
LOS is blocked

actual result
LOS is clear

As a side note, if adding rubble counters with levels indicated on them (rather than having separate level and rubble counters) would be helpful for the problem, such new counters would probably be better for players too.

**Comment by derimmer** [comment]
@jrvjrv you said 

> As a side note, if adding rubble counters with levels indicated on them (rather than having separate level and rubble counters) would be helpful for the problem, such new counters would probably be better for players too.

This is exactly the way to fix this. Creating such counters (and the metadata for them) would basically implement a fix with no code changes. At present, any rubble counter, regardless of whether it is on top of a level counter or not, is treated as being at ground level. The best way to fix this is with new rubble/level counters. I have not created counters before so a good learning opportunity for me. . .

**Comment by derimmer** [comment]
I have coded a fix for upper level rubble. If anyone would care to test it for me I would appreciate it. You can get the test VASL module [here](https://www.dropbox.com/s/m7lcn4s8p8ux2sd/vasl-6.4.5.vmod?dl=0).

If you do give it a try I would appreciate your feeback back on 
(1) whether the LOS check works properly with the upper level rubble counters; and 
(2) what you think of the counters themselves. The counter for level 0 contains a coloured stripe at the bottom which is either gray for stone or brown for wood. Selecting type from the popup menu should switch it. Counters for levels 1, 2, and 3, don't contain this stripe. Which do you prefer? 

The upper level counters can be found on the toolbar and also in the counter panel - Info-Destroy-Rubble. Note that I am refering to counters and not overlays.

Doug

**Comment by derimmer** [comment]
Done
