### ISSUE TITLE
More counter fixes

### ISSUE THREAD

**Issue by BigAl737** [vasl-developers/vasl#545]
I'll take these.

http://www.gamesquad.com/forums/index.php?threads/vasl6-4-4-now-available.151371/post-1969703

Counter image for German 20L(6) AA gun corrected.
No problem with this -- but why not correct the (identical problem) with the 20L AA FlaK 30 and 20L AA FlaKvierling 38 images as well?

(The problem that was fixed for the 20L AA FlaK 38 was the removal of the "star" next to the MA on the front of the counter.)

Counter for Finnish T-26(C)r with BMG option added
Erm ... no? What I see now is a second entry for "T-26B(r)" (which does indeed have a BMG). There should be one entry for "T-26B(r)" -- with two images (one with and one without the BMG) -- and the same again for the T-26C(r). We still do not have a T-26C(r) with BMG. [Mind you the artwork now in place for the T-26C(r) is much improved, and stands out like a (very handsome) sore thumb compared to all of the other Finnish vehicles.]

**Comment by derimmer** [comment]
@BigAl737 let me know when you are ready to push these to GitHub and we can work on it together.

**Comment by BigAl737** [comment]
Will do Doug. Thanks.

**Comment by BigAl737** [comment]
The feedback requesting the removal of the star from the 20L AA FlaKvierling 38 is incorrect:

![image](https://user-images.githubusercontent.com/10384413/55424078-e5457580-552b-11e9-8fc1-c20c08c9fe0d.png)

**Comment by BigAl737** [comment]
Pushed the change to the Flak30counter branch (I think).

I'll handle the T-26 issue in it's own thread #518.

**Comment by derimmer** [comment]
Yes, as far as I can see you have (all you are doing is changing the image file right, none of the traits need to change?). 

so next step is to push the change from Flak30counter to develop so it can be included in the next build. You do this by creating a "pull request" - never mind the language inversion for now. Go to the Flak30counter branch on GitHub. on the right side of the line that tells you the branch is one commit ahead of develop you should see "Pull Request". click it and then then so long as you see green text and buttons, keep clicking on Create Pull Request, Merge, etc, there should be 2-3 clicks and then you will be 
done and you will see a screen that lets you (a) delete your branch - a good idea unless you intend to reuse it for other changes in the short term, and (b) close the issue. 

Message me at any point if you are confused/unclear.

**Comment by BigAl737** [comment]
Yep, just a simple image file change. No new code required.

I'll get back to this in a couple of days. Thanks for your help!

**Comment by BigAl737** [comment]
Corrections confirmed by Doug. Closing.
