### ISSUE TITLE
KFW Extension Testing

### ISSUE THREAD

**Issue by BigAl737** [vasl-developers/vasl#547]
CURRENT VERSION:

[KFW_DRAFT_006.zip](https://github.com/vasl-developers/vasl/files/3827761/KFW_DRAFT_006.zip)

DRAFT 06 fixes numerous errors (Thanks Brent Morris!)

[*Searchlight instructions*](https://github.com/vasl-developers/vasl/issues/547?_pjax=%23js-repo-pjax-container#issuecomment-478364655)

[*US Marine 768 footnote 16 info*](https://github.com/vasl-developers/vasl/issues/547?_pjax=%23js-repo-pjax-container#issuecomment-488827300)

Al

**Comment by BigAl737** [comment]
SEARCHLIGHTS....

Here's the intent on how they're supposed to work.

to be continued...

**Comment by BigAl737** [comment]
I know about this:

![image](https://user-images.githubusercontent.com/10384413/55293110-f6ad4700-539e-11e9-8830-7dcec90a0c55.png)

Still trying to find where it's referencing these deleted counter images.

**Comment by derimmer** [comment]
Al, early returns from a friend to whom I passed the link.

1. The British Oxford Carrier 3 - in MTR vehicle is just a copy of the Oxford Carrier. The former should not have T6, and should have ROF 1, 1PP* (not 9PP), should have AAMG -/-/2.
2. The North Korean PTP obr 42 anti-tank gun has a too truncated drop down list. This list is missing the following options: Label, CA change, Prep Fire, Defensive Fire, HIP, Move and Conceal.
3. The Game Info dialog still only shows Allied/Axis as an option; I was expecting to see UN/CF {United Nation / Communist Forces} or something like that. No big deal.
I used the lastest version of VASL (6.4.4) for this work.

I believe point 3 is entirely outside your extension!

**Comment by BigAl737** [comment]
RE point 3...

You're referencing game turn markers? If so, there's more:

![image](https://user-images.githubusercontent.com/10384413/55295722-d8eeda80-53bc-11e9-8ed9-281160c15422.png)

Are you not seeing the others in the right side scroll window?

**Comment by BigAl737** [comment]
RE point 2...

All NK guns had that issue. How did that happen?!? Fixed all.

Working on the British 3 inch mortar carrier. Will post extension version 2 tomorrow morning.

Thanks!

**Comment by BigAl737** [comment]
RE point 1...

There's a Carrier 3in mortar:
![image](https://user-images.githubusercontent.com/10384413/55296197-903a2000-53c2-11e9-980d-14c6510fee89.png)

and an Oxford Carrier 3in mortar:
![image](https://user-images.githubusercontent.com/10384413/55296180-726cbb00-53c2-11e9-9d60-e2ae1e7fc3f5.png)

I think the extension depicts these correctly.

![image](https://user-images.githubusercontent.com/10384413/55296223-ea3ae580-53c2-11e9-9003-8e8f439dffd8.png)


![image](https://user-images.githubusercontent.com/10384413/55296215-d1cacb00-53c2-11e9-91aa-dd417805995f.png)

**Comment by derimmer** [comment]
Re point 3

I think it is more the scenario info dialog which is part of the VASL code:

![image](https://user-images.githubusercontent.com/7696161/55298660-e1ff9c00-53fc-11e9-8daf-8dd9f8154ba3.png)

**Comment by BigAl737** [comment]
You're right. The extension doesn't touch this.

I believe all 3 items have been addressed. Version 2 is available in lead post. Only changes were to fix the Russian guns and I found and deleted the references to old counters.

**Comment by BigAl737** [comment]
DRAFT version 3 posted

**Comment by BigAl737** [comment]
10 days remaining for feedback.

**Comment by hongkongwargamer** [comment]
![image](https://user-images.githubusercontent.com/26445969/56468153-b2bbd800-645a-11e9-8190-4b120df953a4.png)

Gents .. when I right click on these .. there's no menu item for ELR'ing them?

**Comment by hongkongwargamer** [comment]
![image](https://user-images.githubusercontent.com/26445969/56468171-ef87cf00-645a-11e9-8cac-853f8a680135.png)

Also .. when you CTRL-H the 328 .. it turns into a HIP'd 628AE?

**Comment by BigAl737** [comment]
Good stuff Jackson. I’ll look into these. 

The HIP issue pertains to all VASL counters with layered art. Don’t think there’s anything I can do about this but I’ll look into it to be sure.

**Comment by ATGreat** [comment]
All the Communist North Korean Leaders are missing most of the functions. The only options available to them are: Wound,ELR,BH,Clone,Delete.

**Comment by ATGreat** [comment]
The North Korean 152 ART,and both AA counters don't have the show info command.

**Comment by hongkongwargamer** [comment]
> The North Korean 152 ART,and both AA counters don't have the show info command.

That's probably 'cause there's no special ammo / QSU to show.

**Comment by hongkongwargamer** [comment]
> All the Communist North Korean Leaders are missing most of the functions. The only options available to them are: Wound,ELR,BH,Clone,Delete.

![image](https://user-images.githubusercontent.com/26445969/56537303-c8341d80-6592-11e9-9773-accf0fce9326.png)

It's the same situation with other SMCs if you test them in the counter box.  Other options appear when you drag them out to a map.

**Comment by ATGreat** [comment]
> 
> 
> > All the Communist North Korean Leaders are missing most of the functions. The only options available to them are: Wound,ELR,BH,Clone,Delete.
> 
> ![image](https://user-images.githubusercontent.com/26445969/56537303-c8341d80-6592-11e9-9773-accf0fce9326.png)
> ![image](https://user-images.githubusercontent.com/26445969/56537411-0d584f80-6593-11e9-8620-b38d133d2ebc.png)
> 
> It's the same situation with other SMCs if you test them in the counter box. Other options appear when you drag them out to a map.

Maybe I don't have the most recent version. All my testing has been done on a map for just that reason.

**Comment by ATGreat** [comment]
In your example there you are using the regular North Korean Leaders. The Leaders in the Communist tab are the ones not functioning.

**Comment by hongkongwargamer** [comment]
> > > All the Communist North Korean Leaders are missing most of the functions. The only options available to them are: Wound,ELR,BH,Clone,Delete.
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/26445969/56537303-c8341d80-6592-11e9-9773-accf0fce9326.png)
> > ![image](https://user-images.githubusercontent.com/26445969/56537411-0d584f80-6593-11e9-8620-b38d133d2ebc.png)
> > It's the same situation with other SMCs if you test them in the counter box. Other options appear when you drag them out to a map.
> 
> Maybe I don't have the most recent version. All my testing has been done on a map for just that reason.

Ah .. check the top post for version 3.

**Comment by hongkongwargamer** [comment]
> In your example there you are using the regular North Korean Leaders. The Leaders in the Communist tab are the ones not functioning.

So you mean the Communist CHINESE Leaders .. not Communist Korean leaders then?

**Comment by ATGreat** [comment]
They are listed under the North Korean tab as Communist Guerillas.

**Comment by hongkongwargamer** [comment]
Gotcha
![image](https://user-images.githubusercontent.com/26445969/56538745-71c8de00-6596-11e9-891f-76af0692c1c7.png)
Partisan leader (for comparison)
![image](https://user-images.githubusercontent.com/26445969/56538776-9329ca00-6596-11e9-8c1b-e033bb91e4a4.png)

**Comment by BigAl737** [comment]
> The North Korean 152 ART,and both AA counters don't have the show info command.

These are just cut and paste copies of their Russian counterparts. I checked the Russian equivalents and they don't have a show info option either. As Jackson pointed out, there is no info to show for these units.

Thanks for your feedback! I'm checking out everything you guys are finding. Much appreciated.

**Comment by BigAl737** [comment]
> All the Communist North Korean Leaders are missing most of the functions. The only options available to them are: Wound,ELR,BH,Clone,Delete.

Good catch. A typo in a prototype was the culprit. Fixed.

![image](https://user-images.githubusercontent.com/10384413/56540924-9b422500-6516-11e9-8e89-055eae645d50.png)

**Comment by BigAl737** [comment]
Fixed the missing OUNC MMCs

![image](https://user-images.githubusercontent.com/10384413/56541181-700c0580-6517-11e9-9d0d-afb6d446707b.png)

**Comment by BigAl737** [comment]
RE ELRing the NK 628 Assault Engineers. These were included as a player convenience since these counters do not exist in KFW. They are a straight copy and paste from the Russian 628 AE unit and it does not have the ELR option. So the question is, can a Russian 628 AE deploy? I thought it ELRs into 2 broken 328 AE hs.

**Comment by BigAl737** [comment]
Working on the optional deployment of the USMC 768 sq. It's not a standard ELR so I don't think I should include this optional ability into the HoB menu. I'm making a stand alone unit to represent this optional ability.

**Comment by hongkongwargamer** [comment]
> RE ELRing the NK 628 Assault Engineers. These were included as a player convenience since these counters do not exist in KFW. They are a straight copy and paste from the Russian 628 AE unit and it does not have the ELR option. So the question is, can a Russian 628 AE deploy? I thought it ELRs into 2 broken 328 AE hs.

Russian AE's do not have underlined morale .. and the rulebook doesn't award them with ELR 5.  Do you have a reference as to where it says AE's ELRs into 2 HS?

**Comment by BigAl737** [comment]
> > RE ELRing the NK 628 Assault Engineers. These were included as a player convenience since these counters do not exist in KFW. They are a straight copy and paste from the Russian 628 AE unit and it does not have the ELR option. So the question is, can a Russian 628 AE deploy? I thought it ELRs into 2 broken 328 AE hs.
> 
> Russian AE's do not have underlined morale .. and the rulebook doesn't award them with ELR 5. Do you have a reference as to where it says AE's ELRs into 2 HS?

No rules reference. Just a mistaken belief that they would to maintain their AE status as half squads. There's an unofficial Q&A that says the AE status is lost upon ELR if directed by SSR. So it seems that AE units could or could not maintain AE status after ELR depending on the SSR that grants them AE status.

I did a quick check. The VASL default seems to be that AE units do not have an ELR menu option. That's true with all AE squads for all nationalities except for the German 548 AE. As such I don't see the need here to add the ability for the North Koreans for several reasons; 1. The Russian 628 AE unit doesn't have an ELR option; 2. If I "fix" the North Korean AE unit, I feel I must fix the other nationalities too. That's outside the scope of this extension; 3. I just threw in the AE units for player convenience. And the only reason I did that is because of Bullets For Breakfast SSR 7.

I think it's best to leave the VASL default in place here. If players need to ELR a North Korean AE unit, they will can dig it out of the counter tray, like they have to do for all other nationalities.

I'm open to hearing any further thoughts on this issue.

**Comment by BigAl737** [comment]
> Good stuff Jackson. I’ll look into these.
> 
> The HIP issue pertains to all VASL counters with layered art. Don’t think there’s anything I can do about this but I’ll look into it to be sure.

I tried to get creative here and got all excited that I found a solution but then I realized the light in the tunnel was indeed a train :-( This may have to remain as is.

**Comment by hongkongwargamer** [comment]
> > > RE ELRing the NK 628 Assault Engineers. These were included as a player convenience since these counters do not exist in KFW. They are a straight copy and paste from the Russian 628 AE unit and it does not have the ELR option. So the question is, can a Russian 628 AE deploy? I thought it ELRs into 2 broken 328 AE hs.
> > 
> > 
> > Russian AE's do not have underlined morale .. and the rulebook doesn't award them with ELR 5. Do you have a reference as to where it says AE's ELRs into 2 HS?
> 
> No rules reference. Just a mistaken belief that they would to maintain their AE status as half squads. There's an unofficial Q&A that says the AE status is lost upon ELR if directed by SSR. So it seems that AE units could or could not maintain AE status after ELR depending on the SSR that grants them AE status.
> 
> I did a quick check. The VASL default seems to be that AE units do not have an ELR menu option. That's true with all AE squads for all nationalities except for the German 548 AE. As such I don't see the need here to add the ability for the North Koreans for several reasons; 1. The Russian 628 AE unit doesn't have an ELR option; 2. If I "fix" the North Korean AE unit, I feel I must fix the other nationalities too. That's outside the scope of this extension; 3. I just threw in the AE units for player convenience. And the only reason I did that is because of Bullets For Breakfast SSR 7.
> 
> I think it's best to leave the VASL default in place here. If players need to ELR a North Korean AE unit, they will can dig it out of the counter tray, like they have to do for all other nationalities.
> 
> I'm open to hearing any further thoughts on this issue.

All good.  I am just happy to have the discussion.  Heads up - for the Objective Schmidt module, German 537 Engineers ELRs to conscripts.  The PT mdx reflects that as well.

**Comment by BigAl737** [comment]
Great stuff guys. Thanks for your eyes on target. All issues addressed or fixed. DRAFT version 4 available in top post. This is going public soon but there's still opportunity for more feedback. Thanks in advance.

**Comment by BigAl737** [comment]
Gonna release this for public review on May 1st. Any input before I do? DRAFT version 4 is in the top post.

**Comment by hongkongwargamer** [comment]
Gents .. I wonder if you'd consider making 
![Screenshot 2019-04-30 at 23 29 07](https://user-images.githubusercontent.com/26445969/56973616-c9230b80-6b9f-11e9-9a92-62f594dca702.png) 
![image](https://user-images.githubusercontent.com/26445969/56973663-e1932600-6b9f-11e9-9d40-6ed425ef59d9.png)

For Communists and non Communists so we can put them on TURN TRACK to indicate reinforcements and "special" events

And a Phase Wheel . that just says "Communists" and "Non Communists" in the chat box?
![image](https://user-images.githubusercontent.com/26445969/56973834-3c2c8200-6ba0-11e9-9b0f-7bb9ffee5053.png)

**Comment by BigAl737** [comment]
I will do that Jack. Great idea.

**Comment by BigAl737** [comment]
DRAFT version 5 is released. Feedback now moved to GS.

http://www.gamesquad.com/forums/index.php?threads/the-kfw-vasl-thread.149281/post-1951462

**Comment by BigAl737** [comment]
The US Marine 768 squad has an optional ability to deploy/ELR into 3x248 half-squads using procedures set forth in Chapter W footnote 16. I created two stand alone units to accommodate this option.

![us768fn16Sq](https://user-images.githubusercontent.com/10384413/57105985-af391400-6cd8-11e9-9c74-e9dc3b22e934.png)

![us248fn16Hs](https://user-images.githubusercontent.com/10384413/57105994-b52ef500-6cd8-11e9-9ee6-323727dcd067.png)

**Comment by BigAl737** [comment]
I've received some excellent feedback on the draft version. I'll make those changes and go official release asap.

**Comment by BigAl737** [comment]
See top post for update

**Comment by BigAl737** [comment]
Official public release version uploaded to git hub. Sam, please add to VASL.info website as appropriate. Thanks. I'll update the top post and the GS reference link once it's on vasl.info.

**Comment by styson** [comment]
It's been uploaded to vasl.info!

**Comment by BigAl737** [comment]
Extension incorporated into core VASL 6.5.1.
