### ISSUE TITLE
bdRileys data file format incorrect

### ISSUE THREAD

**Issue by jrvjrv** [vasl-developers/vasl#554]
The data file has two different lines that begin with "version". I am guessing vasl looks at the last one. vasl downloads the board each time it is opened: http://www.gamesquad.com/forums/index.php?threads/vasl-map-online-problem-suggestion-form.88223/page-31#post-1972256

**Comment by BigAl737** [comment]
Should be fixed. New version is 1.6. JR please confirm and close issue at your discretion.

**Comment by jrvjrv** [comment]
looks good. thanks!
