### ISSUE TITLE
Password recovery

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#558]
I received a pm on GS:

"Just a quick question. I ran into a problem with my laptop. Is there anyway to recover my VASL password from my computer?"

Anybody have any thoughts?

**Comment by zgrose** [comment]
It is possible, but I don't know how much you want to advertise it because it is slightly labor intensive for you.

1- Get a vlog/vsav from them.
2- Run VASL in debug mode.
3- Set a breakpoint where it checks if the user secret matches for concealments.

I forget the exact line, but I've done it.

**Comment by jrvjrv** [comment]
How you might recover depends on what the problem on the laptop is. If the vasl preferences still exist, the password is stored in plain text in the prefs file. On linux the preferences file is stored in ~/.VASSAL/prefs/VASL, under the key "SecretName." On windows it's stored somewhere in the user directory. Mac: probably like linux but no guarantees. 

If the vasl preferences don't exist, they you may be setting a breakpoint, etc.

JR

**Comment by derimmer** [comment]
Thanks to you both. This should do it.
