### ISSUE TITLE
Add ELR trait to Russian 628/328 AE units

### ISSUE THREAD

**Issue by BigAl737** [vasl-developers/vasl#561]
Jackson brought up a great point in a discussion on this subject for the KFW extension. I just received RF, studied the scenarios, and not being much of a player, didn't realize until now how often Russian 628 AE units are utilized in the system. Much more so than their limited use (so far) in KFW. So I think this is a issue of more importance than I initially gave credit.

Russian 628/328 AE units should ELR to 527/227 units.

**Comment by derimmer** [comment]
Closing now as this should be worked on as part of #862
