### ISSUE TITLE
Starter Kit PTO Boards m, n, o!!

### ISSUE THREAD

**Issue by TheSQLGuru** [vasl-developers/vasl#563]
The SK PTO module has shipped, so there will soon be over 1300 people chomping at the bit to play those scenarios!! The vast majority of them do not have local opponents, so PLEASE make getting an initial cut at those boards a priority!

**Comment by TheSQLGuru** [comment]
I have slapped together functional copies of boards m and o from PROOF jpegs of those boards I used during playtesting. I have asked MMP if I can post them up for use until the Board Elves are able to get them officially released.

**Comment by BigAl737** [comment]
Let me know what MMP says. Usually we have to wait a few months before posting a VASL version.

**Comment by TheSQLGuru** [comment]
They asked me to not post the ones I created publicly. I didn't understand
that initially, but upon reflection I realized that it is probably to
prevent a drop-off in initial sales due those that may get an illicit copy
of the rules and just play on VASL without making a purchase.

Kevin G. Boles
SQL Server Consultant
SQL Server MVP 2007 - 2012
Indicium Resources, Inc.
@TheSQLGuru

**Comment by BigAl737** [comment]
That's consistent with the past. We will get these boards done at an appropriate time. You're welcome to that project if you'd like.

**Comment by TheSQLGuru** [comment]
If I had any bandwidth I would love to, just to learn about how they are
done. Sadly I have had a bunch of medical problems over the last 2 years
and am so far behind on life and work I can't even see the top of the hole
I am in. :-(

Kevin G. Boles
SQL Server Consultant
SQL Server MVP 2007 - 2012
Indicium Resources, Inc.
@TheSQLGuru

**Comment by BigAl737** [comment]
Hi Kevin, Sorry to hear about your health issues. I’ll pray for a speedier and complete recovery. Also for a bigger shovel so you can fill that hole :-)

You’re spot on about why we wait a few months before attempting the boards. At some point I think VASL increases sales but probably not during initial product release. But then, what do I know. 

Take care Kevin. You’re welcome to help if/when you can. Sometimes it’s nice to simply have a fresh pair of eyes on something. 

Al

**Comment by TheSQLGuru** [comment]
Per an email with Perry and a posting, you are cut loose to create and
release boards m, n, and o for VASL. I have jpeg files of m and o from MMP
if you need them, although I don't know if they are of the final release of
the boards or not.

I really wish I could help you! I would love to learn more about the
process. :(

Kevin G. Boles
SQL Server Consultant
SQL Server MVP 2007 - 2012
Indicium Resources, Inc.
@TheSQLGuru

**Comment by BigAl737** [comment]
Thanks Kevin. I’ve put them up for completion. I’ve got the files I need.

Al

**Comment by BigAl737** [comment]
I'm gonna close this issue. I've opened three more that address each board individually. Brian, please assign yourself to the new issues if you want any/all of these boards.

**Comment by TheSQLGuru** [comment]
BTW, I'm going to post up on the ASLSK FB group to see if any members there
are inclined to help you out with the maps. Hopefully at least one or two
of our 1500 members will join your collective.

Kevin G. Boles
Indicium Resources, Inc
(sent from phone)

**Comment by TheSQLGuru** [comment]
I am toying with the possibility of offering a bounty to our ASLSK FB Group
members to jump into your group and knock out the m, n, o ASLSK PTO maps. I
wanted to ask though:

1) Is such a thing kosher?

2) Is it possible for anyone to work on any VASL Cooperative Open Item?

Kevin G. Boles
SQL Server Consultant
SQL Server MVP 2007 - 2012
Indicium Resources, Inc.
@TheSQLGuru

**Comment by Javaslinger** [comment]
Hi Kevin,
With regards to #1  The team received the board files a few months back.  There is a process that is unfortunately time consuming and requires particular skills and training.  Flooding the team with new help isn't alway useful because those with the skills don't have the time to teach them.  Some of it can be learned with the limited documentation, but it's not easy.  People very familiar with Photoshop or GIMP, particularly with selections and layers would be most helpful, but that's just step one. 

I don't know what #2 is.  Can you contact me directly via email?

**Comment by TheSQLGuru** [comment]
I don't have your email. But the question was just if someone (viable) parachutes in, could they just start working on m, n or o - disregarding the age/priority (if it matters) of the Open Items List. It is a moot point likely, because no one jumped when I first posted about helping this group. :-) 

Thanks for the reply, and KUDOs for doing great work for the community!

**Comment by bkemp01** [comment]
They are in progress, likely 2-3 weeks out as an optimistic estimate. The notion of just jumping in and knocking things out is not a realistic expectation for those that are not already familiar with the process. There is a learning curve and time commitment that anyone is free to undertake but I don’t think conscripts would be very helpful right now.

FYI a simple SK style board can easily take 15-20 hours for someone with experience, complex boards double or more. None of us are getting paid to do this as a full time job so finding that kind of spare time ain’t always easy and usually translates into weeks.
