### ISSUE TITLE
VASLize RO Board

### ISSUE THREAD

**Issue by BigAl737** [vasl-developers/vasl#564]
Draft version 0.09 of bdRO available here:

https://www.dropbox.com/s/vg6mvet9fh22ged/bdRO?dl=0

Ground Snow and Gutted Factories overlays are selectable here:

![image](https://user-images.githubusercontent.com/10384413/67149534-cce34100-f258-11e9-997f-56d538b1d369.png)

The other terrain transformations won't work or will give you wild results.

LOS is not enabled. I'll get the required files to Doug soon.

This board aligns with bdRBv3. See here for instructions: #565

Please let me know of any issues. Thanks.

**Comment by BigAl737** [comment]
There's no factory walls. I'll fix that.

**Comment by BigAl737** [comment]
Doug, the gif map (sans hexgrid) for non-inherent terrain is here:

https://www.dropbox.com/s/pn1bd9xgd7m60z4/bdRO-LOS-noninherent-001.gif?dl=0

The gif map for inherent (with hex grid but without factory floor debris hexes) is here:

https://www.dropbox.com/s/b4c5gi9sx2innw1/bdRO-LOS-inherent-001.gif?dl=0

I will be cropping the borders to remove the white space (not visible on the LOS gif). Not sure if that would mess you up. You can see the vasl version of the map in the top post link. The metadata file is a copy of RB vasl metadata. I still need to update the bldg hexes to reflect the RO map.

I figure this is a start. Let me know whatever you need to work your LOS magic.

**Comment by derimmer** [comment]
OK. Thanks. 

 

I am running an ASL tournament in Ottawa this weekend so I can’t look at this right away. But I should have some time to dedicate to this next week.  

 

Doug

**Comment by derimmer** [comment]
Hi Al

Finally had some time to look at this. At present, the RO and RB do not align well. This is only a problem if they will be used together in VASL. This is what the board join looks like:

![RORB](https://user-images.githubusercontent.com/7696161/58580080-4fbc1e80-821a-11e9-8500-5b38f3e34c90.PNG)

If bdRO and bdRBv2 are never meant to be used together (meaning you are going to create one joined board) then this is ok. Otherwise there are three problems

(1) bdRO (width = 2005 pixels) needs to be the same width as bdRBv2 (2012) pixels. Especially important for cropping
(2) The A1 center dot offset (22.0, 32.5 in bdRbv2) needs to be the same on boards or the hex centres will not be aligned
(3) The paper maps include a physical overlap of about half a hex on the board edge of bdRBv2 and the top edge of bdRO. VASL doesn't know how to handle this. One or perhaps both boards need to be shaved to ensure that they abut properly. 

I can't really go further on the LOS work until (1) and (2) above are resolved. 

Again, if the boards are never meant to be ajoined then all these problems go away. Let me know! 

Doug

**Comment by zgrose** [comment]
IMO, you'd be better off making a bdRORB that joins the images in Photoshop/GIMP/etc to support CGs (I *think* that's the main time the maps are joined). That way you don't need to whack the standalone maps.

**Comment by BigAl737** [comment]
I’ve been experimenting. Things I’ve learned...

I will have to make a new version of the Red Barricades board. Shouldn’t be too hard. The Red October board is done.

Both boards will be their full size.

Both boards will meet up and play nicely with one another. To make this happen you simply crop the RO board from the 1 hex row to the bottom most hex row, essentially just cropping the 0 row from the RO board. It works great. 

The Red Factory overlays, to include a ground snow overlay, are gonna be included in the Overlay extension. Drag and drop, eezy peezy.

My plan is to soon release a draft version of both boards. The updated overlay extension will release next. After the inevitable corrections from sharp eyed Stalingrad masters, I’ll release final board versions. Doug, LOS can come out after the draft versions are released.

That will at least give guys the ability to play while we add enhancements at a more moderated pace.

**Comment by derimmer** [comment]
Sounds like a plan.

**Comment by BigAl737** [comment]
![image](https://user-images.githubusercontent.com/10384413/58725398-7d74a500-838b-11e9-8604-9ea8e53cc4ec.png)

The RO board is cropped from 1-48 in the screenshot. I need to add the hex grid details to the RB board and we are ready for a draft release.

Doug, I'll have to work up another LOS version of the RB board for you.

Any feedback at any time is much appreciated.

**Comment by davidsullivan317** [comment]
You can't even tell the images where joined - looks great!

**Comment by BigAl737** [comment]
As summer wanes, I should have more time to finalize this map and #565 as well. Release versions will soon follow.

**Comment by BigAl737** [comment]
...soon being a relative term of course :-)

Working on this again.

**Comment by BigAl737** [comment]
Please see top post for update. Thanks.

**Comment by derimmer** [comment]
Here is a link to the RO board with los added:

https://www.dropbox.com/s/eeo0dl4tfr4mqwy/bdRO.zip?dl=0

You will need vasl6.6.2-beta3.vmod to make it work:

https://www.dropbox.com/s/207jkw5mmmvotm4/vasl-6.6.2-beta3.zip?dl=0

Both of these will give you access to a zip file. Unzip them as normal and then use the extracted files as normal. 

Remember when using RBv3 and RO together you must crop RO to coordinates 1-48. 

RO introduced a new hex configuration (in los terms) and it took me a while to sort out how to get it to work in a variety of crop configurations. Think I have now but it certainly needs a test drive both for accuracy of the los and for cropping. 

Al, assuming that we find no serious errors, do we want to put all of this out of GS? I am happy to do it.
