### ISSUE TITLE
6.5.0 plan of attack

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#566]
Over the last two years, since May 2017, we have put out a new VASL module twice a year: spring-fall 2017, spring-fall 2018, spring 2019, covering vasl6.4.0 to vasl6.4.4. Several of these had substantive enhancements but a couple included just minor bug fixes to the module and counters.

For 6.5.0, I would like to propose that we (1) aim for a major substantive release and (2) take the time to get the work done, aiming for a release in 2020, probably in the fall. Releases of new boards, counter extensions, etc could continue in the meantime but bug fixes would not.
Does this make sense?

Listed below are my thoughts about what we might try to include in 6.5.0. Anything missing? Other suggestions? Italicized items are already tagged for 6.5

Enhancements – visible to the user
1. Incorporate FW Extension into Core VASL module
2. Add Casualties bin and “put in casualties bin” plus pop up text box (#499 and 541)
_3. Update EC/Weather counters (#142)_
4. Finish LightWoods additions (#483, #484)
5. Add HIP toggle to chat reporting (#501)
6. Move Up/Down building level – add to move options sub-menu
7. Hidden text label for AL, G, Sz, etc notes  
8. Counter Finder tool for finding obscure counters in the counter panels

Enhancements – not visible to the user
9. Fix some prototype issues to make counter creation easier/more accurate
10. Eliminate the vasl-boards-extensions repository (#517)

Bug Fixes
11. LOS Fix for rubbled upper levels and split levels (#542 and 543)
12. Fix other overlay bugs (#546, #540, #539)
13. Support SSR terrain changes in the overlay extension; crop-able overlays, re-sizeable overlays (#464, 525, 519)

Board Fixes
14. Complete application of LOS to Deluxe boards (#500)
15. Update FB boards to 6.0+ (#470)
16. Fix BFP Board2 (#474)
_17. Add LOS to KGP boards (#412)
18. Enable use of .png files as board image files._

Counter Fixes
TBD

**Comment by zgrose** [comment]
Fixing the double-transparency for HIPed counters would be nice. Might just be a side-effect of item 9 in your list. Somewhat related, if there is a way to fix the transparency and counters with layers issue, that would be nice, too.

**Comment by bkemp01** [comment]
#590 is ready for 6.5

**Comment by derimmer** [comment]
I now have a beta version of VASL6.5 ready for general release. Here is an updated version of my previous list, showing what got done and what fell by the wayside. I think there is enough here to warrant releasing 6.5.

Please let me know if you are in the middle of doing something that you would like to be included in 6.5. I plan to release the beta version this coming week unless someone asks me to put it on hold.


Enhancements – visible to the user
1. Incorporate FW Extension into Core VASL module DONE
2. Add Casualties bin and “put in casualties bin” plus pop up text box (#499 and 541) DONE SKIP 541
3. Update EC/Weather counters (#142) DONE
4. Finish LightWoods additions (#483, 484, 583) DONE
5. Add HIP toggle to chat reporting (#501) SKIP
6. Move Up/Down building level – add to move options sub-menu SKIP
7. Hidden text label for AL, G, Sz, etc notes SKIP
8. Counter Finder tool for finding obscure counters in the counter panels DONE

Enhancements – not visible to the user
9. Fix some prototype issues to make counter creation easier/more accurate SKIP
10. Eliminate the vasl-boards-extensions repository (#517) DONE

Bug Fixes
11. LOS Fix for rubbled upper levels and split levels (#542 and 543) DONE
12. Fix other overlay bugs (#546, #540, #539) 539 DONE Big Al
13. Support SSR terrain changes in the overlay extension; crop-able overlays, re-sizeable overlays (#464, 525, 519) SKIP
14. HIP Counters retained during LOS Checks (#408) SKIP
15. VASL Freezing on LOS Checks (#588) maybe when changing levels  SKIP
16. Opponents pieces staying on when doing check  SKIP
17. String not on hex centre (?)  SKIP
18. LOS Bug fix to handle BFPDW b and deluxe boards when flipped DONE
18. LC wreck label bug fix   DONE
19. Concealment Chart corrected

Board Fixes
14. Complete application of LOS to Deluxe boards (#500) DONE
15. Update FB boards to 6.0+ (#470) DONE
16. Fix BFP Board2 (#474) DONE
17. bd40 bug fix DONE
18. Add LOS to KGP boards (#412) SKIP
19. Enable use of .png files as board image files (#500) DONE

Counter Fixes
Several minor bugs were fixed over the last year  DONE

Update documentation DONE

**Comment by derimmer** [comment]
vasl-6.5.0 official release will go out tomorrow, April 15

**Comment by BigAl737** [comment]
And there was much rejoicing :-)

Congrats Doug. Major effort on your part.
