### ISSUE TITLE
Storage Tanks being treated as building during transformation

### ISSUE THREAD

**Issue by Javaslinger** [vasl-developers/vasl#578]
No idea if anything can be done, but I noticed on BFP B that when I set all buildings to wooden, the grey storage tanks also turned to wood.  Somewhat confusing for identification purposes as they now resemble Towers more than storage tanks.

**Comment by bkemp01** [comment]
I believe this can be accomplished by changing the color palette used for tanks/towers.

**Comment by derimmer** [comment]
This appears to have been fixed; perhaps not as intended. At present, BFP A and B do not show any change when the All Wood or All Stone transformations are applied. Other BFP boards and non-BFP boards do apply the transformation properly.

The immediate issue with the storage tanks on BFP B has been resolved. If there is a problem with BFP A and B not transforming, we can open a new issue.
