### ISSUE TITLE
Overlay Extension Main Thread

### ISSUE THREAD

**Issue by BigAl737** [vasl-developers/vasl#591]
Since the Overlay Extension is always in development, this thread is where I'll post the most recent DRAFT versions for input.

Current Released Version is 1.02

Latest Draft version is 1.03 DRAFT 01.

[VASLOverlays_v103 DRAFT 01.zip](https://github.com/vasl-developers/vasl/files/3827754/VASLOverlays_v103.DRAFT.01.zip)

Unzip and add to your VASL extension folder (remember to make inactive previous versions of VASLOverlays extensions).

**What's New**
DRAFT 01 added the RB specific overlays, updated the HTML placeholder (check it out as I think it's really cool), and added some easy reference usage reminders.

**Comment by BigAl737** [comment]
Official public release version 1.3 uploaded to git hub. Sam, please replace version 102 on VASL.info website. Thanks. I'll update the top post and the GS reference link once it's on vasl.info.

**Comment by styson** [comment]
added to vasl.info!

**Comment by BigAl737** [comment]
Doug has said that we can't add the ability to crop, resize, nor terrain transform overlays placed via the Overlay Extension (#519, #525, #392).

I'm asking you for your opinion on what the future for this extension looks like. Should we keep it, go back to the old way, a little of both, use SSOs and BSOs more often?

Personally, I hate overlays. Maintaining the extension is hard enough but maintaining the old way is not something I will volunteer for. Of the two, I like the extension better, despite it's short comings. It's much easier to use. It just doesn't look great if there's a terrain transform or overhang to crop. If we keep the extension, I will volunteer to keep it up to date.

My vote is to keep the extension. Let the old way rot and die. Use SSOs and BSOs for scenarios with overlays that need to be terrain transformed or cropped.

**Comment by hongkongwargamer** [comment]
As a User - I vote for keeping the extension.  However, until a week ago I would have said the contrary.  

I have had a few too many issues with opponents who didn't have the extension installed.  As a layman I wasn't aware that the new way wasn't backwards compatible.  That until setting up for a scenario where the designer gives you the flexibility to place overlays where and in a configuration you want.  That would have been horrible with the old way (without having to pull out the physical stuff).  

Can the extension be "built in"?

**Comment by BigAl737** [comment]
Good points Jack. Thank you.

Yes the extension could be built in. It would increase the size of the VASL module by quite a bit but maybe that's not a concern. The more I think of it, the more I like the idea.

**Comment by Javaslinger** [comment]
I agree with Jack.  The last 3 opponents I've had to instruct them on installing the overlay extension.  Until it's built in, it's just not going to take off.  And if both players need it for it to work, then I think we need to build it in.

Sent from Yahoo Mail on Android 
 
  On Tue, Apr 7, 2020 at 7:50 PM, Allan Cannamore<notifications@github.com> wrote:   


Good points Jack. Thank you.

Yes the extension could be built in. It would increase the size of the VASL module by quite a bit but maybe that's not a concern. The more I think of it, the more I like the idea.

**Comment by zgrose** [comment]
The advantage of extensions over integration in the core module is that one can have a more aggressive cadence of extension releases.

Maybe there is a way we can have a win-win (at least for extensions for which we have direct control) and somehow allow for them to get pulled down much like the boards do? May require a restart of VASSAL but that seems like a small price to pay.

On the other hand, I wouldn't want to download the 23429 extensions HKW has loaded just because I start up a scenario with him...

So maybe not a great idea. But I think there is a better solution that moving to a monolithic architecture.

**Comment by BigAl737** [comment]
Updated extension to be uploaded shortly. This version adds an opacity option to help position overlays and a place for SSO overlays. This will allow me to quickly respond to user requests for SSOs without the need to update the associated mapboard.

**Comment by derimmer** [comment]
I think we can close this as an issue. @BigAl737 has done a great job getting the extension out there and continuing to update it.
