### ISSUE TITLE
Re-implement charts as maps

### ISSUE THREAD

**Issue by zgrose** [vasl-developers/vasl#592]
We're using the Charts feature for charts (shocking!). It is possible to use Maps for charts and this allows for Zoom controls. Probably other side effects but does seem to be the way other modules do their charts these days (I happen to be looking at the Talon module from GMT).

**Comment by derimmer** [comment]
If this were to proceed it would be the time to bring the PTO Terrain chart extension into the VASL module

**Comment by derimmer** [comment]
@zgrose Do you remember how someone would actually implement this?

**Comment by zgrose** [comment]
I can take a peek at the Talon module. I don't know how many bells and whistles it had (tabs, etc) and I'll get back to you.

**Comment by zgrose** [comment]
Here is how the button and such are defined and here is what it ends up looking like:

<img width="606" alt="Screenshot 2023-06-08 155253" src="https://github.com/vasl-developers/vasl/assets/5044847/e52a600c-dba0-430b-bbed-03919d1c5e62">

<img width="429" alt="Screenshot 2023-06-08 155339" src="https://github.com/vasl-developers/vasl/assets/5044847/e48acca4-1042-4dee-9341-c27258f6edd7">

**Comment by zgrose** [comment]
Dunno but I did notice that when I was in edit mode, the graphic didn't show either.

**Comment by derimmer** [comment]
Just had a thought. No reason I can't grab the Talon module and see how they did it.

**Comment by derimmer** [comment]
OK. Compared with Talon and found that I had added the "board" image in the wrong hierarchy. Got that sorted and it displayed. Added the standard zoom functionality. Can't use mouse wheel but still. I will convert the existing charts in 6.6.7 and then we can see about others. I may talk to Neil U about his charts. 

I see there is an option for an HTML chart, which I presume means one that enables links and other HTML functionality. Any thoughts about how we might use that?

**Comment by zgrose** [comment]
I have a sneaking suspicion that trying to get all the layout and formatting to match the MMP charts would be quite the chore as HTML instead of scans/photoshop/etc work.

**Comment by derimmer** [comment]
Agree with you 100%. Not a way to go for the official ASL charts. 

Might be useful as a top-level navigator for charts - we could add more - such as those in RSCh.vmdx which I believe are known as the "Spilky Charts". I find it hard to navigate to the right one whenever I need it; usually in the heat of battle. 

BTW, anyone know who created the extension in the first place?

**Comment by zgrose** [comment]
Rich Spilky?

**Comment by derimmer** [comment]
@zgrose I downloaded Talon and opened it up and used it as a model for VASL. It all seems to work except that only about 10% of the IFT is visible and I can't figure out how to enlarge the display area in the map window. So, I am going to give up on this and put it on the back burner. Not enough bang for me to spend any more bucks on it.

**Comment by zgrose** [comment]
Looks like map windows try to guess the size based on the image in it, at least that was the impression I got from a quick google. But ya, sounds like more hassle than it is worth at the moment. I took a pass at looking over the properties and couldn't find anything either.
