### ISSUE TITLE
VASLize bdl

### ISSUE THREAD

**Issue by BigAl737** [vasl-developers/vasl#598]

**Comment by derimmer** [comment]
Al, appreciate the enthusiasm. But these boards (i, j, k l) have already been done. The issue was closed in June of  2108. Is there a problem with them?

**Comment by BigAl737** [comment]
Oh thank goodness :-)

I overlooked that in my haste to catch up with what needs to be done. Thanks.

**Comment by BigAl737** [comment]
Opened in error
