### ISSUE TITLE
Wishing to export some configuration to other modules

### ISSUE THREAD

**Issue by wga8888** [vasl-developers/vasl#602]
I started playing regular VASL server play and found two capabilties I wish to implement to other module i manage such as VSQL. VASL configuration is extensive so I thought I would just ask where in the configuration I can find the details [where to look].

1) for just about every module;
 -Control+Right Click on a selected unit to create the red circle to draw opponent's attention to where the next action will be.  Very useful for games with large map areas.
2) for VSQL
 - the Malf MG button that when depressed highlights with a red circle all the malf units and broken units that may want to do something in a Rally Phase.

thanks, bill thomson; bill@wargameacademy.org

**Comment by derimmer** [comment]
vasl/src/VASL/build.module/map

ASLPieceFinder for red circle to highlight a particular location for an opponent.

ASLBrokenFinder for button the hightlights broken units and equipment with a red circle.

**Comment by wga8888** [comment]
Hello Doug,
  
 Thanks for the quick reply.  If my pursuit is too much of a request, can 
let it drop.   but,
  
 Using your lead, I found the three finders in the VASL config (ASLPiece, 
ASLBroken, ASLSniper)

 Looking at any one does not tell me much

 I assume there is some custom java class files for for this or something 
else? My goal is to add at least the Piece Finder intoother modules but 
need to figure out how.  I assumed (always questionable) this is a 
possibility so I unzipped the module for look for a folder of class files.  
I cannot identify something in the META-INF, VASL, org files.

  
 In my earlier days I had a vassal team of which one the three was Brent 
Easton.  Scattered across my score of modules are about 10 custom code 
capabilities created by Brent that are not yet the vassal engine.  For a 
time he was drafted into the engine team but I believe he eventually 
dropped out later .  Unlike Brent I am not a programmer.  I have mixed 
success transferring some of the sets of class files from one module to 
another using Brent's instructions.  Perhaps as they were created 10 years 
ago on a much earlier version of vassal.
  
 VASL was the first module (succeeding VASL.exe).  I worked on the next 9, 
often as the project manager.  I configure, Brent added unique 
capabilities, the third was Jeff Wise who did custom graphics.  For a time, 
VSQL (module #3) had capabilities that VASL did not yet have.   Loss touch 
with Brent and Jeff when my family life went downhill for many years.   
Have done another score modules since, focusing on game titles with lo lots 
of organized pbem ladder/tournament play.   Also any game I want to play 
even if cannot be put on the vassal page (SPI titles, etc).
  
  Bill Thomson 817-501-2978 CST (-6 GMT) skype: wga8888; 
www.wargameacademy.org; Facebook Messenger

  
 -------- Original Message --------
> From: "Doug Rimmer" <notifications@github.com>
> Sent: Saturday, January 04, 2020 8:23 PM
> To: "vasl-developers/vasl" <vasl@noreply.github.com>
> Cc: "wga8888" <bill@wargameacademy.org>, "Author" 
<author@noreply.github.com>
> Subject: Re: [vasl-developers/vasl] Wishing to export some configuration 
to other modules (#602)
>
> vasl/src/VASL/build.module/map
>
> ASLPieceFinder for red circle to highlight a particular location for an 
opponent.
>
> ASLBrokenFinder for button the hightlights broken units and equipment 
with a red circle.

**Comment by davidsullivan317** [comment]
The right answer here is to talk to Brent or Joel an convince them to add the map pointer to VASSAL proper. It wouldn't be that much work. Then any module designer could add it to their maps with a few clicks.

**Comment by derimmer** [comment]
Agree with Sully (as always). However, to help you understand how it works in VASL at present, two of the three finder files do the same thing, that is they handle a button click. For the code that actually creates the buttons on the toolbar and sets up the action listener which then triggers the finder classes, look at QC.java in the same folder as the three "finder" files. Around line 1100 you will start to see code that creates the buttons and then around line 1700 sets up the action listener. 

ASLPieceFinder works differently in that there is no button involved. The functionality is driven by a click on the map and the mouse listener is built into ASLPieceFinder. ASLPieceFinder is also different in that it uses the Command structure in VASSAL to trigger actions on the opponents screen whereas the other two finders simply show up on the screen of the player pushing the button.

All three classes extend VASSAL classes and use the Buildable functionality of VASSAL.

Hope that helps.

**Comment by wga8888** [comment]
I worked with Brent over several years on a dozen of modules with Jeff Wise 
in the early/mid 2000s, including modules #2-10 including VSQL. Brent as a 
java programmer, added identified custom capabilities not in the engine via 
a folder containing java class files.  There are about 10 of these spread 
over about 10 WGA vassal modules.  Some eventually made it into the engine 
after Brent was drafted into the engine team .  I have had intermittent 
success moving these into other modules via Brent's 's instructions. 
Perhaps as were created in the much earlier days of the Vassal Engine 
[compatibility?] 
  
 Joel joined in the group effort to make the The Longest Day module mid 
2000s, about the time I had to drop out for a number a years due to family 
issues. [I am currently enhancing this module, benefiting from a group of 
players who are actively using it in pbem games; I now playing as well.
  
  A vassal engine new capability would benefit future modules.  I would 
need a folder with the class files to add ASLPieceFinder into existing 
modules.  [Typically a folder of class files added into an un-ziped module, 
then import the primary class file while editing the top level of the 
module.]
   
What is the best method to make a request for consideration?  I have been 
out of contact with Brent & Joel; both have since moved on to vassal admin. 

  
  Bill Thomson 817-501-2978 CST (-6 GMT) skype: wga8888; 
www.wargameacademy.org; Facebook Messenger

  
 -------- Original Message --------
> From: "David Sullivan" <notifications@github.com>
> Sent: Sunday, January 05, 2020 6:41 AM
> To: "vasl-developers/vasl" <vasl@noreply.github.com>
> Cc: "wga8888" <bill@wargameacademy.org>, "Author" 
<author@noreply.github.com>
> Subject: Re: [vasl-developers/vasl] Wishing to export some configuration 
to other modules (#602)
>
> The right answer here is to talk to Brent or Joel an convince them to add 
the map pointer to VASSAL proper. It wouldn't be that much work. Then any 
module designer could add it to their maps with a few clicks.

**Comment by wga8888** [comment]
This task has been accomplished.  The LookAt capability has been generalized by Paul Blankenship with help from David Sullivan.  This is being dropped into to my various WGA vassal modules and others via collaboration as they get updated. 

Issue closed
