### ISSUE TITLE
board 4b has incorrect woods hexes

### ISSUE THREAD

**Issue by styson** [vasl-developers/vasl#607]
Board edge woods are in the wrong hexes.

![image](https://user-images.githubusercontent.com/178219/73101765-0a89e280-3eb6-11ea-84a2-6e34bb95b38a.png)

**Comment by bkemp01** [comment]
I have updated bd4b including the LightWoods and DenseJungle overlays. I haven't been able to get the LOSGUI tool to work for me today so @derimmer please perform your magic.
I have not updated anything outside of the src folder.

**Comment by derimmer** [comment]
Will do.

**Comment by derimmer** [comment]
@bkemp01 I had some difficulty applying los. I think this was due to the fact that "HasHills" had been set to false in the BoardMetadata.xml file. Once I corrected this los-gui worked fine. 

I will push this up to develop and add bd6.4 to the website momentarily.

**Comment by bkemp01** [comment]
That's good to know, I didn't think to check that. Thanks a lot!

**Comment by derimmer** [comment]
Just found an error. Z12 is set as a wooden building in BoardMetadata.xml when it should not be. Will fix and reissue. Other than that, LOS seems to be working fine and auto-syn worked fine.
