### ISSUE TITLE
bd23 Light Woods transformation not working

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#611]
This was reported on GS and I have investigated. There is a bug but it is a weird one. 

In short, certain terrain transformations are implemented using overlays stored in the board file which also contains the file OverlaySSR, an xml list of the allowable transformations for the board along with the name of the .gif image file to be used. 

This xml list is converted into a list of OverlaySSRule objects containing the transformation name and the name of the .gif image file. Code in SSRFilter.java iterates through this list of objects and finds the one that matches with the transformation selected by the user. 

BUT, in the case of bd23, there are 13 items in the list, including one for LightWoods. The iterator skips over LightWoods!! It does not test LightWoods and find an error, it simply ignores this item in the list. I have moved it around in the list and it still ignores it. As far as I can see the OverlaySSRule for LightWoods is properly constructed. But it is never used by the iterator. The iterator shows the correct number of OverlaySSRule objects, including the LightWoods item.

I have done a quick check of other boards and the LightWoods transformation seems to work fine. 

Thoughts or ideas?

**Comment by BigAl737** [comment]
Three trouble shooting ideas,

Delete one of the transforms (not LtWoods of course) so there's 12 and see if the problem persists;

Add a bogus transform so there's 14 and see if the problem persists;

Rename the lightwoods transform and associated gif file and see if the problem persists.

**Comment by bkemp01** [comment]
Looks like the 23_LightWoods.gif file is missing from the bd23 archive.

**Comment by BigAl737** [comment]
Here it is if needed...

![23_LightWoods](https://user-images.githubusercontent.com/10384413/74110302-d8c07f00-4b37-11ea-8920-2b01529236a5.gif)

**Comment by bkemp01** [comment]
the file is present in boards/src but was not included in the archive file in bdFiles

**Comment by derimmer** [comment]
It is in the file that I have been testing (I may have added it myself) and still no joy.

**Comment by bkemp01** [comment]
Maybe there was something corrupt with the old archive, I created a new bd23 from the files in src and it now works fine for me.

**Comment by BigAl737** [comment]
Working for me too. Using VASL 6.4.4 and it loaded bd 23(v6.2).

**Comment by derimmer** [comment]
Good news and well done. I think you are right Brian, something rotten in the old archive.
