### ISSUE TITLE
Merging KFW counters into VASL

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#614]
Al's KFW extension has been available for a while and there are no reports of major problems. So, I think it is ready to be merged into the main VASL module. I am willing to do this as I also need to add a property to the new unit counters to have them work with casualty bin. 

My question is how to best organize the KFW counters in VASL? For new nationalities that is no problem but how about those American 446 counters - where do they go? 

For new infantry counters for existing nationalities I am thinking of a new tab below the SQ and HS tabs (so for American units under SQ there would be 3 tabs: Army, USMC and Korea. For guns and vehicles and planes, new items would fit under the existing tabs for Gun and Vehicle type. 

Does that seem sensible? Any other ways of doing it?

**Comment by derimmer** [comment]
Here is a link to the beta version of vasl6.5 which includes the KFW counters.

https://www.dropbox.com/s/fibog3bv1gdbu10/vasl-6.5-beta1.vmod?dl=0

For the NK, CC, SK, and OUNC counters, I simply created nationality tabs as per the regular structure for Allied or Axis countries. For American and British units, I integrated them in to the existing structure, hopefully in an easy to find way. 

For Markers, I put all the OBA stuff into a new tab Other / OBA-Korea. I put the Regular Hills / Steep Hills counter in Info - KFW Hills. I put the Phase counters in Other – Phase Track and the turn counters in Other – Turn Markers. I put the Bayonet Charge counter in Unit – HW/Banzai/Bayonet.

I think that covers everything. 

This beta version includes the Casualties Bin functionality so you can check that it works for KFW counters if you want. It also includes the Counter Finder functionality but I have not updated it to include the KFW counters. I thought I would wait unit we were comfortable with where the Markers counters should be before doing so. 

Let me know if you spot any problems or errors.

**Comment by derimmer** [comment]
Should have added: I suggest removing the KFW extension if you have it added before testing the KFW migration to VASL6.5

**Comment by hongkongwargamer** [comment]
Thanks mate, any chance we can make it so that it says "6.5 Beta" under Module Version in the VASSAL Module Library box instead of "6.4.5"?  Makes it less confusing amongst several VASL installs.

**Comment by derimmer** [comment]
Sorry, in this particular case, I cannot. This version contains everything that is in the earlier versions of 6.4.5, all of which are beta tests, as is this one. So, you can delete all your versions of 6.4.5 and use this one (unless you have a version that comes from someone else). 

My apologies for this. I did try to create the right names. Sometimes what actually shows up in VASSAL surprises me.
