### ISSUE TITLE
VASLize board DN Dinant

### ISSUE THREAD

**Issue by bkemp01** [vasl-developers/vasl#617]

**Comment by BigAl737** [comment]
Hi Brian,

I have time to put a draft copy of this board out today. That'll give players a chance to use it while we bide our time. Don't want to undo anything you're doing though. Would you like me to do this?

**Comment by bkemp01** [comment]
Go for it, Al

Thanks

**Comment by BigAl737** [comment]
vroom vroom :-)

**Comment by BigAl737** [comment]
Taking a little longer than expected. It's wider than we have a VASL hexgrid for. Should get it out tonight.

**Comment by BigAl737** [comment]
Here's a temporary link to draft version 0.1. No bells and whistles. Just basic ASL playing on this map. Please check it out and let me know if you see any show stoppers before I release it to the masses. Thanks.

https://www.dropbox.com/s/8sp854k9jxspsxt/bdDinant?dl=0

**Comment by BigAl737** [comment]
bdDinant v0.2 is the latest. Same link as above or watch for the release on GS.

**Comment by styson** [comment]
Any update on the map @BigAl737 ?

**Comment by BigAl737** [comment]
Hi Sam,

No change in status. v0.2 is still the latest. The only thing it's lacking is breaking out the terrain groups so Doug can add LOS. It may be a bit before I get to this. Otherwise v0.2 is fully functional so if you'd like to upload it the website, please do.

**Comment by BigAl737** [comment]
No feedback on this board in months. Pushed to website. This one is done.
