### ISSUE TITLE
Landing Craft wreck depiction looses its label

### ISSUE THREAD

**Issue by mtrodgers99** [vasl-developers/vasl#620]
When Landing Craft with label "Anything" is flipped to its wreck side, the label disappears. Sometimes there are still passengers on board (in the cloaking box) that can unload, like for a broached wreck.

**Comment by zgrose** [comment]
I believe this is the case for all Replace With... traits. Could be wrong though.

**Comment by derimmer** [comment]
The VASSAL manual indicates that the Replace With trait includes a "Match Current State" property that should carry over labels and other other states to the new counter. I looked at a few LC counters and this property is set for them. Michael, can you give us a specific counter reference?

**Comment by mtrodgers99** [comment]
The LC was a Japanese SHOHATSU.
![LC before](https://user-images.githubusercontent.com/6097151/76654408-400b8d80-6541-11ea-997f-17611fe78020.jpg)
![LC after](https://user-images.githubusercontent.com/6097151/76654413-43067e00-6541-11ea-80f6-4100c187b5fd.jpg)

**Comment by bkemp01** [comment]
I'm puzzled by this one. It applies to all of the LC. I checked both the normal and wrecked counters and both have the text label property so match current state should carry over the labels just like it does for AFV.

**Comment by zgrose** [comment]
Trait order?

**Comment by BigAl737** [comment]
I think the text trait differences in the non-wrecked/wrecked prototypes is the issue.

Ex: LCA uses the prototype shLC. The text label in that prototype has a blue background. The wreck for the LCA uses the shWRK prototype. The text label in that prototype has a white background. When I make both text labels the same in each prototype, I get:

![image](https://user-images.githubusercontent.com/10384413/77121455-172b4280-69f0-11ea-96ed-ca5ca7b4e212.png)

**Comment by bkemp01** [comment]
ahh good find Al, I think there is something in the docs about traits must match

**Comment by derimmer** [comment]
Well done Al, I would certainly never have thought of that!

I will undertake to fix this for the LC as I have already changed them for the casualty bin so I might as well do this fix too.

**Comment by BigAl737** [comment]
Now...do we keep the white or the blue? I don't have a preference personally.

**Comment by derimmer** [comment]
white will stand out better in ocean hexes. Just MHO.

**Comment by derimmer** [comment]
I fixed the two prototypes and tested it on every LC. All good.
