### ISSUE TITLE
Reorganize the BFP extension

### ISSUE THREAD

**Issue by BigAl737** [vasl-developers/vasl#621]
I'm working on adding OtO2 content and importing the Corregidor the Rock extension into the main BFP extension. As I do so, I'm thinking it's time to break out the content in the main BFP extension and put it in one place so it's easier to pull counters. I was thinking of a format with a single BFP pull down menu for each of BFPs products. The pull down menu would be further organized with panels and lists. It would look something like this:

![image](https://user-images.githubusercontent.com/10384413/76854466-facab280-6803-11ea-9add-34ef8721bef3.png)

The other option is to leave the extension as is and add the CtR and OtO2 content to the BFP pull down menu. I really don't want to try to embed this content into the core module counter bins. It gets buried and hard to find I think.

**Comment by bkemp01** [comment]
I would be in favor of this approach. In fact, I had started down this path with my initial work on the OS additions but 1 out of 2 testers was very much against so I settled on a slight compromise instead.

**Comment by BigAl737** [comment]
Interesting. Let's see if they protest here. I'd like to learn the reason.

**Comment by styson** [comment]
I'm definitely in favor of this. Will make adding new products easier in the future.

**Comment by BigAl737** [comment]
As a voice from BFP, you carry a lot of clout :-)

**Comment by BigAl737** [comment]
Summer is just about over. My last month of work is September. BFP is an incredible supporter of ASL and VASL and more than deserves an updated extension. It's time for me to resurrect this.

If there's any naysayers out there, now's the time to voice your opinion.

**Comment by BigAl737** [comment]
This is out for public review...

http://www.gamesquad.com/forums/index.php?threads/bfp-vasl-extension-update.159170/post-2035539

**Comment by derimmer** [comment]
@styson @BigAl737 I have updated BFP_v44_DRAFT001.vmod to enable the casualty bin functionality to work with units in the extension. I hope I got everything right. I have renamed it BFP_v44_DRAFT002.vmod. 

Unfortunately you will not be able to test all of the Cas Bin functionality until I issue VASL6.6.2 which includes a bunch of changes to the cas bin. But the functionality found in 6.6.1 should now work for the extension units. The other functionality has been added to the extension but needs 6.6.2 to work. I can explain what that new functionality is if you really care. 

I have zipped the extension. Extract to use. 
[BFP_v44_DRAFT_002.zip](https://github.com/vasl-developers/vasl/files/5810638/BFP_v44_DRAFT_002.zip)

**Comment by BigAl737** [comment]
Thanks Doug. I'll get started adding the Operation Neptune counters to it. Will also take it out of DRAFT mode.

**Comment by BigAl737** [comment]
ITR2 and Op Neptune additions are done.

Submitted a rough draft to Rick for testing and modifications before going final.

**Comment by BigAl737** [comment]
Almost ready to go final.

I’ve posted a draft version on GS. You can check it out here:

http://www.gamesquad.com/forums/index.php?threads/bfp-vasl-extension-update.159170/post-2035539

Please feel free to share it with others.

**Comment by derimmer** [comment]
@BigAl737 @styson I believe this should be closed as the new (excellent) version 5 of the BFP extension is out and available via vasl.info and other places.
