### ISSUE TITLE
Add BFPs OtO2 counters to the BFP Extension; VASLize the map

### ISSUE THREAD

**Issue by BigAl737** [vasl-developers/vasl#622]
I'm working on both. Completion of this issue is resting on the decision we make about reorganizing the BFP extension itself. #621

**Comment by BigAl737** [comment]
Trying to leave as much information as possible and maintain readability. I'll keep using the Has Notes trait for absolute clarity. But I think most of the back of the counter notes are readable without without having to open the Has Notes window.

What do you think?

![M4A2aoto2](https://user-images.githubusercontent.com/10384413/76988100-106dd400-68f9-11ea-8621-25eefa591a39.png)
![M4A2aoto2b](https://user-images.githubusercontent.com/10384413/76988111-14015b00-68f9-11ea-8cc5-d44dd6648982.png)
![T-70oto2](https://user-images.githubusercontent.com/10384413/76988121-16fc4b80-68f9-11ea-9d19-973af643c377.png)
![T-70oto2b](https://user-images.githubusercontent.com/10384413/76988127-18c60f00-68f9-11ea-9640-29b592541a47.png)

**Comment by derimmer** [comment]
Personally, I love it. The superscript numbers are illegible to my eyes but that is not important. It is clear that there is a superscript and so players can then use Info or read Chapter H for clarification. 

I like the font size for the T-70 vehicle name on the front counter better than the M4A3(a).

**Comment by bkemp01** [comment]
Wow, those look great Al. The most important info is legible for me. Sure wish there was a good way to use SVG because then you could zoom in as needed to see the small stuff. I haven't kept up with the SVG discussions for a while but I seem to recall it basically worked but not so well when counters are rotated.

**Comment by BigAl737** [comment]
That is indeed the problem with SVG. The cardinal 0 and 180 rotations look great and you can zoom in while maintaining complete clarity. VASSAL rasterizes the images when it rotates them. Still a case could be made for SVG if VASL would show image pop ups in an unrotated state. Maybe that's a change we should consider?

Doug, I agree that the M4A2(a) text is a little small. I'll see if I can make it bigger. If I can't fit the vehicle name, it's the first to go to make room for more important stuff.

RE the superscripts...there's no way I can make these big enough to be legible but I agree with you, they serve a purpose to remind players to look at the Has Notes info. I'll leave them in when able.

**Comment by BigAl737** [comment]
Bigger M4A2a

![M4A2a-OtO2](https://user-images.githubusercontent.com/10384413/77020474-bbea4900-6938-11ea-8dbc-4fd3c77f350c.png)

Wondering if it's better to leave off the name if it won't fit along one of the sides of the vehicle art.

![OT34(L)-OtO2](https://user-images.githubusercontent.com/10384413/77020479-bee53980-6938-11ea-8e0f-cf95c1b0c675.png)

**Comment by derimmer** [comment]
IMHO keep the names. I could read the M4A2(a) easily. And the OT-34(L).

**Comment by BigAl737** [comment]
Thanks Doug. I've been keeping them as much as able. Also keeping vehicle size too.

![ISU152-OtO2](https://user-images.githubusercontent.com/10384413/77127817-cec95000-6a02-11ea-83c6-ec824704902e.png)
![PT3485-OtO2](https://user-images.githubusercontent.com/10384413/77127846-d852b800-6a02-11ea-9fdc-e8c3d1a3afb3.png)

**Comment by uckelman** [comment]
> VASSAL rasterizes the images when it rotates them.

There was no simple way around this due to the way traits stack. It would be a colossal amount of work to adjust V3.2 so that SVG is rasterized at the last possible stage after all transformations are applied. If someone wants to undertake that, I won't object, but I'm prioritizing release of V3.3 (which lets us use newer versions of Java) and after that V4 work, so I won't put my own time into it, and should someone decide to work on the SVG rendering,  will expect to see thorough testing before the changes go into a release. (You'll have crisp SVG rendering in V4 because rendering will be designed for it rather than retrofitted.)

**Comment by BigAl737** [comment]
Thanks for the explanation Joel. It'd be a colossal amount of work to add the SVG image files too. We are fine until V4 someday.

The only suggestion I have is that we may consider changing the Mouse Over trait to show images in an unrotated orientation.

**Comment by BigAl737** [comment]
I've completed the OtOv2 map. Here's the link to the gif:

https://www.dropbox.com/s/lfzc8uwm5g349cq/bdOtO2.gif?dl=0

If someone with a paper copy of the map please proof this for me, I'd appreciate it. Comments and suggestions welcome as well.

Doug, this one will be easy to add LOS. I'll be sending you that file soon. It'd be cool if we offered it with LOS right outta the chute.

**Comment by uckelman** [comment]
> It'd be a colossal amount of work to add the SVG image files too.

The way to do it in the long run is to _generate_ all the piece images with a script and a spreadsheet, like I did for _The Longest Day_ module.

**Comment by BigAl737** [comment]
I'll check out that module. I'll bet I learn some cool VASSAL tricks.

I'm not much of a programmer so have only used scripts rarely. I'm interested to learn how though. Could you provide your spreadsheet so I can see how it works?

Another short term option is to generate 6 SVG orientations for each counter, then add those as PNG images in a Layer trait. Maybe I'll mess with that a little in the OtO extension. I recall testing this quite a while back and realizing it wasn't worth it but it'd be good to visit it again.

Probably the best short term option is to change the Mouse Over trait to show objects in an unrotated state.

**Comment by bkemp01** [comment]
Interesting, I'd love to hear about this script/spreadsheet method also.

**Comment by bkemp01** [comment]
@BigAl737 I have a copy of the paper map and will proof this weekend. Are you also handling the new DW geo boards?

**Comment by derimmer** [comment]
Happy to do it.

**Comment by BigAl737** [comment]
> @BigAl737 I have a copy of the paper map and will proof this weekend. Are you also handling the new DW geo boards?

Thanks Brian. 

I've got the files for the geo boards but haven't started on them yet. They're available if someone wants to take them.

**Comment by bkemp01** [comment]
@BigAl737 I didn't detect any errors, just a couple of suggestions...
Slopes obscured by shellholes in some hexes (i.e. C30, G7, Y27, CC10).
L0/L-1 crest line hidden by grain (SE corner, lower left).
Hex center dots hard to see in grain (black on printed map).

**Comment by BigAl737** [comment]
Good stuff Brian. Thanks!

**Comment by derimmer** [comment]
I believe that you are adding the OtO counters to the version of the extension which I have already updated to include the dynamic property  on all unit counters (except SW) in order for the casualty bin function to work properly. If so, you may want to consider adding that property to the OtO units. There are slight variations to the property for Infantry, Guns, Vehicles and Planes. Plus, the SQ and HS version of the property is different from the Crew/SMC version. 

If you would prefer, I can add the property after you have made all other changes to the extension.

**Comment by BigAl737** [comment]
New version of bdOtO2 posted here:

https://www.dropbox.com/s/ebkfzgut1qxf0vg/bdOtO2?dl=0

The version number is unchanged. You'll know you have the updated version if the grain hex centers are black.

Good finds Brian...thanks!

Any others with feedback/corrections?

**Comment by BigAl737** [comment]
> I believe that you are adding the OtO counters to the version of the extension which I have already updated to include the dynamic property on all unit counters (except SW) in order for the casualty bin function to work properly. If so, you may want to consider adding that property to the OtO units. There are slight variations to the property for Infantry, Guns, Vehicles and Planes. Plus, the SQ and HS version of the property is different from the Crew/SMC version.
> 
> If you would prefer, I can add the property after you have made all other changes to the extension.

I'll do that Doug. Thanks for the reminder.

**Comment by bkemp01** [comment]
Looks real good Al. Beware there is already a bdoto2 in the repo so the
file name conflicts.

**Comment by BigAl737** [comment]
I did see that but thought my v2 would automatically update upon download (like the geo boards)?

Else, I think we can delete the old bdoto2 from the repo as the new bdOTO2 is the same except with updated graphics.

**Comment by bkemp01** [comment]
I should be able to dive into the DW8&9 boards this weekend.

**Comment by bkemp01** [comment]
BFPDW8ab & BFPDW9ab are in progress.

**Comment by bkemp01** [comment]
DW8 & DW9 are complete.

**Comment by BigAl737** [comment]
The boards and maps have been done. The counters are in the latest BFP extension update:

http://www.gamesquad.com/forums/index.php?threads/bfp-vasl-extension-update.159170/post-2035539

I need to get bdOtO2 to the website. Can someone show me how to do that so that it updates automatically on download?

**Comment by derimmer** [comment]
Same way as any other board:

1. put board files in a folder (unzipped) in the boards/src folder of the vasl repo
2. put the bdXX file in the boards/bdFiles folder of the vasl repo
3. update v5boardVersions.txt and v5boardVersions.xml in the boards folder of the vasl repo

That is sufficient to have it show up in the dropdown and auto sync.

To then add it to the website
1. Zip the bdXX file and and add it to the appropriate folder of the vasl-website repo.
2. Update the versions.json file in the boards folder of the vasl-webiste repo.
3. Add the board reference to the appropriate .htm file in the vasl-website repo (probably others.htm which is where the other bfp boards are).

Happy to walk you through it.

**Comment by derimmer** [comment]
Al, the extension seems to work fine based on my first few drive-throughs. 

One comment. I see that the casbin functionality is there for the counters. Good. 

I am doing some bugfixes to the casbin now. One thing I have had to do is add a dynamic property iCVP to all SW counters. 

1. This avoids a Bad Data in Module message from showing up in the chat area if someone puts a SW in the casbin.
2. dm mortars > 60 mm have a 2 CVP value same as their assembled versions.

I have uploaded these changes to github if you want to see them. I can also walk you through how to make them. Or, once the extension is finalized, I would be happy to make the changes for you.

**Comment by derimmer** [comment]
Al, just realized that I have two other casbin fixes to do, both of which will involve triggers actions and changing some counters. 

Think it probably makes more sense for me to do all the changes to the BFP extension at one time. If you guys are ok with that.

**Comment by BigAl737** [comment]
Make any changes you need Doug. I'll grab an updated copy from you when you're finished.

**Comment by BigAl737** [comment]
From another thread asking where the latest BFP extension can be had...I think you got it but here it is:

https://www.dropbox.com/s/87ltjtso9p7ilow/BFP_v44_DRAFT_001.vmdx?dl=0

**Comment by BigAl737** [comment]
> Same way as any other board:
> 
> 1. put board files in a folder (unzipped) in the boards/src folder of the vasl repo
> 2. put the bdXX file in the boards/bdFiles folder of the vasl repo
> 3. update v5boardVersions.txt and v5boardVersions.xml in the boards folder of the vasl repo
> 
> That is sufficient to have it show up in the dropdown and auto sync.
> 
> To then add it to the website
> 
> 1. Zip the bdXX file and and add it to the appropriate folder of the vasl-website repo.
> 2. Update the versions.json file in the boards folder of the vasl-webiste repo.
> 3. Add the board reference to the appropriate .htm file in the vasl-website repo (probably others.htm which is where the other bfp boards are).
> 
> Happy to walk you through it.

Thanks Doug. I've done this process before. For some reason I thought it was changed recently. Three boards I'm going to add: bdOtO2, bdDinant, and bd25ETO.

**Comment by BigAl737** [comment]
This is done.

**Comment by derimmer** [comment]
> Make any changes you need Doug. I'll grab an updated copy from you when you're finished.

WRT the BFP extension, I will make the casbin changes over the next number of months. There will be no point in releasing an updated extension until vasl6.6.2 comes out as it will be matching the changes made in 6.6.2.

**Comment by derimmer** [comment]
Hi Al

 

Here is a link to the revised extension on Dropbox. 

https://www.dropbox.com/s/btjzc2i1vheyavt/BFP_v44_DRAFT_001.vmdx?dl=0

 

My changes were primarily

 

1.	Adding iCVP to SW so that if they are sent to the Casbin they don’t trigger an annoying “Bad Data” warning.
2.	Adding BH and ELR cvp changes to Infantry SMC (in PiF mainly).

 

I can’t think of anything else I need to add at present. Back to you. 

 

Doug

**Comment by derimmer** [comment]
Al, hold on this. More testing found a bug or two. I will get you a new version shortly.
