### ISSUE TITLE
Weather/EC counters missing image files

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#645]
Some of the new image files that Allan C kindly created for the new Weather/EC counters did not get pushed up to VASL.

**Comment by bkemp01** [comment]
FYI seem to be a few others...
- Bad Data in Module: Image not found Currentright.png
 - Bad Data in Module: Image not found WinterExtreme.png
 - Bad Data in Module: Image not found FBbr44-Typhoon(rkt).png
 - Bad Data in Module: Image not found FBbr44-Typhoon.png
 - Bad Data in Module: Image not found ObsPlaneL19.png
 - Bad Data in Module: TACP Radio malf [Send to Location - Send to Axis Casualties] - Zone not found Zone[{"Axis Casualties"}]=Axis Casualties
 - Bad Data in Module: TACP Radio malf [Send to Location - Send to Allied Casualties] - Zone not found Zone[{"Allied Casualties"}]=Allied Casualties
 - Bad Data in Module: Image not found FBam44-P47.png
 - Bad Data in Module: Unrecognized image type air
 - Bad Data in Module: Image not found ObsPlaneAN-2.png
 - Bad Data in Module: Image not found ObsPlanePo-2.png

**Comment by derimmer** [comment]
As we say in the Navy, fuck!

 

This is enough that I will have to issue a revised mod. Damn. Sloppy work on my part. 

 

What were you doing to get the TACP Radio error? It should not have a CVP value, should it?

 

Thanks for finding this.

**Comment by bkemp01** [comment]
Right click on the counter in the tray

![image](https://user-images.githubusercontent.com/4276070/79495880-42a34c00-7ff3-11ea-8d17-7ecdc886cc98.png)

**Comment by derimmer** [comment]
Sorry for these errors. We had a lot of counter changes to deal with and I messed up a few. 

The weather counter missing images have been added. Al is sending me some missing images for the planes and I will add them to the module. The TACP counter should not have the Cas Bin menu as it is a SW. However, it was created using the unit prototype and so it does have the menu. Al, any reason why you used the unit counter? If not, I suggest we change the prototype to whatever is used for SW normally. If there is a reason to use the Unit prototype, I can set the counter's CVP value to 0 which will eliminate the error messages.

**Comment by BigAl737** [comment]
Re the TACP malf marker: It needs to be able to HIP, Move, Label, Disabled, Clone and Delete. I don't think it needs to Conceal. I think I chose the Unit prototype as it gave me the first 3. I added the 4th directly to the counter itself. Clone and Delete are inherent. If there's another prototype that would give you the first 3 and not cause the error message, feel free to use it instead.

![image](https://user-images.githubusercontent.com/10384413/79531084-bbb79900-801d-11ea-8397-a3672e65e637.png)

**Comment by BigAl737** [comment]
If you could add one more blank piece, then the red and blue would line up nicely:

![image](https://user-images.githubusercontent.com/10384413/79531469-e9e9a880-801e-11ea-8faa-800d46da7117.png)

**Comment by derimmer** [comment]
I have created a vasl-6.5.1 module available at the link below. It fixes all of the errors Brian found. Plus I changed the Axis OB and Allied OB tab names. See what you think. 

https://www.dropbox.com/s/btvfwi883hhk20g/vasl-6.5.1.vmod?dl=0

I would appreciate it if someone could test it to make sure I got it right this time.

A couple of notes: please look at the US and British FB in particular. Have we got all the necessary images there? Any duplications? Are the w/o Bomb sides correct in all cases?

Brian, please note that the error you came across "Unrecognized image type air" is associated with the Chinese Air tab in the BFP extension. The Chinese do not have an Air tab in the core VASL module. 

Al, I fixed the Korea OBA tab as per your request. Setting the CVP value for the TACP Radio Malf counter to 0 removed the error reporting without messing up anything else so I went for the simple solution. 

If this module passes the test, I will use it to integrate Sam's helpful notes on the dist directory. 

I may wait a while before releasing it to the world in case anything else pops up.

**Comment by bkemp01** [comment]
Found an additional instance of the TACP Radio Malf counter and another missing image...

![image](https://user-images.githubusercontent.com/4276070/79672026-4920f780-819c-11ea-9f47-d73b125044f9.png)

**Comment by derimmer** [comment]
Thanks. Yes, and there is one other ObsPlane as well, Fi-156.. Al sent me the counters and I plain forgot to add them 

In terms of the TACP, this is the one I worked on. 

1. Where is the other one? I knew it was there but could not find it for the life of me today. 
2. The error message occurs (a) as soon as you right click the TACP Radio Malf counter or (2) when you select the Send to Cas Bin option from the pop up. In my version, the Allied and Axis options are greyed out when I click on Send to Cas Bin and I don't get the error.

**Comment by bkemp01** [comment]
The TACP Radio Malf counter appears in 2 locations...
1. Other > OBA - Korea
2. Allied/UN O/B > American > HS > Korea > USMC

**Comment by derimmer** [comment]
OK. I have updated these additional errors and fixed an error reporting issue with Gliders. They contain the Cas Bin functionality but again I have set the value to 0. It is a case of all planes or no planes as they all derive from the Plane prototype. 

Brian, I noticed that my version of the BFP extension is dumping a lot of counters into the Russian Air tab for some reason. I think the counters are also showing up where they should be. Not sure if they are all BFP counters but they all go away when I remove the extension. Could be an error just with my version as I edited it and maybe screwed it up.

**Comment by bkemp01** [comment]
Looked at the BFP extension problem mentioned and what I'm seeing is caused by renaming the top level o/b tabs. This breaks any extension that adds counters to an existing allied/axis o/b.

**Comment by derimmer** [comment]
OK. Well, I won't push that change up to github! <sound of truck backing up>.

**Comment by derimmer** [comment]
I have pushed the counter fixes to develop without changing the tab names from their original names.

**Comment by derimmer** [comment]
Missed an error
