### ISSUE TITLE
Hi I found the 6.5.0 vasl mode make the mistake

### ISSUE THREAD

**Issue by xigema** [vasl-developers/vasl#647]
chinese army,north korea set as Axis OOB

I suggest that put all the FW module in the FW OOB as well.

thanks

**Comment by derimmer** [comment]
Personally, I think a better solution would be to rename the Allied OB tab Allied/UN OB and to rename the Axis OB tab Axis/Communist.

**Comment by xigema** [comment]
thanks for reply. I think that would not be a good ones for the Tab.I guess maybe this is for program settings.So may i ask if what could i do things for helping as that would be a single tap as Communist OB and UN OB.thanks.

**Comment by derimmer** [comment]
VASL is an open source tool so you are free to make changes to it as you wish. See the Wiki tab at the top of the screen for instructions on how to get started. I would also suggest that you look at the VASSAL design guide on the VASSAL site as you will probably need to use the VASSAL editor to edit the VASL module. If you want changes available to the wider community you should push changes to this github repository as explained on the wiki.

**Comment by zgrose** [comment]
Axis / Communist is going to make for a needlessly long tab name, IMO. I liked Axis / Allies / FW myself but I agree that the Axis/Allies labeling is pervasive (e.g. SAN) so having the mapping at the top of the counter hierarchy helps orient the user to what to expect in the rest of the system.

**Comment by bkemp01** [comment]
Renaming the top level allied/axis o/b tabs breaks every extension that adds counters to an existing o/b. As @zgrose said the use of allied/axis is pervasive within VASL. This either needs to be left alone or the KFW forces moved to a completely separate tab structure.

**Comment by zgrose** [comment]
I thought VASSAL assigned IDs to elements, but looking through the buildFile I see that is only the case for pieces. I agree, that pretty much kills changing the tab labels.

**Comment by xigema** [comment]
thanks to all. I have done some test about this issue.Result is like below:
(My changed to FW oob tap is name 6.5.0S)
1.in 6.5.0S it is seen that load a map need to choose the map twice. In 6.5.0 and 6.4.3 is OK.
2.in 6.5.0S that Sniper is not used.

I guess R1 is not known for reason and I need your help.
And in R2 as the Set Scenario Information is only can type  Axis/Allied so the problem is found there maybe.

So that It seems to be a big case to fit that problem.Need more ways to think about it.

**Comment by derimmer** [comment]
I think we can all agree that renaming the Allied O/B tabs and Axis O/B tabs is not the right way to go and would create more problems than it solves. 

That leaves what to do about the KFW counters. Moving them to a completely separate tab structure is doable but is a lot of work that would be prone to errors. 

In the interim players can continue to use the KFW extension if they prefer its structure to the 6.5.0 organization.

**Comment by zgrose** [comment]
If you edit the XML directly, I don't think it would be that bad to move them around. I'll try to take a first pass at the process this week.

**Comment by derimmer** [comment]
@zgrose I am just about to push up to github changes that will fix the minor counter errors founds so far (missing images mainly). That will include a new version of the buildFile. I would suggest using this new version.

**Comment by zgrose** [comment]
Yup, I was more going to validate that we could simply cut and paste my way to #winning before I really sat down and did it. I will use the most current buildFile.

**Comment by xigema** [comment]
Thanks many to you both. I could think that would be a hard work for the legecy settings.  It is hard to learn program in Java for me,because my work is using the Unity3d Tools to program for colleges.I would be happy to accept ,If you could give me some ways of doing on this project,Thanks
