### ISSUE TITLE
Possible Missing Russian MG counter?

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#649]
I received this as a message on GS:

"Could you ask your VASL gurus to add the counter for 12.7mm (russian version of the 50 cal) to the russian counter mix, I think it is important the weapon is used during stalingrad etc ,and if I remember correctly cannot be dissassembled. It is widley used and the US 50 cal is the wrong counter for this era of the war. I tried to add a picture, but cannot do it from here.They are in the votg, and red factories, and Festung Budapest I believe."

I don't have enough historical knowledge to know if a counter is needed/worth-the-effort or not. 

If not, feel free to close this issue.

**Comment by zgrose** [comment]
Looks to be referring to this counter.
![_hmg](https://user-images.githubusercontent.com/5044847/79760943-69f56400-82e6-11ea-8494-0eabc18e5b13.png)

**Comment by BigAl737** [comment]
I'm working on counters now so I will do this.

**Comment by BigAl737** [comment]
ruHMG50(r).png

![ruHMG50(r)](https://user-images.githubusercontent.com/10384413/79773671-36164080-82de-11ea-8ea4-c960daee80c1.png)

ruHMG50(r)b.png


![ruHMG50(r)b](https://user-images.githubusercontent.com/10384413/79773676-37476d80-82de-11ea-9b16-4672932df352.png)

Can't find a dm counter for this mg. I checked VotG, BV, FB, and RF. It doesn't say "no dm" on the back of the counter. I'm guessing it should. Maybe there is errata I'm missing?

**Comment by zgrose** [comment]
A9.8 shows an Russian .50 cal HMG dismantled counter. No idea if they crafted an alternate version for this alternate weapon image. I bet we could share the dm counter for both though...

![_hmg2](https://user-images.githubusercontent.com/5044847/79776039-c1053400-82fa-11ea-94de-a260884de2da.png)

**Comment by BigAl737** [comment]
So it appears it can dm. And I'd agree that it would share the .50 cal dm counter. I'll put a word out on GS to confirm. Else here's the dm counters; just a simple name change of the existing counters.

ruHMG50(r)dm.png

![ruHMG50dm](https://user-images.githubusercontent.com/10384413/79780576-9611e480-82e8-11ea-8497-fa495b5c9b9b.gif)

ruHMG50(r)dmb.png

![ruHMG50dmb](https://user-images.githubusercontent.com/10384413/79780639-ae81ff00-82e8-11ea-93c6-1a2079008670.gif)

**Comment by BigAl737** [comment]
After a productive GS discussion: [http://www.gamesquad.com/forums/index.php?threads/russian-50-cal-hmgs.157339/post-2016046](url)

I think we can add these 4 counters to the Russian SW window (frontside/backside):

OFFICIAL:
![ruHMG50(r)](https://user-images.githubusercontent.com/10384413/79907187-acda3900-83c5-11ea-9c45-62ca2d53f9ec.png)
![ruHMG50(r)b](https://user-images.githubusercontent.com/10384413/79907197-b368b080-83c5-11ea-865a-c83f18d5f659.png)


![ruHMG50(r)dm](https://user-images.githubusercontent.com/10384413/79907203-b6fc3780-83c5-11ea-9dd7-b68d6f5d7e39.png)
![ruHMG50(r)dmb](https://user-images.githubusercontent.com/10384413/79907211-ba8fbe80-83c5-11ea-9640-141b563bc819.png)

OPTIONAL:
![ruHMG50(r)](https://user-images.githubusercontent.com/10384413/79907234-bf547280-83c5-11ea-824d-8f41524c33e3.png)
![ruHMG50(r)b](https://user-images.githubusercontent.com/10384413/79907245-c4192680-83c5-11ea-8438-b411b45dc2b6.png)


![ruHMG50(r)dm-opt](https://user-images.githubusercontent.com/10384413/79907256-c7acad80-83c5-11ea-811c-0cbaabf96cf1.png)
![ruHMG50(r)dm-optb](https://user-images.githubusercontent.com/10384413/79907270-cbd8cb00-83c5-11ea-9343-81f45bc05d9c.png)

The front side of the optional counters should be labled OPT 5PP once created in the counter window.

**Comment by zgrose** [comment]
Not so sure grudge SSR counters should be in the main module since there is no guidance as to why they are present.

**Comment by BigAl737** [comment]
I see your point but I don't think it's consistently followed. There's counters in core that I don't recognize from an official source...
![image](https://user-images.githubusercontent.com/10384413/79936088-f9903500-8402-11ea-901f-b7c8a5020143.png)
for instance.

Not saying I disagree but if we don't add them to core, where do we put them?

**Comment by zgrose** [comment]
Yes, but that counter doesn't *look* like a Russian HMG in every way except the PP so the odds of confusion are low.

> if we don't add them to core, where do we put them?

Well, you guys already know I'm a big fan on the modular design over the monolithic app design, so I'd put optional counters in an optional extension!

Just my 2 cents... As long as it's clear in the UI how to get the "rules-standard" counter and the "homebrew" version, then I think the likelihood of people playing with the incorrect counter can be somewhat mitigated.

**Comment by BigAl737** [comment]
I agree that two practically identical counters side by side could be confusing, label or no. I don’t want that either. 

I like the idea of a home brew extension but that’s an issue for another time I think. 

How about I add a layer trait to the dm counters that overlays 3pp with 5pp? The short cut could be labeled “optional 5pp“. There’d be one dm counter but with two pp options. The default would be 3pp. Players must physically change it to 5pp. Sort of like the counter equivalent to a board SSO.

**Comment by zgrose** [comment]
BTW, the point on GS about dismantling to 5PP is pretty valid, too. Why bother?

**Comment by BigAl737** [comment]
Okay, the verdict is out, no 5pp option. Add a new HMG(r) and HMG(r) dm counter to the Russian SW window.

HMG(r) Front:
![ruHMG50(r)](https://user-images.githubusercontent.com/10384413/80642547-22bc5100-8a13-11ea-9ebd-76c6d7f5c991.png) 
Back:
![ruHMG50(r)b](https://user-images.githubusercontent.com/10384413/80642566-28b23200-8a13-11ea-871d-05efb934337f.png) 


HMG(r) dm Front:
![ruHMG50(r)dm](https://user-images.githubusercontent.com/10384413/80642578-2c45b900-8a13-11ea-8028-d7b53f30849c.png) 
Back
![ruHMG50(r)dmb](https://user-images.githubusercontent.com/10384413/80642596-310a6d00-8a13-11ea-954a-72ce7cce2cf7.png)

**Comment by BigAl737** [comment]
Incorporated into VASL 6.5.1.
