### ISSUE TITLE
Counter naming error: FT-17 730(f) and FT-17 730m(f)

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#653]

**Comment by BigAl737** [comment]
I recall this being completed?

**Comment by derimmer** [comment]
I don't remember one way or another. I can't find a commit that deals with it nor can I find the original post that caused me to create the issue. And I don't recall what the issue was. 

I am no help at all! LOL.

**Comment by derimmer** [comment]
Checked with rulebook. Names of CMG and 37 version are still reversed in VASL. Will push fix today.
