### ISSUE TITLE
British LMG (KW version) missing a dash

### ISSUE THREAD

**Issue by BigAl737** [vasl-developers/vasl#655]
This counter (under mouse pointer):
![image](https://user-images.githubusercontent.com/10384413/80245009-6a5b6b00-8616-11ea-9f88-ced0f9c6c6c6.png)
is missing the dash between FP and range and the spray fire underline.

Corrected counter:
![brLMG(2-8)KFW](https://user-images.githubusercontent.com/10384413/80245292-e8b80d00-8616-11ea-9519-b5d714f45ff6.png)

**Comment by BigAl737** [comment]
Incorporated into VASL 6.5.1.

**Comment by derimmer** [comment]
Atta boy Al!
