### ISSUE TITLE
KFW M37 HMC SPA Errata

### ISSUE THREAD

**Issue by BigAl737** [vasl-developers/vasl#658]
Per MMPs errata:
http://www.multimanpublishing.com/tabid/58/CategoryID/4/ProductID/333/PageIndex/3/Default.aspx

This vehicle is not turreted. Here's the corrected counter:
![usM37HMC](https://user-images.githubusercontent.com/10384413/80641862-fd7b1300-8a11-11ea-9edc-010fd930b599.png)

The turret prototype will need to be corrected as well. It should change to:
![image](https://user-images.githubusercontent.com/10384413/80642046-49c65300-8a12-11ea-948b-7573bde0c6fa.png)

Doug, I hope this is an adequate manner to get errata like this to you for inclusion in the next update.

**Comment by derimmer** [comment]
Yes, perfect. Thanks.

**Comment by BigAl737** [comment]
Cool. I don't mind adding the counter image to the image folder and modifying the build file. 
But I'm not sure if those changes will be captured for the next release.

**Comment by BigAl737** [comment]
There's a couple of others for the next release as well:

#659  #655 and #649

**Comment by derimmer** [comment]
I am not rushing the next release as the VASSAL guys are also making some changes to VASL to make it compatible with VASSAL3.3. I want to make sure that is all done before releasing a new version. And understand what the users will have to do. Will we all have to install a new java rte version? I don't know.

So, if you want to go ahead adn make these changes in the build file, that would be great and we will be able to wait until you are done. I am not planning on doing much work on VASL in the next couple of months as I try to wrestle the AREA project to the ground.

**Comment by BigAl737** [comment]
Well it's never easy...

I tried to push the counter images for this issue and the others mentioned above using the online interface but it put them in the main VASL repo. Then I tried to put the counters in their correct folders using SourceTree but SourceTree says I have an invalid user name or password even though I can log onto GitHub. Never had that issue with SourceTree before and don't know how to fix it.

**Comment by uckelman** [comment]
> Will we all have to install a new java rte version? I don't know.
Windows and Mac packages for 3.3.0 will have Java bundled with them. Linux will not, but this is generally not a problem on Linux since most distros have package management.

**Comment by derimmer** [comment]
Good to know. Thanks. 

I am thinking that the VASL version that works with VASSAL3.3.0 should be VASL7.0?

**Comment by derimmer** [comment]
@BigAl737 when you referred to the "online interface" did you mean the upload button on GitHub? If not, give that a try. You might have to be in the right images folder before you click. I am not sure as I have never used it but would seem to work. If you are going to try it this way, I would do it straight into develop and not to a branch.

As for SourceTree, shut it down, try it again. If it still doesn't work, create a new account.

**Comment by uckelman** [comment]
> I am thinking that the VASL version that works with VASSAL3.3.0 should be VASL7.0?

I would call it 6.6 if it's only the changes I'm making for compatibility, but it's not up to me.

**Comment by BigAl737** [comment]
@derimmer That is the online interface I used after having all the issues with SourceTree. It worked great but I didn't have the correct folders selected when I uploaded. Lesson learned.

I spent some time this morning sleuthing online trying to troubleshoot SourceTree and actually found something that worked. Will see what happens next when I try to update the build file. So for now, problem solved and all new counters are nestled in their correct folders.

**Comment by derimmer** [comment]
@BigAl737 what doesn't kill you makes you stronger! LOL

**Comment by zgrose** [comment]
I like 6.6 as well.

**Comment by BigAl737** [comment]
Doug, is the buildfile in VASL/dist the same one that's in the VASL 6.5.0 release? If not, can you build me a VASL version that has the most current buildfile? I don't want to lose any changes you've been making when I update the build file for this issue and #649. Thanks.

**Comment by derimmer** [comment]
The buildfile in VASL/dist in develop is the most current one which includes some updates I made to fix other errors in 6.5.0. It is definitely the one you should use. 

I don't believe any of the changes being made in relation to VASSAL would impact the buildFile.

**Comment by uckelman** [comment]
> I don't believe any of the changes being made in relation to VASSAL would impact the buildFile.

They won't. They're purely code changes.

**Comment by BigAl737** [comment]
Incorporated into VASL 6.5.1.
