### ISSUE TITLE
KW Phase Track Bug

### ISSUE THREAD

**Issue by BigAl737** [vasl-developers/vasl#659]
From GS:
http://www.gamesquad.com/forums/index.php?threads/vasl-kw-bug.157443/post-2017399

I confirmed this.

I can fix this by editing a couple of lines in the build file. Doug what's the protocol for modifying the build file so that the fix is imported for the next release?

**Comment by derimmer** [comment]
Once you have changed the build file locally you need to push it up to github - first to your branch and then create a pull request to merge it into develop. Once it is in develop then it will be in the next version whenever that is released.

**Comment by BigAl737** [comment]
Incorporated into VASL 6.5.1.
