### ISSUE TITLE
Clean up Extensions page of vasl.info

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#675]

**Comment by derimmer** [comment]
VASSAL Bug Report 14265 contains a reference to class QCMod which I can only find in extension chatter-plus-2.21.vmdx. This extension is currently marked obsolete - in normal VASL system. 

Anyone know of a reason not to delete this from the Extensions page since it appears that it can cause crashes?

**Comment by styson** [comment]
I removed the reference.

**Comment by derimmer** [comment]
Is there a reason not to delete the KFW extension from the extensions page on vasl.info?

**Comment by hongkongwargamer** [comment]
Doug - there are ASL’rs who are vehemently against classifying “Communist Chinese" as “Axis”.  Providing the KFW extension allows a way to access the Forgotten War counters without surrendering to the hated classification.

**Comment by derimmer** [comment]
closing as no further action required
