### ISSUE TITLE
Extracting and generalizig VASL ASLSniperFinder for other modules

### ISSUE THREAD

**Issue by wga8888** [vasl-developers/vasl#679]
VASL ASLSniperFinder highlights the location of the Snipers on board that may be 'lost' in map with high counter density.  This problem exists for other key counters in modules of other game titles.  I am revamping THE LONGEST DAY vassal module, leading a project team.  I would like to gain the ability to highlight a number of key counter types in a campaign game map which may have 1000+ counters in play.  Such as where are the few Replacement counters, Supply counters, etc.  I see value in other modules I have/exercise with large maps/high counter densities. 

 I would like to gain the configurable (java class files?) code to export this capability into the VSQL (Virtual Squad Leader module) and in modified form for some of my other modules for commonly used markers in those titles. Not being a java programmer myself, I would require assistance from someone with the necessary expertise skill and access to the VASL code; where I can then use Add Imported Class. bill@wargameacademy.org . ocat

**Comment by Wargamerx** [comment]
No need to export java.  Assign marker values to the types of units you
want to highlight and then give them a layer that is displayed when they
select the specified hotkey.  Check out the Case Blue/Guderian's Blitzkrieg
2 module for examples

**Comment by wga8888** [comment]
Thanks,
  
 will look into it.  I ahve been doing modules since the start but am not up to date on the newer capabilities.
  
  Bill Thomson 817-501-2978 CST (-6 GMT) skype: wga8888; www.wargameacademy.org; Discord #7339

  
 -------- Original Message --------
> From: "Wargamerx" <notifications@github.com>
> Sent: Sunday, May 10, 2020 8:30 PM
> To: "vasl-developers/vasl" <vasl@noreply.github.com>
> Cc: "wga8888" <bill@wargameacademy.org>, "Author" <author@noreply.github.com>
> Subject: Re: [vasl-developers/vasl] Extracting and generalizig VASL ASLSniperFinder for other modules (#679)
>
> No need to export java. Assign marker values to the types of units you
> want to highlight and then give them a layer that is displayed when they
> select the specified hotkey. Check out the Case Blue/Guderian's Blitzkrieg
> 2 module for examples
>
