### ISSUE TITLE
Add counters from CdG/Dinant

### ISSUE THREAD

**Issue by BigAl737** [vasl-developers/vasl#683]
Counters are done. I'll be uploading them to images asap.

**Comment by BigAl737** [comment]
Counters are in images.

I'll be adding them into VASL by modifying the buildfile. I'll make sure to use the latest buildfile version before doing so. Probably do this in several merges so as not to tie up the buildfile for any length of time. Will announce here when I start on one of the updates.

**Comment by BigAl737** [comment]
I'll be updating the buildfile through out the day. You'll see a commit when I'm done. Thanks.

**Comment by BigAl737** [comment]
CdG and Dinant additions are done though I need to test each piece for functionality and confirm the VP values. If you have time, see what I've done and make suggestions for how to do it better. I also took the opportunity to do some clean up and reorganization of the KW turn markers. Finally, I added the missing KW US LMG.

**Comment by BigAl737** [comment]
Doug, I've got a little more clean up to do. Can you give me a week or so heads up before you release a new VASL version? Thanks.

**Comment by derimmer** [comment]
Take the time you need. No one is clamouring for it so we can wait. The bug fixes are minor to CdG/Dinant is the main reason to release.

 

Doug

**Comment by BigAl737** [comment]
I'm updating the build file today. I'll be done by tonight if folks could avoid making changes to it till then. I'll post here when I'm done. Thanks.

**Comment by BigAl737** [comment]
Done with the build file mods. CdG/Dinant is ready to go.

**Comment by BigAl737** [comment]
Incorporated into VASL 6.5.1. Will open a new issue as required to handle any needed corrections.
