### ISSUE TITLE
BSO disabling all los - can they be like other overlays?

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#686]
From @zgrose 
Here is a new idea though... Some BSO are pretty benign. For example, the LOS stops in my scenario (the ASL231 file) because I used the BSO to put in a bridge.
VASL.build.module.map.boardPicker.BoardException: Unsupported scenario-specific rule: BSO_40_I1-I4Bridge. LOS disabled

This seems super harsh for what should be a helpful BSO but it turns off LOS on 98% of the map because of 2 hexes. This makes me want to avoid using BSO since the cost-benefit equation has flipped against wanting nice looking maps if I lose my LOS features.

Would it be a big stretch to offer the user the opportunity to keep LOS knowing that BSO x, y, z may make the results dubious? That is, does the LOS engine break if you just leave it enabled but there is a BSO change somewhere on the map?

**Comment by BigAl737** [comment]
Or maybe identify these more benign BSOs and convert them for use through the VASL Overlay extension instead.

**Comment by zgrose** [comment]
And some of them certainly are (bridges, for example). I think the problem is that lots of BSO don't make for good, canned overlays, but I could be wrong.

**Comment by derimmer** [comment]
Just pushed up some changes that now treat BSO and SSO overlays as regular overlays for los purposes. LOS is no longer disabled for the entire board but only when crossing an overlays (and the usual warning message shows). 

Some terrain transformations (ie Light Woods) are implemented graphically by overlays. In these cases, los was still working everywhere. I don't think I have broken this!

@BigAl737 I have done this on the assumption that BSO and SSO overlays all contain "BSO" or "SSO" in the overlay name. I am sure we will find exceptions to this. It will be fixable by updating the bdXX file and not by changing the mod so that is a good thing. I would certainly encourage using "BSO" and "SSO" when naming such overlays.

**Comment by BigAl737** [comment]
@derimmer ...

Copy your last. This should go in some instruction manual or something, else I'll forget :-)

Will the code you implemented to recognize BSO or SSO in the overlay name work with BSO or SSO overlays drag and dropped from the Overlays extension?

**Comment by derimmer** [comment]
> Will the code you implemented to recognize BSO or SSO in the overlay name work with BSO or SSO overlays drag and dropped from the Overlays extension?

Good thought. I had overlooked this.

The answer, now that i have checked, is no, because it doesn't need to. The draggable overlays, because they are actually counters, are handled differently by the los engine. I have tested the basic overlays, one of the RB overlays and the one SSR overlay that I could find (bd25). All worked as intended.
