### ISSUE TITLE
What's the difference between bd25 and bd25a?

### ISSUE THREAD

**Issue by BigAl737** [vasl-developers/vasl#699]
Both are in the vasl boards bdfiles folder.

bd25 is in vasl boards src folder but bd25a is not.

Thanks.

**Comment by bkemp01** [comment]
I don't see a difference, but I do see a scenario that needs 2x bd25... DftB#6 First Clash in Tunisia

**Comment by derimmer** [comment]
I believe that I have fixed the Vaal code to allow for this and keep los working. But of course this is bd25 so los does not work anyway. But 2 boards of the same number should.

**Comment by BigAl737** [comment]
Thanks. I'll test this before I close this issue.

**Comment by BigAl737** [comment]
Test results:

VASL will allow you to open two same numbered boards and the LOS works inter and intra board.

VASL will allow you to open 2 bd25's.

The LOS engine dies whenever bd25 is in play, singly, doubly, with other boards...etc. I could not get the LOS engine to work with bd25 in play in any form or fashion. 

I don't think there is a need for bd25a but I'll let someone else make that call.

**Comment by derimmer** [comment]
los does not work on any of the desert boards, including bd25 as they use a non-standard color palette. It may be time to have another look at that. I will create an issue.

**Comment by BigAl737** [comment]
Roger. What I didn't know is that bd25 kills the LOS engine on other non-desert boards in play as well.

**Comment by derimmer** [comment]
We have now created bd25ETO on which los works. And so now los works on bd25 as well. It still doesn't work on other desert boards.

I think we can ditch bd25a. I will delete it and we will see if anyone notices!
