### ISSUE TITLE
Underlays do not work with overlay files

### ISSUE THREAD

**Issue by davidsullivan317** [vasl-developers/vasl#70]
Underlays do not work with overlay files

**Comment by derimmer** [comment]
Does anyone remember what problem this causes? Does it matter?

**Comment by BigAl737** [comment]
I don't recall. David is still around I believe.

**Comment by davidsullivan317** [comment]
"Underlays" are the color changes to SSR support transformation like "grain is open ground." These are not enforced on overlays. The only pain point if I remember is winter colors with overlays, where it looks pretty garish.

**Comment by derimmer** [comment]
Been doing some testing on this and it seems to be working (why, I don't know) for some transforms. 

![underlaytest](https://user-images.githubusercontent.com/7696161/127206585-a5635179-0199-4b0e-b3e4-e9fb5054e392.PNG)

In the image above, the orchard, building and brush overlays were added before the snow transform. The woods in AA were added afterward. 

Are there other issues that are still not solved? I know that if you add terrain overlays to hills they still show a ground level background. Anything else?

**Comment by derimmer** [comment]
I have fixed the issue with overlay ground level when placed on hills/valley. The level 0 terrain now changes to the hill/valley OG colour. This works for the old school overlays and not @BigAl737 's fancy drag-and-drop extension, which would require a different solution. Commit coming soon.
