### ISSUE TITLE
Release VASL6.5.1.beta

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#711]
I am ready to build 6.5.1-beta1. Here is the list of changes: 

New in version 6.5.1-Beta1:
Counters, lots of lovely Counters:
The CdG/Dinant counters are added in this release
Bug fixes:
	There a number of bug fixes to the KFW counters added in 6.5.0
The EC/Weather counter labels can now be changed/removed and several bugs are fixed
A missing acquisition counter was added to the QC bar acquisition dropdown
Change to the Counter Search algorithm to allow for more near misses to produce a result (eg. partials like "mine" should find minefield counters.

It is a small list but there a numerous counter fixes along with Al's great job of banging out CdG/Dinant. I don't see anything major waiting in the wings. I would like to get this out now and then focus on 6.5.2 which would be 6.5.1 but running under VASSAL3.3.0 (with Java11 built in). 

Anyone working on something I should wait for?

**Comment by BigAl737** [comment]
Not me.

**Comment by bkemp01** [comment]
nothing new for me either

**Comment by derimmer** [comment]
the beta has been out for a month with no major issues. I am ready to release it officially, incorporating the additional commits that Al has pushed up since the beta release. Anyone working on anything else that I should wait for?

Unless there is a reason to wait, I will release 6.5.1 next week.

**Comment by derimmer** [comment]
Can somebody have quick look at the website repo and tell me why the VASL6.5.1 download isn't working. I built the module and uploaded it as I normally do. As far as I can see the filenames are a perfect match as required. Must be something small that I am just not seeing. Need a fresh pair of eyes.

**Comment by derimmer** [comment]
Belay that. Working now. The push to the website must have been a bit slower than normal. Any vasl6.5.1 is out. 

On to the VASSAL3.3.2. We will pull it into develop shortly once we have done some cleanup up and back up in the vasl repo.
