### ISSUE TITLE
Chinese 50mm MTR(r) dm pp

### ISSUE THREAD

**Issue by BigAl737** [vasl-developers/vasl#714]
From GS:
http://www.gamesquad.com/forums/index.php?threads/updated-vasl-counter-needed.158088/post-2023534

The VASL version shows 2pp. The print version shows 3pp:

![MTR(r)](https://user-images.githubusercontent.com/10384413/86971459-af734180-c11d-11ea-88fe-655ca273b37e.jpg)

I'll fix this by uploading the following:

![chM50rdm](https://user-images.githubusercontent.com/10384413/86971541-d3368780-c11d-11ea-98f3-6878ce9004bc.gif)
![chM50rdmb](https://user-images.githubusercontent.com/10384413/86971548-d598e180-c11d-11ea-960e-ccce2b191bdb.gif)

**Comment by BigAl737** [comment]
@derimmer , as I understand it, this fix will automatically be included with the next VASL version you release. There is no further action on your part. I'm leaving this issue open however in case it helps you to remember that this should be part of the next VASL release. You may close it at your discretion.

**Comment by derimmer** [comment]
If you have pushed it to develop that will be the case.

**Comment by BigAl737** [comment]
I did push it to develop. Thx Doug. Closing this issue now.
