### ISSUE TITLE
Issues Cleanup

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#718]
Now that 6.5.1 is out, I suggest it is time to clean up our issues list. For those who have assigned themselves issues, I think there are a number that could be closed. I leave it up to you to decide (I ain't your mama. LOL).

@BigAl737 
#683
#680 
#663
#659
#658
#655
#654
#649
#593
#547

@bkemp01 
#617
#599

Unless anyone objects I am going to close #679, #678, #677, #676 as these seem to have nothing to do with VASL development, 

I have created a 6.5.1 release and tag in the repository (properly I think) and created the release-6.5.1 branch. 

With that I think we can move on to VASL6.6.0 featuring VASSAL3.3.2.

I will wait a couple of days before pulling VASSAL3.3.2 changes into develop in case anyone has any issues/comments.

**Comment by BigAl737** [comment]
#617 was assigned to me. It's not completed so I left it opened. Else all other issues referenced to me above have been closed.
