### ISSUE TITLE
Draggable overlays appear to be off set when zoomed out

### ISSUE THREAD

**Issue by davidsullivan317** [vasl-developers/vasl#72]
When I zoom out on my map view any draggable overlays appear to be off set from there original position. Not sure whether this is a bug in Vasl or a problem with my computer graphics.

**Comment by derimmer** [comment]
Given the age of this, I assume this refers to overlays accessed via the orchard button on the toolbar and NOT overlays dragged from the overlays extension. I checked using those old draggable overlays today and they all stayed put when zoomed out. Whatever the causes, it seems resolved. Closing this one.
