### ISSUE TITLE
Overlay problems

### ISSUE THREAD

**Issue by davidsullivan317** [vasl-developers/vasl#73]
Strange overlay problem see in two places: DTO (http://forums.gamesquad.com/showthread.php?114157-Weird-bug-using-wadis-in-broken-terrain&p=1621534#post1621534) and PTO (http://forums.gamesquad.com/showthread.php?111256-VASL-5-9-3-Support-Thread&p=1576065&viewfull=1#post1576065     also   http://forums.gamesquad.com/showthread.php?111256-VASL-5-9-3-Support-Thread&p=1577431&viewfull=1#post1577431)

**Comment by davidsullivan317** [comment]
Not going to make 6.2

**Comment by FredKors** [comment]
I'm checking the #73. Not sure to find the problem soon.

2015-01-01 18:18 GMT+01:00 David Sullivan <notifications@github.com>:

**Comment by davidsullivan317** [comment]
Okay - didn't hear back positively that you were looking at it. We can play it by ear.

**Comment by FredKors** [comment]
#73 1st strike

I've fixed the DTO problem ((
http://forums.gamesquad.com/showthread.php?114157-Weird-bug-using-wadis-in-broken-terrain&p=1621534#post1621534)


It was due to the fact that an overlay was shared between two maps and the
copy of the overlay on the 2nd map had a (wrong) reference to the 1st map.

Complex to find but only one line of code to change.


2015-01-01 18:24 GMT+01:00 David Sullivan <notifications@github.com>:

**Comment by FredKors** [comment]
#73 2nd strike

http://forums.gamesquad.com/showthread.php?111256-VASL-5-9-3-Support-Thread&p=1576065&viewfull=1#post1576065

I've found the problem, not the solution.

The 'Use Swamp pattern for Marsh adj. to Jungle' applies two rules:
SwampToSwampPattern, that is handled directly by the overlay 5, and the
SwampToMarsh, that uses the default OverlaySSR and creates an underlay
for... the overlay. I don't know if this is correct, but the underlay
creates an image based on that of the board (and not on that of the
overlay). So, when the overlay is painted, a phantom copy of the board
(shifted, rotated and containing only the marshes) is painted also.



2015-01-01 21:52 GMT+01:00 Federico Corso <fredkors66@gmail.com>:

**Comment by FredKors** [comment]
#73 <https://github.com/vasl-developers/vasl/issues/73> 3rd strike

http://forums.gamesquad.com/showthread.php?111256-VASL-5-9-3-Support-Thread&p=1576065&viewfull=1#post1576065

My previous post was wrong.

The 'Use Swamp pattern for Marsh adj. to Jungle' applies two rules:
SwampToSwampPattern and the SwampToMarsh.

The SwampToSwampPattern is handled directly by the overlay 5 AND by the
default OverlaySSR. THIS is the problem: the specific OverlaySSR doesn't
overwrite the default OverlaySSR (that creates a wrong underlay based on
the board etc.) and both are active at the same time.



2015-01-01 23:31 GMT+01:00 Federico Corso <fredkors66@gmail.com>:

**Comment by FredKors** [comment]
I have a fix for the #73

To avoid the coexistence of a specific and a default OverlaySSR, I decided
that the default OverlaySSRs are overridden by specific OverlaySSRs (if
any).

I don't know if this is acceptable, so I created a new branch for this fix.

2015-01-02 0:11 GMT+01:00 Federico Corso <fredkors66@gmail.com>:

**Comment by davidsullivan317** [comment]
Sounds reasonable to me; I say we roll with it.

**Comment by FredKors** [comment]
Anyway Underlays work only for Boards (and not for Overlays).

Should I merge the mods?

2015-01-02 16:27 GMT+01:00 David Sullivan <notifications@github.com>:
