### ISSUE TITLE
BSO for AP111

### ISSUE THREAD

**Issue by BigAl737** [vasl-developers/vasl#736]
http://www.gamesquad.com/forums/index.php?threads/vasl-map-online-problem-suggestion-form.88223/post-2029746

**Comment by BigAl737** [comment]
These overlays are now in the Overlay extension.

**Comment by derimmer** [comment]
Al, where do we find the latest version of the overlay extension?

**Comment by BigAl737** [comment]
> Al, where do we find the latest version of the overlay extension?

Here: https://www.dropbox.com/s/87ltjtso9p7ilow/BFP_v44_DRAFT_001.vmdx?dl=0

**Comment by derimmer** [comment]
Thanks. But that's the BFP extension. I am looking for the overlay one.

**Comment by BigAl737** [comment]
Oops, sorry. The latest Overlay extension is on the VASL downloads page. v2.04.
