### ISSUE TITLE
Prisoners missing Reset CvP

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#740]

**Comment by VaslingStew** [comment]
Is this when prisoners have NO CVP?
At that point, simply don't send them to the CVP table right?

**Comment by derimmer** [comment]
This would allow for prisoners to have any value (0, normal 2 for squad, 1 hs, or double under various conditions). As with all other units, there is supposed to be a Reset option to set the value for whatever you like. Sometimes VC will say, 1 VP for every unit that . . . . So, units should be able to have variable cvp value.
