### ISSUE TITLE
Build VASL6.6.0

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#741]

**Comment by uckelman** [comment]
We're aiming to release 3.4.3 today or tomorrow, btw.

**Comment by derimmer** [comment]
OK. Thanks. I am having to put 6.6.0 on hold while I sort out the warning messages that show up when dragging a unit onto the mapboard. I am trying to use the new method in piece mover but am having no luck with it so far.

**Comment by derimmer** [comment]
When I try to run 6.6.0 in my IDE using the non-deprecated method in PieceMover, this is the error message I get:

VASSAL: File '[Ljava.lang.String;@5cde6747' of unknown type 

and the module won't start. I don't know what to make of this.

**Comment by uckelman** [comment]
Can you give me a bit more context there? What "non-deprecated method in PieceMover" are you talking about? Is there a stack trace?

**Comment by derimmer** [comment]
From VASSAL3.4.2 PieceMover:

 /** @deprecated */
    @Deprecated(
        since = "2020-08-06",
        forRemoval = true
    )
    protected void applyKeyAfterMove(List<GamePiece> pieces, Command comm, KeyStroke key) {
        ProblemDialog.showDeprecated("2020-08-06");
        comm.append(this.applyKeyAfterMove(pieces, key));
    }

    protected Command applyKeyAfterMove(List<GamePiece> pieces, KeyStroke key) {
        Command comm = new NullCommand();

        GamePiece piece;
        for(Iterator var4 = pieces.iterator(); var4.hasNext(); comm = ((Command)comm).append(piece.keyEvent(key))) {
            piece = (GamePiece)var4.next();
            if (piece.getProperty("snapshot") == null) {
                piece.setProperty("snapshot", ((PropertyExporter)piece).getProperties());
            }
        }

        return (Command)comm;
    }

VASL uses the first version of the method. With 3.4.2 this produces a warning message in chat the first (and only the first) time a counter is dragged onto the mapboard. 

I have been trying to amend the VASL code in ASLPieceMover.java to work with the second version of the method instead of the first. This is the revised code (comm is already constructed and used earlier in the method that contains this code so I had to rename it to comm1 as comm is created as a null Command in the new VASSAL method):

Command comm1 = comm;
        // Apply key after move to each moved piece
        if (map.getMoveKey() != null) {
            comm1 = comm1.append(applyKeyAfterMove(allDraggedPieces, map.getMoveKey()));   //applyKeyAfterMove(allDraggedPieces, comm, map.getMoveKey());
        }

        tracker.repaint();
        return comm1; 

I will try to find a stack trace.

**Comment by derimmer** [comment]
There is no stack trace. This is what I get when I run the module in debug mode:

"C:\Program Files\Java\jdk-11.0.7\bin\java.exe" "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA 2020.1.1\lib\idea_rt.jar=50074:C:\Program Files\JetBrains\IntelliJ IDEA 2020.1.1\bin" -Dfile.encoding=UTF-8 -classpath C:\Users\dougr_000\IdeaProjects\vasl\target\classes;C:\Users\dougr_000\.m2\repository\org\vassalengine\vassal-app\3.4.2\vassal-app-3.4.2.jar;C:\Users\dougr_000\.m2\repository\ch\qos\logback\logback-classic\1.2.3\logback-classic-1.2.3.jar;C:\Users\dougr_000\.m2\repository\ch\qos\logback\logback-core\1.2.3\logback-core-1.2.3.jar;C:\Users\dougr_000\.m2\repository\com\miglayout\miglayout-swing\5.2\miglayout-swing-5.2.jar;C:\Users\dougr_000\.m2\repository\com\miglayout\miglayout-core\5.2\miglayout-core-5.2.jar;C:\Users\dougr_000\.m2\repository\javazoom\jlayer\1.0.1\jlayer-1.0.1.jar;C:\Users\dougr_000\.m2\repository\jivesoftware\smack\3.0.4\smack-3.0.4.jar;C:\Users\dougr_000\.m2\repository\jivesoftware\smackx\3.0.4\smackx-3.0.4.jar;C:\Users\dougr_000\.m2\repository\commons-codec\commons-codec\1.14\commons-codec-1.14.jar;C:\Users\dougr_000\.m2\repository\commons-io\commons-io\2.7\commons-io-2.7.jar;C:\Users\dougr_000\.m2\repository\gnu\getopt\java-getopt\1.0.13\java-getopt-1.0.13.jar;C:\Users\dougr_000\.m2\repository\org\apache\commons\commons-lang3\3.11\commons-lang3-3.11.jar;C:\Users\dougr_000\.m2\repository\org\apache\xmlgraphics\batik-codec\1.13\batik-codec-1.13.jar;C:\Users\dougr_000\.m2\repository\org\apache\xmlgraphics\batik-awt-util\1.13\batik-awt-util-1.13.jar;C:\Users\dougr_000\.m2\repository\org\apache\xmlgraphics\xmlgraphics-commons\2.4\xmlgraphics-commons-2.4.jar;C:\Users\dougr_000\.m2\repository\commons-logging\commons-logging\1.0.4\commons-logging-1.0.4.jar;C:\Users\dougr_000\.m2\repository\org\apache\xmlgraphics\batik-bridge\1.13\batik-bridge-1.13.jar;C:\Users\dougr_000\.m2\repository\org\apache\xmlgraphics\batik-shared-resources\1.13\batik-shared-resources-1.13.jar;C:\Users\dougr_000\.m2\repository\org\apache\xmlgraphics\batik-transcoder\1.13\batik-transcoder-1.13.jar;C:\Users\dougr_000\.m2\repository\org\apache\xmlgraphics\batik-svggen\1.13\batik-svggen-1.13.jar;C:\Users\dougr_000\.m2\repository\org\apache\xmlgraphics\batik-util\1.13\batik-util-1.13.jar;C:\Users\dougr_000\.m2\repository\org\apache\xmlgraphics\batik-constants\1.13\batik-constants-1.13.jar;C:\Users\dougr_000\.m2\repository\org\apache\xmlgraphics\batik-i18n\1.13\batik-i18n-1.13.jar;C:\Users\dougr_000\.m2\repository\org\apache\xmlgraphics\batik-dom\1.13\batik-dom-1.13.jar;C:\Users\dougr_000\.m2\repository\org\apache\xmlgraphics\batik-css\1.13\batik-css-1.13.jar;C:\Users\dougr_000\.m2\repository\org\apache\xmlgraphics\batik-ext\1.13\batik-ext-1.13.jar;C:\Users\dougr_000\.m2\repository\org\apache\xmlgraphics\batik-xml\1.13\batik-xml-1.13.jar;C:\Users\dougr_000\.m2\repository\xml-apis\xml-apis-ext\1.3.04\xml-apis-ext-1.3.04.jar;C:\Users\dougr_000\.m2\repository\org\apache\xmlgraphics\batik-extension\1.13\batik-extension-1.13.jar;C:\Users\dougr_000\.m2\repository\org\apache\xmlgraphics\batik-anim\1.13\batik-anim-1.13.jar;C:\Users\dougr_000\.m2\repository\org\apache\xmlgraphics\batik-gvt\1.13\batik-gvt-1.13.jar;C:\Users\dougr_000\.m2\repository\org\apache\xmlgraphics\batik-parser\1.13\batik-parser-1.13.jar;C:\Users\dougr_000\.m2\repository\org\apache\xmlgraphics\batik-svg-dom\1.13\batik-svg-dom-1.13.jar;C:\Users\dougr_000\.m2\repository\org\apache\xmlgraphics\batik-swing\1.13\batik-swing-1.13.jar;C:\Users\dougr_000\.m2\repository\org\apache\xmlgraphics\batik-gui-util\1.13\batik-gui-util-1.13.jar;C:\Users\dougr_000\.m2\repository\org\apache\xmlgraphics\batik-script\1.13\batik-script-1.13.jar;C:\Users\dougr_000\.m2\repository\org\codehaus\janino\janino\3.1.2\janino-3.1.2.jar;C:\Users\dougr_000\.m2\repository\org\codehaus\janino\commons-compiler\3.1.2\commons-compiler-3.1.2.jar;C:\Users\dougr_000\.m2\repository\org\slf4j\slf4j-api\1.7.30\slf4j-api-1.7.30.jar;C:\Users\dougr_000\.m2\repository\org\swinglabs\swingx\swingx-all\1.6.5\swingx-all-1.6.5.jar;C:\Users\dougr_000\.m2\repository\net\java\dev\timingframework\timingframework\1.0\timingframework-1.0.jar;C:\Users\dougr_000\.m2\repository\org\netbeans\wizard\0.998.1\wizard-0.998.1.jar;C:\Users\dougr_000\.m2\repository\org\apache\maven\maven-artifact\3.6.3\maven-artifact-3.6.3.jar;C:\Users\dougr_000\.m2\repository\org\codehaus\plexus\plexus-utils\3.2.1\plexus-utils-3.2.1.jar;C:\Users\dougr_000\.m2\repository\net\bytebuddy\byte-buddy\1.10.14\byte-buddy-1.10.14.jar;C:\Users\dougr_000\.m2\repository\org\jdom\jdom2\2.0.5\jdom2-2.0.5.jar VASSAL.launch.Player --standalone C:\Users\dougr_000\IdeaProjects\vasl\target\vasl-6.6.0-beta3.jar
VASSAL: File '[Ljava.lang.String;@49d3c823' of unknown type 

Process finished with exit code 1

**Comment by derimmer** [comment]
Getting a similar warning message for VASSAL.counters.Labeler.drawLabel

In this case, both versions of the method are deprecated. So there is nowhere to go.

**Comment by uckelman** [comment]
The comment above `applyKeyAfterMove`:

```
/**
 * @deprecated Use {@link #applyKeyAfterMove(List, KeyStroke)} to return Commands
 */
```

**Comment by uckelman** [comment]
The comments for the two `Labeler.drawLabel` methods: 
```
/** @deprecated Use {@link VASSAL.tools.image.LabelUtils#drawLabel(Graphics, String, int, int, int, int, Color, Color)} instead. **/
```
```
/** @deprecated Use {@link VASSAL.tools.image.LabelUtils#drawLabel(Graphics, String, int, int, Font, int, int, Color, Color, Color)} instead. **/
```
The methods you're referred to are exactly the same, just moved to `LabelUtils`.

**Comment by derimmer** [comment]
Thanks. I do not see those comments in my 3.4.2 version of Labeler. Perhaps they are in 3.4.3. In any event, I will give them a try.

**Comment by uckelman** [comment]
They're in 3.4.2: https://github.com/vassalengine/vassal/blob/3.4.2/vassal-app/src/main/java/VASSAL/counters/Labeler.java

**Comment by uckelman** [comment]
Where did you get that code for `PieceMover.applyKeyAfterMove()` containing `var4`? That's not the code we had in 3.4.2, nor was it like that in 3.2.17.

**Comment by derimmer** [comment]
> They're in 3.4.2: https://github.com/vassalengine/vassal/blob/3.4.2/vassal-app/src/main/java/VASSAL/counters/Labeler.java

That looks nothing like the VASSAL class Labeler that is included in my IDE. I find it in my VASL project under External Libraries: 

Maven: org.vassalengine:vassal-app:3.4.2. When I select a VASSAL class from this, the path statement for it looks like this:
C:\Users\dougr_000\.m2\repository\org\vassalengine\vassal-app\3.4.2\vassal-app-3.4.2.jar!\VASSAL\counters\Labeler.class

The .m2 directory is tied to my IDE (JetBrains) if I recall correctly.

**Comment by derimmer** [comment]
> Where did you get that code for `PieceMover.applyKeyAfterMove()` containing `var4`? That's not the code we had in 3.4.2, nor was it like that in 3.2.17 (or any time between).

Same as my answer to the above. Whenever I am working in my IDE and I need to access a VASSAL class it takes me to the same place.

**Comment by uckelman** [comment]
Then something is screwed up with your IDE.

Oh, geez, could it possibly be that your IDE is showing you a decompiled version of the class files in the JAR?! That's _awful_ if that's what's happening.

**Comment by derimmer** [comment]
When I open a VASSAL class in my IDE, here's what shows up at the top. 

![vASSAL](https://user-images.githubusercontent.com/7696161/94064605-e9b4bc80-fdb7-11ea-82a6-c71e5f3534bd.png)

**Comment by uckelman** [comment]
All `applyKeyAfterMove(List<GamePiece> pieces, Command com, KeyStroke key)` does is this:
```
comm.append(applyKeyAfterMove(pieces, key));
```

So you change this
```
if (map.getMoveKey() != null) {
  applyKeyAfterMove(allDraggedPieces, comm, map.getMoveKey());
}
```
to this:
```
if (map.getMoveKey() != null) {
  comm.append(applyKeyAfterMove(allDraggedPieces, map.getMoveKey()));
}
```

**Comment by derimmer** [comment]
Sorry, I could not add more to that comment for some reason. So, should I be clicking on download sources or what? I have no idea that this isn't a valid view of the VASSAL class.

**Comment by derimmer** [comment]
> All `applyKeyAfterMove(List<GamePiece> pieces, Command com, KeyStroke key)` does is this:
> 
> ```
> comm.append(applyKeyAfterMove(pieces, key));
> ```
> 
> So you change this
> 
> ```
> if (map.getMoveKey() != null) {
>   applyKeyAfterMove(allDraggedPieces, comm, map.getMoveKey());
> }
> ```
> 
> to this:
> 
> ```
> if (map.getMoveKey() != null) {
>   comm.append(applyKeyAfterMove(allDraggedPieces, map.getMoveKey()));
> }
> ```

Nope. Doesn't work. But I may have screwed something else up trying to fix this. Very frustrated. Need to step away for a bit.

**Comment by uckelman** [comment]
I don't use an IDE, so I can't advise about what you need to do there. I've asked the other guys if they have any idea.

**Comment by uckelman** [comment]
> Nope. Doesn't work.

That change compiles just fine for me.

**Comment by uckelman** [comment]
> When I open a VASSAL class in my IDE, here's what shows up at the top.
> 
> ![vASSAL](https://user-images.githubusercontent.com/7696161/94064605-e9b4bc80-fdb7-11ea-82a6-c71e5f3534bd.png)

Do you see in the upper left there that it says "Decompiled .class file"? This is why you're seeing odd variable names and none of the comments.

**Comment by derimmer** [comment]
> > Nope. Doesn't work.
> 
> That change compiles just fine for me.

I created a new vasl project in my IDE and made the change to applyKeyAfterMove. The module builds and runs but I still get the warning message in the chat window the first time I drag a unit. Should it go away if we are using the new version of the method?

**Comment by uckelman** [comment]
The newer version of `applyKeyAfterMove()` doesn't produce that message. If you're still seeing that message, then you're still calling the old version.

**Comment by derimmer** [comment]
> The newer version of `applyKeyAfterMove()` doesn't produce that message. If you're still seeing that message, then you're still calling the old version.

Yes, I added the new one but didn't remove the old one. I am going crazy! Now it works without the warning message. So that just leaves the Labeler to LabelUtils change which is harder because it is not clear where VASL users Labeler.

**Comment by uckelman** [comment]
```
[uckelman@scylla vasl]$ git grep drawLabel
src/VASL/build/module/map/CounterDetailViewer.java:          drawLabel(g, new Point(x, y + 5), text, Labeler.CENTER, Labeler.TOP);
src/VASL/build/module/map/CounterDetailViewer.java:      drawLabel(g, new Point(x, y), report, Labeler.RIGHT, Labeler.BOTTOM);
src/VASL/counters/ASLHighlighter.java:      Labeler.drawLabel(g, p.getMap().locationName(p.getPosition()),
```
The first two instances of `drawLabel` are calling a method of `CounterDetailViewer`, so aren't relevant. It's just the last one that you need to change. The whole change is just replacing `Labeler` with `LabelUtils`, and adjusting the import.

**Comment by derimmer** [comment]
I have the last one working. Wasn't sure about the top two because they user a reference to Labeler. 

It now appears to run without the messages appearing. 

Thanks for your help and patience. I really got myself in a mess there.

**Comment by uckelman** [comment]
I hadn't spotted those---yes, those should also be switched to `LabelUtils`.

**Comment by yanlyub** [comment]
> Sorry, I could not add more to that comment for some reason. So, should I be clicking on download sources or what? I have no idea that this isn't a valid view of the VASSAL class.

Yes click on download sources to get the the actual Vassal source code, this will also add the Javadoc which you can read with ctrl+Q in IntelliJ.

**Comment by derimmer** [comment]
Thanks.

**Comment by Cattlesquat** [comment]
I would have made the same mistake.
