### ISSUE TITLE
NK units are not concealing properly

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#747]
concealing a NK smc on top of NK squads does not conceal all the units in the stack

**Comment by BigAl737** [comment]
I'll tackle this unless someone else would prefer to do it.

I hope to gain some GS community insight to the issue first.

Also, there's a suggestion out there that involves coding. If it's deemed best to go that route, I'm not your guy :-)

http://www.gamesquad.com/forums/index.php?threads/north-korean-smc-russian-counters.158804/post-2031603

**Comment by derimmer** [comment]
@BigAl737 I was hoping you would pick it up. I would be very surprised if it is a coding issue. Almost certainly a counter problem in my mind.

**Comment by BigAl737** [comment]
I've got this fixed. Also changed the Vichy French 1/2 counters to conceal as Germans.

@derimmer I'm planning on cut and pasting the entire North Korean OB, the entire Vichy French OB, and the nkXXX(KFW) prototypes to the build file. My base build file is not current with the one in the repository. Will this mess up anything you've done, like with the casualties bin?

**Comment by derimmer** [comment]
@BigAl737 I have made quite a number of buildFile changes since 6.6.1.  If it is not too much trouble, I would prefer that you use the buildFile that is currently in the repository and redo the changes. If it is a lot of work for you, let's discuss.

Did you make your changes to the 6.6.1 buildFile using the VASSAL editor or did you edit the buildfile by hand?

**Comment by BigAl737** [comment]
Hi Doug, it's no problem. I should have done that in the first place. I used the VASSAL editor but for the redo I'll edit the build file by hand. I'll make sure I don't undo anything you've done.

**Comment by BigAl737** [comment]
Here's my plan:

North Korean conceal with Russian
Vichy French 1/2" counters conceal with German (there aren't any Vichy French 5/8" counters but see below for more on this)

As for the others on the list:
Hungarian - German; already does.
Chinese - Partisan- Russian; Partisans already do. Chinese I won't change as they have their own cardboard ? concealment counters.
OUNC-South Korea - US; won't change as OUNC and SK have their own cardboard ? counters.

More on the Vichy French...

Vichy French use French 5/8" counters thus also use French 5/8" concealment counters. I don't know if that's a problem but VASL will provide this work around: Use the 
![image](https://user-images.githubusercontent.com/10384413/104957939-99bbc000-597b-11eb-9b61-f17d92e96159.png)
 counter with a text note defining the unit. This counter uses the German 
![image](https://user-images.githubusercontent.com/10384413/104957900-81e43c00-597b-11eb-867e-8e2f179b8901.png)
 counter.

**Comment by BigAl737** [comment]
Tested and pushed. The only issue I found is that the concealment status of a concealed dm'd 5/8" MTR does not carry over to the 5/8" MTR counter when assembled. The reverse is also true. This is true for all nationalities so this rates its own issue should we desire to fix this.

**Comment by derimmer** [comment]
@BigAl737 Great work Al. I have checked the buildFile in github and it is looking good.

**Comment by BigAl737** [comment]
Thanks Doug. All changes made manually. Not fully tested. More info in PR #847 comments.

**Comment by BigAl737** [comment]
I was able to open VASL 6.6.1 with VASSAL 3.5.0-SNAPSHOT-dab116dbe. Testing complete. I did not find any errors. Maybe this one can be put to bed?

**Comment by derimmer** [comment]
agreed
