### ISSUE TITLE
VASL or VASSAL error message

### ISSUE THREAD

**Issue by BigAl737** [vasl-developers/vasl#748]
I've been getting this in the text dialog box when I open VASL:

![image](https://user-images.githubusercontent.com/10384413/94380651-dc167400-00e2-11eb-8a2c-c91a14cd7581.png)

I think it is referring to one of the extensions I'm loading. Is there a way to tell which one?

**Comment by BigAl737** [comment]
VASL 6.6.0 and VASSAL 3.4.3.

I don't get this with other VASSAL modules and extensions.

**Comment by zgrose** [comment]
It will be one with java code in it, which isn't many of them. Either take em all out and add them back in one at a time or dump your extension list here and we can take some educatated guesses

**Comment by BigAl737** [comment]
Thanks Zoltan. I just finished that exercise and never got the message on any of them. So I don't think it's an extension after all.

I started a new VASSAL and VASL session and started a new game with bd00. So far so good. I then selected a new board for the scenario:

![image](https://user-images.githubusercontent.com/10384413/94382471-47634480-00e9-11eb-875f-500cedb7a177.png)

and got the error message when the board selection window opened.

![image](https://user-images.githubusercontent.com/10384413/94382320-b724ff80-00e8-11eb-9cdb-da65cdaa1dee.png)

I changed bd00 to bd04 but I don't think it's board specific. I think it's an issue with the internal change board code.

**Comment by derimmer** [comment]
These are VASSAL message built into the new versions. I worked with Joel U to eliminate a couple before releasing 6.6.0 but we are going to keep finding them. I came across one using the TerrainSSR dialog earlier today.  I suspect that 3.4.3 will contain additional ones on top of the ones added to 3.4.2.

They are info message and don't reflect an error or a crash. They can be ignored and we will be telling people this all winter.

**Comment by uckelman** [comment]
As I said in the GameSquad forum:

> You don't need to wait to hit these at runtime to find them. Add the following line to your pom.xml in the `<configuration>` section for the maven-compiler-plugin: `<showDeprecation>true</showDeprecation>`.
>
> That will make the compiler show all the deprecated methods and fields you're using. I hadn't known that false was the default for that or I would have included it in the last PR I made.

**Comment by derimmer** [comment]
> As I said in the GameSquad forum:
> 
> > You don't need to wait to hit these at runtime to find them. Add the following line to your pom.xml in the `<configuration>` section for the maven-compiler-plugin: `<showDeprecation>true</showDeprecation>`.
> > That will make the compiler show all the deprecated methods and fields you're using. I hadn't known that false was the default for that or I would have included it in the last PR I made.

Tried this. Think it worked. I got lots of deprecateds but only 8 Marked For Removal. I will work away on these but I don't want to hold up 6.6.1 for them. They will be in the spring build.

**Comment by derimmer** [comment]
Morris, can we close this one now?
