### ISSUE TITLE
DASL boards grain upgrades

### ISSUE THREAD

**Issue by BigAl737** [vasl-developers/vasl#749]
Have a request to make the grain on the DASL boards differentiate better from the hills.

http://www.gamesquad.com/forums/index.php?threads/vasl-map-online-problem-suggestion-form.88223/post-2031571

The DASL boards don't use the standard grain fill as the geo boards. Besides aesthetics, was there a reason for this? Should I update the DASL boards with the geo board grain fills?

He also mentions that the buildings don't transform. I'm finding they do.

**Comment by derimmer** [comment]
Link to #815
