### ISSUE TITLE
Toolbar images are fuzzy in 6.6.0

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#751]
Toolbar counters and text are not as clear as before and definitely not as clear as counters/text on the map.

**Comment by uckelman** [comment]
I may know why. Can I see an example?

**Comment by derimmer** [comment]
This is what was sent to me.

![Screenshot 2020-09-28 145508](https://user-images.githubusercontent.com/7696161/94493124-d0e24780-01b9-11eb-8843-6328ab03593c.jpg)

**Comment by uckelman** [comment]
What OS is this? Is it a HiDPI display?

**Comment by derimmer** [comment]
> What OS is this? Is it a HiDPI display?

User says its Windows 10 and that his graphics settings are set at 1920x1080 with 60p Hz. Beyond that he doesn't know how to confirm it's HiDPI.

**Comment by uckelman** [comment]
Can you point me to where in the code the buttons are created?

**Comment by derimmer** [comment]
VASL.buildModule.Map.QC.java

**Comment by uckelman** [comment]
That's what I thought. Can you be more specific within that file? QC.java is a disaster.

**Comment by uckelman** [comment]
I think I've found what's wrong. `CreateButtonIcon()` is totally broken.

**Comment by derimmer** [comment]
Sorry you had to find this on your own. Away from my desktop for a while. Thanks for your help on this.

**Comment by derimmer** [comment]
@uckelman Hi, not to rush you (and I know that you have other things to do that recode VASL!) but I was wondering if you had been able to make progress on this. I am about to release VASL6.6.1 which will contain the fix that Brian provided for the moving units out of a stack problem. Would be nice if I could include this fix as well. I can certainly wait a bit if you can give me a timeline. Thanks.

**Comment by uckelman** [comment]
I'm working on it again now. I don't know how much longer it will take, but I'm not finishing anything else first.

**Comment by uckelman** [comment]
I have a solution now; I'll get you a PR for it on Tuesday.
