### ISSUE TITLE
Disappearing units in moving stacks

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#753]
From FB:

So, two games played with VASL 6.6.0 so far. In both games I've had a couple of instances where, when trying to move an infantry stack, one or more of the units in the stack disappears - on both players' boards. So for example, leader + squad + LMG move together, but only the LMG appears in the hex moved to; the other units have vanished.

**Comment by hongkongwargamer** [comment]
This "phenomenon" also happens in VASL logs created in 6.6.0

As you play the log back a stack will get caught somewhere whereas the chatter indicates the stack is still moving.  Then counters in the stack "disappears" but when you hover the pointer over it, you can still see the whole stack.  

I am back on VASSAL 332 + 660 beta 1 .. doesn't seem to be an issue there.

**Comment by derimmer** [comment]
Tested it further myself today. Happened every time I tried to move units out of a stack. When dropped in the new hex, the stack offset disappears so only the top counter is visible. While the whole stack shows up in the Detail Viewer, units and sw appear in reverse order than they should. This is a pretty significant problem. Concealment does not seem to be the issue as it happened in my test with both concealed and unconcealed stacks. 

I was using VASSAL3.4.2 with VASL6.6.0. 

@uckelman - any thoughts about VASSAL changes in 3.4.x that could be causing this? Jack reports no problem with VASSAL332 and VASL660beta1.

**Comment by derimmer** [comment]
From GS:

The code for the movePieces() method in PieceMover.java was slightly changed as of 3.4.2, as part of fixing a (very old, but repeated) crash/exception involving moving Stacks.

Modules that subclass PieceMover and override movePieces() with custom code are therefore "missing some updated code" for stack moving, and that is causing the problem.

Two options:
(1) Ideally, pull the latest code from PieceMover.java from 3.4.5 source, reintroduce your unique changes, and go from there. (This is the idea case because it keeps you the closest to the mainline VASSAL code, meaning it will be the easiest to maintain in the future -- that does not mean it would be the easiest thing to do in the first place though).
(2) Alternatively, open the PieceMover.java from 3.4.5 source, extract lines 597-601, and introduce them at an appropriate point in your own movePieces() method, and that should hopefully get you back on track.

The relevant lines (597-601) are:

Java:
            //BR// We've made a new stack, so put it on the list of merge targets, in case more pieces land here too
            mergeCandidates = new ArrayList<>();
            mergeCandidates.add(dragging);
            mergeCandidates.add(parent);
            mergeTargets.put(p, mergeCandidates);
You can find the latest source for PieceMover here:
https://github.com/vassalengine/vassal/blob/release-3.4.5/vassal-app/src/main/java/VASSAL/build/module/map/PieceMover.java

Best,

Brian

**Comment by derimmer** [comment]
My view:

Do option  (2) above in the short term and issue 6.6.1. 6.6.0 is virtually useless until this is fixed. 

In the next release, 6.6.2, planned for next spring, implement option option 1 with whatever is the current version of VASSAL at that time.
