### ISSUE TITLE
Ammo Depleted Marker

### ISSUE THREAD

**Issue by BigAl737** [vasl-developers/vasl#755]
Request from the field to have an ammo depleted marker similar in style and appearance to the vehicle first and final fire marker.

http://www.gamesquad.com/forums/index.php?threads/ammo-depletion.158884/post-2032380

**Comment by derimmer** [comment]
Al, I suggest you reach out to Stephen Stewart. He was thinking about working on this. He was also doing some work on turrets and  might need your help on that.

**Comment by BigAl737** [comment]
Certainly. Stephen, you out there?

**Comment by derimmer** [comment]
This has now been done and will be issued with VASL-6.6.5-beta3 for testing. It does not us counters but displays depleted ammo status.  See #1204 

GS: http://www.gamesquad.com/forums/index.php?threads/depletable-ammo-status.172105/
