### ISSUE TITLE
Buttons in ASLDiceOverlay aren't wide enough for their text

### ISSUE THREAD

**Issue by uckelman** [vasl-developers/vasl#760]
![Screenshot from 2020-10-13 20-08-06](https://user-images.githubusercontent.com/442741/95905416-ba7ae500-0d90-11eb-895c-a4483b91092d.png)

Many of the buttons in the sidebar show "..." instead of their actual text because the buttons are set to a fixed width which is too narrow for the text to be displayed. (I see this on Linux.) 

The problem is here:
```
    public void CreateToolbar()
    {
        if (m_Toolbar == null)
        {
            final int iW = 32;
```

The correct way to handle this would be to set the width of each button after checking the width of the longest string to be displayed.

**Comment by zgrose** [comment]
Interesting that it also places the toolbar at the top of your window... IIRC, it is supposed to anchor to the bottom of the left or right section (at least, that's where I've always seen it placed).

**Comment by derimmer** [comment]
@zgrose I assume you are talking about the Dice Over the Map toolbar which shows on the side. I suspect it was just a function of the size of the map window. On my machine it does anchor itself to the bottom left or right but can be about the same height as the map window, especially if I have the counter palette open and expanded.

**Comment by zgrose** [comment]
Correct. Could well be the map portion of the window was small, just never seen the dice buttons that high.

**Comment by derimmer** [comment]
@uckelman this may be device dependent in the same way that the fuzzy toolbar is. I have VASSAL 3.2.127, 3.4.2 and 3.4.6 installed and the dice sidebar shows fully and clearly regardless of VASSAL version. And my toolbar at the top of the window is as clear in one as the other. There is no requirement to use the dice sidebar so I am not inclined to worry about it until someone points it out. Certainly not in 6.6.1.

**Comment by uckelman** [comment]
> Correct. Could well be the map portion of the window was small, just never seen the dice buttons that high.

My monitor is 2560x1440. I get this at all window sizes, tiny up to maximixed. I'm sure it's not due to the size of the window.

**Comment by uckelman** [comment]
I consider this to be a serious issue; at the very least, it looks shoddy. I've pushed a fix (#766) that ensures these buttons are wide enough for their labels. I'd appreciate seeing that in 6.6.1.

**Comment by zgrose** [comment]
Just so we're all on the same page as to what I'm talking about, in the original screenshot, the toolbar appears to be anchored to the top (note how the pin is right under the main toolbar and there is space under the <-> button at the bottom. In my Windows, the toolbar appears to be anchored to the bottom of the window. Image is from 6.6.0 and VASSAL 3.4.2. Not sure if this is just a Linux thing and it's always looked that way on Linux, or if something else has changed (I haven't run anything off develop recently).

![Screenshot 2020-10-14 185527](https://user-images.githubusercontent.com/5044847/96057765-4c492780-0e4f-11eb-9691-9c0540e3e361.png)

**Comment by uckelman** [comment]
Oh geez, if somebody was trying to put the "pin" button in the corner, so that the tops of both toolbars are aligned... that's not the way to do it. I had no idea it was intended to be that way---but my PR doesn't affect that at all.

**Comment by zgrose** [comment]
The Pin isn't meant to be aligned, that was just a coincidence in my screenshot. Taller image attached.
![Screenshot 2020-10-14 190809](https://user-images.githubusercontent.com/5044847/96058373-a0084080-0e50-11eb-9d2a-9dbc5288aa23.png)

**Comment by uckelman** [comment]
Oh, I see, the side buttons are intended to be shoved to the bottom. I'll check into why it's not that way on Linux in the morning.

**Comment by uckelman** [comment]
I messed with the layout for more than an hour and have reached the conclusion that `GridBagLayout` is a load of crap. As I hadn't even known that alignment of that toolbar was wrong until @zgrose pointed it out, I'm unwilling to sink more time into it.

**Comment by derimmer** [comment]
Understood. Appreciate the help. I will build and release 6.6.1 now
