### ISSUE TITLE
VASSAL tiles the VASL 6.6.1 images on every load of the vmod

### ISSUE THREAD

**Issue by zgrose** [vasl-developers/vasl#767]
Checking to see if it is something local to my machine causing this...

**Comment by derimmer** [comment]
I am definitely not getting that on my machine. I download the version from vasl.info, extracted and ran it. No problem.

**Comment by zgrose** [comment]
Just throwing things out there as an FYI as they come up. Will update as I know more.

**Comment by zgrose** [comment]
It certainly happened over and over, I even started with a fresh VASSAL preferences folder and a computer restart. It seemed to always want to tile the DO and DD images (the standard and deluxe draggable overlays, IIRC). After opening the VASL Preferences dialog, it seems to have stopped tiling. If that sets off any light bulbs, I can dig further. Otherwise probably can go into the "that's odd" bucket for now.

**Comment by derimmer** [comment]
I am not hearing of anyone else having the same experience. Shall we close this one out?

**Comment by zgrose** [comment]
Probably, if I can get it to trigger again, I have a few extra places to look.
