### ISSUE TITLE
CTRL LEFT Click showing pop up menu on MAC in 661

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#768]

**Comment by zgrose** [comment]
I believe some version of VASSAL 3.3.x was the first place this changed. CTRL-Left Click is "supposed" to show the context menus on Macs. I think that keystroke was being prevented from bubbling up and now it isn't.

**Comment by uckelman** [comment]
We did a bunch of work over summer to rectify some Mac key issues, and I suspect that now VASL is on the wrong side of those. I'll see if I can get you a summary of what's changed so you can adjust as necessary.

**Comment by derimmer** [comment]
Much appreciated.

**Comment by derimmer** [comment]
CTRL-3 and CTRL-4 have also been noted as note working. Their menu equivalents do however.

**Comment by zgrose** [comment]
FWIW, I could not reproduce those issues, but I have a couple theories. Maybe I'll try a screen share with @hongkongwargamer

**Comment by hongkongwargamer** [comment]
> CTRL-3 and CTRL-4 have also been noted as note working. Their menu equivalents do however.

CTRL-3 and CTRL-4 works after I turned off DESKTOP SWITCHING (to Desktop 3 and Desktop 4) on the Mac

**Comment by hongkongwargamer** [comment]
CTRL-LEFT CLICK still pops the right click menu when trying to get the "This Guy" circle

**Comment by uckelman** [comment]
There's a fix for a different problem in 3.4.7 which by happenstance will make your red circle work with Command + Left Click on a Mac. I'm not sure quite when 3.4.7 will be released---we have three or four issues we're still working on for it---but I would guess still during October.

**Comment by derimmer** [comment]
@hongkongwargamer @zgrose 

Is this still an issue - and by this I mean left-click still popping the right-click menu on one of those damn Macs? 

Did the VASSAL versions subsequent to 3.4.6. solve this?

**Comment by zgrose** [comment]
I'll let HKW answer since I'm not VASLing much on Macs these days...

**Comment by hongkongwargamer** [comment]
> @hongkongwargamer @zgrose
> 
> Is this still an issue - and by this I mean left-click still popping the right-click menu on one of those damn Macs?
> 
> Did the VASSAL versions subsequent to 3.4.6. solve this?

Yes.

I am on VASSAL 3.5.3 + VASL 6.6.1

**Comment by derimmer** [comment]
@hongkongwargamer Which question are you responding yes to? LOL

**Comment by hongkongwargamer** [comment]
> @hongkongwargamer Which question are you responding yes to? LOL

Yes --> left-click still popping the right-click menu
No --> Did the VASSAL versions subsequent to 3.4.6. solve this?

**Comment by uckelman** [comment]
You'll want to check if this happens with VASSAL 3.5.3 with a module other than VASL.

**Comment by hongkongwargamer** [comment]
> You'll want to check if this happens with VASSAL 3.5.3 with a module other than VASL.

Yes.  w/ Wooden Ship & Iron Men 1.0

**Comment by derimmer** [comment]
Can someone with a MAC please check if this is still happening in 6.6.2/3.5.5? Thanks muchly.

**Comment by hongkongwargamer** [comment]
VASSAL 3.5.5 VASL 6.6.2

Mouse Left Click on a counter does NOT pop a menu
CTRL-Mouse Left Click on a counter pops the "Right Click Menu"

As per normal on a Mac

**Comment by derimmer** [comment]
Thanks. 

We can declare victory, close the issue and fix the next problem!
