### ISSUE TITLE
Github Dependabot notice

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#769]
![gitsnip2](https://user-images.githubusercontent.com/7696161/96277020-ba056880-0fa1-11eb-9375-ad3a8c72e994.PNG)

@uckelman @davidsullivan317 @zgrose 

This seems to come from Github. I have never seen one before so am not sure how to handle. 

All it requires is a minor version change to junit in our pom.xml. I am happy to make this change and have it apply to vasl6.6.2 spring release.

Thoughts?

**Comment by zgrose** [comment]
JUnit isn't part of the distribution, it is a test runner. You should be safe to update it.

**Comment by uckelman** [comment]
Yes, this. It's a build dependency for you, not a runtime dependency. You don't need to do a new release for it, but merging the change to the master branch now should be fine.

VASSAL upgraded to it last week and we've seen no problems.

**Comment by derimmer** [comment]
Done
