### ISSUE TITLE
Scenario dashboard

### ISSUE THREAD

**Issue by davidsullivan317** [vasl-developers/vasl#77]
I'd love to create a dashboard feature to consolidate scenario status/information, allowing us to manage it in way that is convenient to the user and allows us to improve the playing experience. 

Ideas floating through my head include:

* Game length
* HTML scenario text 
* The current turn
* The current phase with arrow to increment 
* Weather/EC details 
* Sniper and booby trap numbers
* ELR/SAN
* Notes
* OBA
* Night stuff
* River/stream depth, etc.
* VP counter
* Reinforcement turns
* etc.

We could make the UI very unobtrusive - hide it, dock it, roll over, etc. 

Fun things we could do with it:
* Reduce counter clutter and the UI entropy 
* When phase is advanced applicable counters could be removed (eliminating the "remove all" menu)
* Players could enter reminders to do stuff on phase advance ("Remove smoke!" "Roll for blaze spread!")
* Advancing the CC to RPh would bump the turn
* Sniper/bobby trap triggers could be phase aware. 
* Give us a simple way to add things like automatic blaze spreading
* Flip/remove smoke counters

**Comment by mistertakai** [comment]
Why did you close this one? It's a really cool idea! Maybe we can put some conceptional work in it at a later point in time...

**Comment by BigAl737** [comment]
I've been working on an extension that allows you to click through the ASoP. I think that would be cool.
