### ISSUE TITLE
VASLize SK boards k and l

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#770]
Starting new naming convention for SK and Deluxe boards with the same letter identifier, ie "k". Add SK or DEL after the letter (ie bdkSK).

We are not renaming existing SK or Deluxe boards at this time as it will break all existing games using those boards.

**Comment by zgrose** [comment]
My $0.02 would be to use the full text of StarterKit and Deluxe. Potentially even with a dash.

I can envision a board 'ask' so getting ahead of the curve might be nice.

bdmStarterKit, or bdm-StarterKit; and
bdmDeluxe, or bdm-Deluxe

Should be super safe and understandable by everyone without resorting to magic codes like SK and DEL.

**Comment by derimmer** [comment]
I think SK is pretty clear. Agree that Deluxe would be better than DEL. 

bdkSK and bdlSK are on vasl.info and will show up in your boardpicker dropdown.

**Comment by styson** [comment]
Awesome. Added and verified at http://www.texas-asl.com/boards.htm
