### ISSUE TITLE
Board directory mismatch causing VASSAL error

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#773]
Need to handle the exception.

From VASSAL bug 13519:

opening the VotG map to create a new game

VASL v6.6.1 3.4.6

java.lang.NullPointerException: Cannot invoke "VASL.build.module.map.boardArchive.BoardArchive.getBoardName()" because "this.VASLBoardArchive" is null
 at VASL.build.module.map.boardPicker.ASLBoard.initializeFromArchive(ASLBoard.java:137)
 at VASL.build.module.map.ASLBoardPicker.updateBoard(ASLBoardPicker.java:508)
 at VASL.build.module.map.ASLBoardPicker.getBoard(ASLBoardPicker.java:601)
 at VASSAL.build.module.map.BoardPicker.getLocalizedBoard(BoardPicker.java:453)

Uckelman wrote:

he problem here is this, in ASLBoard:

        try {
            VASLBoardArchive = new BoardArchive(archiveFile.getName(), archiveFile.getParent(), ASLMap.getSharedBoardMetadata());

        } catch (IOException e) {

            ErrorDialog.dataError(new BadDataReport("Unable to open board file", archiveFile.getName(), e));
        }

        boardFile = archiveFile;
        setCommonName(VASLBoardArchive.getBoardName());

When there's been an exception, VASLBoardArchive is null on the last line, so something else needs to happen in that case.

**Comment by derimmer** [comment]
Just wrapping this in a try-catch seemed to avoid the vassal error.

**Comment by uckelman** [comment]
If you continue on after the catch block when there's been an `IOException`, then, yes, `VASLBoardArchive` can be null. That's why you have to return from the catch block, so that nothing after it executes when an `IOException` has happened.
