### ISSUE TITLE
Bad Things overlays not highlighted by Malf finder

### ISSUE THREAD

**Issue by BigAl737** [vasl-developers/vasl#776]
This: 

![image](https://user-images.githubusercontent.com/10384413/97096048-3982df80-1613-11eb-9dd3-5cb759b0ed2a.png)

is not highlighted by this:

![image](https://user-images.githubusercontent.com/10384413/97096077-78189a00-1613-11eb-945d-cb79eb034cb9.png)

**Comment by BigAl737** [comment]
I've updated the Bad Things prototype to fix this.

**Comment by BigAl737** [comment]
@derimmer Hi Doug,

The fix is to add two trigger traits and a BRK Layer trait to the Bad Things prototype and a BadThingsBlank.png to the images folder. I pushed this to Allan003 branch but when I try to merge into develop it says it can't automatically merge. Not sure how to proceed from here so am asking for your help. Thanks.

**Comment by derimmer** [comment]
Your changes look good to me but github isn't liking that you are making changes to the buildFile. It would not let me push it to develop either.  I don't know why. I took a quick look and you seem to be using a recent version of the buildFile. 

However, the last changes to the buildFile were made on October 13th. If the buildFile that you changed is from before that, I think this would be the source of the problem. I suggest downloading the current buildFile, making the changes to it and pushing it up to Allan003. then I think your merge into develop should work.

**Comment by derimmer** [comment]
Looks like the changes are in develop now. Well done.

**Comment by BigAl737** [comment]
I'll close this. It works on my local system. Hopefully it'll work when you release the next build.
