### ISSUE TITLE
Finnish counter graphics

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#788]
The Finnish counters should be reviewed to ensure that graphics are consistent with VASL norms in terms of clarity.

**Comment by BigAl737** [comment]
This will be a big job but here's a sampling...

![fi447S](https://user-images.githubusercontent.com/10384413/97493145-67b93580-1919-11eb-9497-cb457a49d51e.png)
![fi20L6](https://user-images.githubusercontent.com/10384413/97493155-6ab42600-1919-11eb-92c4-447218dbfe07.png)
![fiL80](https://user-images.githubusercontent.com/10384413/97493162-6b4cbc80-1919-11eb-97c2-82d0cf0acc57.png)

**Comment by derimmer** [comment]
Looks great. In my mind this is not a high priority so if it takes a while, it takes a while.

**Comment by BigAl737** [comment]
It's taken a while :-)

I've been working hard on this the past week. The good news is that when I started up again, I learned I was farther along than I remembered. The bad news is there was still a long ways to go. The good news is I've got the vast majority done, to include (I think) all the counters that are in the MMP HP scenarios. The bad news is I'm getting burned out. The good news is I think we can get what I've done released and I'll finish up when I get more wind in my sails.

Doug, if I give you access to the updated fi images folder, could you incorporate it into a test VASL build for me?

**Comment by derimmer** [comment]
Good news 3 bad news 2. It's a win.

Yes Al, I totally agree with your plan. Let's release what you've got. Send me the images and I will get them into the next 6.6.6 beta release which will come out this coming week. The official release of 6.6.6 will be early April so that should give us time for debugging, etc. 

As always, super work Al. 

6.6.6 will also contain some bug fixes for Finns that BH/ELR so a good step forward on this nationality.

**Comment by derimmer** [comment]
Finns updated. Here it a link to a new beta for testing.

https://www.dropbox.com/s/hweeji1c2pkb8kr/vasl-6.6.6-beta5.vmod?dl=0

I haven't yet pushed the changes to github. I have it lined up and it tells me there are about 120 updated images. Does that sound right Al.

**Comment by BigAl737** [comment]
120 sounds right on.

Just did a quick check and I don't see any problems with the counters update. The 20L(4) and 20L(6) AA guns don't seem to malf/limber correctly. That's not due to the counter update though. I didn't add the Finn's to VASL so I'm not sure if what I'm seeing is how the author did it or not. I'll dive deeper and let you know.

**Comment by BigAl737** [comment]
The non QSU Finnish guns show malfunction status by superimposing an X over the counter. This could probably be refined with specific malfunction status counters like other nationalities. I've created some of these for the Finns but I don't have time to implement them at present. This issue should become it's own probably.

**Comment by BigAl737** [comment]
@derimmer please change the 20L AT PstK/40 from the current .gif version to the .png version. The png version is in the fi/gun folder. You can delete the .gif version.

**Comment by BigAl737** [comment]
I'm noticing something that I don't think occurred previously. This is occurring with the Finnish guns and also with a sampling of the German guns. If the gun is non-QSU, limbers, malfunctions, then moves to a new hex, it is replaced with it's functioning limbered side. The same is true with unlimbered guns but since they can't move, it's not as big of a deal. This might be a new issue worth a look.

**Comment by derimmer** [comment]
This is the peril of doing good work. . . . it creates more necessary work. Story of my life.

Thanks for doing this Al. Much appreciated. The graphics update is a big step forward. 

I will create some issues and around the limbered guns. Since no one has posted about this previously, I don't think many people are being affected by it. So, it can go on the list and be dealt with when it is dealt with. I did a fair number of counter issues in 6.6.6 and kind of have in my mind to focus on the rest of them in 6.6.8. 

Improvements to VASSAL (and my knowledge of VASSAL) means that I am finding counters easier to fix. Except for graphics issues where I continue to rely on your expertise - stay safe!

**Comment by derimmer** [comment]
@BigAl737 The 20L AT PstK/40.png image appears to be missing the (6) IFE info. It is on the .gif image and shows in my Chapter H. 

I am going to release 6.6.6-beta5 tomorrow. We will get this fix into the official release.

**Comment by BigAl737** [comment]
Right you are. Good catch. I'll get that fixed for the official release. I'd like to get all the mortar 5/8 and 1/2 counters updated by then as well. After that, I'll complete this project as time and desire permits.

**Comment by BigAl737** [comment]
Here's the corrected counter:

![fiAT20L](https://user-images.githubusercontent.com/10384413/218907710-ed2fbd4d-c83b-41fe-aadf-d483ca0e0b32.png)
