### ISSUE TITLE
LOS and Desert Boards

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#795]
Can we get los to work on the desert boards, starting with bd25?

**Comment by SOSBlackbird** [comment]
I would really like to second this! LOS on Bd25 with its elevations would be a big help.

**Comment by BigAl737** [comment]
Doug, could you start with bd25ETO? I think I used the VASL palette when I converted this board. It'd be cool if you could apply the LOS engine to bd25ETO and then copy it to bd25.

There are no LOS obstacles on the other desert boards. Those should be easy to do I'd think.

Let me know how I can help.

**Comment by derimmer** [comment]
Sounds like a plan Al.

**Comment by BigAl737** [comment]
It's in GitHub now. v0.2. Once you get LOS working, you can reload it as v1.0.

**Comment by derimmer** [comment]
I see it on the website as well. Somewhat non-sequential but that's ok. LOL!

**Comment by BigAl737** [comment]
10z, 17z, and now 25ETO have caused a disturbance in the force :-)

**Comment by derimmer** [comment]
Every board in its place and a place for every board.

**Comment by derimmer** [comment]
Al, I have added los to bd25ETO. Here is a link to a dropbox version: https://www.dropbox.com/s/5th7n2w0uw0wf1i/bd25ETO?dl=0

Could you or someone else check that the los is working properly. In particular, with respect to the los INTO/FROM Depressions. I don't have time to check it thoroughly right now. 

If you can get it checked then I will release version 1.0 (i have not yet updated the boardmetadata.xml file).

**Comment by BigAl737** [comment]
You are fast! I'll look at it over the weekend.

**Comment by BigAl737** [comment]
I'll post here as I find stuff.

With the cursor in J3 I get a green string:

![image](https://user-images.githubusercontent.com/10384413/99133065-ea521e00-25c4-11eb-9fc7-d772eb3c23a2.png)

When I drag the cursor into I3 it turns red:

![image](https://user-images.githubusercontent.com/10384413/99133115-153c7200-25c5-11eb-953d-655c67933480.png)

**Comment by derimmer** [comment]
Hi Al

 

Thanks for this. I would have to check the depression cliff rules but I think the los should be good from I3 to J3. 

 

BTW, you are doing OUTSTANDING work on those boards. Great to see them.

 

Doug

**Comment by BigAl737** [comment]
Thanks Doug.

You get the same effect if I draw a LOS from N3 to vertex N2/O3/N3:

![image](https://user-images.githubusercontent.com/10384413/99140455-b5f35780-25ee-11eb-8c28-6ed6435df9cb.png)

But if drag the cursor to O3 the line turns red. Note that I'm not drawing a new LOS...simply dragging the cursor.

![image](https://user-images.githubusercontent.com/10384413/99140482-ea671380-25ee-11eb-82db-8c4fef61363c.png)

LOS N3 to O3 is green so I'm not sure why the above is happening.

![image](https://user-images.githubusercontent.com/10384413/99140518-1d110c00-25ef-11eb-93ac-87a6119c595b.png)

**Comment by BigAl737** [comment]
If I draw a LOS from Z6 to vertex BB5/CC5/CC6 with the cursor in CC6, the LOs is red:

![image](https://user-images.githubusercontent.com/10384413/99140616-d53eb480-25ef-11eb-8ac0-b7f01cf0de2b.png)

If I draw the same LOS with the cursor in BB5, the LOS is green:

![image](https://user-images.githubusercontent.com/10384413/99140634-f0a9bf80-25ef-11eb-94a8-4b6a04dca08f.png)

**Comment by derimmer** [comment]
Thanks for this Al. Clearly an error. 

 

LOS from vertices is tricky. I will check all of these out. It may take a while as there are lots of depressions on the board. At some point, we should just put the board out there and then wait for the bug reports. But I will do some more work first. 

 

Doug

**Comment by derimmer** [comment]
> If I draw a LOS from Z6 to vertex BB5/CC5/CC6 with the cursor in CC6, the LOs is red:
> 
> ![image](https://user-images.githubusercontent.com/10384413/99140616-d53eb480-25ef-11eb-8ac0-b7f01cf0de2b.png)
> 
> If I draw the same LOS with the cursor in BB5, the LOS is green:
> 
> ![image](https://user-images.githubusercontent.com/10384413/99140634-f0a9bf80-25ef-11eb-94a8-4b6a04dca08f.png)

Al, I have checked this out and the same behavior exists on other boards with hills such as bd02 and bd83. I believe this is deliberate to highlight that bypassing units in those hexes would be at the higher level (A4.34). Even though bypass is not possible in many of these hexes I think the los engine is programmed to allow the los. 

Either that or this is a bug that has been there forever and applies to any board with elevation differences.

Either way, I don't think this is specific to bd25ETO and should not hold up its release. 

That just leaves the depression hexes to sort out.

**Comment by derimmer** [comment]
> Thanks Doug.
> 
> You get the same effect if I draw a LOS from N3 to vertex N2/O3/N3:
> 
> ![image](https://user-images.githubusercontent.com/10384413/99140455-b5f35780-25ee-11eb-8c28-6ed6435df9cb.png)
> 
> But if drag the cursor to O3 the line turns red. Note that I'm not drawing a new LOS...simply dragging the cursor.
> 
> ![image](https://user-images.githubusercontent.com/10384413/99140482-ea671380-25ee-11eb-82db-8c4fef61363c.png)
> 
> LOS N3 to O3 is green so I'm not sure why the above is happening.
> 
> ![image](https://user-images.githubusercontent.com/10384413/99140518-1d110c00-25ef-11eb-93ac-87a6119c595b.png)

Al, I have checked other boards and find a similar pattern. I think this may have to do with crest-line depression hexsides. I am not sure it is working properly but again it is not a bd25ETO issue.

**Comment by derimmer** [comment]
> I'll post here as I find stuff.
> 
> With the cursor in J3 I get a green string:
> 
> ![image](https://user-images.githubusercontent.com/10384413/99133065-ea521e00-25c4-11eb-9fc7-d772eb3c23a2.png)
> 
> When I drag the cursor into I3 it turns red:
> 
> ![image](https://user-images.githubusercontent.com/10384413/99133115-153c7200-25c5-11eb-953d-655c67933480.png)

I believe the LOS is correctly blocked from I3 as per B19.51 and B19.52. I am not certain about the inhex los. I am still searching for a clear rules reference on this. But again, this is how the los engine is currently coded and bd25ETO is not an exception.

**Comment by derimmer** [comment]
I have added LOS to bd25ETO. The depressions were a PITA. I will see if I can copy the los over to the Desert version.

**Comment by derimmer** [comment]
> Doug, could you start with bd25ETO? I think I used the VASL palette when I converted this board. It'd be cool if you could apply the LOS engine to bd25ETO and then copy it to bd25.
> 
>

This was a genius idea and worked like a charm. I have it working. Got to take a break and play some ASL right now so will push the board up later today

**Comment by derimmer** [comment]
When adding los to the other desert boards also check behaviour of the Terrain SSR theatre dropdown, which appears to kick out the los engine when DTO is selected.

**Comment by derimmer** [comment]
Somebody, I don't think it was me, has previously tried to add LOS to desert boards 26-31. It was not working even though the right files were in the bdXX files. 

Today I was able to discover that there were 2 entries in the sharedboardmetadata.xml file for Scrub, one of which was using the same RGB combo as Open Ground. This was causing the problem. Once I removed it, los checking worked on those boards. 

Of course, there are only 3 terrain types on those boards: Open Ground, Scrub and Hammada. Scrub and Hammada have exactly the same LOS impact as open ground. So that doesn't really get us that far. But, the next group of desert terrain (Deirs, Hillocks, and Sand) which are implemented by Al's draggable ovelays can also be added to the los using the same code structure in VASLGameInterface which handles Foxholes. Wadis remain an issue and I haven't got to F13 Alternate Terrain Types. But we should be able to get at least some los working on Desert Boards.

**Comment by derimmer** [comment]
I have just issued a beta version for testing. See FB or GS. I have some minor code cleanup to do and then I will push changes to github. All changes were to VASL and not the desert boards. 

I would like some help creating new versions of the Sand Dunes overlays (old school not the new draggable ones) that I can use for high crest dunes. They need to have slightly different colors than the existing ones that I am using as low crest dunes. So it is  a question of altering the existing overlays. Any volunteers?

Thanks.

**Comment by derimmer** [comment]
BTW, I was able to find a way to update the board losdata when creating a game to reflect the los changes due to an overlay. This should be portable beyond desert overlays to most other overlays, particularly those of a single terrain type (grain, brush, woods, etc).
