### ISSUE TITLE
Moving counters by key combo not marking moved or reporting move in chat in vasl6.6.1

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#828]
http://www.gamesquad.com/forums/index.php?threads/vasl-counter-movement-with-keypad.159688/#post-2040068

**Comment by mtl1971** [comment]
Partially addressed by https://github.com/vasl-developers/vasl/pull/854

1. Mark moved works.
2. Moves reported, but counter by counter rather than all together.

**Comment by derimmer** [comment]
Super!

**Comment by mtl1971** [comment]
Reopening to handle concatenated move reports.

**Comment by mtl1971** [comment]
This should address the concatenated move report chatter for multiple units:
https://github.com/vasl-developers/vasl/pull/860

**Comment by mtl1971** [comment]
I think this can be marked as 'done' now.

**Comment by mtl1971** [comment]
I think this can be marked as 'done' now.
