### ISSUE TITLE
GitHub will require two-factor authentication in August

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#829]
I did something on GitHub recently that caused them to send me a message about this:

https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/

Sam will this affect auto-syncing boards in any way?

Anyone have thoughts about this?

**Comment by uckelman** [comment]
This isn't supposed to affect unauthenticated operations, such as cloning or fetching from a public repo. You don't need a password to sync up boards, right? (I don't remember entering one the last time I did.)

**Comment by derimmer** [comment]
> This isn't supposed to affect unauthenticated operations, such as cloning or fetching from a public repo. You don't need a password to sync up boards, right? (I don't remember entering one the last time I did.)

Correct, although you do have to be online in VASSAL which does require a pw. I wasn't sure if this made a difference. I take it that it does not. Thanks!

**Comment by uckelman** [comment]
Yes, but that's a password used for access to your saved games, so isn't used for GitHub at all.

**Comment by derimmer** [comment]
I keep getting messages about this. So, I set it up using a free app called Authy (one of the ones recommended by GitHub). 

The setup process is diabolically bad but I appear to have it working. Still not sure if it is going to be required to push commits but that is what it sounded like to me.

**Comment by uckelman** [comment]
That's going to be for GitHub login, on the site, not for repo access. I set up Google Authenticator for that, which was pretty easy.

**Comment by BigAl737** [comment]
I've been using SourceTree to access the GitHub VASL repository and just got another deprecation email (appended below). Will this authentication change affect my access through SourceTree?

_Hi @BigAl737,

You recently used a password to access the repository at vasl-developers/vasl with git using git/2.24.1.windows.2.

Basic authentication using a password to Git is deprecated and will soon no longer work. Visit https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information around suggested workarounds and removal dates.

Thanks,
The GitHub Team_

**Comment by uckelman** [comment]
Yes, you really should be using an SSH key for git access. That's by far the easiest and most widely used way.

**Comment by BigAl737** [comment]
Thanks Joel. I've found some GitHub docs on how to do this so will give it a go.
