### ISSUE TITLE
Building LOS information in hex 10U6 missing?

### ISSUE THREAD

**Issue by zgrose** [vasl-developers/vasl#842]
I can draw LOS to/from 10U5 Level 1 but I can't get VASL to do the same for 10U6.
3.4.12 + 6.6.1

Didn't try every other hex, but U6 seems to be the only broken one so far.

**Comment by derimmer** [comment]
Just checked and there is a typo in the boardmetadata.xml file for bd10. U5 is listed twice; obviously one should have been U6. Will fix and release the new board tonight.
