### ISSUE TITLE
ALT + Click generates a flare ping on the map, but is also used to select new style overlays

### ISSUE THREAD

**Issue by mtl1971** [vasl-developers/vasl#855]
Not a major issue, but ALT clicking a region shows the Flare animation - but that key combo is also used to select new style overlays. Can we assign a new key/click combo for one or the other?

**Comment by hongkongwargamer** [comment]
> Not a major issue, but ALT clicking a region shows the Flare animation - but that key combo is also used to select new style overlays. Can we assign a new key/click combo for one or the other?

I tested the “Flare” with an opponent, whilst I can see it when I hit the key combo, he can’t.  Is this something you want to take a look at?

**Comment by mtl1971** [comment]
I think so, HK... What versions of VASSAL and VASL were you and your opponent using, and was it Mac / PC?

**Comment by hongkongwargamer** [comment]
I am on VASSAL 3.5.0 - SNAPSHOT - d334a25aa .. VASL 6.6.1 on a Mac
My opponent's on the latest Linux version of VASL.  I don't know what his VASSAL version is.

**Comment by mtl1971** [comment]
I don't think Flare is in the latest release of VASSAL : 
https://github.com/vassalengine/vassal/tree/release-3.4.13/vassal-app/src/main/java/VASSAL/build/module/map
as compared to master:
https://github.com/vassalengine/vassal/tree/master/vassal-app/src/main/java/VASSAL/build/module/map

So if your opponent isn't on the 3.5 beta, there isn't anything in his version to show the Flare feature.

**Comment by zgrose** [comment]
Maybe VASL needs a button/toggle to flip into "overlay selection mode" so that it's clearer when we're overriding VASSAL behavior and when we're not so that we can flatten this ever spiraling tree of clicks and clicks+modifiers?

**Comment by mtl1971** [comment]
That's a good idea, but might be one to do when VASSAL development has settled down a bit.
What do you think of:
1. Replacing the current VASL red circle with the new Flare on CTRL + Click - they do the same thing, only the Flare is spiffier.
2. Change the new overlay selection toggle to SHIFT+Click to match the old overlays - unless we went with ALT+Click for the new overlays for a specific reason?

**Comment by derimmer** [comment]
> 1. Replacing the current VASL red circle with the new Flare on CTRL + Click - they do the same thing, only the Flare is spiffier.

If the "Flare" is the pulsing red circle then spiffier is in the eye of the beholder. I messed everyone around with the red circle thing when I made it a preference in 6.6.1 and the default was off. I would suggest that we not change the red circle counter finder in 6.6.2. We could beta test the Flare in 6.6.3 and see if people like it or have near epileptic shocks as I did. 

> 2. Change the new overlay selection toggle to SHIFT+Click to match the old overlays - unless we went with ALT+Click for the new overlays for a specific reason?

@BigAl737 you created the ALT+Click for selecting draggable overlays. Any reason? I would be loath to change. As the OP said, it is not a big deal. If you are clicking to select an overlay, you are probably in setup not gameplay and the red circle is not a problem. 

We have more serious problems when our key combos conflict with other MAC key combos which seems to happen on a regular basis. 

Managing key combinations is major problem. Virtually everything in VASL is driven off key combinations. Any VASSAL trait used by a counter required a key combo. I created lots of them when doing the casualties bin. We have no known structure or organization for doing so and I don't even think we have a complete and up-to-date mapping of them. Nor where they vary between OS. This should be created as a separate issue. I will post in the VASSAL forums about whether we can generate a list of key combos in use.

**Comment by BigAl737** [comment]
I chose Alt+click because I was always inadvertently selecting underlays and overlays with Shift+click. That drove me nuts. I've since made it well known through graphic reminders and GS posts that Alt+click selects overlays that I've created in the past 4 or so years. I'd hate for that to have to change.

The cross over effect being discussed is mitigated somewhat since a key combo is assigned to a specific counter. However I believe VASSAL key combos would usurp VASL key combos. Counters and overlays added in the past many years have taken in to account that Ctrl+click is reserved for the VASL this guy circle ever since David created it.

If VASSAL introduces new key combos it affects way more than just VASL. This has the potential to break many modules already in existence. I use Alt+click in some of my other modules.

I haven't done any testing with VASL or other modules with the latest VASSAL to determine if indeed this is module breaker.

**Comment by uckelman** [comment]
You're supposed to be able to turn off the animation by setting one of two values in the Flare config to 0---but it seems not to be working. We're looking into it.

**Comment by uckelman** [comment]
There's now a preference for disabling the Flare animation, which will be in 3.5.0 later today.

**Comment by BigAl737** [comment]
Just tested this with VASL 6.6.1 and my other mods I've created that use the Alt+click combo. While the flare doesn't break the module, it does select the piece along with displaying the flare. I have to click off the piece to deselect it. Disabling the flare preference solves the accidental selection issue but disables the flare so that's not really a viable solution. This is a bummer as it reintroduces the reason I chose Alt+click years ago...to avoid accidental selection of underlaying images with Shift+click. The VASL "This guy thingy" used Ctrl+click. Is there a reason the VASSAL flare couldn't use Ctrl+click as well?

**Comment by uckelman** [comment]
@BigAl737 The Flare component has several different options for activating it. You can set it to one of the choices other than Alt-click.

Disabling the Flare animation does not disable the Flare, only the animation. With the animation disabled, you get a static circle instead of an oscillating one.

**Comment by derimmer** [comment]
> @BigAl737 The Flare component has several different options for activating it. You can set it to one of the choices other than Alt-click.

@uckelman I could not figure out how to set the Flare to a different key combo. There did not seem to be a preference. Do we do this in code?

**Comment by mtl1971** [comment]
It's done with these props (From Flare.java, latest vassal master):
`  // Friendly (localizable) names for modifier key combinations
  public static final String FLARE_ALT_LOCAL       = Resources.getString("Editor.Flare.flare_key_desc", Resources.getString("Keys.alt"));                       //$NON-NLS-1$ //$NON-NLS-2$
  public static final String FLARE_CTRL_LOCAL      = Resources.getString("Editor.Flare.flare_key_desc", Resources.getString("Keys.ctrl"));                      //$NON-NLS-1$ //$NON-NLS-2$
  public static final String FLARE_COMMAND_LOCAL   = Resources.getString("Editor.Flare.flare_key_desc", Resources.getString("Keys.meta"));                      //$NON-NLS-1$ //$NON-NLS-2$
  public static final String FLARE_ALT_SHIFT_LOCAL = Resources.getString("Editor.Flare.flare_key_desc", Resources.getString("Keys.alt_shift"));                 //$NON-NLS-1$ //$NON-NLS-2$
  public static final String FLARE_SHIFT_COMMAND_LOCAL = Resources.getString("Editor.Flare.flare_key_desc", Resources.getString("Keys.shift_command"));         //$NON-NLS-1$ //$NON-NLS-2$
  public static final String FLARE_CTRL_SHIFT_LOCAL = Resources.getString("Editor.Flare.flare_key_desc", Resources.getString("Keys.ctrl_shift"));               //$NON-NLS-1$ //$NON-NLS-2$
  public static final String FLARE_ALT_COMMAND_LOCAL = Resources.getString("Editor.Flare.flare_key_desc", Resources.getString("Keys.alt_command"));             //$NON-NLS-1$ //$NON-NLS-2$
  public static final String FLARE_CTRL_ALT_LOCAL = Resources.getString("Editor.Flare.flare_key_desc", Resources.getString("Keys.ctrl_alt"));                   //$NON-NLS-1$ //$NON-NLS-2$
  public static final String FLARE_ALT_SHIFT_COMMAND_LOCAL = Resources.getString("Editor.Flare.flare_key_desc", Resources.getString("Keys.alt_shift_command")); //$NON-NLS-1$ //$NON-NLS-2$
  public static final String FLARE_CTRL_ALT_SHIFT_LOCAL = Resources.getString("Editor.Flare.flare_key_desc", Resources.getString("Keys.ctrl_alt_shift"));       //$NON-NLS-1$ //$NON-NLS-2$
`

**Comment by uckelman** [comment]
You set it in the Editor.

**Comment by BigAl737** [comment]
Unless I'm misunderstanding...

Folks aren't gonna go changing this in the editor. Is it possible to add a click box in preferences to switch this from Atl+click to Ctrl+click.

If an easy option is not possible, this added feature pretty much breaks all my modules.

**Comment by uckelman** [comment]
You are the maintainer of those modules. _You_, as maintainer of those modules, can set Flare to use Alt+click in the Editor.

**Comment by BigAl737** [comment]
So I did misunderstand. I'll check this out. Thanks.

**Comment by uckelman** [comment]
However, I advise against setting anything to Ctrl-click. Ctrl-click is the standard combo for  toggling selections, and has been for ages, not just in VASSAL but ubiquitously across a vast array of programs---so your modules were already broken, before we ever introduced Flare.

**Comment by BigAl737** [comment]
That's why I didn't use Ctrl+click. I used Alt+click, which was an option for the does not stack trait. But now VASSAL has introduced a conflict with Alt+click.

To be honest, I'm not sure why VASSAL chose to use Alt+click for the flare since Alt+click was already in use as an option to select a piece that had the does not stack trait.

Hmmm, not sure what to do now.

Take a break I guess and think things through.

**Comment by Cattlesquat** [comment]
You can also change Flare to "Ctrl+Alt" or "Alt+Shift". That should move it out of conflict with anything else?

**Comment by BigAl737** [comment]
Good options to consider @Cattlesquat , thanks.

**Comment by BigAl737** [comment]
@uckelman why were my modules broken before VASSAL even introduced the Alt+click flare? I was just using the VASSAL provided option to select a non-stackable piece. What am I missing? I'm not trying to be cheeky, I just want to understand what I did wrong. Thanks.

**Comment by mtl1971** [comment]
Forgive me if this is a silly question - I'm rather new to VASL (and VASSAL) development. Would the best practice to change this be to:
1. Build the VASL module.
2. Open it in the editor, set flare to it's desired state / key combo via that, and save it
3. Extract the buildfile from the module generated by the edit in step 2, and add that to source control

**Comment by BigAl737** [comment]
In re-reading this thread it appears that VASL will ditch the legacy Ctrl+click and adopt the Alt+click for the flare. After giving it a lot of thought (too much thought :-) ... 

I've decided to do nothing. I'll keep the Alt+click in the overlay extension and my other VASL contributions. I'll let the users decide if that's a problem or not. Hopefully they won't find it a problem.

**Comment by derimmer** [comment]
> Forgive me if this is a silly question - I'm rather new to VASL (and VASSAL) development. Would the best practice to change this be to:
> 
> 1. Build the VASL module.
> 2. Open it in the editor, set flare to it's desired state / key combo via that, and save it
> 3. Extract the buildfile from the module generated by the edit in step 2, and add that to source control

This is exactly how @BigAl737  and I have been making changes via the editor - usually to fix individual counter bugs or when I re-did the weather/ec counters. A vmod file is a zip file and changing the suffix and extracting the buildfile works well.

**Comment by Cattlesquat** [comment]
I'm pretty sure by already "broken" he's referring to the fact that VASL used Ctrl+Click for its version of flare when that key combo was theoretically reserved by VASSAL for toggling items in a selection. As opposed to any subsequent choices you made about Alt+Click, which were of course "fair game" at the time. :)

>>@uckelman why were my modules broken before VASSAL even introduced the Alt+click flare? I was just using the VASSAL provided option to select a non-stackable piece. What am I missing? I'm not trying to be cheeky, I just want to understand what I did wrong. Thanks.

**Comment by derimmer** [comment]
I had created a general issue about using key commands #856.

I had also posted on VASSAL about tracking key commands. See #856 responses. 

I think we should move further discussion beyond the flare issue to #856

**Comment by uckelman** [comment]
@BigAl737 In 3.5.1 there will be additional options for selection of Does Not Stack pieces. You can find this already in the current test build,  VASSAL-3.5.1-SNAPSHOT-5f94370b2: http://www.vassalengine.org/~uckelman/tmp/

**Comment by BigAl737** [comment]
This is great news! I'll check it out. Thanks!

**Comment by derimmer** [comment]
I am going to close this issue as Al has decided to take no action for now. I have created several new issues to deal with some of the broader questions that got raised in this thread.
