### ISSUE TITLE
Issue VASL6.6.2-beta

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#864]
I am beginning to focus in on getting a beta version of VASL6.6.2 out the door around the beginning of March.

So far, we have tagged 31 issues with the 6.6.2 milestone. 20 of them are closed, which I assume means that they will be part of 6.6.2. 11 are still open. I am working on a couple of them, mainly LOS issues. 

If any of you are working on any of the other open issues (or anything else that you would like to see included in 6.6.2), please let me know where you are at. Early March is not fixed in stone and if you need a bit more time, that it doable. 

Since VASSAL3.5.1 is officially out, I will also bump the VASSAL version from 3.5.0 to 3.5.1. 

To view the open issues tagged with 6.6.2, click on Issues then Milestones from the list above the issues list. Then click Open (under the green progress bar).

**Comment by derimmer** [comment]
@uckelman Do we have a timeline for VASSAL3.5.4? There is a bug fix in there (the missing first character) that I am inclined to wait for.

**Comment by uckelman** [comment]
We'll release 3.5.4 during March, but I'm not sure quite when yet.

**Comment by BigAl737** [comment]
Hi Doug,

When you do release please credit Gordon Molek and Walter Parker for their assistance with the custom turn markers and phase wheel. Gordon did all the turn and reinforcement marker graphics. Walter figured out the way to get the phase tracker to go up to turn 40. Without their help, I would not have had the time to add these components. Thanks.

**Comment by derimmer** [comment]
I have added this info to the release notes.

**Comment by uckelman** [comment]
You will want to test against current VASSAL 3.5.4 development builds from the master branch, which you can get [here](https://github.com/vassalengine/vassal/actions).
