### ISSUE TITLE
Chinese type 22 AC concealment

### ISSUE THREAD

**Issue by BigAl737** [vasl-developers/vasl#880]
Conceals as Allied Minor. From GS:

[http://www.gamesquad.com/forums/index.php?threads/chinese-type-22-ac-concealment.160653/post-2048264](url)

Confirmed. Actual on left; Expected on right:

![image](https://user-images.githubusercontent.com/10384413/110252094-2f151280-7f30-11eb-8a4f-455114701137.png)

@derimmer is there time to fix this before your 6.6.2 beta release?

**Comment by BigAl737** [comment]
@derimmer 

Simple fix to the buildfile. I made the change and built the module locally to make sure it worked (it does). Pushed to Allan001 branch. I did not merge with develop as I don't want to risk messing up your build that you are close to releasing.

Please merge at your discretion but don't delete the Allan001 branch. I'd like to keep using it (I think :-)

**Comment by derimmer** [comment]
i have pushed this to develop and will add it to the 6.6.2 build, which is waiting for vasl3.5.4 as there is an important fix in it.
