### ISSUE TITLE
Italian 347 BH to 447

### ISSUE THREAD

**Issue by BigAl737** [vasl-developers/vasl#902]
Got a Perry 'sez on this one. The 1st Line Italian 347 should BH to an Elite 447. I haven't confirmed that VASL is incorrect but have been told it is.

http://www.gamesquad.com/forums/index.php?threads/italian-3-4-7-battle-hardens.161166/post-2052590

**Comment by hongkongwargamer** [comment]
Thanks Al .. VASL is not incorrect per se.  The Italian 347 just don't offer a BH option under HOB.

**Comment by BigAl737** [comment]
I've got this done but the develop/buildfile master is missing from the dist folder on my local system. A fresh pull request didn't change that. Not sure how to proceed with updating the most recent buildfile version.

**Comment by BigAl737** [comment]
Desired result after change:

it347 1sq BH to 447 Esq
it347 1sq ELR to 336 Csq

it137 1hs BH to 247 Ehs
it137 1hs ELR to 126 Chs

After BH or ELR, you should never again see a 347 or 137 in the BH/ELR chain.

**Comment by derimmer** [comment]
I have built vasl6.6.2 using your commit and it seemed to work perfectly.
