### ISSUE TITLE
Captured Concealed Weapons get the Wrong Concealment counter

### ISSUE THREAD

**Issue by BruceCarson** [vasl-developers/vasl#921]
This one may be a bit tough to "fix", but if a stack captures an enemy's support weapon and then gains concealment, the weapon ends up with an extra concealment counter of the original owner's type.  What should happen is only one concealment counter is gained of the new owner's nationality.

![image](https://user-images.githubusercontent.com/3753108/116793409-9fee2c00-aa94-11eb-834d-c0278edd76c1.png)

Here's what's in that stack:
![image](https://user-images.githubusercontent.com/3753108/116793496-112ddf00-aa95-11eb-93f3-a80e59f9b2cf.png)

**Comment by derimmer** [comment]
Many people deal with this by HIPing the captured weapon and adding a concealment counter of the possessing side
