### ISSUE TITLE
What to do in VASL6.6.3?

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#925]
6.6.2 is out and I haven't had to issue an urgent update as I needed to do last year with both official releases. Could it be that I am learning? Or just lucky?

In 6.6.3 I am going to focus on all of the outstanding issues dealing with board problems. As you will all recognize right away, boards are not part of the VASL mod and can be dealt with at any point. True, and we should continue to release new board versions whenever they are ready. However, some of the items in our issues list that touch on boards will need code changes and those will be targeted for 6.6.3. 

Thanks to @BigAl737, I have been able to add LOS to the Singling HASL map (code changes made it into 6.6.2) and I am working on Dinant (code changes are required and will be in 6.6.3). I have a test module/board ready to go if anyone feels like testing?

So, that's my starting plan for 6.6.3. I love a good plan but someone wise once said that the purpose of plans is to change them. So, if you want to add or suggest other items for 6.6.3, please go ahead. You can use the Milestone tool on the right hand side of the Issues view to add an item to the 6.6.3 plan.

**Comment by mtl1971** [comment]
What I think might be good:

Housekeeping:
I think Joel's suggestion to add some code quality tools to the build process are a great idea - I thought I could do that for 6.6.3, and do some work there with a view to improving / cleaning up / modernizing the VASL codebase.

It would be good to start putting some unit tests into the codebase. This is a huge job though, and will likely be spread over several releases.

Bugfixes:
What does everyone reckon are our top priorities here are? 

Maintenance:
New maps, new counters. I'd like to lend a hand here if I can - if anyone has a spare moment, I wouldn't mind a quick tutorial on how to go about working on new maps, and the best practices we use when adding pieces to the game.

Features:
I'd also like to improve the dust die handling and add more environment features to VASL - improved LV, Mist, etc. with chatter reminders (that can be turned on & off).
Are there any other things people would like to see in VASL?

**Comment by derimmer** [comment]
Hi Morris

Agree with the housekeeping and encourage you to go ahead with that as I know nothing about either. 

The features sound good to me as well – especially since you want to do them. I am all in favour of working on stuff that we want to!

I would be happy to help show you around maps. Do you want to do that by email or a skype session?

I can get you started on counters as well although @BigAl737 is the resident expert. 

As for bug fixes, our priorities are simply the stuff that we want to work on. I don't think there is anything really "broken" about VASL at present so I don't see anything that demands a fix.

**Comment by mtl1971** [comment]
Hi Doug. Great - an email would be a good start, then maybe we could followup with a skype call?

I'll crack on with the housekeeping.
![image](https://user-images.githubusercontent.com/67708834/119489312-781c7c00-bd53-11eb-930a-e6f08b59f2a5.png)

Oh boy...
