### ISSUE TITLE
Java learning tools

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#926]
Everything I know about java coding (admittedly not that much) is self-taught with much help from my friends here. 

I am beginning to think that maybe some structured learning about coding and project structure/management is called for. 

There are a billion online courses out there.

Anyone have any advice/suggestions about courses/learning tools that they have found helpful?

Many thanks.

**Comment by johnpettit** [comment]
If you happen to have a Linked In Premium account, they have a vast array of video tutorials on nearly everything. I found them quite useful and nuanced. Target a specific subject ('Debugging with IntelliJ') and there was a video. Video quality is good and there's some testing/exercises. You even get a 'Certificate' fwiw.

Regards


JP

**Comment by uckelman** [comment]
Adding a linter like PMD or checkstyle to your build process is a good thing to do. You can learn a lot about what's considered bad practice from those, and it also would help you find and clean up some of those things in VASL. (If you're interested, I can point you to where we have those set up in VASSAL.)

**Comment by dmarteinson** [comment]
By doing - competitive programming sites have practice content, I highly recommend hackerrank.
Problems are relatively quick to do once you've done a couple.  As well as basic language problems there are algorithm-oriented problems which may also be useful.

Reading: 
Basic: Java and object-oriented programming:  Thinking in Java by Bruce Eckel is free online these days IIRC.  It was written a long while ago but is one of the best Java Programming books imho.
Meta:  anything by Robert (a.k.a. uncle Bob) Martin.  But in particular Clean code.
He has some talks on youtube which are also entertaining.

I like Joel's idea of seeing what static code analysis feedback you get, and running it on VASL itself might be interesting..
YMMV but it's not too hard to  run a maven project through SonarQube or just to use a plugin in your IDE.

**Comment by derimmer** [comment]
@johnpettit Thanks John. Unfortunately I am not on linkedin. 

@uckelman Thanks Joel. Yes, I would be very interested in following up on your suggestions. 

@dmarteinson Thanks for the range of ideas. I will check out some of the readings and hackerrank. 

Appreciate you taking the time to reply.
