### ISSUE TITLE
A New Approach to Vehicle Bypass

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#937]
We currently have a vehicle bypass counter. I think there are two things that are true about it:

1. Nobody ever remembers where to find it.
2. It adds to the counter clutter and some players find it confusing. 

Given the success of the Bad Things labels on AFVs in reducing counter clutter, I thought a similar approach might work for displaying bypass status (and actually for moving the AFV in to bypass position), as follows:

1. Move the AFV into the hex as if there were no bypass
2. Right-click->Move->Bypass (new item)-> Hexside (new submenu same as moving counter one hex by numpad).
3. VASL rotates the counter and sets it on the hexside as per the Hexside selected
4. VASL adds colour to the corner of the counter closest to the centre of the hex being bypassed. 

This (a) avoids the additional bypass counter and (b) auto-positions the AFV which can sometimes be tricky for non-adept mouse users like me.

Thoughts and suggestions?

I will try to build this into a 6.6.3 beta version and we can get user reaction.

**Comment by zgrose** [comment]
Corner marker ain't a bad idea. Not a fan of the moving to an edge part since during the MPh that sounds super annoying and creates one system for Infantry and one system for AFV.
