### ISSUE TITLE
Improved acquisition handling

### ISSUE THREAD

**Issue by davidsullivan317** [vasl-developers/vasl#94]
I would love to see a change in how acquisition is handled. I've been playing DTO lately and the number of acquisition counters can be extreme. I believe acq could be handled by a simple line drawn between the firing unit and the target unit. The line could be thin for -1 acq and thicker for -2 and change in color for area acq. A button could turn the acquisition lines on and off as needed. This would save tons of time spent in labeling counters and manually searching out acquisition counter. Also it would provide a really useful overview of the total state of your acquisition.

**Comment by davidsullivan317** [comment]
I'm actually thinking it might not be that hard to add a general ability to link counters. Something like:
- select two (or more?)counters
- select a link option from menu
- when either counter is selected a line would be drawn between the two linked counters. 

Would of course need a way to unlink.

**Comment by davidsullivan317** [comment]
I have counter linking working in 6.4 and have created a [beta2 build](https://www.dropbox.com/s/we0f5dnl741ljds/vasl-6.4.0-beta2.vmod?dl=0) that includes it. The primary motivation is dealing with ACQ markers, but links work for all pieces so you're limited only by your imagination. Tunnels, boresighting, the sky's the limit. 

Here's how it works:

1. Select (only) 2 counters
2. Press CTL+ALT+L to link them
3. Press CTL+ALT+U to unlink them

When one or the other of the linked pieces is selected (only) a line is draws between them.
![image](https://cloud.githubusercontent.com/assets/5281926/25308229/a8ca4b20-2775-11e7-9361-f17be3ab0a88.png)

You cannot see links to your opponent's HIP or concealed counters. 

Please mess around with it and let me know if you think it can be improved and/or if you see any issues. I thought about adding a three-way toggle button - no links/all links/links to selected counters - but not sure that's worth the fuss.

The component ("Piece Linker") is editable in the VASSAL game editor (line color, line thickness, hotkeys), but I did not create profiles options. Again, I'm not sure that's worth the fuss.

Now you can play Clash Along the Psel without losing your sanity. 

P.S. remind me to remove the debug code before we ship. Getting old you know.

**Comment by zgrose** [comment]
Groovy. An issue I'm just raising now because I'm sure someone will raise it on GameSquad is: how will this display / be reported to the other player because it can be used to generate a free LOS check.

I know you can just string your monitor for a silent LOS check, so just floating this out there.

Whether intentional or not, I see you can do a MA and SA and that the linkage can be between anything which is handy for Bore Sighting.

Seems to be working well in OS X so far, too.

<img width="398" alt="screen shot 2017-04-22 at 4 37 52 pm" src="https://cloud.githubusercontent.com/assets/5044847/25309154/1069593e-277a-11e7-8d1b-b65976cbd11b.png">

**Comment by davidsullivan317** [comment]
Thanks for checking it out. 

I did think about the LOS side effect. Players will have to agree on how to use links. If you use it for the obvious stuff in OP those are situations where the LOS is allowed.

**Comment by BigAl737** [comment]
I haven’t tested it yet.

Was thinking it might be better to draw a circle around linked counters instead? This would avoid the free LOS issue.

BTW, I really like the option to change line thickness. Would love to have this option for the current LOS feature.

Al

**Comment by derimmer** [comment]
For me, I would prefer the line especially for acquisition as it would help with drm calculations for hindrances. Just my view. 

Doug

**Comment by derimmer** [comment]
Had a chance to test drive and really like it. Works great for acq; super for BRT! But I like the flexibility it offers to link any two counters of whatever type. I go with keeping it flexible and keeping it simple. Ready to ship!
