### ISSUE TITLE
Concealment bug

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#959]
For certain vehicles, (German Turreted), once they are concealed they cannot be moved using the CTRL-Numpad key combo

**Comment by derimmer** [comment]
More detail and a cry for help. 

The German PzKw IB is a CT turreted vehicle. When concealed, right clicking the ? counter will not display the move menu and the vehicle cannot be moved using CTRL-Numpad key combo.

The German PzJgI is an OT non-turreted vehicle. When concealed, right-clicking the ? counter displays the move menu and the vehicle can be moved using CTRL -Numpad key combo.

The counter look like this in VASSAL edit mode:

![image](https://user-images.githubusercontent.com/7696161/123524564-3ad04480-d699-11eb-84dd-561e6c455acc.png)

All the properties appear to be identical except for the prototypes: geCTtur and geOTnt respectively. These in turn look like this:

![image](https://user-images.githubusercontent.com/7696161/123524652-c6e26c00-d699-11eb-9fd7-5b39fcbfa52a.png)

The getCTtur prototype contains an extra Trait turreted and an extra prototype repTCA, neither of which would seem to impact the move menu. Both contain the prototype Unit58vw which is the one that contains the move menu. 

Can anybody see or think of a difference in the counters that would be causing the difference observed in the game? 

If a 5/8 counter is placed on either vehicle from the counter window, the move menu is present and works for both vehicles. 

It may be that the problem is with how the counters interact with the Concealable class. The two types of vehicles do not produce the same results in Concealable when using the right-click method. When dragging a ? counter from the counter tray, the counters behave the same as each other but use different methods in the class than the right-click method triggers. 

The only reason I can think of for the right-click method of adding ? to produce different results is due to distinction between the counters - but I cannot find it!

**Comment by zgrose** [comment]
Not 100% sure where these values are supposed to be set in the module builder UI but the basic problem is that the PzJg I has a "fully defined" concealment definition and the PzKw IB does not.

Set a breakpoint on the first line in `VASL.Counters.Concealable.mySetType()` and when you debug you'll see that the PzJg I has an input string of:
`conceal;C;ge/geqmark58;ge;;VASSAL.build.module.PieceWindow:?/VASSAL.build.widget.ListWidget:ge/VASSAL.build.widget.PieceSlot:L?`

The PzKw IB has:
`conceal;C;ge/geqmark58;ge;;`

Because that definition is "" (empty string), the concealmentMarker field is set to null.

Because the concealmentMarker == null, when you invoke the concealment command, which calls `createConcealment()`, instead of cloning the defined marker, it creates one from scratch in this block:

````
    if (p == null) {
      p = new BasicPiece(BasicPiece.ID + "K;D;" + imageName + ";?");
      boolean large = imageName.indexOf("58") > 0;
      if (!imageName.startsWith(nation)) { // Backward compatibility with generic concealment markers
        large = imageName.substring(0, 1).toUpperCase().
            equals(imageName.substring(0, 1));
        String size = large ? "60;60" : "48;48";
        if (nation2 != null) {
          p = new ColoredBox(ColoredBox.ID + "ru" + ";" + size, p);
          p = new ColoredBox(ColoredBox.ID + "ge" + ";"
                             + (large ? "48;48" : "36;36"), p);
        }
        else {
          p = new ColoredBox(ColoredBox.ID + nation + ";" + size, p);
        }
        p = new Embellishment(Embellishment.OLD_ID + ";;;;;;0;0;"
                              + imageName + ",?", p);
      }
      p = new Concealment(Concealment.ID + GameModule.getUserId() + ";" + nation, p);
      p = new MarkMoved(MarkMoved.ID + (large ? "moved58" : "moved"), p);
      p = new Hideable("hide;H;HIP;255,255,255", p);
      p = new FreeRotator("rotate;6;88,130;90,130;CA cw;CA ccw;;;", p);
    }
````

This is why the PzJg I gets a clone of the user-visible 5/8" ? concealment marker (which has the Move menu) and why the PzKw IB does not.

I suspect that someone forgot to update the prototypes after they altered behaviors or that someone was trying to use defaulting to save work. /shrug

You can see the missing information here right after the Uncit58vw\\ bit:

````
        <VASSAL.build.module.PrototypeDefinition name="geCTtur">+/null/prototype;DBUnit	rotate;6;88,130;90,130;CA cw;CA ccw;;;\	prototype;Unit58vw\\	conceal;C;ge\/geqmark58;ge;;\\\	emb2;;2;;;2;B;;2;;;;0;false;0;0; , ;+ BU,+ CE;true;;;;false;;1;1;true;;66,130;\\\\	prototype;repTCA\\\\\	prototype;repVCA\\\\\\	turr;ge\/geBU;ge\/geCE;S;A;r\\\\\\\	report;65\,130,83\,130,66\,130;$location$: $newPieceName$ *;;;\\\\\\\\	report;79\,130;Motion in $location$ *;;;\\\\\\\\\	placemark;Motion;79,130;VASSAL.build.module.PieceWindow:?\/VASSAL.build.widget.PieceSlot:Motion;null;0;0;false;;;13633;0;false\\\\\\\\\\	label;76,130;Label;10;191,226,251;0,0,0;t;0;c;0;b;c;$pieceName$ ($label$);Dialog;0;0;TextLabel;\\\\\\\\\\\	mark;Hindrance\\\\\\\\\\\\	piece;;;;/	0\	\\	null;\\\	1\\\\	\\\\\	\\\\\\	3\;;false\\\\\\\	-1\\\\\\\\	-1\\\\\\\\\	\\\\\\\\\\	\\\\\\\\\\\	true\\\\\\\\\\\\	null;257;0;;0</VASSAL.build.module.PrototypeDefinition>
        <VASSAL.build.module.PrototypeDefinition name="geOTtur">+/null/prototype;DBUnit	rotate;6;88,130;90,130;CA cw;CA ccw;;;\	prototype;Unit58vw\\	conceal;C;ge\/geqmark58;ge;;VASSAL.build.module.PieceWindow:?\/VASSAL.build.widget.ListWidget:ge\/VASSAL.build.widget.PieceSlot:L?\\\	emb2;;2;;;2;B;;2;;;;0;false;0;0; , ;+ CE,+ BU;true;;;;false;;1;1;true;;66,130;\\\\	prototype;repTCA\\\\\	prototype;repVCA\\\\\\	turr;ge\/geCE;ge\/geBU;S;A;r\\\\\\\	report;65\,130,83\,130,66\,130;$location$: $newPieceName$ *;;;\\\\\\\\	report;79\,130;Motion in $location$ *;;;\\\\\\\\\	placemark;Motion;79,130;VASSAL.build.module.PieceWindow:?\/VASSAL.build.widget.PieceSlot:Motion;null;0;0;false;;;13587;0;false\\\\\\\\\\	label;76,130;Label;10;191,226,251;0,0,0;t;0;c;0;b;c;$pieceName$ ($label$);Dialog;0;0;TextLabel;\\\\\\\\\\\	mark;Hindrance\\\\\\\\\\\\	piece;;;;/	0\	\\	null;\\\	1\\\\	\\\\\	\\\\\\	3\;;false\\\\\\\	-1\\\\\\\\	-1\\\\\\\\\	\\\\\\\\\\	\\\\\\\\\\\	true\\\\\\\\\\\\	null;257;0;;0</VASSAL.build.module.PrototypeDefinition>
````

I suggest the fastest path to resolve, with minimal side-effects, is to just add the missing counter definition into the buildFile directly.

**Comment by derimmer** [comment]
@zgrose You are right that the problem stems from concealmentMarker not being set for the PzKw IB. And you are right that for some reason the definition of the concealment for the PzKw IB is missing info. That is what I had not noticed - despite staring at the buildFile entries!!! 

How the hell that happens is beyond me. I may have to puzzle it out a bit more as I believe that the problem is not restricted to  vehicles which use the geCTtur prototype. It may apply to other nationalities as well. 

But you have put me on the right track here Zoltan. Thanks for your as always excellent help.

**Comment by derimmer** [comment]
@zgrose Your solution worked for vehicles using the geCTtur prototype. Thanks again.

I will now search for other nationalties/vehicle type prototypes missing the same info.
