### ISSUE TITLE
Stopping ASLBoardPicker.java causing VASSAL crash when no board selected

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#984]
Transferred from VASSAL bug 2489

**Comment by derimmer** [comment]
@uckelman @zgrose  I would appreciate your help if you are willing as I try to learn how to handle errors and exceptions. 

VASSAL bug 2489 is an NPE bug caused when a user clicks on a board in the boardpicker that does not exist in the selected directory and the directory is not their default directory so auto-syncing downloads to a different directory. This produces a VASSAL warning message. The user can select other boards or change the directory and continue selecting boards. If, however, the user clicks "Finish" before a valid board has been selected, a crash happens. 

The crash takes place in ASLBoard.java line 174 when it tries to use a VASLBoardArchive instance which is null. 

I could not see a way to handle the error effectively at this point in the code, as the  ASLBoard method involved returns a boolean and either t/f value would allow the code to continue where it will simply trigger another NPE. 

So, I thought I would handle the error earlier. I identified where the program returns to VASL code after "Finish" is clicked. ASLMap.setBoards() seems to be the place. If I handle the error here then the VASL window opens with a blank map and instructions to the user pasted in the chat window. This seems to work. 

I "handle the error" by testing for the conditions that would allow it to happen (no valid board selected) and then prevent the code continue to execute to the point where the NPE would be triggered. There is no try catch involved. Is this the right strategy?

I believe that I have created PR#985 and invited you to review it to see if I am on the right track here.  Any advice you could provide would be greatly appreciated. 

In case, that doesn't work, here is the revised method from ASLMap:

`public synchronized void setBoards(Collection<Board> c) {

        Iterator it = c.iterator();
        while (it.hasNext()) {
            VASLBoard testboardexists = (VASLBoard) it.next();
            if (testboardexists.getVASLBoardArchive() == null) {
                GameModule.getGameModule().getChatter().send("Board missing. Auto-synching of boards requires board directory in board picker matches the board directory set in preferences. Close this game and start new game");
                return;
            }
        }
        super.setBoards(c);
        String info = "Using board(s): ";
        for (Board board : boards) {
            ASLBoard b = (ASLBoard) board;
            info += b.getName() + "(v" + b.getVersion() + ") ";
        }
        GameModule.getGameModule().warn(info);
        buildVASLMap();


    }`

**Comment by zgrose** [comment]
Seems a reasonable quick-fix to me. I presume `testboardexists` is never null itself?

**Comment by derimmer** [comment]
> Seems a reasonable quick-fix to me. I presume `testboardexists` is never null itself?

Yes, it seems that the collection c is never empty. Even when a board cannot be found a shell board is created in the collection so c always has a member (at least by this point in the code). 

Thanks!

@uckelman  VASSL itself seems to handle a no real board situation by looking for a defaultsetup (see BoardPicker.setup()). Is this different from a predefined setup? Should we use this option to handle the problem?

**Comment by uckelman** [comment]
> The crash takes place in ASLBoard.java line 174 when it tries to use a VASLBoardArchive instance which is null.

I'm not finding the code you're referring to. Is that the right location? On what branch?

**Comment by derimmer** [comment]
> > The crash takes place in ASLBoard.java line 174 when it tries to use a VASLBoardArchive instance which is null.
> 
> I'm not finding the code you're referring to. Is that the right location? On what branch?

Sorry, I was looking at my dev build which obviously had some other changes. 

In GitHub, feature/terraintransformations/vasl/src/VASL/build/module/map/boardPicker/ASLBoard.java line 181

**Comment by uckelman** [comment]
Initial comment: It goes against convention to have a non-static variable name starting with a capital letter (and usually static variables starting with a capital letter are all caps and also final). It took me a moment to realize that `VASLBoardArchive` was a member instead of a class.

**Comment by uckelman** [comment]
I left a comment for you on #985.
