### ISSUE TITLE
Auto-generate acq counters and link

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#986]
From FB:
Issue: currently drag an acq from the drop down list, select the gun/vehicle to link with (often needing to double-click to expand a stack), make sure you select just those two counters, press ctrl-l (ctrl-alt-l on Mac).
1) This starts to feel fiddly in large vehicle intensive games (think Prokhorovka playtest with over a hundred vehicles in play).
2) Whenever multiple units are targeting the same hex, it's hard to tell which acq belongs to whom, as the red lines all lead to the target hex and not the acq counters per se.
Proposal: add an option in a gun/vehicle unit right-click list (with suitable ctrl-shortcut), that creates an acq counter which is linked and with the same label as the parent counter (this would help ID acqs in a stack).  The acq would necessarily appear in the parent unit's hex, and would then simply need dragging to its destination (which you currently have to do anyway).  Default size obviously 5/8" for MTR, I'd be happy with either size default with other units as can easily adjust with ctrl-s (although 1/2" default makes more sense for AT guns).

Thought: add two options: (1) create, label, link; (2) create, label. There are those that don't care for linking (free los checks).

**Comment by styson** [comment]
did we ever add curved links for acq markers? can they be toggled?

**Comment by derimmer** [comment]
> did we ever add curved links for acq markers? can they be toggled?

No we never did add curved links.

Not sure that with the current implementation method we would be able to toggle between straight and curved lines. At present, it is implemented only by keystroke and there are no menu commands. Part of the value of the auto-generate approach is that it would involve menu commands, one of which could be to toggle curved/straight. 

IMHO, I am not a fan of curved lines. I hear the rationale about a straight line providing a free los check; in my view there are easier ways to cheat in VASL. That being said I am happy to try and implement curved lines if others would like. Doing it as a toggle gives players a choice (a third value on the toggle would be no line at all).

**Comment by styson** [comment]
I was thinking the toggle would be for the link itself. That might already be there, I don't know.
Perhaps the straight/curved would be  a setting option.

**Comment by derimmer** [comment]
Currently, there is no toggle for the link itself. The only thing that exists right now is two key combos, CTRL-ALT-L to turn on linking and CTRL-ALT-U to turn it off. In both cases, a vehicle/gun and an acq counter must be selected and must be the only counters selected.  This can get cumbersome in high counter density scenarios.

**Comment by derimmer** [comment]
What I have ben able to do so far:

1. Add a place marker trait to the vehicle/gun menu so that Right-click -> Add Acq puts an acq counter of the correct nationality right on top of the veh/gun. 
2. Immediately applying the ALT-CTRL-L keycombo results in the acq being linked to the weapon. It can then be dragged to the target hex.

I have chosen not to add the label copy feature as there are mixed views about the utility of this.

I cannot get 1 & above to be combined into a single key stroke. I have tried a variety of workarounds/hacks/fiendish programming and cannot find a solution. 

But I think the above is a modicum of progress and makes creating an acq and linking a bit easier. It will be in the 6.6.5-beta for testing.

**Comment by derimmer** [comment]
This is as much as I am going to do on this issue for now so I am closing the issue. It will be in 6.6.5
