### ISSUE TITLE
code cleanup 

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#987]
when I push commits up to github, my IDE (IntelliJ) gives me lots of warning messages. So, I have been playing around with the code analysis and cleanup tools that come with the IDE. I may push up a commit or two that contains changes suggested by those tools.

I would be interested to know if people think they are worth the effort.

**Comment by zgrose** [comment]
Coming from the Visual Studio world, most of these "linting" changes rarely alter the function of the program but rather convert the code to conform to some style standard. So you may want to see if you agree with the style standard first. I'm not a fan of dropping { } except for the most trivial cases, e.g. (`if (foo == null) return;` but that's just me.

**Comment by uckelman** [comment]
I concur about blocks with `if`. I tend to replace single-line `if` statements with blocks whenever I edit nearby code.

**Comment by uckelman** [comment]
In fact, I think literally all of those changes are worse.

**Comment by derimmer** [comment]
OK. well, I will rollback these changes! Thanks for taking the time to look. I will try some different ones in the near future. In part, I am doing this to see if these "warnings" and "suggestions" from the IDE can serve as a teaching tool for me to learn about best practices (as opposed to mere style standards).

**Comment by uckelman** [comment]
> to learn about best practices

If you want that, I'd look into PMD (which we use in VASSAL). That has rules which are substantive. (Search for `pmd` in our repo. There's a bit for setting it uo in one of the poms, and then an XML config file.)

**Comment by derimmer** [comment]
> > to learn about best practices
> 
> If you want that, I'd look into PMD (which we use in VASSAL). That has rules which are substantive. (Search for `pmd` in our repo. There's a bit for setting it uo in one of the poms, and then an XML config file.)

You had kindly made that suggestion before. I can get PMD as  plugin for my IDE and had installed it but forgot about it. I just ran it: it had 4395 things to say about VASL! I will break it down into smaller chunks and start to explore. Thanks

**Comment by uckelman** [comment]
You need to be selective about what rules you enable. Have a look at our [pmd.xml](https://github.com/vassalengine/vassal/blob/master/vassal-app/src/test/resources/pmd.xml) to see what we're using. 

The index of all the rules is [here](https://pmd.github.io/latest/pmd_rules_java.html), which includes descriptions of what each one does.

The rules are categorized; I'd start with some of the ones in the Performance category; complying with those is both a good idea and fairly easy in most cases.

**Comment by derimmer** [comment]
Very helpful. Thanks a lot!

**Comment by derimmer** [comment]
I believe I have reverted all of the style changes. I have also found how I can edit the rules used by the PMD plugin in my IDE so I can cross-reference with the VASSAL list.  I will close out this issue and may reopen one if I get myself into trouble again.
