### ISSUE TITLE
Tracing los from offboard observer

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#989]
It has been requested that we add the ability to trace los from an offboard observer location. 

I have been thinking about how to do this. 

First of all, as you know offboard observer locations are in fact onboard as they are set to a certain level of a board edge hex (or half-hex). So, what is needed is to create a level in the hex where the OBO is located). This can be done for non-adjacent levels such as factory ground levels and roofs so I see no problem adding a location to the hex data. 

I think the OBA window would be the ideal place to get the user input in order to create such a location. This could be non-visible to the other player. 

The OBA window, while quite functional, is utilitarian at best and could use some layout work as well. But I see no reason why the OBO location could not be captured via this window. The other option would be the Info window that tracks, SAN, ELR, and Booby Trap Levels. 

Players would be able to cheat by simply skipping along the board edge hexes with the los tool and trying to find an upper level location in the hex. But, then, there are so many other ways to cheat that I don't think we need worry about it. 

Any thoughts, suggestions, or comments?

**Comment by zgrose** [comment]
Can the LOS tool just be made to allow origin/target elevations that don't exist? AKA, just force the elevation to be X instead of Y via user input?

**Comment by derimmer** [comment]
Yes but it would be evelation X in addition to Y. Hex.resetTerrain() is used to set non-ground level locations in a hex, depending on the terrain type of the hex. It would be easy to create a method that would do the same based on a terrain type passed as a parameter. Would have to create a new "terraintype" for OBO.

**Comment by derimmer** [comment]
![OBOsnip](https://user-images.githubusercontent.com/7696161/129657663-ff203cab-46fa-4b54-b058-22a9d3428f5e.PNG)


So I can create the OBO location and have the los tool find it. 

The OBA form looks worse than ever so I have to work on that. 

I also have to have to the location persist as part of saved games.

**Comment by zgrose** [comment]
I presume `OBO Hex` will take the board name, too? 36E1, etc.

**Comment by zgrose** [comment]
And I'm not sure I understand why it would be X+Y since the idea would be to ignore X and just force the start/end to Y. But looks like you've got a handle on it so far.

**Comment by derimmer** [comment]
> And I'm not sure I understand why it would be X+Y since the idea would be to ignore X and just force the start/end to Y. But looks like you've got a handle on it so far.

@zgrose I thought I understand what you meant by this in your earlier post but now I am not sure. What is x and what is y?

**Comment by zgrose** [comment]
So you're pulling an LOS thread from A1 to F6. F6 has a multi-level building in it so you're allowed to CTRL-uparrow (iirc) to set the target level to Level 1. If you press uparrow again, VASL stops because there is no Level 2. If F6 was Open Ground, it wouldn't allow you to uparrow to Level 1 since it "knows" there is only Level 0 in the hex.

What I suggested is to simply allow for the target/origin to be moved to levels that do not exist. AKA, remove whatever check stops you from going to Level 2 in a building hex that only has a Level 1 location.

If you know the location in the code where is makes these decision, give me a file/line number and I can check if that seems plausible/easy to do.

**Comment by derimmer** [comment]
> So you're pulling an LOS thread from A1 to F6. F6 has a multi-level building in it so you're allowed to CTRL-uparrow (iirc) to set the target level to Level 1. If you press uparrow again, VASL stops because there is no Level 2. If F6 was Open Ground, it wouldn't allow you to uparrow to Level 1 since it "knows" there is only Level 0 in the hex.
> 
> What I suggested is to simply allow for the target/origin to be moved to levels that do not exist. AKA, remove whatever check stops you from going to Level 2 in a building hex that only has a Level 1 location.
> 
> If you know the location in the code where is makes these decision, give me a file/line number and I can check if that seems plausible/easy to do.

Unfortunately the code does not work that way. The Hex.resetTerrain() method creates non-ground level locations in hexes that should have them. It will create level -1 locations (cellars) and level 1, 2, 3, roof, etc locations. But it only creates the locations that are needed. And it is the existence of those locations that allow the string to move up/down levels. So, nothing is stopping the target/origin to be moved to levels that don't exist, there is simply no way to do that. 

The code that moves the los thread up and down levels is found in VASLThread.mousePressed() lines 333-4 and VASLThread.keyPressed() lines 812-3 and 833-4.

**Comment by zgrose** [comment]
OK, I see the bits. Probably not worth the effort to create virtual levels just yet.

**Comment by derimmer** [comment]
> I presume `OBO Hex` will take the board name, too? 36E1, etc.

Well it does now, LOL! Thanks for this reminder. This was the trickiest bit so far. Took me a long time to find a way to do this as the vasl los hexgrid does not store board info. 

What's left is persisting the information. Jut a matter of using Commands properly.

**Comment by zgrose** [comment]
Do the boxes display to both sides because that may be a problem to address, too.

**Comment by derimmer** [comment]
Understood. that it one of the things that I am going to test with another player.

**Comment by davidsullivan317** [comment]
I know I'm late here but I think there is simpler approach. When LOS is checked just add levels as necessary and mark them as virtual. E.g. you can up-arrow in any hex to move the level up to some reasonable max level. Don't add the levels to the map - manage them in temporarily in the LOS class during the LOS check.

**Comment by zgrose** [comment]
That's basically what I was suggesting, but it looks like a bit of work that Doug might want to avoid.

**Comment by davidsullivan317** [comment]
> That's basically what I was suggesting, but it looks like a bit of work that Doug might want to avoid.

It shouldn't be. If no upper location exists create it on the fly and link it in. Should only be a few lines of code unless I'm missing something.

**Comment by zgrose** [comment]
That was my idea to expand Location.getUpLocation() and Location.getDownLocation() to build stuff on the fly. I'm not sure if a Location instance knows enough to build a pseudo Location on the fly. Currently the Location instances seem to built out in resetTerrain(), here is an example:

````
            this.stairway = "Stone Building, 1 Level".equals(this.centerLocation.getTerrain().getName()) || "Wooden Building, 1 Level".equals(this.centerLocation.getTerrain().getName()) || oldStairway;
            previousLocation = this.centerLocation;
            if (!"Wooden Building".equals(centerLocationTerrain.getName()) && !"Stone Building".equals(centerLocationTerrain.getName()) && centerLocationTerrain.getLOSCategory() != LOSCategories.FACTORY && this.isMultihexBuilding()) {
                terrain = this.map.getTerrain("Cellar");
                l = new Location(this.centerLocation.getName() + " Cellar ", -1, this.centerLocation.getLOSPoint(), this.centerLocation.getLOSPoint(), (Point)null, this, terrain);
                previousLocation.setDownLocation(l);
                l.setUpLocation(previousLocation);
            }
````

I agree it can probably be done, and getUpLocation() and getDownLocation() is probably the place to do them, but I'm wary of side-effects since I don't have much time to implement to test.

Plus the idea of recording the offboard observer is pretty useful in it's own right regardless of the presence of pseudo Locations in a hex.

**Comment by davidsullivan317** [comment]
One final thought and I'll shut up. Going the virtual route would also be useful for tracing LOS to climbers, aircraft, etc.

**Comment by derimmer** [comment]
I see two possibilities. 

1. You enable the creation of virtual levels in any hex by using getUpLocation() and getDownLocation. If the level doesn't exist, you just create it. I think creating another level on the fly would not be hard. We would need a generic terraintype just as i have added an OBObserver terraintype. The rest of the info required is available. For OBO, you might have to create 2 or 3 to go from ground level of a grain hex, for example, to a level 4 OBO, but that can be done. Nothing would tell you that you were at the right level beyond the Level X display of the string. That is a drawback I think. Plus, for hexes with upper level buildings this might result in players mistakenly creating virtual levels beyond the roof. Low risk but someone will do it. 

So, simple, yes, but less informative and less precise than my current method in that it could be done in any hex and any time.

2. Allow such creation but only in an OBObserver hex - ie one identified in the OBA window. This would require a verification check every time. Not hard but additional overhead.

I should be able to test my current effort online in the next day or so. Meanwhile, I will look at how to implement your option. 

I will push my code changes to branch feature/terrainfixes on github if you want take a look. It only touches two classes: OBA and Hex.

**Comment by zgrose** [comment]
Yes, some people do use the LOS tool to validate their rules knowledge, so the label on the thread would have to highlight that the Location doesn't appear to be real according to the LOS data (which we all know SSR can invalidate anyway).

**Comment by derimmer** [comment]
I now have your approach working as well. I will test both with a user shortly and will let you know what they think. I can post a link to a beta module if either of you want.

**Comment by derimmer** [comment]
> Going the virtual route would also be useful for tracing LOS to climbers, aircraft, etc.

I'm not sure about this. I have read the Aerial LOS rules (both for planes and Aerial Observers. Beyond the fact that I can't make head-nor-tail of them, I see no reference to a level being assigned either to a plane or an aerial observer. It appears that obstacles may create blind hexes if in adjacent hexes. I don't see how any version of the los thread could be applied to these rules. 

Can anyone explain this to me?

**Comment by derimmer** [comment]
> I now have your approach working as well. I will test both with a user shortly and will let you know what they think. I can post a link to a beta module if either of you want.

Tested with a user yesterday. He was fine with either approach. Liked mine slightly better because it specified "OB Observer" in the LOS string.  However, he didn't like that the opponent could see the OBO location in the OBA window. Plus, the OBO location did not persist for some reason. So, still work to do. Doing a test with another player next week.

I may leave both options in. There is no conflict between them. Your approach only gets invoked when there is no "real" location, including an OBO one. So, if an OBO location is created before a los is drawn, that code will take precedence. But a user could continue to create "virtual locations" above the OBO location. But not inbetween a two real locations, such as ground level and an OBO on say level 4. You won't be able to create virtual locations at level 1, 2, or 3, but you would at level 5 and beyond.
