### ISSUE TITLE
Trace LOS to crest location of depression

### ISSUE THREAD

**Issue by jrvjrv** [vasl-developers/vasl#994]
LOS from 24B8 to 24D9 is reported as blocked, which is correct if the unit is IN the depression. Unlike with buildings there seems to be no way to move to the crest level of a depression hex. My suggestion would be to make up arrow, down arrow, ctrl-up arrow and ctrl-down arrow work in a similar way to buildings for LOS traced to depression hex centers.

**Comment by derimmer** [comment]
I believe that if you draw a los to one of the vertices of the crest hexside you will get the correct los (but make sure that you are drawing it to the hex with the crest - slight movement of the mouse around the target vertex will move it from one of the three hexes to another.

**Comment by jrvjrv** [comment]
Tracing to the vertex gets the right level but is not the correct LOS except when the LOS to the hex center enters exactly on a hexspine. If LOS is not traced into the crest hex on a hexspine, the LOS to a vertex is not the same as to the hex center. LOS to a unit in crest is traced to the hex center. You can sort-of fake it by tracing both to the vertex and to the center, but only sort-of, and you have to know what you are doing.

**Comment by derimmer** [comment]
I agree completely.

Quite accidently, I will have fixed this issue in 6.6.3. I was asked to implement los drawn to/from and Offboard Observer. I did this in two ways:

1. By Creating Offboard Obsever as a terrain type and then having the user specify a hex(es) in which to add it. This done by the OBA window which I have redone as there was a bug there anyway. Using the UpArrow or Ctrl-UpArrow key combo, you would go from the highest level in the hex to an OBO level specified by the user (skipping intermediate levels just like Factory Roofs).

This helps the crest issue not one bit. 

2. By allowing virtual levels to be created on the fly by using UpArrow or Ctrl-UpArrow in any and all hexes. With this method, a new virtual location is created above the current highest location in the hex (to a max of 10). Unfortunately you can't drill down to -10. 

This should address the crest issue specifically. 

![virtualsnip1](https://user-images.githubusercontent.com/7696161/132951539-22b87657-8975-46c2-895b-45786aadfeac.PNG)
![virtualsnip2](https://user-images.githubusercontent.com/7696161/132951540-62fd825b-d288-40ec-a44c-1f14cc9af98d.PNG)

If anyone wants to test these methods and/or review the revised OBA window and give me feedback, I would appreciate it. Especially if you could review it with a friend and make sure it works for both players (both will need the beta module).

Here is a link to the module:

https://www.dropbox.com/s/rgy89ixl0olh3hc/vasl-6.6.3-beta4.vmod?dl=0

Two points about adding an OBO: (1) you must specify a board as well as the hex. So 17EE6 not just EE6; (2) for boards 1-9, it must be 01-09. So 04R1 not 4R1.

**Comment by derimmer** [comment]
Fixed by #989.
